### ISSUE TITLE
turborepo hangs after building the first app

### ISSUE THREAD

**Issue by idirmosh** [vercel/turborepo#1002]
### What version of Turborepo are you using?

1.1.10

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### node version

v16.14.2

### Describe the Bug

i have a monorepo with two apps when i try to build them turbo get stuck on right after finishing the first app but when i change the name of that app as shown bellow turbo goes ahead and builds the entire project, this happened to me early today the app name was `web` when and then i changed it to `frontend` and it worked fine. now it doesn't, so basically turbo will only be happy if i keep changing the name of the app. 

![Recording-2022-04-04-17-55-50-from-Snipclip](https://user-images.githubusercontent.com/41597907/161639632-c3e79e32-415e-4354-95e8-934b96c5ba64.gif)

i don't practically know if this an issue with turbo or im doing something wrong, but the fact that changing the name of the folder made me think that its more a turbo issue.

### Expected Behavior

all apps should build when running `yarn run build`

### To Reproduce

- Clone this repo : https://github.com/idirmosh/issuestracker
- `yarn install`
- `yarn run build`

**Comment by relferreira** [comment]
I'm with the same problem. @idirmosh have you found a solution?

**Comment by gsoltis** [comment]
@relferreira can you try with the latest version of `turbo`?

**Comment by relferreira** [comment]
I upgraded to turbo@1.2.3, and unfortunately, I'm still facing the same problem

![image](https://user-images.githubusercontent.com/4078815/163253199-f4473b6a-7193-478e-82be-5402b900fc4e.png)

**Comment by idirmosh** [comment]
same thing on the latest version of `turbo`

![Capture](https://user-images.githubusercontent.com/41597907/163280248-ec6ae74e-1bc5-4368-854f-859c8d7d707f.JPG)

![sdasd](https://user-images.githubusercontent.com/41597907/163280381-a1cd8177-5df3-4dfa-b73a-416d4cbc3836.JPG)

**Comment by gsoltis** [comment]
You have a circular dependency. `ui` depends on `frontend`, and `frontend` depends on `ui`. If you actually need the dependency from `ui` -> `frontend`, you'll need to pull the functionality out of `frontend` into a different, shared component that both `ui` and `frontend` can depend on. 

I'm going to look into adding some cycle detection so we can give a helpful error message in this situation.

**Comment by relferreira** [comment]
@gsoltis, you were right. It was a circular dependency problem.
Just to let you know, I tried version 1.2.4, but it didn't print the error.

Thanks a lot
