### ISSUE TITLE
Adding cache false to a previously cached process fails

### ISSUE THREAD

**Issue by zomars** [vercel/turborepo#1010]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Adding `cache: false` to a task that was previously cached still hits the cache.

### Expected Behavior

Adding `false` should not hit the cache.

### To Reproduce

- Add a task a let it generate a cache
- Add `cache: false`
- Run the task again and the cache will hit.

**Comment by gsoltis** [comment]
Agreed, tasks that cannot be cached should also not read from cache. I'll get a PR up to address this.
