### ISSUE TITLE
Yarn2 Support

### ISSUE THREAD

**Issue by chav-aniket** [vercel/turborepo#1017]
### Describe the feature you'd like to request

Hi, I would like to explore using turborepo for an application I'm currently building. The only problem is that this project uses yarn2, so I would love to have turborepo offer the same compatability. 

### Describe the solution you'd like

yarn2 support

### Describe alternatives you've considered

I'm not sure whether turborepo works with pnpify? If it does then I suppose an alternative exists.

**Comment by jaredpalmer** [comment]
Yarn 2 with pnp is supported `turbo run` with v1.2, but not `turbo prune`

**Comment by chav-aniket** [comment]
Thanks for the quick reply! It seems the documentation is outdated as installation specifies yarn 1, it'd be nice to have that reflect the current state.

**Comment by jrolfs** [comment]
@jaredpalmer so the `prune` thing is specific to PnP, then, right? Just looking to get the facts straight so I can help update the docs ;)
