### ISSUE TITLE
`--filter=[origin/main]` not working as expected

### ISSUE THREAD

**Issue by weyert** [vercel/turborepo#1032]
### What version of Turborepo are you using?

1.2.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac
Gitlab CI (shared gitlab.com runner) using Alpine docker image

### Describe the Bug

I am trying to execute the `lint` and `test` commands against all changed packages since `origin/main` but it doesn't appear to work. If I try to use the same filter in `pnpm` it works as expected and executes them but when I try to use the same filter with `turbo` it doesn't detect any changes.

```
❯ pnpm run lint --filter=...\[origin/main\]  
Scope: 33 of 35 workspace projects
```

vs

```
❯ turbo run test --filter=\[origin/main\] --dry-run
Packages in Scope
Name Path 

Tasks to Run
```

The command lint is defined in `turbo.json` as:
```
"lint": {
      "dependsOn": ["^build"],
      "outputs": ["coverage/code-climate.json"],
      "cache": false
},
```

### Expected Behavior

I would expect the `turbo` to match the behaviour of `pnpm` and execute the command against all the changed packages compared to passed `origin/main`-branch

### To Reproduce

1. Create a new branch of your repo
2. Run `pnpm run lint --filter=[origin/main]`
3. Next, run `turbo run lint --filter=[origin/main]`
4. Notice that in last command for `turbo` no packages were executed

**Comment by yuriburk** [comment]
I noticed that --filter=[HEAD^1] is not working either

**Comment by weyert** [comment]
Thank you @gsoltis ! Looks like its working again :D

**Comment by moogus** [comment]
Is there a fix for this I seem to be having the same issue

**Comment by moogus** [comment]
just downloaded it to `turbo: 1.5.6` everything started working again

**Comment by moogus** [comment]
@gsoltis, this still seems to happen when filtering against remote branches `--filter=[origin/develop]` changing one package in a repo all packages are included.  Tried it with node 14 and 18.  Any suggestions>

**Comment by gsoltis** [comment]
@moogus can you verify that there is a reference for the remote branch locally? I.e. does `git` know about the branch? If so, can you open a new issue?
