### ISSUE TITLE
Better DX for Remix + Turborepo

### ISSUE THREAD

**Issue by nareshbhatia** [vercel/turborepo#1035]
### Describe the feature you'd like to request

The kitchen-sink example is a great demo of how to use Turborepo with nextjs, vite and remix. The nextjs and vite versions work vey smoothly - when a component in the ui package is changed, the apps immediately reflect the change. However, the Remix app does not show the change. I have to stop the apps and run `nx run dev` again to see the change.

### Describe the solution you'd like

Remix app picks up a change in the ui package immediately.

### Describe alternatives you've considered

None

**Edit**

I see that an issue has been filed in the remix repo for this with a potential solution: https://github.com/remix-run/remix/issues/1193

**Comment by jaredpalmer** [comment]
This is an upstream issue with Remix. Closing for now

**Comment by jdnichollsc** [comment]
@nareshbhatia any of these PRs can solve your issue too:
- https://github.com/remix-run/remix/pull/2985
- https://github.com/remix-run/remix/pull/3188

**Comment by nareshbhatia** [comment]
@Jarrodsz, this is the example I was referring to. But that was a year ago, so it may have changed.

I have a my own example with React, React+Remix, React+Next.js over here: https://github.com/code-shaper/movie-magic

Another example using React+Tailwind: https://github.com/code-shaper/bullsfirst-tailwind
