### ISSUE TITLE
Feature request: Allow inputs outside of package dir

### ISSUE THREAD

**Issue by TxHawks** [vercel/turborepo#1064]
### Describe the feature you'd like to request

I'd like to be able to bust the cache of specific tasks based on changes files (as described in #706). For instance, I'd like to be have an `.eslintrc.js` at the root of the repository which packages can extend, and that changes to that file will bust the cache of the `lint` task in all packages.

Currently, there are two options for a repository-wide config to bust the cache:

1. Extract it a workspace package and add that package as a dev dependency;
2. Include the file in the `globalDependencies` array.

Both these options are lacking, because they do not allow for granularity busting the cache per package, and will always bust the cache for _all_ tasks. 

### Describe the solution you'd like

To be able to specify files outside the package directory in the `inputs` array:

```jsonc
{
  "pipeline": {
    "lint: {
      "outputs": [],
      "inputs": [
        "src/**",
        ".eslintrc.js",
        // Asuming `../../` is the repository root
        "../../.eslintrc.js"
      ]
  }
}
```

### Describe alternatives you've considered

I guess this could also be it's out field separate from `inputs`, maybe like a per-task `globalDependencies`.

**Comment by mantljosh** [comment]
I have a similar need where I have a graphql server that generates a schema file, and a graphql client that needs to run relay compiler using that schema. It doesn't really make sense for the client to list the server as a code dependency (i.e. building the main server code shouldn't cause a downstream build of the client), and even if we did that it would not be granular to _just_ schema changes (similar to the OP's issue with extracting things into a package).

**Comment by gsoltis** [comment]
@TxHawks I think what you have in your example should work now. Can you confirm?

**Comment by TxHawks** [comment]
@gsoltis I'll only be next to a computer tomorrow. Will test against canary then.

Thanks

**Comment by TxHawks** [comment]
Seems to work just fine.

Thank you!

**Comment by jplwood** [comment]
@gsoltis Just checking in on this thread. I was just trying this out and it doesn't seem to work for workspace-level `turbo.json` files. e.g., if I have a workspace `./apps/api` and a `turbo.json` file in it like:

```json
{
  "extends": ["//"],
  "pipeline": {
    "build": {
      "inputs": ["../../api.Dockerfile"]
    }
  }
}
```

If I change my root `api.Dockerfile` file and run `npx turbo run build --filter="api...[HEAD]" --dry=json` the output indicates my package hasn't changed. 

So this is a use-case with per-workspace globalDependencies, but per the [Workspace Configuration#Limitations](https://turbo.build/repo/docs/core-concepts/monorepos/configuring-workspaces#limitations), you can't set that value per workspace. I expected to be able to point to a root file via `inputs`, but it doesn't seem to work.

_(yes, we could put the dockerfiles in the related workspace folders, but currently are limited by an org-defined ci workflow making this difficult... trying to find a workaround)_

**Comment by psychobolt** [comment]
I've created a issue https://github.com/vercel/turbo/issues/8762
