### ISSUE TITLE
Move `cache` to `afero` 

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#1069]
We want to incrementally move to https://github.com/spf13/afero for our filesystem abstraction. This will enhance our ability to test `turbo`. 

As a first and incremental step, let's move our `cache` abstraction to accept an afero filesystem so we can ultimately write `fs_cache_test.go`. 

**After this,** we can lift and move our afero fs up into run.go and begin moving other parts of the codebase, ultimately all the way up to main.go I suppose.

**Comment by nathanhammond** [comment]
We're actively removing `afero` in #1339 after discovering that it is not a viable approach.
