### ISSUE TITLE
`--filter=[origin/main]` not working for headless branches

### ISSUE THREAD

**Issue by weyert** [vercel/turborepo#1079]
### Describe the feature you'd like to request

If you try to use the `--filter=[origin/main]` command to detect the changes between current and the `origin/main`. Only on Gitlab the default behaviour is to use headless branches for their pull/merge requests and appears not to work.

### Describe the solution you'd like

I think it  would be great to improve the wait the `git diff` command is executed it appears that the following works for Gitlab CI but I have to confirm it again:

```
git diff --name-only origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
```

In the above `$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME` is the name of the pull request and the `$CI_MERGE_REQUEST_TARGET_BRANCH_NAME` would be the branch merging into typically `main`.

### Describe alternatives you've considered

Stop using `--filter=[origin/main]` or similar filter arguments

**Comment by szk2s** [comment]
I am trying to use branch comparison with --filter syntax in GitHub actions and have run into a similar issue. I have a workflow triggered by pull_request events, which seems to create a dedicated branch such as `pull/500/merge` where the job is executed. `git-diff-action/main` shows the diff correctly, but `npx turbo run test --filter="...[github-diff-action/main]"` results in an error `unable to check diff vs. git-diff-action/main: exit status 128`. I think the feature `--filter=[base...head]` would solve this situation too.

**Comment by szk2s** [comment]
With Github Actions, we have a similar issue.
When triggering jobs by `pull_request` event, Actions makes a dedicated branch like `pull/615/merge`. 
In that branch, while `git diff origin/develop` successfully shows the diff, `npx turbo run test --filter="...[origin/develop]"` shows an error message: `failed to resolve packages to run: git comparing with origin/develop: exit status 128`.

I bet things like `--filter=[base...head]` will solve this issue too.

**Comment by henrysha** [comment]
I ran into the same issue, and solved it by using `--filter=...[HEAD^1]` with `fetch-depth` of `actions/checkout` set as `2`.  apparently, the first commit that `actions/checkout` gets is the merge commit that merges the PR branch into the target branch. This resulted in diffing only the first commit containing all the info about the changed packages, since it is a merge commit.

**Comment by weyert** [comment]
@gsoltis Can you release a new canary build so I can verify this ticket is resolved for my use case in Gitlab?

**Comment by gsoltis** [comment]
@weyert unfortunately, I don't have the access to push the button for that. I think we're aiming for a canary in a week or so though.

**Comment by weyert** [comment]
@gsoltis @jaredpalmer Any news whether you would cut a canary this week?

**Comment by awxalbert** [comment]
Hi @gsoltis , thanks for your work, I've been experiencing the same issue. When integrating turborepo with gitlab CI, I might have a few questions:

1. What is the correct way to do in a MR pipeline ? For me, I'd like to **filter** all changed packages in this MR, but don't know the right syntax
2. When MR is merged, I'd also like to run tasks based on packages that has changed in the MR, still not sure the correct syntax here

It would be really helpful if there is a **guide** about this kind of stuff, I really want to use turbo in my new projects, and these may be blocking the process, thanks again.

**Comment by weyert** [comment]
@awxalbert Yes, I haven't got it working yet

**Comment by staznz** [comment]
Did you ever solve this @weyert ? I'm experiencing the same issue.
