### ISSUE TITLE
Cache miss even when `inputs` pattern is specified to run in particular folder

### ISSUE THREAD

**Issue by nazimamin** [vercel/turborepo#1085]
### What version of Turborepo are you using?

1.2.4

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Tasks are being re-run even when `inputs` is specified and files are changed outside the `inputs` pattern. 

`    "lint": {
      "outputs": [],
      "inputs": ["pages/**"]
    },`
    
``

### Expected Behavior

If `inputs` pattern is defined, tasks should only run for patterns that are defined in `inputs`

### To Reproduce

1. Clone : https://github.com/nazimamin/turbo-repo-test
2. Yarn install
3. Run `yarn lint`
4. Run `yarn lint` again (Full Turbo)
5. cd into `apps/docs` folder
6. change something in `README.md` file
7. Re-run `yarn lint` -> You'll notice that we get `cache miss` and `docs` build is being re-run. We expect the docs build not to re-run because `inputs` is specified to only re-rerun if anything in the `pages` folder has changed.

**Comment by sppatel** [comment]
I am seeing the same thing - didn't realized you had opened a similar issue but opened https://github.com/vercel/turborepo/issues/1085

**Comment by gsoltis** [comment]
Hmm, I'll take a look

**Comment by gsoltis** [comment]
@mcrowder65 you're absolutely right, there's still an issue. It has to do with still hashing files that have outstanding changes. This is a pretty good one:
 1. I missed it at first in manual testing because I was toggling between two states of an irrelevant file, and after a couple runs, both were in the cache and so caused a hit
 2. Our tests miss it because this bug is specified to _uncommitted_ changes. whereas our test commits its changes.

Thanks for flagging, I'll get a PR up to address this.

**Comment by mcrowder65** [comment]
Thank you so much 🙏 @gsoltis 

This is working by ignoring readme and jenkinsfiles, but I'm trying to have it ignore my test files when building, and I'm not sure it's working...

I have this:

```js
"inputs": [
        "src/!(*.test).js"
]
```
As my inputs, and it's not catching changes to my source js files...

I'm running turbo `v1.2.9-canary.1`

It's expecting a glob right?

This glob tester is saying my glob is correct, but I'm not sure https://www.digitalocean.com/community/tools/glob?comments=true&glob=src%2F%21%28%2A.test%29.js&matches=false&tests=src%2FApp.js&tests=src%2FApp.test.js

**Comment by gsoltis** [comment]
@mcrowder65 Currently, we pass `inputs` directly to `git`, which supports a bit of a [different syntax](https://css-tricks.com/git-pathspecs-and-how-to-use-them/).

I think this highlights an inconsistency on `turbo`'s side: we should be using consistent glob syntax wherever we can. So in the meantime, I suspect you can get it to work by smuggling through the proper `git <pathspec>` syntax, but in the future we may try do a unification that will ultimately cause that to break. Although hopefully still also give you tools to glob the files you want.

cc @nathanhammond re: globbing

**Comment by gsoltis** [comment]
I filed #1241 since I think that's the particular issue now.
