### ISSUE TITLE
ERROR  failed to calculate global hash: error hashing files

### ISSUE THREAD

**Issue by carpad88** [vercel/turborepo#1097]
### What version of Turborepo are you using?

1.2.4

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I keep getting this error when trying to deploy turborepo on vercel

```
ERROR  failed to calculate global hash: error hashing files. make sure that 
git has been initialized failed to hash files/vercel/path0/package.json, 
/vercel/path0/package-lock.json: git hash-object exited with status: exit status 128
```

### Expected Behavior

Get a succesful deployment

### To Reproduce

I have set up this command on Vercel

`cd ../.. && npx turbo run build --filter=medusa-admin --include-dependencies --no-deps`

And my turborepo is set uo like this

```json
{
  "pipeline": {
    "build": {
      "dependsOn": [
        "^build",
        "$GATSBY_MEDUSA_BACKEND_URL"
      ],
      "outputs": ["public/**"]
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "cache": false
    }
  }
}
```

**Comment by gabro** [comment]
Same issue with 1.2.5, it only happens on the CI.

I've downgraded to 1.2.3 and it fixes the issue, so this seems to be a regression introduced in 1.2.4.

**Comment by weyert** [comment]
Yes, having the same issue on my Mac

**Comment by lacherogwu** [comment]
Same here when I try to run ```npm run build``` on docker

I downgraded to version 1.2.3 and it's working.

**Comment by weyert** [comment]
This the error I am getting when running `pnpm run lint` which has the following script definition `turbo run lint --cache-dir=.turbo-cache --no-deps`.

>  ERROR  failed to calculate global hash: error hashing files. make sure that git has been initialized failed to hash files /Users/xxx/Development/Projects/monorepo-playground/package.json, /Users/xxx/Development/Projects/monorepo-playground/pnpm-lock.yaml: passed 2 file paths to Git to hash, but received 3 hashes
 ELIFECYCLE  Command failed with exit code 1.

**Comment by messenjer** [comment]
Same here when I try to run npm run build on ci gitlab (with turborepo v1.2.6).

I downgraded to version v1.2.3 and it's working.

**Comment by messenjer** [comment]
We are using the docker node 16-alpine : https://hub.docker.com/_/node 

This docker uses the alpine 3.15 : https://github.com/nodejs/docker-node/blob/4e0fff70002f51c2b121c9b231917abcb63d2b1a/16/alpine3.15/Dockerfile 

And the git version should be 2.34.2-r0  https://pkgs.alpinelinux.org/packages?name=git&branch=v3.15

**Comment by gsoltis** [comment]
I wasn't able to reproduce with that git version, but if anyone wants to try with a build from #1195 we should get a better error message to help track this down.

**Comment by MateoAV** [comment]
Hi, I am having the same issue. I already tried running the command with latest v1.2.8 of Turborepo and still showing:

```
ERROR  failed to calculate global hash: error hashing files. make sure that git has been initialized failed to hash files /Users/mateovivas/Documents/Gymdoor/gymdoor-mono/package.json, /Users/mateovivas/Documents/Gymdoor/gymdoor-mono/package-lock.json: git hash-object exited with status: exit status 128
error Command failed with exit code 1.
```

I think the problem started after I deleted the node_modules folder and the package-lock.json file to change my package manager to yarn. However, I have already commited my changes in git and still showing the error. When deploying the Github Actions workflow works fine.

**Comment by messenjer** [comment]
I think that the commit with the better message is not on v1.2.8. How can we test it?

**Comment by bezoerb** [comment]
Error message on v1.2.8:
> ERROR  failed to calculate global hash: error hashing files. make sure that git has been initialized failed to hash files directory/package.json, directory/package-lock.json: passed 2 file paths to Git to hash, but received 3 hashes

**Comment by bezoerb** [comment]
Fixed for me in v1.2.9

**Comment by dep** [comment]
Still a problem for me in `1.2.16`.  After using the quickstart instructions, I receive:

```
▶ npx turbo run test
 ERROR  failed to calculate global hash: error hashing files. make sure that git has been initialized failed to hash files /Users/dpeck/invoca/Titan/package.json, /Users/dpeck/invoca/Titan/package-lock.json: git hash-object exited with status: exit status 128. Output:
cbe71e18f1dd4bbc985e879b1b9b1c342996d452
fatal: could not open '/Users/dpeck/invoca/Titan/package-lock.json' for reading: No such file or directory
```

**Comment by sid9102** [comment]
Can confirm this is also an issue for me on 1.2.16 on a docker container. Tests run fine on my macbook, but fail in container.

**Comment by Erns** [comment]
This is an issue on my end.  v1.2.3 works, but all the newer ones appear that they don't.

This happened after we started to use pnpm and once we deleted the package-lock.json file.  Newer versions of turborepo ran dev command runs fine with pnpm when the package-lock.json is present from our npm remnants, but started to spit out this error when deleting the package-lock.json file.  Works fine downgrading to v1.2.3, however.

**Comment by gsoltis** [comment]
I *think* the `package-lock.json` issue might be separate from the `git` issue. 

@dep @sid9102 @Erns are you all trying to use `npm`? Or `pnpm`?

**Comment by sid9102** [comment]
npm in my case

**Comment by kevin-key1** [comment]
what worked for me in jenkins pipeline was using turbo@1.2.3 and using clean install rather than just install. hopefully this helps at least one super frustrated individual. wish i could give some sort of techy/cool explanation, but i'm just a noob and got lucky with 1 permutation out of probably 150

btw, using npm@8.3.0 with node@14 docker image

**Comment by jzecca** [comment]
Same issue with turborepo 1.3.1 + yarn on `node:16-alpine` docker image.


Everthing was working properly, until an hour ago when I restarted my containers:
```
ERROR  failed to calculate global hash: error hashing files.
make sure that git has been initialized failed to read `git hash-object`:
exec: "git": executable file not found in $PATH
```
I have no clue what I could have done to trigger this.

I removed all my `.turbo` & `node_modules` folders, pruned my container, restarted the Docker daemon, still no luck.

---

Ended up creating a simple `Dockerfile` as a workaround:
```dockerfile
FROM node:16-alpine
RUN apk add git
```
and using it in my `docker-compose.yml`:
```yaml
services:
    turbo:
        # image: node:16-alpine
        build:
            context: ./docker/node
```

**Comment by jzecca** [comment]
The error disappear if I remove
```json
  "globalDependencies": [
    ".eslintrc.js"
  ],
```
from my `turbo.json` file.


Looks like ***[this](https://github.com/vercel/turborepo/issues/531)*** could be the issue (my `.eslintrc.js` - and the whole folder - is mounted as a volume).
This would explain why I had no issue when building, since nothing is mounted at build time.

If confirmed, the issue probably needs to be reopen.

**Comment by benduran** [comment]
Confirmed this issue is also happening using `npm@8.14.0`. Specifically, it's the error about failing to compute the global hash. `pnpm` didn't have this issue (it currently has other issues not fully installing all deps)

**Comment by kellyndassler** [comment]
I am having a similar issue to @Erns -- I migrated my turbo/react app from npm to yarn, and upon deleting the package-lock.json, I get the same error message (when using latest version of turbo).

`ERROR  failed to calculate global hash: error hashing files. make sure that git has been initialized failed to read git hash-object: exit status 128`

Upon downgrading to 1.2.3, it works. Any update would be great!

**Comment by gsoltis** [comment]
@kellyndassler is `git` available in the environment where you are running this?

**Comment by firemuzzy** [comment]
just got the issue too as I am moving out stuff to a monorepo, does any body know of way to debug this? 

the hash-object command in workin in the terminal

```
❯ git hash-object turbo.json
ee4e7578d58631700adcbcfc0052dfe0852f140e
```

**Comment by yceffort** [comment]
after upgrade from 1.2.3 to 1.4.6, it happens.

```
> turbo run start

 WARNING  cannot find a .git folder. Falling back to manual file hashing (which may be slower). If you are running this build in a pruned directory, you can ignore this message. Otherwise, please initialize a git repository in the root of your monorepo
 ERROR  failed to calculate global hash: error hashing files: could not hash file pnpm-lock.yaml.
open pnpm-lock.yaml: no such file or directory
 ELIFECYCLE  Command failed with exit code 1.
```

1.2.3 works fine.

**Comment by pgonzalez-santiago** [comment]
Same issue in here. I removed package-lock.json to use yarn.lock instead and I am getting the error. I needed to downgrade turbo from `latest` version to `1.2.4`. In `1.2.5` appears de error.

**Comment by nathanhammond** [comment]
A large number of you are reporting issues with the same symptom but different underlying root causes. If you can create a reproduction starting from `npx create-turbo@latest` and share the repository we will be able to rapidly resolve your issue.

Alternatively, with enough information from everybody commenting on this issue, we may be able to guess how to create a reproduction on our side with enough reports. In order for your information to be actionable we need, at least:
- the array of things specified as `globalDependencies`.
- whether or not each of the files in `globalDependencies` exist.
- the output of `git hash-object` for each of the files in that array. (Path is from the repository root.)
- the specified `packageManager` in your `package.json` file, if any.
- the package manager you are using and version.
- whether or not you have run the install for your monorepo.
- git version
- node version
- are you using docker, and if so how is your container set up?

As of now we do not have enough information to resolve any of the issues reported here. I'm going to tag this as needing a reproduction, and once we have that we'll be able to resolve it.
