### ISSUE TITLE
git warning log output prevents correct hash generation

### ISSUE THREAD

**Issue by anchan828** [vercel/turborepo#1103]
### What version of Turborepo are you using?

1.2.5

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

I tried to run turbo run within docker-compose + node:16.14.2-alpine image, then got an error.

```
ERROR  failed to calculate global hash: error hashing files. make sure that git has been initialized failed to hash files /app/package.json, /app/package-lock.json: passed 2 file paths to Git to hash, but received 3 hashes
```

<img alt="ca7b7be9adbaa3cc5bbdbc0fa21b9d27" src="https://user-images.githubusercontent.com/694454/164895162-92aefaa3-a9b3-4384-a651-86de082ef47d.png">

### Expected Behavior

Ignore warning logs output by git and work correctly.

### To Reproduce

I have created a minimal reproduction repository: https://github.com/anchan828/turborepo-docker-node-issue

---
I have also done some research and will report back.

When I check the log output, I see that `git hash-object` is outputting a warning and the count is not correct.

```
warning: unable to access '/root/.config/git/attributes': Permission denied
474514748a2b748e95feffec18c188d90af9fb6e
236450b52fcc26600b536bd2012ef5ad88c265f2
```

I added the following code and verified that it works correctly, omitting the warning log, but there were problems in other areas as well.

```go
hashOrWarnings := offByOne[:len(offByOne)-1]

hashes := []string{}

for _, hashOrWarning := range hashOrWarnings {
	if strings.HasPrefix(hashOrWarning, "warning: ") {
		fmt.Printf("%v\n", hashOrWarning)
		// ignore warnings
		continue
	}
	hashes = append(hashes, hashOrWarning)
}
```

Similarly, `git status` also outputs warnings when run with `pipeline.task.inputs` in the turbo.json.

```
warning: unable to access '/root/.config/git/ignore': Permission denied
```

These are warnings and do not interfere with the operation of git. Therefore, turbo should also work correctly.
I think need to write a process to remove warning logs on all git command outputs.

**Comment by gsoltis** [comment]
@anchan828 can you confirm if this is fixed with the latest canary build? We are now only using `stdout` from `hash-object`, which I think should solve this.

**Comment by anchan828** [comment]
@gsoltis Is the latest canary build available? `1.2.9` appears to be the latest.

<img width="671" alt="5e4adaee8b7d2fff4e25d3ec58a33a00" src="https://user-images.githubusercontent.com/694454/168195073-ae11f0d4-7494-48a7-9ed6-4c1e7e8830de.png">
 
I tried with `1.2.9` but could not confirm due to other issues.

```
ERROR  reading user config file: could not create any of the following paths: /root/.config/turborepo, /etc/xdg/turborepo
```

![](https://t.gyazo.com/teams/unity/3201222e50007df0efdf82cac0c83986.png)

Updated repo: https://github.com/anchan828/turborepo-docker-node-issue

**Comment by anchan828** [comment]
I think this problem is the difference between the root user of Docker and the node user of the node image. If there is some solution and it is documented, I think be considered resolved...

**Comment by anchan828** [comment]
I think this is not a turbo issue, so I will close this issue. Thank you for the confirmation.
