### ISSUE TITLE
Cannot append `--filter` argument to package.json script when using PNPM

### ISSUE THREAD

**Issue by willster277** [vercel/turborepo#1104]
### What version of Turborepo are you using?

1.2.5

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

There is different behavior between NPM and PNPM when using the `--filter` option in conjunction with package json scripts.
This gives PNPM users a more difficult way of running multiple scripts while filtering packages, while NPM (and possibly yarn, I'm yet to test) users can do things in a simpler way.

PNPM users cannot add filters to one run of a package json script by running `pnpm my-turbo-script --filter=some-pkg`, as the filter will apply to pnpm, not turbo.
NPM users however can do this easily.

This means that PNPM users will have to either have a large bank of package json scripts, or they will have to type out the command in full if they want to use a filter, or use some hacky alternative.

### Expected Behavior

Regardless of package manager, the developer experience should be equally amazing. This means regardless of `pnpm`, `yarn`, or `npm run`, the script and flags that follow should have the same effect.

### To Reproduce

Setup a turborepo project however you like, ideally have several scripts known to turbo for each package.

In the root `package.json`, have the following script;
```jsonc
{
  "scripts": {
    "turbo:all": "turbo run build lint test" // or whatever scripts are known
  }
}
```

Run the following commands and observe their outputs;
```sh
npm run turbo:all --filter=some-pkg

pnpm turbo:all --filter=some-pkg

pnpm run turbo:all --filter=some-pkg
```

Notice that while the npm command correctly applies the `--filter` to turbo in the `turbo:all` script, the pnpm commands instead apply the `--filter` to pnpm itself, resulting in;
```
None of the selected packages has a "turbo:all" script
```

### To Clarify:

putting the `--filter` flag inside of the `scripts` in `package.json` as shown below does work, however calling some script `turbo:all` by running `pnpm turbo:all --filter=some-pkg` does not.

```jsonc
{
  "scripts": {
    "turbo:all": "turbo run build lint test --filter=some-pkg" // this works as expected
  }
}
```

**Comment by zanona** [comment]
Sorry if I'm missing something here, but on npm command arguments must be passed after a double dash when invoked through npm, like `npm run turbo:all -- --filter=some-pkg`, not sure if this is also the case with pnpm though.

**Comment by willster277** [comment]
:facepalm: of course, I had completely forgotten about that.
Interestingly though, on npm the `--` prior to the arguments isnt needed, at least not in this case.

Thank you for correcting me, the solution is to simply run
```sh
pnpm turbo:all -- --filter=some-pkg
```

**Comment by Snailedlt** [comment]
I know this is closed already, but for the people finding this issue, know that you can also use the --filter option before the script you want to run like this:  `pnpm --filter=some-pkg my-turbo-script`
