### ISSUE TITLE
ENV VAR to --force all tasks

### ISSUE THREAD

**Issue by sppatel** [vercel/turborepo#1122]
### Describe the feature you'd like to request

It would be good to have a ENV VAR that could trigger --force for all tasks.  This way in a CI environment you could have a parameterized build that forces a full run.  There 

### Describe the solution you'd like

An ENV VARIABLE called TURBO_FORCE that can be set as an alternate to --force.

### Describe alternatives you've considered

Have a CI parameter then then has to trickle down to all CI jobs to conditionally check if --force should be passed though.

**Comment by jaredpalmer** [comment]
This already exists? https://github.com/vercel/turborepo/blob/main/cli/internal/run/run.go#L476-L478

**Comment by sppatel** [comment]
Hmm, is this the same thing? with TURBO_REMOTE_ONLY=true set, its going to just ignore the local cache - but STILL read from the remote cache.   

With --force, as I understand you're bypassing both remote AND local caches and forcing the task to re-execute.  

So I'm not sure how TURBO_REMOTE_ONLY would address the scenario where you want to force reexecution across all CI jobs and repopulate the cache.

**Comment by jaredpalmer** [comment]
TURBO_FORCE is what you'd like
