### ISSUE TITLE
Can't build on windows when yarn in located in a path with a UTF-8 special character 

### ISSUE THREAD

**Issue by sebastienlabine** [vercel/turborepo#1130]
### What version of Turborepo are you using?

1.2.5

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

When running yarn turbo run build, the build fails saying it can't find yarn 

```
Error: Cannot find module 'C:\Users\S├®bastien\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js'
```
However yarn is located at this path. 

Running npx turbo run build works. My guess is that it's an encoding problem, that makes it impossible to find yarn and breaking the build.

### Expected Behavior

Being able to build my packages.

### To Reproduce

Install yarn in a folder with a UTF-8 encoding special character. 

Create a turbo build repo.

Have a package that can be build with lets say rollup.

run ` yarn turbo run build`

**Comment by nathanhammond** [comment]
Heya @sebastienlabine! I would need a *lot* more information about your setup (Windows is complicated) in order to attempt to debug this.

One hypothesis is that it is a Yarn issue. For example, here is the same issue showing up in another place: https://qna.habr.com/q/1103156

As a step one in debugging, if you install turbo globally (e.g. `npm install -g turbo`) you can directly execute `turbo run build`. Do you get the same output?

Also, when you pass information back, can you paste the entire error message and stack?

**Comment by sebastienlabine** [comment]
hey @nathanhammond! 

I agree, from the looks of it could be a yarn issue. He also has an utf-8 character in his yarn path, so pretty sure it narrows it down to a common problem.  Plus, it only happens when running the script using yarn run. From what I can observe, I have no problem with running the command using npx or from turbo when it's installed globally.

Here's the output of yarn build (which calls turbo run build)
```powershell
$ turbo run build
• Packages in scope: @smartbills/core-ui, @smartbills/react, @smartbills/react-charts, @smartbills/react-core, @smartbills/react-native, @smartbills/styles
• Running build in 6 packages
• Remote computation caching enabled (experimental)
@smartbills/react-native:build: cache miss, executing 4201f9421be5d37f
@smartbills/react-core:build: cache miss, executing c96331a4de81c0e7
@smartbills/react-native:build: node:internal/modules/cjs/loader:936
@smartbills/react-native:build:   throw err;
@smartbills/react-native:build:   ^
@smartbills/react-native:build:
@smartbills/react-native:build: Error: Cannot find module 'C:\Users\S├®bastien Labine\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js'
@smartbills/react-native:build:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
@smartbills/react-native:build:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
@smartbills/react-native:build:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
@smartbills/react-native:build:     at node:internal/main/run_main_module:17:47 {
@smartbills/react-native:build:   code: 'MODULE_NOT_FOUND',
@smartbills/react-native:build:   requireStack: []
@smartbills/react-native:build: }
@smartbills/react-core:build: node:internal/modules/cjs/loader:936
@smartbills/react-core:build:   throw err;
@smartbills/react-core:build:   ^
@smartbills/react-core:build:
@smartbills/react-core:build: Error: Cannot find module 'C:\Users\S├®bastien Labine\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js'
@smartbills/react-core:build:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
@smartbills/react-core:build:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
@smartbills/react-core:build:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
@smartbills/react-core:build:     at node:internal/main/run_main_module:17:47 {
@smartbills/react-core:build:   code: 'MODULE_NOT_FOUND',
@smartbills/react-core:build:   requireStack: []
@smartbills/react-core:build: }
@smartbills/react-core:build: Error: command finished with error: command (packages\react-core) yarn run build exited (1)
@smartbills/react-native:build: Error: command finished with error: command (packages\react-native) yarn run build exited (1)
@smartbills/react-charts:build: cache miss, executing 59d0a6f0ff489fb1
```

**Comment by nathanhammond** [comment]
Starting to look even more like a yarn issue. If you switch package managers to `npm`, does that work?￼

**Comment by sebastienlabine** [comment]
Yes it works. Will report to the proper channels! Thanks.
