### ISSUE TITLE
Improve demo repo with incremental build example

### ISSUE THREAD

**Issue by finn-orsini** [vercel/turborepo#1136]
### Describe the feature you'd like to request

When running `npx create-turbo@latest`, the resulting repo does not showcase one of `turbo`s most appealing features - `incremental builds`, i.e. the first bullet point [here](https://turborepo.org/docs#why-turborepo): 

> Incremental builds: Building once is painful enough, Turborepo will remember what you've built and skip the stuff that's already been computed.

The generated repo contains three libraries and two applications - but none of the libraries have their own build script. Without one, they are built as part of the application builds. This does not illustrate that turbo can cache the build of libraries that have not been updated.

<details> <summary> More Detail If Needed </summary> 

A version of the generated repo can be seen [here](https://github.com/finn-orsini/turbo-repro-filter-dry-output). In the generated example, `turbo run build` only runs two tasks: `web:build` and `docs:build`. When any of the applications or libraries change, they are fully rebuilt. This includes re-building the consumed library, even if it was not updated.

If one of the libraries is updated to have a build script, the behavior changes to include that as a separate task - `web:build`, `docs:build`, and `ui:build`.

This is illustrated on the [`lib_build_example`](https://github.com/finn-orsini/turbo-repro-filter-dry-output/pull/1) branch of the example repo. Note - this is probably not a great example overall, but serves the purpose for this issue.

Now, if one of the apps changes without changing the above library, the library build is cached, i.e. `ui:build: cache hit, replaying output 02bfc9ed4d3fe559`, and the overall build will contain the three tasks: 

```
Tasks:    3 successful, 3 total
Cached:    1 cached, 3 total
Time:    14.499s
```
</details>

### Describe the solution you'd like

In the generated repository, at least one of the libraries contains a build script to demonstrate incremental builds.

### Describe alternatives you've considered

Would be fine to leave as-is if folks don't agree that this is an important feature to showcase.

**Comment by tknickman** [comment]
Thanks for the suggestion! We're working through adding some new examples now. The `tailwindcss` example was just merged this week and contains a package (ui) with a build script that showcases this exact feature. 

You can check it out here: https://github.com/vercel/turborepo/blob/main/examples/with-tailwind/packages/ui/package.json
