### ISSUE TITLE
Directories named `test` or `tests` are ignored

### ISSUE THREAD

**Issue by kraenhansen** [vercel/turborepo#1143]
### What version of Turborepo are you using?

1.2.5

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a repo with a sub-package named `tests` and I'm experiencing issues running scripts in it using `turbo run`.
Basically it seems turbo completely ignores the existence of it.
While building the repro, I found the same behaviour when the directory is named `test`.

I suspect this is the offending source-code: https://github.com/vercel/turborepo/blob/main/cli/internal/context/context.go#L385-L386

I've narrowed it down to [this PR](https://github.com/vercel/turborepo/pull/310), first released as turbo@1.0.15 and verified the bug does not appear on turbo@1.0.14.

### Expected Behavior

I'd expect Turbo to recognise any directory matched by the `workspaces` array of the root `package.json`.

If this is indeed intended behaviour I would expect this being explicitly called out on [Docs / Troubleshooting](https://turborepo.org/docs/troubleshooting) and perhaps [Docs / Guides / Migrate from Lerna](https://turborepo.org/docs/guides/migrate-from-lerna) (since that was a perfectly valid configuration with Lerna).

### To Reproduce

See https://github.com/kraenhansen/turbo-test-issue for a complete reproduction.

Steps it takes:
1. Create a mono-repo with three sub-packages explicitly mentioned in the root's `package.json`, two of which should have their directories named `test` and `tests` respectively.
2. Add a `build` script to all of the sub-packages.
3. Initialize a `turbo.json` with a pipeline containing `"build": { "dependsOn": ["^build"] }`.
4. Try running the build command (use `--dry-run` to keep things clean) and notice how the `test` and `tests` packages are not listed in "Packages in Scope".

**Comment by nathanhammond** [comment]
So, you're right, this is behaving precisely as I would have expected. 😅 I even wrote some tests to ensure that `includes` couldn't overwrite `excludes` this week.

One of the upcoming things that we have on our list is to make sure that `getWorkspaceIgnores` matches the upstream behavior in each package manager precisely, at which point this behavior will definitely be addressed.

We've already tracked down those places and plan to port over the logic. In the mean time I *believe* we can drop the `tests` ignores. I'll make sure that I [find out why it was added](https://en.wiktionary.org/wiki/Chesterton%27s_fence) and see what's going on.

***

npm:
https://github.com/npm/map-workspaces/

pnpm:
https://github.com/pnpm/pnpm/tree/main/packages/find-packages
https://github.com/pnpm/pnpm/blob/3966afcecea69c9c8ee8c495bc4bde8f39da9e95/packages/find-workspace-packages/src/index.ts#L32

berry:
https://github.com/yarnpkg/berry/blob/8e0c4b897b0881878a1f901230ea49b7c8113fbe/packages/yarnpkg-core/sources/Workspace.ts#L62-L64
https://github.com/yarnpkg/berry/blob/a23509561b9bac2e6375d05a18f2cdc920793f7d/packages/yarnpkg-core/sources/Manifest.ts#L414-L433

yarn:
https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/config.js#L856
https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/config.js#L819-L826

**Comment by nathanhammond** [comment]
(Thank you for the detailed report and making this easy.)
