### ISSUE TITLE
prune command failing with --cwd

### ISSUE THREAD

**Issue by fr0609** [vercel/turborepo#1159]
### What version of Turborepo are you using?

1.2.5

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

--cwd command not working.

### Expected Behavior

--cwd command works

### To Reproduce

Run
```
turbo prune --scope=rs-frontend --docker --cwd=./out/rs-frontend
```
Getting

ERROR  package.json: open /Users/dev/monorepo/out/rs-frontend/package.json: no such file or directory

I upgraded from 1.1.2 to 1.2.5 and the --cwd command is no longer working for me.

**Comment by gsoltis** [comment]
`--cwd` is intended for setting the root of the monorepo when `turbo` is being run in a different directory. In this case, it does not set the output of `turbo prune`. The output directory is currently always going to to be `<monorepo root>/out`

**Comment by ewnd9** [comment]
I rely on this behaviour (setting unique `--cwd`) to build docker containers concurrently (see https://github.com/ewnd9/node-grpc-micro-services-demo/blob/436e5b59171b2a955aef098d505f9ac14d70f530/packages/shared/tooling/src/turbo-docker.ts#L27, `turbo@1.1.2`)

@gsoltis Is there any workaround?
