### ISSUE TITLE
Running pipelines with --filter using globs not working

### ISSUE THREAD

**Issue by wouter-leistra** [vercel/turborepo#1199]
### What version of Turborepo are you using?

1.2.8

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Starting today after updating to turborepo 1.2.8 through @latest, I can no longer successfully use the `--filter=pkg-*` on my terminal. A message is shown that no packages could be found / mismatch.

I use Fish terminal (if that matters at all I don't know) 

### Expected Behavior

It works as documented, like in prior versions. 

### To Reproduce

Set up a monorepo with multiple packages, using yarn 1 workspaces and attempt to run a pipeline with filter argument utilizing globs

**Comment by raphaelluchini** [comment]
I am using 1.5.6 and facing the same issue. Could somebody help? :)

**Comment by wouter-leistra** [comment]
Yeah using "'s resolved the issue for me as well.

**Comment by nathanhammond** [comment]
If you find this issue via search: all filters can be quoted, and _should_ be quoted if your shell does any sort of expansion.

I'm closing and locking this issue. If you encounter something weird with quoting please file a new issue.
