### ISSUE TITLE
 Different caches per OS

### ISSUE THREAD

**Issue by Suyashtnt** [vercel/turborepo#1205]
### Describe the feature you'd like to request

There should be an ability where you can set caches to be different depending on the OS. E.g if a windows pc a MacOS computer cannot use the cache and has to make its own, but a windows computer can use the cache. This is specifically for remote caching reasons across CI builds, as with rust the caches builds are platform-depentent, and a windows build will not work on linux.

### Describe the solution you'd like

In the turbo.json file you can set a pipeline to be platform-dependent somehow. E.g pipelines.pipeline.cachePerPlatform

### Describe alternatives you've considered

What I’m doing currently is disabling remote caching

**Comment by lodmfjord** [comment]
https://turborepo.org/docs/reference/configuration

Isn't the simplest solution using globalDependencies with different env between platforms?

**Comment by Suyashtnt** [comment]
> [turborepo.org/docs/reference/configuration](https://turborepo.org/docs/reference/configuration)
> 
> Isn't the simplest solution using globalDependencies with different env between platforms?

I didnt know you could use it via env vars. TIL
