### ISSUE TITLE
examples with yarn2

### ISSUE THREAD

**Issue by matart15** [vercel/turborepo#1210]
### Describe the feature you'd like to request

Looks like yarn2 ( now yarn 3 ) is supported 
https://github.com/vercel/turborepo/issues/1017

But I am not sure how to change to yarn3. 

Should I do it on root folder only or on each packages and apps? Cuz, yarn3 creates .yarn folder in them

### Describe the solution you'd like

it would be nice to have 1 example with yarn3, if it is suppported.

### Describe alternatives you've considered

not sure

**Comment by lodmfjord** [comment]
```sh
yarn set version 3.x
```

from the projects root folder.

**Comment by matart15** [comment]
thank you.
