### ISSUE TITLE
Example broken in vercel build with `'eslint-config-custom@*' is not in this registry.`

### ISSUE THREAD

**Issue by jacobcoro** [vercel/turborepo#1218]
### What version of Turborepo are you using?

@latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Followed the demo [here](https://www.youtube.com/watch?v=_sB2E1XnzOY&t=204s) word for word.
Pushing to vercel it gives the error in the title.

I suspect it was related to this recent change? https://github.com/vercel/turborepo/pull/1174

### Expected Behavior

It to build

### To Reproduce

Follow the demo, or clone my repo https://github.com/jacobcoro/kava-turborepo

**Comment by jacobcoro** [comment]
Tried renaming acme to custom. No dice.

**Comment by jacobcoro** [comment]
Vercel was also not able to find the shared tsconfig during build
`web:build: error TS6053: File 'tsconfig/nextjs.json' not found.`

**Comment by jacobcoro** [comment]
Used a relative import for that and it got the next error:
```


web:build: Type error: Cannot find module 'ui' or its corresponding type declarations.
--


<span>web:build: </span><span class="ansi_bold__mDgXl ansi_fg-red__BW_zV">&gt;</span><span class="ansi_fg-gray__HbNfh"> 1 | </span><span class="ansi_fg-cyan__S1J1P">import</span><span> { </span><span class="ansi_fg-yellow__Py4n4">Button</span><span> } from </span><span class="ansi_fg-green__raq3f">"ui"</span><span class="ansi_fg-yellow__Py4n4">;</span>
```

It seems that during the vercel build, none of the monorepo links, aka,
`"local-link" : "*"`
are working

**Comment by jacobcoro** [comment]
Looks like I was missing this install prefix line from here: https://vercel.com/docs/concepts/git/monorepos#step-3.5:-optional-settings-if-using-npm-workspaces

Guess this is a RDFTM moment. But pretty upset that that video wasted 3 hours of my life debugging this crap.

**Comment by ybidois** [comment]
Hi @jacobcoro, having the same issue, but no docs anymore about the settings. Can you tell me what that prefix line was?

**Comment by ybidois** [comment]
I just found it back on another page thanks to a thorough Google Search: https://vercel.com/docs/concepts/monorepos/turborepo

**Comment by nathanhammond** [comment]
@mattpocock This video apparently needs to note a bit about the `install command` on Vercel: https://www.youtube.com/watch?v=_sB2E1XnzOY&t=204s
