### ISSUE TITLE
Cache is hit after dependency files were changed

### ISSUE THREAD

**Issue by cinan** [vercel/turborepo#1221]
### What version of Turborepo are you using?

1.2.8

### What package manager are you using / does the bug impact?

Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

In some cases, cache is hit (altough it should be missed) after package dependencies has been changed.

### Expected Behavior

Cache should be missed.

### To Reproduce

Testing repo: https://github.com/cinan/turbo-cache-bug (this is vanilla turborepo installed with `npx create-turbo@latest`)

I ran `yarn lint` for the 1st time to build new cache. After that I changed `packages/eslint-config-acme/index.js` content and re-ran `yarn lint`. I can see `FULL TURBO` -- all caches are hit.

The 2nd time I ran `yarn lint` I'd expect cache is missed for all packages where `eslint-config-custom` dependency is mentiond in dependencies list.

**Comment by gsoltis** [comment]
I think this is behaving as expected. The `eslint-config-custom` doesn't define a `lint` task, so it doesn't get run. And the `lint` task definition in `turbo.json` doesn't list any dependencies, as typically linting a package doesn't depend on linting its dependencies. 

So you've changed a package without a `lint` script, then asked `turbo` to run `lint` again, but nothing relevant to linting the packages that have a `lint` script has changed.
