### ISSUE TITLE
Basic starter project with pnpm fails to lint

### ISSUE THREAD

**Issue by Ryshackleton** [vercel/turborepo#1238]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

After creating a monorepo using `pnpx create-turbo@latest`, if I run `pnpm run lint`, I get the following error:

```
ui:lint: ESLint couldn't find the config "custom" to extend from. Please check that the name of the config is correct.
ui:lint:
ui:lint: The config "custom" was referenced from the config file in "/Users/ryshackleton/REPOS/basic-pnpm/.eslintrc.js".
ui:lint:
ui:lint: If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
ui:lint:
ui:lint:  ELIFECYCLE  Command failed with exit code 2.
ui:lint: Error: command finished with error: command (packages/ui) pnpm run lint exited (1)
```

I am using pnpm@7.0.1 and have noticed [this issue](https://github.com/vercel/turborepo/issues/1190) as well, but was still able to install packages and run the build commands. 

### Expected Behavior

I would expect lint scripts in the example projects to work out of the box. As it stands I have no idea how to configure lint files as packages if the example project doesn't function as expected.   The comment in the `.eslintrc.json` file in the example states that:
```
  // This tells ESLint to load the config from the package eslint-config-custom
  extends: ["custom"],
```

However, if the lint script doesn't work, I have no idea how to correctly specify the `eslint-config-custom` as the config to load from.

### To Reproduce

1. `pnpx create-turbo@latest`
2. Choose a name: `my-pnpm-repo`
3. Choose a package manager: `pnpm`
4. `cd my-pnpm-repo`
5. `pnpm run lint`

It's worth noting that `pnpm run build` works just fine for me.

**Comment by itstheandre** [comment]
Also happened to me

**Comment by jacksonblankenship** [comment]
Happening to me as well

**Comment by jacksonblankenship** [comment]
You need to add `eslint-config-custom` to your root project dev dependencies.


`./package.json`
```json
{
  "devDependencies": {
    "eslint-config-custom": "workspace:*",
  },
}
```

**Comment by NatoBoram** [comment]
> You need to add `eslint-config-custom` to your root project dev dependencies.
> 
> `./package.json`
> 
> ```json
> {
>   "devDependencies": {
>     "eslint-config-custom": "workspace:*",
>   },
> }
> ```
> 
> https://github.com/vercel/turborepo/blob/main/examples/with-pnpm/package.json

**404 - page not found**

The `main` branch of `turbo` does not contain the path `examples/with-pnpm/package.json`.

**Comment by jon-ressio** [comment]
Looks like the pnpm example was removed between v1.6.3 and v1.7.0 (technically looks like removed in the v1.6.4 canary).  Would be nice to get that restored.  Following the pnpm example worked for me where the https://turbo.build/repo/docs/guides/tools/eslint guide didn't work.  I got errors like eslint couldn't find the next.js file in my eslint custom config package.

https://github.com/vercel/turborepo/tree/v1.6.3/examples/with-pnpm
https://github.com/vercel/turborepo/tree/v1.7.0/examples/with-pnpm
