### ISSUE TITLE
Turbo uses inconsistent globbing syntax

### ISSUE THREAD

**Issue by gsoltis** [vercel/turborepo#1241]
### What version of Turborepo are you using?

1.2.9

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

In some cases, `turbo` uses the `doublestar` globbing syntax. In other cases, globs get passed to `git`, which has its own [syntax](https://css-tricks.com/git-pathspecs-and-how-to-use-them/). 

### Expected Behavior

Passing a glob to `turbo` should be the same everywhere

### To Reproduce

Compare globs used in `outputs` vs `inputs`

**Comment by mcrowder65** [comment]
Thanks @gsoltis 🙏

**Comment by unional** [comment]
I think this is a big one. Also discovering this. And it looks pretty bad.

A simple config:

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "baseBranch": "origin/main",
  "pipeline": {
    "build": {
      "inputs": [
        "src/**/*.ts"
      ]
    }
  }
}
```

This does not detect changes in `src/*.ts`. It only detects `src/abc/def.ts`

**Comment by sppatel** [comment]
I opened https://github.com/vercel/turborepo/issues/1250 before seeing this - seems related.

**Comment by alexn-s** [comment]
apparently i encountered the same bug. i thought the bug was the hashing and not globs. is there any progress on this matter? it is really counter intuitive

**Comment by cpitt** [comment]
Just hit this as well.... Some better documentation is probably needed until this get fixed. very confusing... pathspec is not glob

for now this is what I have using pathspec with the glob directive.... 

```json
      "inputs": [":(glob)src/**/*.[jt]s", ":(glob)src/**/*.[jt]sx"],
```

**Comment by dobesv** [comment]
I opened a PR to at least document the different rules, I guess that could be one solution the problem.  Although it's not as ideal as getting the globbing to be the same everywhere:

https://github.com/vercel/turborepo/pull/1690/files

**Comment by gsoltis** [comment]
Closing, as of v1.4.4, `turbo` uses doublestar for globbing inputs and outputs
