### ISSUE TITLE
Error while reading user config file

### ISSUE THREAD

**Issue by ooflorent** [vercel/turborepo#1270]
### What version of Turborepo are you using?

1.2.7

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

After updating `turbo` from 1.2.6 to 1.2.7, turbo crashes when it is launched. I run it in a node v16 container on self hosted GitHub Actions runner. When ran locally (on my MBP), it runs as expected.

```
$ turbo run test
 ERROR  reading user config file: could not create any of the following paths: /.config/turborepo, /etc/xdg/turborepo
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems that #1156 introduces the issue.

### Expected Behavior

`turbo` should not crash on startup if it is unable to read the user config file.

### To Reproduce

I'm not sure what to provide here…

**Comment by jaredpalmer** [comment]
Is this still happening in 1.2.9

**Comment by ooflorent** [comment]
Yes. With the same error:
```
 ERROR  reading user config file: could not create any of the following paths: /.config/turborepo, /etc/xdg/turborepo
```

**Comment by ronaldh46** [comment]
I am also getting this error using Azure DevOps Pipelines CI/CD, using the latest Turborepo.

```
> turborepo-basic-shared@0.0.0 build
> turbo run build

 ERROR  reading user config file: could not create any of the following paths: /home/vsts/.config/turborepo, /etc/xdg/turborepo
```

Any updates?

**Comment by nathanhammond** [comment]
Hey y'all, apologies for the delay. I believe that #1328 should address this issue and make sure that we don't encounter it again.
