### ISSUE TITLE
Unable to use turbo from 1.2.6+

### ISSUE THREAD

**Issue by weyert** [vercel/turborepo#1282]
### What version of Turborepo are you using?

1.2.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Executing a command like `pnpm exec turbo run test --concurrency=1` for 1.2.6+ causes a high cpu usages and memory usages and a command that causes close to 100% cpu usages and a memory usages up 25gb+ (system has 16gb). After a while the `turbo` instance will cause the computer to slow down and a forced restart (power button)

Unable to use `turbo` to execute a task command defined

### Expected Behavior

Able to execute the command in a similar manner as on 1.2.5 without high cpu and memory usage

### To Reproduce

MacBook Pro 14" M1
Latest maCOS
PNPM 6.32.9

Small mono-repo with ~49 packages 

run the command:

```bash
pnpm exec turbo run test --concurrency=1 --continue
```

**Comment by gsoltis** [comment]
Yikes. Can you verify that `--dry` works? What happens if you run w/o `--continue`?

**Comment by weyert** [comment]
Appears to have been resolved in most recent releases of `turbo`. Closing this ticket for now :)
