### ISSUE TITLE
Unable to --ignore root level task

### ISSUE THREAD

**Issue by sppatel** [vercel/turborepo#1284]
### What version of Turborepo are you using?

1.2.11

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I adopting 1.2.11 for root level tasks.  It appears as if applying the root filter `--filter=//` works as expected.  However the --ignore filter `--ignore=//` does not.  I've tried other alternatives such as `--ignore=*` `--ignore='./'` - neither work.

### Expected Behavior

Should be able to ignore root out.

### To Reproduce

(1) add a root level task.
(2) run the task with `--ignore=//`
(3) The root task still runs.

**Comment by gsoltis** [comment]
What directory specifically are you trying to ignore? Something like `<ROOT>/out`?

**Comment by sppatel** [comment]
Wanting to ignore the root task itself.  So for example.. If I have..
```
  "//#format": {
      "outputs": []
    },
    "format": {
      "inputs": [
        "*.js",
        "*.jsx",
        "*.ts",
        "*.tsx",
        "*.json",
        "*.md",
        "**/*.js",
        "**/*.jsx",
        "**/*.ts",
        "**/*.tsx",
        "**/*.json",
        "**/*.md"
      ],
      "outputs": []
    },
```

`turbo run format` would run format in all workspace packages AND the format script specified in the root package.json.  This is great.

`turbo run format --filter=//` would run the format script ONLY in the root package.json.  Also 💯 

However, I have a need to also run format on all workspace packages EXCEPT root.  I would have expected that

`turbo run format --ignore=//` would have excluded execution of the root package.json's format script and just run the ones for each package but the exclusion of `//` is not being respected.

Hopefully that clarrifies.

**Comment by gsoltis** [comment]
Ah, gotcha. You're looking for `--filter=!//`. Note that you'll need to escape as appropriate for your shell (mine is `--filter=\!//`). This tells `turbo` to "select every package except the root".

`--ignore` is for specifying files to ignore when calculating which packages have changed.
