### ISSUE TITLE
Make `--graph` option print to stdout by default

### ISSUE THREAD

**Issue by cowboyd** [vercel/turborepo#1286]
### Describe the feature you'd like to request

The `--graph` option was actually _way_ more useful before I installed graphviz. It is more

* visually succinct
* ergonomic. It requires only a single step instead of three (issue command, read location of output, open with app to read output)
* shareable via copy paste into chat applications and GitHub issues
* composable via unix pipes
* accessible to users with limited vision.

I would like a way to be able to use the stdout print by default and without a warning to use graphviz.

### Describe the solution you'd like

`--graph` by itself prints to stdout by default

This is what you want most of the time to quickly see, debug, and share a graph.

`--graph=FILENAME` prints to the filename using graphviz.

This takes a bit longer, but may be required for certain workflows.

### Describe alternatives you've considered

Two options, default is graphviz

* `--graph`
* `--graph-stdout`

Two options, default is stdout

* `--graph`
* `--graphviz`

A special file reference for stdout:

* `--graph <stdout>`

**Comment by gsoltis** [comment]
I think this could be a good upgrade after #1298 lands. It could follow a similar model to how `--dry-run` is handled, flag-wise.
