### ISSUE TITLE
Caching doesn't seem to correctly bust when discarding git changes

### ISSUE THREAD

**Issue by mmussmann** [vercel/turborepo#1323]
### What version of Turborepo are you using?

1.2.14

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

**Description**
I have setup a validate command that run linting and testing on all the projects. I have found that when I discard a change through e.g. vscode git integration then the turbo cache doesn't seem to bust and just registers a cache hit and outputs the same result as before the discard. 

**Prerequisites**
In the project we have setup some jest tests

**NOTE**
It's only if the changes are being discarded with the git integration.

We have also tried to add the source files the input array but that doesn't change anything.

**Turbo config**
`{
  "$schema": "https://turborepo.org/schema.json",
  "baseBranch": "origin/main",
  "pipeline": {
    "validate": {
      "outputs": []
    }
  },
  "globalDependencies": [".env", ".env.*"]
}
`

### Expected Behavior

I would expect turbo to register a cache **miss** since the files have changed

### To Reproduce

1. Add "expect(false).toBe(true);" to a test
2. Run validate command ( _This works just fine, the command line will register cache miss and output an error_)
4. Discard the test change through vscode source control -> discard
5. Rerun validate command

**Expected**
I would expect turbo to register a cache **miss** since the files have changed

**Actual behavior seen**
Turbo registers a cache hit and outputs the test error even though that code has been discarded.

**Comment by tknickman** [comment]
@mmussmann I just tried to repro this with `npx create-turbo` using `1.2.14` and it looks to be working for me. It's important to note you _should_ be getting a cache hit after discarding changes, but it should **not** be an error. 

For example:
1. `run validate` 
    - SUCCESS
    - cache miss - cashes with hash `xyz`
1. make a breaking change
1. `run validate` 
   - FAIL 
   - cache miss 
1. revert change through vscode source control -> discard
1. `run validate`
   - SUCCESS 
   - cache hit on `xyz`

If you could provide a minimal repro case to help us debug further that would be awesome.

**Comment by mmussmann** [comment]
Yes agreed should be getting a cache hit. but it's reusing the same cache that contains the failure. 

I will see if i can reproduce in a smaller repo and get back.

**Comment by tknickman** [comment]
Great, thanks @mmussmann.

**Comment by mmussmann** [comment]
I have done some work to try and reproduce it in a smaller scale. This is what I came up with. When I follow below steps I get the issue every time. 

NOTE:
Step 4 is key, without that it seems to work.

**Quick how to reproduce:**
1. git clone https://github.com/mmussmann/turbo-caching.git
2. cd turbo-caching
3. pnpm i
4. pnpm test
5. Open packages\ui\Button.test.tsx
6. Update toBe(true) -> toBe(false)
7. pnpm test 
8. git reset --hard
9. pnpm test

**The repo**
It's a repo created with "npx create-turbo" with pnpm setting, then adding jest to reproduce the issue in an easy way.

**Additional system info**
Windows version: Windows 10 Pro
Version: 21H1

**Comment by mmussmann** [comment]
Tried updating my windows version to 21H2, but it didn't make any difference. I can still reproduce it every time, following above steps.

**Comment by mmussmann** [comment]
I did a test using **1.2.17-canary.0**. 

The bug no longer exists, it doesn't find the old cache from the first test. I don't know if it should do that?

But anycase, it would then be a matter of having a cache miss that wasn't needed which is much preferable over having a incorrect cache hit :).

**Comment by nathanhammond** [comment]
@mmussmann We updated the global cache key to stop restoration of possibly-broken caches, so what you're seeing is expected and correct! 👍
