### ISSUE TITLE
eslint doesn't respect eslint-config-custom packages

### ISSUE THREAD

**Issue by arisunarya** [vercel/turborepo#1329]
### What version of Turborepo are you using?

1.2.16

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

so today, i'm generating new turborepo files, when i try to configuring eslint rules on `packages/eslint-config-custom/index.js` it seem's that eslint doesn't respect that, after some investigation turn's out that `eslint-config-custom` is set to `latest`
```
"devDependencies": {
  "eslint-config-custom": "latest",
  "prettier": "latest",
  "turbo": "latest"
}
  ```
  
and i believe that `eslint-config-custom` package are pointing out to this npm packages: https://www.npmjs.com/package/eslint-config-custom

so i try to change `"eslint-config-custom": "latest"` to `"eslint-config-custom": "*"` and its work normaly and respect the config

### Expected Behavior

eslint should respect `eslint-config-custom` config on package folder

### To Reproduce

`npx create-turbo@latest`

**Comment by tknickman** [comment]
Good catch. This was a regression introduced via https://github.com/vercel/turborepo/pull/1325

I'll get this fixed today!
