### ISSUE TITLE
Cannot find root package when filtering by changed packages

### ISSUE THREAD

**Issue by AlbinIzi** [vercel/turborepo#1333]
### What version of Turborepo are you using?

1.2.16

### What package manager are you using / does the bug impact?

Yarn v3, npm

### What operating system are you using?

Linux, Mac

### Describe the Bug

An error occurred when we try to run a command only on changed packages, the root package is not found when file hashes are calculated.
I detected this bug since version 1.2.10.

### Expected Behavior

The command should be triggered on modified packages compare to the specified branch.

### To Reproduce

In your repository, go to the basic example (examples/basic) and run the commands:
`npm i`
`npx turbo run build --filter="...[origin/pnpm]"`

you will see the error:
` ERROR  error hashing package files: cannot find package`

**Comment by jonaslindstr** [comment]
I can add that the command works if you specify an explicit package or a path, e.g. `--filter="web...[origin/pnpm]"` but not if you leave out that part.

**Comment by flex-jonghyen** [comment]
I have same problem.

**Comment by marvinroger** [comment]
Yes, the error `ERROR error hashing package files: cannot find package` seems to happen when turbo tries to hash the root workspace. The 1.2.10 introduced https://github.com/vercel/turborepo/pull/1040, maybe the issue was introduced in this PR?

**Comment by drummerjolev** [comment]
Happening to me as well:

<img width="408" alt="Screenshot 2022-06-16 at 09 23 24" src="https://user-images.githubusercontent.com/5412193/174026656-5b99f389-4bc7-41bf-8cca-54d21b77944f.png">

In an existing Turborepo, I added a new package, ran the command and the error happened. Reproduced both on my local machine and a Github Action.

**Comment by piter2k1** [comment]
I also have same problem (`turbo@1.3.1`) with `--since=origin/master` or with `--filter=...[origin/master]`. When I downgrade `turbo` to `1.2.9` problem gone and all works properly. So, problem exists since `turbo@1.2.10`.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/749112/175832636-23fe0005-9f75-4857-b2c6-fd01adad3b0f.png">

**Comment by gsoltis** [comment]
Are you trying to use tasks from the root package?

Could you put together a small sample repo that demonstrates the issue?

**Comment by AlbinIzi** [comment]
You can reproduce with this repository, go to the basic example (examples/basic) and run the commands:
npm i
npx turbo run build --filter="...[origin/pnpm]"

you will see the error:
ERROR error hashing package files: cannot find package

**Comment by marvinroger** [comment]
@gsoltis I think I found the culprit: in the `examples/basic` example, where the issues happens, removing [this line](https://github.com/vercel/turborepo/blob/d83130a8b30b01ae2ce1627f4188e791598ea8b3/examples/basic/package.json#L15) fixes the issue.

It seems that if the root package have either a `dependencies` or `devDependencies` to a workspace in the monorepo (which is a perfectly valid use-case), the issue appears.

**Comment by gsoltis** [comment]
Got it, confirmed I can reproduce it. I'll see what I can do to get this fixed.
