### ISSUE TITLE
When scope does not match any projects, print a warning about falling back to running all projects

### ISSUE THREAD

**Issue by ofirgeller** [vercel/turborepo#1338]
### Describe the feature you'd like to request

if I specify a scope that does not match any projects, turborepo sets the scope to be * (all projects). 

### Describe the solution you'd like

It would be nice if there was a warning printed since this is probably not intentional use of the scope parameter.

### Describe alternatives you've considered

An error might be even better with a flag added for backward compatibility.

**Comment by gsoltis** [comment]
Can you use `--filter` instead of `--scope`? It does not fall back to "all packages" when nothing is matched.

**Comment by ofirgellerSM** [comment]
@gsoltis my version (1.1.0-canary.2) does not have it. will upgrade and let you know! thanks

**Comment by ofirgellerSM** [comment]
yep, filter works for my use case.  thanks!
