### ISSUE TITLE
Can't pass arguments to the underlying command when using `--filter`

### ISSUE THREAD

**Issue by ivolimasilva** [vercel/turborepo#1355]
### What version of Turborepo are you using?

1.2.16

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Can't pass arguments (that start with `-` or `--`) to the underlying command that `turbo` will run, when using `--filter`.

### Expected Behavior

Running:
```
npm run test -- --filter=ui -- --passWithNoTests
```

**Expected** `turbo` to run:
```
npm run test -- --passWithNoTests
```
Only for `ui` package.

In **reality**, `turbo` runs:
```
npm run test
```
Only for `ui` package.

### To Reproduce

Run a command with `--filter` and pass more options. Check **Expected behavior** and the [repo](https://github.com/ivolimasilva/turborepo-args-bug) I've created to easily reproduce the issue.

**Comment by tgmarinho** [comment]
I'm facing the same issue, here the context:

I installed the lib globally:  "dotenv-flow": "3.2.0"

And added a script in the package.json (root): 

Script:
```
"build:app": "dotenv -e .env turbo run build --filter=@crow/app"
``` 

Run:
```
yarn build:app
```

It's ignore the filter and do a build in entire project (packages. apps)

**Comment by xkomiks** [comment]
Why is it marked as ready? The issue cannot be solved without `dotenv`?

**Comment by ZeldOcarina** [comment]
Hey no solution for this yet?

**Comment by taylorqj** [comment]
> Hey no solution for this yet?

I believe with https://github.com/vercel/turbo/pull/1405 you're able to pass args via `npm run test -- -- --someArg --someOtherArg=123`

**Comment by hannanstd** [comment]
add `--` to last of the scripts here https://github.com/ivolimasilva/turborepo-args-bug/blob/main/package.json#L10-L14
like:
```
 "scripts": {
    "build": "turbo run build --",
    "dev": "turbo run dev --parallel --",
    "lint": "turbo run lint --",
    "test": "turbo run test --",
    "format": "prettier --write \"**/*.{ts,tsx,md}\""
  },
```

**Comment by therealemjy** [comment]
> add `--` to last of the scripts here [ivolimasilva/turborepo-args-bug@`main`/package.json#L10-L14](https://github.com/ivolimasilva/turborepo-args-bug/blob/main/package.json?rgh-link-date=2023-11-27T15%3A51%3A35Z#L10-L14) like:
> 
> ```
>  "scripts": {
>     "build": "turbo run build --",
>     "dev": "turbo run dev --parallel --",
>     "lint": "turbo run lint --",
>     "test": "turbo run test --",
>     "format": "prettier --write \"**/*.{ts,tsx,md}\""
>   },
> ```

Thanks, this solution works perfectly!
