### ISSUE TITLE
`react-dom` in `peerDependencies`: Cannot find module '.../node_modules/react-dom/index.js'

### ISSUE THREAD

**Issue by baptisteArno** [vercel/turborepo#1370]
### What version of Turborepo are you using?

1.2.16

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I have a Next.js app `builder` that calls a React component lib `bot-engine`. The lib is built with Rollup.

As soon as I insert `react-dom` into the `peerDependency` of `bot-engine` and build the Next.js app, it throws:

```sh
builder:build: Error occurred prerendering page "/typebots/create". Read more: https://nextjs.org/docs/messages/prerender-error
builder:build: Error: Cannot find module '/Users/baptistearno/Dev/typebot-os/apps/builder/node_modules/react-dom/index.js'
builder:build:     at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
builder:build:     at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
builder:build:     at resolveExports (node:internal/modules/cjs/loader:482:14)
builder:build:     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
builder:build:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
builder:build:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
builder:build:     at Module.require (node:internal/modules/cjs/loader:1005:19)
builder:build:     at require (node:internal/modules/cjs/helpers:102:18)
builder:build:     at Object.6405 (/Users/baptistearno/Dev/typebot-os/apps/builder/.next/server/pages/typebots/create.js:727:18)
builder:build:     at __webpack_require__ (/Users/baptistearno/Dev/typebot-os/apps/builder/.next/server/webpack-runtime.js:25:42)
```

For every page that calls the `bot-engine` lib.

### Expected Behavior

Should build without errors

### To Reproduce

1. `git clone https://github.com/baptisteArno/typebot.io`
2. `cd typebot.io`
3. `yarn`
4. `yarn turbo run build --scope=builder --include-dependencies --no-deps`
5. It builds without error
6. Add `"react-dom": "^18.1.0",` into `peerDependencies` in `packages/bot-engine/package.json`.
7. Run `yarn turbo run build --scope=builder --include-dependencies --no-deps`
8. It should fail with error: `Error: Cannot find module '.../typebot.io/apps/builder/node_modules/react/jsx-runtime.js'`
9. Delete `apps/builder/node_modules`
10. Run `yarn turbo run build --scope=builder --include-dependencies --no-deps`
11. It should fail with the error described above

**Comment by navyfox** [comment]
I think this help you

https://github.com/vercel/next.js/issues/9022
https://www.npmjs.com/package/next-transpile-modules#i-have-trouble-with-duplicated-dependencies-or-the-invalid-hook-call-error-in-react
https://github.com/vercel/next.js/issues/9022#issuecomment-983999752

the last link is the solution to the problem in my opinion

**Comment by navyfox** [comment]
if you have versions of next > 9

**Comment by nathanhammond** [comment]
This is an interesting interaction between a whole bunch of different compile-time resolution of modules systems. It isn't a Turborepo issue. This would also also fail if you directly called `next build` inside of the `builder` directory.

In this case, reading the stack, https://github.com/baptisteArno/typebot.io/blob/main/apps/builder/pages/typebots/create.tsx after transpilation and a whole bunch of stuff appears to attempt to load in a module that is failing resolution inside of `node`, using their CJS resolver.

I'm closing this as a non-Turborepo issue.
