### ISSUE TITLE
Shared eslintrc `plugins` are ignored

### ISSUE THREAD

**Issue by baptisteArno** [vercel/turborepo#1373]
### What version of Turborepo are you using?

1.2.16

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When defining a shared eslint config and extending it, the `plugins` seem to be ignored.

For example, I've added the `@typescript-eslint` plugin, and when I try to disable the `@typescript-eslint/no-explicit-any` rule, it says:

```
Error: Definition for rule '@typescript-eslint/no-explicit-any' was not found.  @typescript-eslint/no-explicit-any
```

### Expected Behavior

Should take into account the plugins and rules

### To Reproduce

1. Clone the basic example
2. Edit `packages/eslint-config-custom/index.js`:
```js
module.exports = {
  ignorePatterns: ['node_modules'],
  env: {
    browser: true,
    es6: true,
  },
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:react/recommended',
    'next/core-web-vitals',
    'prettier',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2018, // Allows for the parsing of modern ECMAScript features
    sourceType: 'module', // Allows for the use of imports
    ecmaFeatures: {
      jsx: true, // Allows for the parsing of JSX
    },
  },
  settings: {
    react: {
      version: 'detect', // Tells eslint-plugin-react to automatically detect the version of React to use
    },
  },
  plugins: ['react', '@typescript-eslint', 'prettier'],
  rules: {
    'react/no-unescaped-entities': [0],
    'react/display-name': [0],
    'prettier/prettier': 'error',
  },
}

```
3. Edit `packages/eslint-config-custom/package.json`
```json
{
  "name": "eslint-config-custom",
  "version": "0.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "eslint": "8.17.0",
    "eslint-config-next": "12.1.6",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.0.0",
    "@typescript-eslint/eslint-plugin": "^5.27.1"
  },
  "publishConfig": {
    "access": "public"
  }
}

```
4. Run `yarn`
5. Edit `apps/web/pages/index.tsx`
```tsx
import { Button } from "ui";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function Web() {
  return (
    <div>
      <h1>Web</h1>
      <Button />
    </div>
  );
}
```
7. Run `yarn turbo run lint --scope=web`
8. It says `Error: Definition for rule '@typescript-eslint/no-explicit-any' was not found.  @typescript-eslint/no-explicit-any`

**Comment by weyert** [comment]
In Pnpm they are automatically hoisted (`eslint*`). Maybe something similar is possible for Yarn?

**Comment by nathanhammond** [comment]
This is, unfortunately, not a Turborepo issue. It is instead one of the most-longstanding open eslint issues: https://github.com/eslint/eslint/issues/3458

The recommended workaround from us here is this: https://github.com/microsoft/rushstack/tree/main/eslint/eslint-patch
