### ISSUE TITLE
All text is white on the documentation site

### ISSUE THREAD

**Issue by yamadapc** [vercel/turborepo#1406]
### What version of Turborepo are you using?

x

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

What I see:

<img width="1728" alt="Screen Shot 2022-06-14 at 8 57 38 am" src="https://user-images.githubusercontent.com/3923654/173461278-c9418778-6597-448c-9008-f0155fec8a60.png">

Disabling the `color-scheme` rule (what I'd expect to see):

<img width="1728" alt="Screen Shot 2022-06-14 at 8 57 47 am" src="https://user-images.githubusercontent.com/3923654/173461313-a7db5e28-a97b-469e-a316-e0d732adf357.png">

### Expected Behavior

Text is not white over white background

### To Reproduce

* MacOS - Set either light/dark-mode on the system settings
* Chrome v102
* Open https://turborepo.org/docs

**Comment by gsoltis** [comment]
Hmm, I can't seem to reproduce this, and I think I have the same setup. Did you have to relaunch chrome to trigger the issue? Or did it occur right after switching macos system settings?

**Comment by yamadapc** [comment]
Interesting, I think this is some extension's fault. I'm sorry for the noise.
