### ISSUE TITLE
Why all examples include only Next.js, and so simplistic and few examples with CI/CD?

### ISSUE THREAD

**Issue by erkand-imeri** [vercel/turborepo#1414]
### Describe the feature you'd like to request

I read the documentation and the hype going on about the turborepo.

My concern is that documentation is not very explicit and detailed and the examples involve only Next.js framework presets.

I do understand that Vercel now is behind Next.js and Turborepo, and that Next.js is an awesome framework but...

### Describe the solution you'd like

I am wondering, (i know it's possible of course). Why don't you post examples for some services/app which are framework agnostic, or minimalistic/core? 

Let's say a preset with express server.

Also, as a new tool which tries to bring innovation and convince us to use, can you show us some examples with CI/CD. A very basic example which we can base of, how do you tackle the monorepo approach with turborepo.

### Describe alternatives you've considered

Extend the documentation about examples, include presets other than Next.js.

Also, extend the documentation about CI/CD.

**Comment by sppatel** [comment]
I would be curious to know what specific issues are you running into.  As an outside adopter, turbo is very framework agnostic and I've had very few concerns with documentation during early adoption.  Granted I've come across a few issues/limitations/enhancements/bugs as well as a few documentation clarification that is needed but I don't consider any of them blockers but merely highlight the potential and impact turbo will have to the community once addressed.  We've been successful in using it in production with over 200+ packages, driven by a CI/CD pipeline (and we are not using Next.js)

It would be good to be more explicit about the issues / questions you are running into/facing.  From what i've seen the developers and the community seem very receptive to questions/issues being reported.

**Comment by erkand-imeri** [comment]
Hello @sppatel, actually i have no problems, and yesterday just started testing with core Express server: https://gitlab.com/erkand-imeri/turborepo-gitlab

It works except for those eslint-next warnings which i might have a look into it.

It's just a question at why all examples are being shown with Next.js (actually i think this is a pretty cool framework).
