### ISSUE TITLE
--concurrency=100% errors on composite GitHub Actions

### ISSUE THREAD

**Issue by jlarmstrongiv** [vercel/turborepo#1417]
### What version of Turborepo are you using?

1.2.16

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

```
Run npx turbo run turbo:build --concurrency=100%
 ERROR  invalid argument "100%" for "--concurrency" flag: strconv.ParseInt: parsing "100%": invalid syntax
Error: Process completed with exit code 1.
```

### Expected Behavior

Turbo runs with 100% of the logical cores

### To Reproduce

Use the concurrency flag in composite GitHub Actions

**Comment by weyert** [comment]
Pretty sure they recently fixed this

**Comment by jlarmstrongiv** [comment]
Oh, thank you @weyert !  I searched for similar issues, but didn’t find it.  Closing as duplicate.
