### ISSUE TITLE
Evaluate Renovate to manage dependency versions

### ISSUE THREAD

**Issue by gsoltis** [vercel/turborepo#1440]
### Describe the feature you'd like to request

Safe dependency version management

### Describe the solution you'd like

Evaluate if renovate can work for us

### Describe alternatives you've considered

dependabot doesn't support `pnpm`.

**Comment by tknickman** [comment]
Renovate is in!

**Comment by reneleonhardt** [comment]
I can't find renovate (or dependabot) in this repo, and Cargo.toml is extremely outdated.

Will automatic updates be enabled eventually to reduce technical debt?
