### ISSUE TITLE
Examples for Next.js are inheriting base TypeScript config

### ISSUE THREAD

**Issue by matthewlilley** [vercel/turborepo#1446]
### What version of Turborepo are you using?

1.3.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Examples in Turborepo for Next.js are inheriting a base typescript config with declaration: true, which causes a ton of portability errors which the cause of is not obvious. I spent many hours tracking this down. I don't think Next.js should have declaration: true, but using the examples provided they will.

### Expected Behavior

To not repeatedly see

[The inferred type of "X" cannot be named without a reference to "Y". This is likely not portable. A type annotation is necessary.](https://github.com/microsoft/TypeScript/issues/42873#)

### To Reproduce

N/A

**Comment by nathanhammond** [comment]
This is a request to drop this line from our example configurations:
https://github.com/vercel/turborepo/blob/d83130a8b30b01ae2ce1627f4188e791598ea8b3/examples/basic/packages/tsconfig/base.json#L6

@tknickman While you're doing your example work can you develop an opinion on what we should do here?

**Comment by matthewlilley** [comment]
Just FYI I kept the options in base and disabled them in the next.js TypeScript config.

**Comment by matthewlilley** [comment]
@tknickman Great. Unusure if declarationMap being true will cause an issue too, I disabled both.

**Comment by tknickman** [comment]
Yea that makes sense - we shouldn't need that for a next.js app itself (but would want this for other packages / libraries)
