### ISSUE TITLE
M1 & Windows WSL2 issues with turbo

### ISSUE THREAD

**Issue by WraithIT** [vercel/turborepo#1463]
### Describe the feature you'd like to request

Turborepo and docker don't work when trying to build from docker-compose or a single Dockerfile.
I have installed turbo in the root folder, and on packages, there are different projects.

Example of a single Dockerfile
There is the node_modules with bin folder containing symlink, even of turbo

<img width="839" alt="Screenshot 2022-06-30 at 22 31 00" src="https://user-images.githubusercontent.com/1633502/176773020-1ba4a5fe-3567-4271-969e-4879e29fe195.png">

The error is that turbo is not a module and prune failed to be executed

### Describe the solution you'd like

Build and run docker-compose or single image

### Describe alternatives you've considered

Is it an architectural problem?

**Comment by nathanhammond** [comment]
@WraithIT Can you paste the exact error message and the stack for it? That'll help me figure out where I need to be focusing in order to track this down.

**Comment by nathanhammond** [comment]
Let's do this one at a time.

`ERROR Could not find turbo.json. Follow directions at https://turborepo.org/docs/getting-started to create one`

`turbo` is successfully being executed, but you're not executing the command in the root of the project so there is no `turbo.json` file.

Fix that issue first.

**Comment by WraithIT** [comment]
> Let's do this one at a time.
> 
> `ERROR Could not find turbo.json. Follow directions at https://turborepo.org/docs/getting-started to create one`
> 
> `turbo` is successfully being executed, but you're already not including the root of the project so there is no `turbo.json` file.
> 
> Fix that issue first.

Including turbo.json inside the Dockerfile with the copy command, it requires the package manager and yarn.lock. Don't I transform this subfolder into another turbo main folder?
