### ISSUE TITLE
Turbo doesn't respect package names

### ISSUE THREAD

**Issue by andyjessop** [vercel/turborepo#1465]
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Taking the default installation, I changed the name of the `ui` package to `@web/ui` because I want my packages namespaced.

In the default `web/pages/index.tsx` I changed the package name, e.g. `import { Button } from "@web/ui";`. I then restarted the TS server.

The result is a TS error:

```
Cannot find module '@web/ui' or its corresponding type declarations.
```

### Expected Behavior

Turbo should understand the names of the packages from the package.json.

### To Reproduce

1. Take a default installation
2. Change the name of the `ui` package to `@web/ui` in the package.json
3. In `web/pages/index.tsx` change the import name, e.g. `import { Button } from "@web/ui";`.

**Comment by sangdth** [comment]
@andyjessop I ran into exactly issue, may I ask how did you solve it? I have nothing fancy, mostly copy from the example.

**Comment by andyjessop** [comment]
I'm really sorry, I should have posted my answer here before closing. I'm afraid I don't remember what the answer was. Maybe you can re-open to get an answer from the team.

**Comment by davestewart** [comment]
I've been testing namespaced packages, but installation appears to favour NPM vs local package names.

Some additional documentation around this would be useful @mattpocock

**Comment by weyert** [comment]
Don’t you need to reinstall the packages, e.g. `pnpm install` when you rename packages?

**Comment by davestewart** [comment]
FWIW I found this post, the last answer may be helpful with regards to scoped packages (I've not tested myself yet):

https://stackoverflow.com/questions/71293685/npm-workspaces-warn-some-package-name-in-filter-set-but-no-workspace-folder-p

**Comment by nathanhammond** [comment]
@weyert is correct.
