### ISSUE TITLE
Alternative config format supporting comments (like YAML)

### ISSUE THREAD

**Issue by trevorr** [vercel/turborepo#1470]
### Describe the feature you'd like to request

I'd like a richer alternative to `turbo.json`, such as `turbo.yaml`. JSON is ubiquitous and great for data exchange, but it lacks several features of a good source code format. In particular, it doesn't have a way to include comments, which are extremely useful for capturing organizational knowledge, such as why things were done a certain way or what known issues exist. Its simple, rigid syntax is also not the most user-friendly for manually written files.

### Describe the solution you'd like

If Turborepo is run in a directory that doesn't have a `turbo.json` file, but does have a `turbo.yaml` file, use that for configuration. Supporting YAML would add the following features essentially for free (since parsed and resolved YAML is equivalent to JSON):

- comments
- anchors, aliases, and extensions (for avoiding repetition)
- improved readability due to reduced syntax (e.g. quoting)

### Describe alternatives you've considered

One could generate `turbo.json` from `turbo.yaml` by introducing a wrapper around `turbo` that translates the configuration file before running `turbo`.

Related to #217

**Comment by weyert** [comment]
Yeah, there is a regression of supporting comments in side `turbo.json` using JSON5.

**Comment by trevorr** [comment]
Ah, I see that from #1283. JSON5 would solve most of the issue. Does/could Turborepo support the filename `turbo.json5`, so that IDEs can recognize the format?

**Comment by weyert** [comment]
There is a PR by @bguedes-moz to fix this issue so that's great. Probably you would need to switch the selected language in the editor to get the correct color coding but that's not a biggy (for me).

**Comment by bguedes-moz** [comment]
I don't really look at the highlighted errors on IDE but the syntax change should do the trick like @weyert suggested. 
Or we could support both `.json` and `.json5` extensions.

**Comment by trevorr** [comment]
Supporting the alternate extension seems like an easy change that will save
a lot of confusion and IDE configuration clicks for a lot of people. I know
I'm not alone in not being able to handle the red lines in my IDE. 😅 I'll
volunteer to submit a PR if that's the best way to do this.

I still think it would be nice to have YAML as an option, but it would be
much less important with JSON5 working.

**Comment by nathanhammond** [comment]
Hey y'all! We're definitely not going to add YAML support but we will also fix the JSONC stuff. That's a great suggestion to catch the `jsonc`/`json5` file extension difference; we'll make that happen at the same time.

I'm going to close this as the request but it's linked into #1283 and #1472 so that the context isn't lost and we eventually address the primary problems with our current state of the world.

Thanks for the conversation and ideas!
