### ISSUE TITLE
Can't declare dependency on root task

### ISSUE THREAD

**Issue by trevorr** [vercel/turborepo#1471]
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Adding a [root task](https://turborepo.org/docs/core-concepts/pipelines#running-tasks-defined-in-the-monorepos-root-packagejson-file) (added in #1040) to a pipeline `dependsOn` often results in an error, such as:

```
ERROR  error preparing engine: found reference to unknown package: // in task //#generate-shared1
```

[Sample `turbo.json`](https://github.com/trevorr/turborepo-root-dep-test/blob/master/turbo.json)

### Expected Behavior

I expected root task dependencies to work like other [explicit package-task dependencies](https://turborepo.org/docs/core-concepts/pipelines#implicit-dependencies-and-specific-package-tasks).

### To Reproduce

https://github.com/trevorr/turborepo-root-dep-test is a minimal repository with instructions for reproducing the issue. Running the few commands in the `README.md` will produce the error above.

**Comment by gsoltis** [comment]
@trevorr thanks for the repo, that's definitely a bug and we'll get it fixed soon

**Comment by trevorr** [comment]
Thanks for the quick fix! I built `turbo` locally and verified that it also works with my actual repo.

Do you know if this fix will be included in a release soon? Or alternatively, if there's a straightforward way to use a pre-release build in a CI environment? This was blocking our adoption of Turborepo, so now that it's fixed, I'm eager to see how it performs in CI.
