### ISSUE TITLE
Turbo is sending arg `--` (ignore-option) as first argument to script.

### ISSUE THREAD

**Issue by erickponce** [vercel/turborepo#1477]
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Turbo is sending arg `--` (ignore-option) as first argument to script...
this will break a library that are aware of this option, as it will ignore all args after `--`. (like yargs)

So for a command `turbo build test -- --my-script-arg=test`:
the script will receive in its `${@}` 2 args, `--` and `--my-script-arg=test`.

### Expected Behavior

Turbo should forward all args after `--`, but not including `--` as first arg.

### To Reproduce

1. Create a script that `echoe ${@} `
2. then call the script with Turbo, along with some script args like `turbo my-script -- --my-arg=test`
3. the script will echo `-- --my-arg=test` and not `--my-arg=test`

**Comment by cdaringe** [comment]
Not a maintainer 👋 .  Can you elaborate on why is this unexpected behavior? In your example you explicitly passed the second pair. I’m unclear why the current behavior is undesirable. If the CLI dropped the second pair, couldn’t that be argued as confusing behavior? Is dropping your second pair an option?

**Comment by erickponce** [comment]
Hi there @cdaringe ! 👋
I'm not sure I understand what you mean by `my second pair`, but the ideia are:

In a command `turbo run my-script --filter=my-package -- --my-arg=123`
For Turbo to know that it should not parse the script args and rather passthrough them to the script, it detects the arg `--`.
So everything before `--` are for Turbo, and everything after it are for my script, the problem is that Turbo forward even the `--` (separator) as the first item on the array of args to my script:

Turbo args:
`--filter=my-package`

my-script args:
`--`
`--my-arg=123`

This means that if I have a arg parser lib on my command that also recognize `--`, it will drop all my script args.
I think Turbo should use `--` only as a separator, and not add it as one of my-script args.

Observation: I tried to drop the first arg that comes from Turbo with `${@:2}`, but Yarn >= 2 has its own shell, and it doesn't have this feature.

**Comment by cdaringe** [comment]
Sorry about that, my mobile phone rendered `turbo build test -- --my-script-arg=test` as `turbo build test -- --<LINE_BREAK>` giving me the false impression you had simply entered `-- --`. 😆 My bad.

I whipped up two reproductions:

- ❌ `yarn@3.x` reproduction: https://github.com/cdaringe/turborepo-1477-yarn-repro
  - fails just as reported

`yarn dlx turbo run foo --filter=ui -- --bar=baz`

yields the reported failure mode:

```sh
// foo.js
// console.log(process.argv)
ui:foo: [
ui:foo:   '/Users/cdaringe/.fnm/node-versions/v18.0.0/installation/bin/node',
ui:foo:   '/Users/cdaringe/src/my-turborepo-yarn/packages/ui/foo.js',
ui:foo:   '--', # 👀
ui:foo:   '--bar=baz'
ui:foo: ]
```

- ✅  `npm` reproduction: https://github.com/cdaringe/turborepo-1477-reproduction, with single edit off of `npx create-turbo` [here](https://github.com/cdaringe/turborepo-1477-reproduction/commit/b9b94d5da1b1d1692c735a4d4bb8c35c84735fed)
  -  works as expected: `npx turbo run foo --filter=ui -- --bar=baz`

```js
// foo.js
// console.log(process.argv)
ui:foo: [
ui:foo:   '/Users/cdaringe/.fnm/node-versions/v18.0.0/installation/bin/node',
ui:foo:   '/Users/cdaringe/src/my-turborepo/packages/ui/foo.js',
ui:foo:   '--bar=baz'
ui:foo: ]
```

**Comment by erickponce** [comment]
No problem, and thank you for the reproduction details! 😀

**Comment by weyert** [comment]
Looks like both `yarn` and `pnpm` don't go for the `--` approach but only `npm` does?
So with this change you would need to do `turbo run testify -- -- relativePathToTest`?

**Comment by nathanhammond** [comment]
@erickponce Thanks for the report, sounds to me like we need more tests to make sure we do the right things. I've dropped a comment on the PR that @cdaringe opened:

https://github.com/vercel/turborepo/pull/1493#issuecomment-1178535667

**Comment by chris-olszewski** [comment]
#1612 should fix this issue. Reopen if the issue persists

**Comment by cdaringe** [comment]
I had two functional PRs for this issue, without feedback
