### ISSUE TITLE
Re-enable PNPM template

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#148]
### Describe the feature you'd like to request

Actually use the `pnpm` template in `npx create-turbo`

### Describe the solution you'd like

Need to be mindful that PNPM uses `workspace:*` instead of `*` for local dependencies. Would need to scan and replace accordingly	

### Describe alternatives you've considered

- Since PNPM store is getting merged into NPM, PNPM's future remains unclear
- Wait to do this until we parse the pnpm lockfile

**Comment by jacobwgillespie** [comment]
> Since PNPM store is getting merged into NPM, PNPM's future remains unclear

Not exactly related to this issue, but do you have a link for this? I'd be interested in more info, but can't seem to find anything about it on the npm or pnpm repo issues...
