### ISSUE TITLE
Ignore devDependencies in `prune`

### ISSUE THREAD

**Issue by Ghirigoro** [vercel/turborepo#1488]
### Describe the feature you'd like to request

The `prune` command currently examines all dependencies when deciding which workspaces to "prune". This can be a problem if you want to use `prune` to export a sub-project for a production build as you may end up importing a lot of needless dev dependencies. For example, if you have the `@my-project/huge-testing-util` defined in a project's `devDependencies`, turbo will pull in `huge-testing-util` as one of the packages that are pruned and force you to install it's dependencies.

### Describe the solution you'd like

Add a flag called `--ignore-dev-deps` to `prune` that ignores any references to workspaces defined in `devDependencies`.

### Describe alternatives you've considered

I've considered writing scripts to manually remove the offending workspaces from the output of `prune` but it's pretty hacky and will end in tears.

**Comment by joemckenney** [comment]
Big +1 - the workarounds to make this happen right now are pretty painful.  

In our case, we run into this during containerization for production.  We had to add an additional stage in our Dockerfile that removes all dev deps from the `package.json` files in the already pruned monorepo.  Subsequently, we run prune again to get the "production" sparse/partial monorepo. It looks something like this

```
FROM node:16.9.1-alpine AS pruner
ENV NODE_ENV=production
RUN apk update && apk add jq
WORKDIR /app
COPY --from=builder /app/ . 
RUN node scripts/rm-dev-deps.mjs    #delete dev deps in the already pruned workspace
RUN npx turbo prune --scope="@app/server" --docker # run prune again :( 
RUN cp ./out/yarn.lock ./out/json
RUN cd out/json; for pkg in `yarn workspaces list --json | jq .location | sed 's/"//g' | tail -n +2 | xargs`; do mv /app/$pkg/dist /app/out/json/$pkg/; done; cd ../../; 
RUN rm -rf ./apps ./packages ./node_modules ./scripts yarn.lock
RUN mv ./out/json/* .
RUN rm -rf ./out
```

^^ this hack could be avoided with a `--production` flag to prune as suggested in https://github.com/vercel/turborepo/issues/1100.

**Comment by Ghirigoro** [comment]
I didn't realize there was an existing issue with the same request. I'll close this in favor of #1100 to keep the noise down.
