### ISSUE TITLE
Turbo CLI doesn't respect NPM choice

### ISSUE THREAD

**Issue by johncburnette** [vercel/turborepo#150]
### What version of Turbrepo are you using?

Latest via npx

### Describe the Bug

The template used by the turbo CLI does not respect the NPM choice when using `npx create-turbo@latest`. The commands in the package.json are yarn commands. This would work if you had Yarn installed but is unusable if you do not use Yarn. More so, if you choose NPM as your package manager, this file should respect that and also use NPM.

Here is a screenshot of the console and the package.json file it generated:
![image](https://user-images.githubusercontent.com/56326230/145459581-a0e12a8e-b070-4635-9429-2b810a10941e.png)

### Expected Behavior

The package.json file should be using whatever package manager you choose during the prompts from the CLI.

### To Reproduce

1. Create a new repo via `npx create-turbo@latest`
2.  Select NPM as the package manager option
3. Wait for the project to be created and follow the prompts for development
4. You should see an error stating `sh: yarn: command not found` if you do not have yarn installed.

**Comment by jaredpalmer** [comment]
Thanks for the bug report. Seems like an issue with the templates. On it.
