### ISSUE TITLE
NPM dependencies are not being able to resolved while deploying in Google Cloud.

### ISSUE THREAD

**Issue by ferreiro** [vercel/turborepo#1524]
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

I set up a Node.JS monorepo with several applications. They are correctly working in my local environment. However, when I try to deploy it to App Engine in Google Cloud, they are not being able to resolve the local dependencies.

<img width="883" alt="Screen Shot 2022-07-13 at 8 28 42 AM" src="https://user-images.githubusercontent.com/7242959/178665624-f8266e1e-ce6f-4d86-b6f7-9e1ab06cca53.png">

The setup of the application:

* Packages under `/packages/zootools-alerts`
* Consuming those packages from the applications.

Here are my package.json scripts

```js
  "scripts": {
    "deploy": "gcloud app deploy",
    "dev": "nodemon -r dotenv/config ./src/index.js",
    "start": "nodemon -r dotenv/config ./src/index.js --config nodemon.json"
  },
```

### Expected Behavior

It should be able to resolve any dependencies while deploying.

### To Reproduce

https://www.loom.com/share/55aca06de4fd43a3bf51060c9f5a40f6

**Comment by tknickman** [comment]
Thanks for the loom walkthrough, that's super helpful. 

This looks to be an issue with how you're installing on deploy. The following depends on your monorepo setup and `turbo.json`, but generally speaking - to deploy an application that is within your monorepo, you would need to run an `install` from root to ensure your packages are correctly linked, and something like `turbo run build --filter=<app/service>...`. This ensures that your local packages will still be linked as expected, and your app and its dependencies are all built.

**Comment by tknickman** [comment]
This looks to be an issue with workspaces as described above - going to close for now but feel free to reopen if you're hitting more issues!
