### ISSUE TITLE
Non-deterministic scopes identified with changed packages filter 

### ISSUE THREAD

**Issue by finn-orsini** [vercel/turborepo#1528]
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Given:

1) The following directory structure: 

```
- applications
 | - foo
 | - foo-bar
```

2) Changed files in both `foo` and `foo-bar`

running turbo with a changed files filter (`--filter="[HEAD^1]"` or `--filter="[origin/main]"`, etc) does not consistently return both packages in scope, sometimes only identifying the workspace `foo` as changed.

This bug is specific to workspace directories which are a substring of another workspace directory. If the above example directories were updated to `foo-baz` and `foo-bar`, the issue will not present. 

### Expected Behavior

Changed scopes are correctly & consistently identified by Turbo.

We have identified a potential solution by updating [this hasPrefix check](https://github.com/vercel/turborepo/blob/main/cli/internal/scope/scope.go#L207) to include a trailing `/`.  @wvanrensselaer will follow this issue with a PR shortly!

### To Reproduce

- Clone this [example repo](https://github.com/finn-orsini/turbo-filter-bug)
- `pnpm i`
- Make a change to `foo` and `foo-baz` 
- Run `pnpm run build` from repo root a few times 

Output will sometimes identify both packages: 

```
Packages in Scope
Name    Path
//
foo     foo
foo-baz foo-baz
```

And other times only identify `foo`: 

```
Packages in Scope
Name Path
//
foo  foo
```

**Comment by helloitsjoe** [comment]
Can also be reproduced in Turborepo unit tests by adding this test case to `cli/internal/scope/scope_test.go`:

```
{
  name:     "An app changed",
  changed:  []string{"app/app2/src/index.js", "app/app2-foo/src/index.js"},
  expected: []string{"app2", "app2-foo"},
  since:    "dummy",
},
```

And adding this to `packagesInfos`:
```
"app2-foo": {
  Dir: "app/app2-foo",
},
```
It fails intermittently, similar to the example repo above (requires a whitespace change to clear test cache between test runs)

**Comment by nathanhammond** [comment]
Thank y'all for the extremely detailed report. I'll get something that looks like #1533 in today.

**Comment by nathanhammond** [comment]
(And 1.3.2 should be released today with the fix.)
