### ISSUE TITLE
prune --docker not yet implemented for nodejs-pnpm

### ISSUE THREAD

**Issue by keinsell** [vercel/turborepo#1541]
### What version of Turborepo are you using?

1.3.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I was trying to build `Dockerfile` with Node.js application but it seems `turbo` doesn't work at all with `pnpm` - what should I do as temporary fix?

### Expected Behavior

Success

### To Reproduce

I was trying to build `Docker` image with following `Dockerfile`

```
FROM node:alpine AS builder
RUN apk update && apk add git
# Set working directory
WORKDIR /app
RUN npm i -g turbo@canary pnpm
COPY . .
RUN turbo prune --scope=server --docker

# Add lockfile and package.json's of isolated subworkspace
FROM node:alpine AS installer
RUN apk update
WORKDIR /app
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/yarn.lock ./yarn.lock
COPY --from=builder /app/out/full/ .
COPY .gitignore .gitignore
COPY turbo.json turbo.json

RUN pnpm install
RUN pnpx turbo run build --filter=server...

FROM node:alpine AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 expressjs
RUN adduser --system --uid 1001 expressjs
USER expressjs
COPY --from=installer /app .

CMD node services/server/dist/index.js
```

**Comment by tknickman** [comment]
Thanks for reporting, this is on the roadmap! 

We have another issue for this here https://github.com/vercel/turborepo/issues/534 - so I'm going to close this to consolidate discussion there.
