### ISSUE TITLE
Prints "cache miss" for steps that don't use the cache

### ISSUE THREAD

**Issue by dobesv** [vercel/turborepo#1555]
### What version of Turborepo are you using?

1.2.8

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

When you have a pipeline with caching disabled, e.g.

```
"clean": {
      "cache": false
    }
```

And you tell turbo to run that pipeline, it still prints `cache miss` for each workspace.

It's a small thing, but seems a bit confusing.

### Expected Behavior

When caching is disabled it shouldn't print anything related to cache hit or cache miss for that pipeline.

### To Reproduce

Create a turborepo with a pipeline that has caching disabled, and run that pipeline.  See if it says `cache miss`.

**Comment by StevenMatchett** [comment]
Can you create a repo to recreate the issue. When running locally with a disabled cache stage I get the output `cache bypass`

https://github.com/vercel/turborepo/blob/5815666ae853e0598bf3fe6dac9641a0642bd2d7/cli/internal/runcache/runcache.go#L155

**Comment by dobesv** [comment]
Ah, sorry you are right, it must have been fixed in the latest version.
