### ISSUE TITLE
File Permissions not Preserved from Cache

### ISSUE THREAD

**Issue by sverrejoh** [vercel/turborepo#156]
### What version of Turbrepo are you using?

1.0.1

### Describe the Bug

Package files recovered from cache does not preserve the permissions they were originally created with, but are all set to `755`.

### Expected Behavior

Expected behavior would be for turbo to preserve the permission bits from the files originally generated.

### To Reproduce

Run build twice in your turbo project and all files in `dist/`, `build/` or equivalent will have mode `755`.

**Comment by weyert** [comment]
I am wondering if it's related to this bit of the code?
https://github.com/vercel/turborepo/blob/f160c418c9e564659d462f84fa2721ec1823e0a4/cli/internal/cache/cache_http.go#L78-L87

**Comment by rubiagatra** [comment]
interesting will try to investigate

**Comment by rubiagatra** [comment]
@jaredpalmer I think this is about the default value `const DirPermission = os.ModeDir | 0775` on. And the only checking out is in here.

https://github.com/vercel/turborepo/blob/8654fe28951f39b1ffe0f3e83537b6978ee05f42/cli/internal/fs/fs.go#L82-L84

I would like to help any idea to getting started?

**Comment by jaredpalmer** [comment]
The initial PR did not handle binary executables, need to revert and revisit this. We need a more nuanced solution

**Comment by rubiagatra** [comment]
I will take a look for further investigation, need to familiarize myself with the code base more.

**Comment by sverrejoh** [comment]
I wonder how to solve this properly. If we want to preserve file permissions, would we then need to separate the cache for different operating systems? Do you already keep separate cache pools for Windows and Linux? Also, what's the performance penalty for including permissions for each file inserted/extracted out of the cache? Would we wrap each file in some metadata with content and permissions, or would you have separate entries for files' metadata?

Would it make sense to have a setting for this? Leaving files coming out of cache with default system permissions seems way less heavy handed and surprising than chmod'ing everything to 755.
