### ISSUE TITLE
Setting `dependsOn` for dev builds does not build Next.js in `apps`

### ISSUE THREAD

**Issue by AGS1130** [vercel/turborepo#1594]
### What version of Turborepo are you using?

1.3.x

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Hello!

My team is encountering an issue with the `dev` build process for our monorepo. At the moment we have a pretty simple project as follows:
![marketing-nextJS](https://user-images.githubusercontent.com/27118807/181600292-12ad9fb6-4a21-4020-bc8e-5c5c011a75fc.png)

The apps for `docs` and `web` host a Storybook app and Next.js app, respectively. The `web` app depends on the majority of the packages that we have which are a React UI library (react) and a TailwindCSS plugin (theme).

The `theme` package has a bit of an extensive build process. It has a [TS Node](https://typestrong.org/ts-node/) script responsible for building CSS and CSS-in-JS with the [PostCSS cli](https://github.com/postcss/postcss-cli) and [PreJSS cli](https://github.com/axept/prejss-cli). These are needed because [the plugin needs to read our styles in css-in-js](https://tailwindcss.com/docs/plugins#adding-components). The `web` app, when running the default commands `turbo run dev --no-cache --continue --parallel`, breaks because the plugin doesn't finish building out before the `web` app runs.

Our solution is to set a [topological order](https://turborepo.org/docs/glossary#topological-order) for dev by using [the dependsOn in the Turborepo configuration](https://turborepo.org/docs/reference/configuration#dependson).

```json
{
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**"]
    },
    "test": {
      "outputs": ["coverage/**"],
      "dependsOn": []
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "dependsOn": ["^dev"],
      "cache": false
    },
    "clean": {
      "cache": false
    },
  },
  "baseBranch": "origin/dev",
  "globalDependencies": ["$GITHUB_TOKEN"]
}
```

This builds the `docs` app and `web` app in parallel, but `web` will build the package dependencies first before it builds the `web` app. **That is expected.** However, what occurs is the `docs` app finishes building, and the dependencies for `web` app finish building, **but the `web` app itself does not build**.

We've done several things to check that this wasn't an isolated issue related to the `theme` package:
- Remove all the flags for `turbo run dev`
- Set the `dependsOn` property for dev to only work in `web#dev`
```json
{
  "pipeline": {
    "web#dev": {
      "dependsOn": ["^dev"]
    }
  }
}
```
- Isolate the builds for the `docs` app and `web` app
```json
{
  "pipeline": {
    "docs#dev": {
      "dependsOn": ["web#dev"],
      "outputs": ["storybook-static/**"]
    },
    "web#dev": {
      "dependsOn": ["^dev"],
      "outputs": [".next/**"]
    }
  }
}
```
https://user-images.githubusercontent.com/27118807/181622103-d83e9ab0-856d-4df4-8578-f71a26d03342.mov
- Remove the `theme` package as a dependency for the `web` app and all inferences of the plugin in the code

All of this has lead to our conclusion, this is a Turborepo bug.

https://user-images.githubusercontent.com/27118807/181624855-408d7e0e-b50f-44a3-a7cd-37c9e4ce41d9.mov

* Please forgive me on the very short videos. I had to make edits because GitHub only allowed <10mb, but this is the outcome when running `yarn clean && yarn && yarn dev`.

### Expected Behavior

We expect out of the box that running dev will build all the dependencies from `packages` and run the `apps` specifically the Next.js app.

### To Reproduce

Here's the reproducible repo
https://github.com/AGS1130/turborepo-1594

**Comment by mehulkar** [comment]
Thank you for the detailed write up!

Unfortunately, depending on long running tasks is not supported. Since you are already using the `--parallel` flag, you con remove the `dependsOn` in your `dev` task config. I am working on a configuration in #2258 that will allow you to tell Turbo which tasks are long running, so we can error early for you, but it will not fundamentally change the behavior. 

```diff
"dev": {
-      "dependsOn": ["^dev"],
      "cache": false
    },
```
