### ISSUE TITLE
linking remoteCache not working with Vercel

### ISSUE THREAD

**Issue by yowainwright** [vercel/turborepo#1595]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When attempting to connect the remote cache to Vercel, I get this error:

```
could not get team information.
{"error":{"code":"forbidden","message":"Not authorized"}}
```

### Expected Behavior

I am able to successfully connect to Vercel's remove cache!

### To Reproduce

1. Install the pnpm starter

```sh
npx create-turbo@latest .
```

2. Select the `pnpm` option for creation

---

3. Log into Vercel

```sh
pnpm dlx turbo login
```

---

4. Link the repo to Vercel

```sh
pnpm dlx turbo link
```

---

This step fails with the following error messages.

```sh
could not get team information.
{"error":{"code":"forbidden","message":"Not authorized"}}
```

```sh
Command failed with exit code 1: /Users/<UserName>/Library/pnpm/store/v3/tmp/dlx-3027/node_modules/.bin/turbo link
```

---

I assumed this has to do with me not having a Vercel team. 
I tried to set up a team and link, but I received the same error.

Thanks so much!!! 
I love Turborepo!

**Comment by gaspar09** [comment]
Hi @yowainwright , 

It might be a typo in the git issue, but you should run  

`pnpm dlx turbo login` before running  `pnpm dlx turbo link`

**Comment by yowainwright** [comment]
@gaspar09 thanks! Yes, that was a typo in this issue (updated).

The issue enabling remote cache with Vercel is still an issue, though. 

Can I provide more detail? Thank you! 🙏

**Comment by yowainwright** [comment]
Here's a [link](https://www.loom.com/share/1901be391ff44334a7130d9fecb44fc1) to a 2 min Loom video showing my issue.

**Comment by nathanhammond** [comment]
@yowainwright Can you run an attempt that isn't in a nested repository, just to see if that is possibly connected?

**Comment by yowainwright** [comment]
@nathanhammond, of course! 🙏 

```txt
turbo@latest
pnpm@7.6.0
node@16.15.1
m1 mac pro
```

In the [video](https://www.loom.com/share/284b7858277d45599b85fd6718114a4d) I used `pnpx` instead of `pnpm dlx`, however I _think_ they're [the same](https://pnpm.io/6.x/pnpx-cli) (although `pnpx` is deprecated). I'll go through the steps again to double-check.

- [ ] double check using `pnpm dlx` vs `pnpx`

---

##  Feels

I feel like this issue may have to do with a user setting (?). 💭 

I tried setting up a team in Vercel to see if that worked, but I still couldn't get past the same error in the video.

---

## Notes

I have had a Vercel for several years.
![history](https://user-images.githubusercontent.com/1074042/182740115-f7822231-c272-4f8f-9b14-3407d0bd003a.png)

The generated token appears to be showing up in my account.
![toekn](https://user-images.githubusercontent.com/1074042/182740308-4ad1e74b-0429-42d1-93f6-4f930ef25261.png)

**Comment by gaspar09** [comment]
Hi @yowainwright ,

Is this issue isolated to pnpm?
I can see the login is successful, perhaps the pnpm store for the token is causing issues. 
Are you able to login and link when using a locally installed turbo via yarn?

For example, a local node_modules install turbo and running `yarn turbo login` and `yarn turbo link`

**Comment by yowainwright** [comment]
@gaspar09 no, same issue across `node_module` managers! 

It definitely feels like an issue with my Vercel user and Turbo. 

I am able to log in with the Vercel CLI just fine. I even purchased a pro team account and am not getting anywhere.

**Comment by yowainwright** [comment]
@gaspar09 Thanks so much for your response! 

Once I can figure out what's going on, I'll respond with info and can write documentation—if needed/wanted. 

I feel there is some issue with my Vercel user and Turborepo linking.

Things I've tried:

- I ran `pnpm prune cache`
- I tried the setup with yarn and with npm
- I uninstalled and reinstalled turbo

I feel like this must be some issue with my Vercel user (?).
I'm reaching out to Vercel as well. 

I really appreciate the help and am feeling a bit lost on what I've done incorrectly.
🙏

**Comment by gaspar09** [comment]
@yowainwright , I think this is something to do with turbo's token storage. Since you are able to log in.
Are you able to generate a token on vercel and pass that in via:

https://turborepo.org/docs/reference/command-line-reference#--token

for example: 
```
npx create-turbo
// setup pnpm
pnpm run build --token=<token> --team=<team-slug>
```

**Comment by gaspar09** [comment]
After running this you can clear the local cache via 

`rm -rf node_modules/.cache/turbo`
and re-run
`pnpm run build --token=<token> --team=<team-slug>`
to observe cache hits.
![CleanShot 2022-08-08 at 18 53 58@2x](https://user-images.githubusercontent.com/5875536/183567594-72ac9542-8553-47b1-b998-3b428a47c123.png)

**Comment by yowainwright** [comment]
@gaspar09 that worked! 💪 

However, `pnpm dlx turbo link` still fails.  😞

**Comment by nathanhammond** [comment]
@yowainwright This is an extremely strange issue. Can you do me a favor and run this?

```sh
npx create-turbo@latest --use-pnpm ./my-turborepo
cd my-turborepo
npx turbo login

# Does a token show up here?
cat ~/Library/Application\ Support/turborepo/config.json
```

I'm wondering if we're, for some reason, failing to write the login token to disk. Possibly file permissions, who knows.

**Comment by yowainwright** [comment]
^ That fixed my issue! Thanks @nathanhammond & @gaspar09 🙏 👏

**Comment by nathanhammond** [comment]
@yowainwright Thanks for sticking with us on this one!

**Comment by d4mr** [comment]
I have this same issue on Fedora Linux. `rm ~/Library/Application\ Support/turborepo/config.json` This does not help since there is no such file or directory.

Is there documentation of where I can manually generate and paste the tokens into the config?

**Comment by nathanhammond** [comment]
@d4mr that path is for macOS.￼ On Linux it is at:

`~/.config/turborepo/config.json`

**Comment by lperrious** [comment]
Hey @nathanhammond !
I can login to Vercel using `turbo login` and it generates a token.
However when I try to `turbo link` it gives me this error : `could not get user information`.
Do you have any idea on how to fix this please ?
