### ISSUE TITLE
Let prune inherit local lockfile version and cache key

### ISSUE THREAD

**Issue by erj826** [vercel/turborepo#1598]
### Describe the feature you'd like to request

When `turbo prune` generates the `yarn.lock` for yarn >= 2 it hardcodes the lockfile [metadata](https://github.com/vercel/turborepo/blob/main/cli/internal/prune/prune.go#L263). This may be problematic as different versions of yarn may use different lockfile [versions](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Project.ts#L45) and cache keys.

### Describe the solution you'd like

`turbo prune` should read the lockfile metadata from the existing lockfile and pass it to the pruned version.

### Describe alternatives you've considered

An alternative could be running yarn installs without the --immutable flag.

**Comment by tknickman** [comment]
Related: https://github.com/vercel/turborepo/issues/1598

**Comment by tknickman** [comment]
Closing to consolidate discussion on https://github.com/vercel/turborepo/issues/1498
