### ISSUE TITLE
The init template creates a gitignore file instead of .gitignore file

### ISSUE THREAD

**Issue by HosseinAgha** [vercel/turborepo#1605]
### What version of Turborepo are you using?

1,4.0

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Described in the issue title and next sections.

### Expected Behavior

It should create a `.gitignore`

### To Reproduce

Run `yarn dlx create-turbo@latest` it creates a new repository with a `gitignore` file instead of `.gitignore`.

**Comment by tknickman** [comment]
Hey @HosseinAgha, thanks for the report. I just followed your repro steps (and double checked a few other versions / package managers) and was unable to reproduce this. We do have an explicit step to rename the gitignore - so maybe your install hit an error before it reached this step? 

https://github.com/vercel/turborepo/blob/main/packages/create-turbo/src/index.ts#L163-L167

**Comment by HosseinAgha** [comment]
Okay, I tried again and it does not happen anymore. As you suggested maybe it is due to a crash.
