### ISSUE TITLE
Github release 1.4.0 is missing

### ISSUE THREAD

**Issue by robations** [vercel/turborepo#1606]
### Describe the Bug

The latest published tag is v1.4.0, but the latest release shown is 1.3.4.

### Expected Behavior

Maybe this can be automated — can the text for the release can be included in the git repo, and then tagged release will trigger a release?

Or include a changelog where user-facing changes can be collected prior to a release?

Or anything else that could prevent manual process?

### To Reproduce

N/A

**Comment by tknickman** [comment]
It's manual for now - but we're looking to make this automated so we can stay as up to date as possible. I just added in the missing releases, thanks!
