### ISSUE TITLE
The Create React App example is broken

### ISSUE THREAD

**Issue by ImaginaSergio** [vercel/turborepo#1627]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

I've forked this repo to test the cra example, and when I install the dependencies (npm install) and run the project to start testing (npm run dev), it shows me this error: 

```
Module not found: Error: Can't resolve 'react/jsx-runtime' in 'C:\Users\sergi\Desktop\turborepo\examples\with-create-react-app\packages\ui\dist'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

All the console log is this:
![Captura 1](https://user-images.githubusercontent.com/32952029/182884552-1800f1f0-27f1-4a47-8561-6d01bd966d8a.png)
![Captura 2](https://user-images.githubusercontent.com/32952029/182884558-efd7bb84-91c9-470b-9189-cccb8321892e.png)

### Expected Behavior

I expect to run this example in my local environment. Even without any changes of mine, it doesn't works.

### To Reproduce

1. Clone the project.
2. Go to the examples/with-create-react-app folder
3. Run npm install
4. Run npm run dev

**Comment by tknickman** [comment]
Thanks for the report! Issue looks to be that an un-ejected create-react-app doesn't support ECMAScript module dependencies (`.mjs`) without some changes. Interestingly this looks like to does work with yarn, but we'll get this patched!
