### ISSUE TITLE
Create turbo app with examples

### ISSUE THREAD

**Issue by VarunSAthreya** [vercel/turborepo#1647]
### Describe the feature you'd like to request

A CLI flag that can be added to `npx create-turbo` to specify which example we would like to get started with.

### Describe the solution you'd like

A solution would be similar to how `create-next-app` and `create-react-app` works i.e `npx create-turbo@latest --example with-docker`.

### Describe alternatives you've considered

A good alternative would be to add a generic GitHub URL to get started with it similar to how `create-next-app` has.

**Comment by tknickman** [comment]
Yep, this is definitely something we want to do. The only real hurdle here is that our examples are setup to be package manager agnostic (you can get started with npm, pnpm, yarn etc) so we would just need to make some updates to `create-turbo` to adjust these examples post clone for whichever package manager you have selected.

**Comment by mehulkar** [comment]
Same as #664!
