### ISSUE TITLE
ERROR: command finished with error

### ISSUE THREAD

**Issue by long-woo** [vercel/turborepo#1648]
### What version of Turborepo are you using?

1.3.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Other

### Describe the Bug

This is fine locally (Mac), when running the `build:test` command via CI, I get the error in the picture:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/3394035/183427192-ed07068a-bcce-4b2f-b5ac-eb07e92d11b3.png">

### Expected Behavior

normal work.

### To Reproduce

- package.json

```json
"scripts": {
    "dev": "turbo run dev --parallel --filter=./apps/*",
    "build:test": "turbo run build:test",
    "prepare": "is-ci || husky install"
}
```

- tubo.json

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "lint": {
      "outputs": []
    },
    "dev": {
      "cache": false
    },
    "build:test": {
      "dependsOn": ["^build:test"],
      "outputs": [
        "dist/**"
      ]
    }
  },
  "globalDependencies": [
    ".env.*",
    "vite.config.ts"
  ]
}
```

**Comment by long-woo** [comment]
Added `-vvv` output information:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/3394035/183578102-0082b2a8-2e50-41dc-aa11-a0f608a992af.png">

**Comment by long-woo** [comment]
Problem solved by itself！

**Comment by tichopad** [comment]
I've experienced this inside AWS Amplify's runners twice running tasks with topological dependency (e.g. `^build`). I've had no issues in either GitHub's CI or locally so far. It seems to be related to concurrency.

The first time it happened I've been using the default concurrency (10). I fixed it by setting concurrency to 100%.

The second time it started failing with 100% concurrency. This time I had to set concurrency to 3. The runner has 4 available vCPUs.

**Comment by long-woo** [comment]
The `--parallel` option should be used.

**Comment by tichopad** [comment]
Thanks, I will check. `--parallel` unfortunately is not an option as I need to run these tasks in topological order.

**Comment by long-woo** [comment]
I'm sorry, I didn't use `--parallel` in `build`, and finally found that the package under `monorepo` was imported improperly.
