### ISSUE TITLE
Periodically receiving error `Error: command finished with error: %w: EXTRA_VALUE_AT_END="command`

### ISSUE THREAD

**Issue by sppatel** [vercel/turborepo#1683]
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

I don't have alot of info here but I have noticed the following error appear a few times last 24 hours with verbosity increased.  I just want to atleast get awareness and will try to provide more concrete info if and when i can get it.

`Error: command finished with error: %w: EXTRA_VALUE_AT_END="command`

### Expected Behavior

Error should not occur.

### To Reproduce

I do not have a reliable repro at this time.

**Comment by sppatel** [comment]
Closing this as I have not seen this in a long time.

**Comment by purge** [comment]
i'm also getting this - I thought it was caused by changing architecture from intel to arm on my shell but i can't find anything cached that would cause that (culled node_modules and yarn caches).

**Comment by purge** [comment]
i should add i'm reliably getting it every time i'm running it although everything runs fine in CI and on other machines

**Comment by purge** [comment]
update on this - i guessed it might be cached logs but deleting the `.turbo` directories didn't seem to help initially. I upgraded eslint and friends and it still didn't work... but then started working on the next run so i think *one* of those actions did seem to trigger a cache fix somewhere.

**Comment by sppatel** [comment]
Given the comments.. can a contributor re-open this?

**Comment by purge** [comment]
I haven't experienced this issue since i posted these comments. Still no idea what the cause was.

**Comment by tichopad** [comment]
Could be related to https://github.com/vercel/turbo/issues/1648
