### ISSUE TITLE
Turbo prune creating recursive out directories

### ISSUE THREAD

**Issue by toby-lego** [vercel/turborepo#1684]
### What version of Turborepo are you using?

1.4.2

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Running turbo prune from the base of the repository and putting an outdir in the app directory causes it to create a deeply nested directory structure.

Eg. `turbo prune --scope=myapp --docker --out-dir apps/myapp/out` gets you `repo-base/apps/myapp/out/full/apps/myapp/out/full/apps/myapp/out/full/apps/myapp/out/full/apps/myapp/out/full/apps/myapp/out/full/apps/myapp/out/full/apps/myapp/out/full/apps/myapp/out/full/apps/myapp/out/full/apps/myapp/out...`

We want the output in the app folder because that's where the Dockerfile we load it into is, but this obviously isn't useful.

### Expected Behavior

Not to create deeply nested directories/links

### To Reproduce

In a repository with a workspace `apps/myapp` run `turbo prune --scope=myapp --docker --out-dir apps/myapp/out`

**Comment by chris-olszewski** [comment]
I'm currently looking at this area of the codebase. I have a hypothesis about this, but I'll quick confirm. Thanks for reporting!

**Comment by chris-olszewski** [comment]
Until this gets resolved could you just create an npm script that does the moving at the end for you? e.g.
```json
  "scripts": {
    "docker": "turbo prune --scope=myapp --docker --out-dir out && mv out apps/myapp",
```

**Comment by chris-olszewski** [comment]
Looking at this a little more, I think it makes more sense to explicitly disallow this and encourage people to just move/copy output after the pruning happens. Fixing this would involve implementing a special case and version of a recursive copy that detects when the destination is part of the source. At the moment our behavior matches `cp` which I believe is reasonable: 
```
cp -R apps apps/out
cp: apps/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out/out: name too long (not copied)
```

Feel free to reopen if you have strong feelings that this should be supported behavior.

**Comment by toby-lego** [comment]
> Until this gets resolved could you just create an npm script that does the moving at the end for you? e.g.
> 
> ```json
>   "scripts": {
>     "docker": "turbo prune --scope=myapp --docker --out-dir out && mv out apps/myapp",
> ```

Yeah this is similar to the workaround I've ended up implementing.

To explain the use case a bit more, we would prefer to run this from the app directory itself rather than the root, so they look more like this

app/myapp/package.json:
```json
"scripts": {
  "turbo:prepare": "rm -rf out/ && yarn --cwd ../.. run turbo prune --scope=myapp --docker --out-dir apps/myapp/out",
  "docker:build": "docker build ..."
}
```

That way we keep everything related to the build of myapp contained in it's own directory, and different apps can handle this their own way without thinking about common build output areas.

I wouldn't call them strong feelings but just wanted to let you know why this could be useful, even failing like cp does to make it more obvious would be nice.
