### ISSUE TITLE
Permissions change when using turbo vs direct build

### ISSUE THREAD

**Issue by natew** [vercel/turborepo#1691]
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

I can recreate this in the tamagui repo, whenever I run turbo it sets all the generated `types` files to 755 permissions, whereas running directly inside any package will set it to 644.

I see this was somewhat recent, perhaps related issue, or is it possible the build cache has somehow pinned it now to those permissions? https://github.com/vercel/turborepo/pull/1429

### Expected Behavior

Should have same permissions output as running directly.

### To Reproduce

Curious if it will repro:

```
git clone git@github.com:tamagui/tamagui.git --depth=1
./script/ci-prepare.sh
yarn
yarn clean
yarn build
```

Should see any package /types have 755 permissions which you can then verify is 644 by running a `yarn build` directly inside.

**Comment by tknickman** [comment]
Hey @natew, thanks for the report - taking a look into this. I might need some more details for the repro. Here's what I checked:

`yarn`
`yarn clean`
`yarn build` (no cache hit because this is the first build, so the files are _not_ from cache at this point)

Then I checked the permissions of types in a random package (`button`):
```
0 > stat -f %A packages/button/types/
755
0 > ls packages/button/types/
  rw-r--r--   1   knickman   staff     61 B     Mon Aug 15 10:36:42 2022    index.d.ts
  rw-r--r--   1   knickman   staff    123 B     Mon Aug 15 10:36:42 2022    index.d.ts.map
  rw-r--r--   1   knickman   staff      8 KiB   Mon Aug 15 10:36:42 2022    Button.d.ts
  rw-r--r--   1   knickman   staff   1014 B     Mon Aug 15 10:36:42 2022    Button.d.ts.map
```

I then ran:
`yarn clean`
`yarn build` (FULL TURBO this time, so all outputs are from cache)

Then I checked permissions again and saw the same output
```
0 > stat -f %A packages/button/types/
755
0 > ls packages/button/types/
  rw-r--r--   1   knickman   staff    123 B     Mon Aug 15 10:38:46 2022    index.d.ts.map
  rw-r--r--   1   knickman   staff     61 B     Mon Aug 15 10:38:46 2022    index.d.ts
  rw-r--r--   1   knickman   staff      8 KiB   Mon Aug 15 10:38:46 2022    Button.d.ts
  rw-r--r--   1   knickman   staff   1014 B     Mon Aug 15 10:38:46 2022    Button.d.ts.map
```

All looks good here, but let me know if I'm missing something here.

**Comment by natew** [comment]
So I think one clue is this is only happening when I run turbo through a separate node script which runs it as a `spawn`, I tried a fresh install and it doesn't change permissions. So will close this - likely something I need to configure with running it as a sub-process.
