### ISSUE TITLE
Unexpected token 'export' when importing a custom package

### ISSUE THREAD

**Issue by DLesage25** [vercel/turborepo#1718]
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to import a custom package into a workspace in my `/apps` folder. Typescript doesn't complain, but when attempting to run my code I get the following error:

```
api:dev: export * from './user.dao';
api:dev: ^^^^^^
api:dev: 
api:dev: SyntaxError: Unexpected token 'export'
api:dev:     at Object.compileFunction (node:vm:352:18)
api:dev:     at wrapSafe (node:internal/modules/cjs/loader:1032:15)
api:dev:     at Module._compile (node:internal/modules/cjs/loader:1067:27)
api:dev:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
api:dev:     at Module.load (node:internal/modules/cjs/loader:981:32)
api:dev:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
api:dev:     at Module.require (node:internal/modules/cjs/loader:1005:19)
api:dev:     at require (node:internal/modules/cjs/helpers:102:18)
api:dev:     at Object.<anonymous> (/Users/d/GitHub/test/apps/api/src/users/users.service.ts:8:1)
api:dev:     at Module._compile (node:internal/modules/cjs/loader:1103:14)
```

This is the package.json on the custom package:
```
{
    "name": "@test/user-dao",
    "version": "0.0.0",
    "private": true,
    "main": "src/index.ts",
    "types": "src/index.ts",
    "files": [
        "src/**"
    ],
    "dependencies": {
        "mongoose": "^6.5.2",
        "@test/shared": "*"
    }
}
```

And the index.ts file on the custom package:
```
export * from './user.dao';
export * from './user.schema';
export * from './dto';
```

And this is how I'm importing it in the workspace:
```
import { User, UserDao, UserDocument } from '@test/user-dao';

```

I actually see the typings on the workspace that I'm importing the package to, so Typescript seems to understand where the imports come from, but I keep seeing that error on runtime.

### Expected Behavior

The application should run and the imports from the custom package should be made available.

### To Reproduce

1. Create a custom package, have the index.ts of that package be just exports, so 
```
export * from './someFile'
```

2. Make that package available to another workspace. Run the workspace (I'm my case my workspace is a nestJS app).

**Comment by tknickman** [comment]
Hey @DLesage25, this is because you're not building your package - you'll need to transpile it at some point in the build as your nestJS app is looking for cjs it looks like. Typically the package will have a build step, but can you also configure your app to build it as a dependency as well. How exactly to do this depends on your setup (rollup, webpack, etc.) and is out of scope for turbo. If you'd like to see some common methods for this you can take a look at how packages are bundled in our [examples](https://github.com/vercel/turborepo/tree/main/examples)!

**Comment by DLesage25** [comment]
@tknickman super helpful. That got it working. Thank you!

**Comment by LouisGS44** [comment]
@DLesage25 how did you solved it with a NestJS app ?
