### ISSUE TITLE
Pnpm hanging issue

### ISSUE THREAD

**Issue by yovanoc** [vercel/turborepo#1724]
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Other

### Describe the Bug

Tested on Mac, ubuntu and Windows. But only working on windows.

I tried to do a with-docker example for turborepo but with pnpm. Replacing turbo prune with other ways as I see in this issue: https://github.com/vercel/turborepo/issues/534

here's my repo:
https://github.com/yovanoc/turbo-test

When we try to run `pnpm turbo run build --filter=web...` it's hanging forever even if the build finishes.

This is why I done this in the docker file but very dirty.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/7302317/185601159-4e393dbf-c613-44fd-bea6-2e524ce056f0.png">

I think the problem happening turbo cli side, but launching the same command with `--filter=api...` works perfectly fine.

### Expected Behavior

Not hanging so that the docker-compose can work perfectly.

### To Reproduce

Just follow the docker steps in readme.

**Comment by tknickman** [comment]
This looks to be the same issue as https://github.com/vercel/turborepo/issues/1719, as the docker example uses Next.js in standalone mode. I'm going to close this one as a duplicate to consolidate the discussion over there - thanks!
