### ISSUE TITLE
Improve broken / invalid pipeline error messages

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#177]
### What version of Turborepo are you using?

1.x

### Describe the Bug

We should never panic like #161, ever ever. 

### Expected Behavior

Turbo should gracefully fail with an error message and ideally never panic. We already validate the graph for cycles, but it seems like this may have to do with something in the scheduler. 

### To Reproduce

Needs more investigation

**Comment by gsoltis** [comment]
Closing as obsolete. We have several error messages on pipeline configuration-related problems, and can tackle additional ones as they arise.
