### ISSUE TITLE
Non-graphical machine readable `--graph` / `--filter=[git changes]` build list

### ISSUE THREAD

**Issue by kriswuollett** [vercel/turborepo#1788]
### Describe the feature you'd like to request

Turborepo's CLI [`--graph`](https://turborepo.org/docs/reference/command-line-reference#--graph) only outputs the plan for the build in a graphical form. There is also [`--filter`](https://turborepo.org/docs/reference/command-line-reference#--filter) which lets one build only the workspaces that have changed since a base commit.

Turborepo's CLI should support a command named something like `changes` that is machine readable that informs what packages would be built in a non-graphical output format.

### Describe the solution you'd like

Add a subcommand `changes` that outputs JSON like [`dorny/paths-filter`](https://github.com/dorny/paths-filter) such that a CI system can know what downstream work needs to be done like packaging apps up in container images. For example with the starter environment, the output could look like:

```json
{
  "eslint-config-custom": false,
  "tsconfig": false,
  "ui": true,
  "docs": true,
  "web": true
}
```

With that a CI system could package up only the apps that had changes and were built.

### Describe alternatives you've considered

I considered just running build with `--filter` and then just detecting which apps have output directories like `.next/standalone` directories created, and then create the JSON myself, but that seems too bespoke.

Adding functionality to the `--graph` option is a possibility, but it is probably less likely users would take advantage of the actual dependency graph. Just having a flatten map of what would be built would be very useful.

I'm currently using `--dry-run` along with `--filter` if a pull request to basically do the same myself. But would much rather have a simple built in command since Turborepo already offers `--graph` anyways...

**Comment by gsoltis** [comment]
Is there something missing from `--dry-run=json` that you would need?

**Comment by kriswuollett** [comment]
Ah, yes, I did not notice the `json` option on `--dry-run`. Thanks! I think the above could be generated with a `jq` script since it does provide the whole `packages` list and not just `tasks` so I could still know what packages are not being built.
