### ISSUE TITLE
doc link to filter is broken

### ISSUE THREAD

**Issue by kriswuollett** [vercel/turborepo#1790]
### What version of Turborepo are you using?

N/A

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

https://github.com/vercel/turborepo/blob/main/docs/pages/docs/reference/command-line-reference.mdx#--filter link to "dedicated" documentation for filter needs updating.

### Expected Behavior

N/A

### To Reproduce

N/A

**Comment by tknickman** [comment]
These docs are meant to be browsed from the [docs site](https://turborepo.org/docs), not from the mdx docs directly. 

This link does work from the docs site:
https://turborepo.org/docs/reference/command-line-reference#--filter
