### ISSUE TITLE
Browser is not opened in WSL2

### ISSUE THREAD

**Issue by Newbie012** [vercel/turborepo#1804]
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

While running `pnpm turbo login` on WSL2 Ubuntu 20, The terminal is hanging on the following output without opening a browser:
```
>>> Opening browser to https://vercel.com
>>  Waiting for your authorization...
```

According to the following code:

https://github.com/vercel/turborepo/blob/a05816f946250a78eb46540dd4c82b92c7af2954/cli/internal/login/login.go#L142:L147

I assume that the link was supposed to be https://vercel.com/turborepo/token?redirect_uri=http://127.0.0.1:9789

### Expected Behavior

Browser should be opened, and if not, ask the user to click on a link instead.

### To Reproduce

1. Open WSL2
2. Run `pnpm turbo login`

**Comment by chris-olszewski** [comment]
Hi, can you run `which wslview` and `wslview https://github.com` from your WSL shell and report back the results?

**Comment by Newbie012** [comment]
Sorry for keeping you waiting! for some reason, I missed the notification.

```
➜  ~ which wslview
/usr/bin/wslview
➜  ~ wslview https://github.com
/usr/bin/wslview: line 108: /bin/zsh -c 'chown root:kvm /dev/kvm && chmod 660 /dev/kvm'c/Windows/System32/reg.exe: No such file or directory
/usr/bin/wslview: line 98: /bin/zsh -c 'chown root:kvm /dev/kvm && chmod 660 /dev/kvm'c/Windows/System32/chcp.com: No such file or directory
/usr/bin/wslview: line 103: /bin/zsh -c 'chown root:kvm /dev/kvm && chmod 660 /dev/kvm'c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe: No such file or directory
/usr/bin/wslview: line 98: /bin/zsh -c 'chown root:kvm /dev/kvm && chmod 660 /dev/kvm'c/Windows/System32/chcp.com: No such file or directory
```

**Comment by gsoltis** [comment]
Hmm. It looks like `wslview` is not functioning on your system. I suspect this is not a turbo issue, but more likely something to do with ubuntu running in WSL2. I did find something that looked related: https://bugs.launchpad.net/ubuntu/+source/wslu/+bug/1877016

But, it depends on what version of ubuntu you're running

**Comment by Newbie012** [comment]
I'm see.
My version is Bionic, I guess I should have to update it after all these years 😅

Thanks for looking deep into this. I really appreciate it. Hopefully it should help other WSL users.

Feel free to close this issue
