### ISSUE TITLE
Support config file like .js, .ts...

### ISSUE THREAD

**Issue by harrytran998** [vercel/turborepo#183]
### Describe the feature you'd like to request

Hi, thank you for the great lib! But I wonder how about this? 

`turbo.config.js` or `turbo.config.ts`

```js
module.export = {
  baseBranch: 'origin/main',
  pipeline: {
    build: {
      dependsOn: ['^build'],
      outputs: ['.next/**'],
    },
    test: {
      dependsOn: ['^build'],
      outputs: [],
    },
    lint: {
      outputs: [],
    },
    dev: {
      cache: false,
    },
  },
};
  ```
  

### Describe the solution you'd like

I don't know GO but in JS, we have one package to load the config file is [joycon](https://www.npmjs.com/package/joycon)

### Describe alternatives you've considered

  I think this is a very useful feature, it can reduce a lot of clutter inside the package.json scripts field!

**Comment by egoist** [comment]
a turbo.json file would be nice, I don't see the need for a js/ts config file

**Comment by jaredpalmer** [comment]
+1 for turbo.json. not going to start a node.js process for the foreseeable future, so .js isn’t going to happen

**Comment by weyert** [comment]
> +1 for turbo.json. not going to start a node.js process for the foreseeable future, so .js isn’t going to happen

Maybe the solution from k6 could help?  I think they use https://github.com/dop251/goja

**Comment by noghartt** [comment]
+1 for `turbo.json`, it's similar to other config files, but I think that could be given the freedom to use the `.config.(ts|js)` file too.

**Comment by natemoo-re** [comment]
I'd be excited to use `turbo.json`! I agree that blocking startup for a Node process doesn't make a lot of sense right now.

Happy to chat about the hidden complexity of config loading, though! I maintain [`@proload/core`](http://npm.im/@proload/core) and have been down this road.

**Comment by jaredpalmer** [comment]
Moving to #217. Closing

**Comment by softmarshmallow** [comment]
js can take a lot of advantage for dynamicly configuring the configuration, ability to have comments, etc..
