### ISSUE TITLE
ERROR  User not found.

### ISSUE THREAD

**Issue by 7flash** [vercel/turborepo#1838]
### What version of Turborepo are you using?

1.4.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

```
pnpm dlx turbo login
```

![image](https://user-images.githubusercontent.com/4569866/188087319-12cc3744-b014-4308-95c3-825e11064191.png)

```
pnpm dlx turbo link
```

![image](https://user-images.githubusercontent.com/4569866/188087217-d98d25aa-b310-419f-8a34-61ffecd30a9a.png)

### Expected Behavior

expected to link once authorized

### To Reproduce

```
npx create-turbo
```

.devcontainer/Dockerfile

```
ARG VARIANT="18-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-${VARIANT}
```

**Comment by gsoltis** [comment]
This is fixed in `turbo 1.4.5` via #1844
