### ISSUE TITLE
.env example

### ISSUE THREAD

**Issue by yovanoc** [vercel/turborepo#1850]
### Describe the feature you'd like to request

I think it could be a good idea to have env files example.

### Describe the solution you'd like

Like a nextjs app can load automatically en files but a the level of the project, some others projects too, but sometimes we need it a the root of monorepo, and sometimes there is some in common. Maybe we can add the simplest way to manage .env files in an example

### Describe alternatives you've considered

Done it by myself but not satisfied

**Comment by yovanoc** [comment]
I would like to point out that in windows symlinks does not work well over git.. I really don't know how to handle my en vars over a turborepo

**Comment by iduuck** [comment]
Have you tried [this approach](https://stackoverflow.com/a/59761201/2462992)?

**Comment by yovanoc** [comment]
Oh yeah I didn't know about that. I'm not on windows anyways that's just for the example. I'm not sure to force user to configure this and make symlinks all over the repo it's a good idea

**Comment by nathanhammond** [comment]
@mattpocock just landed an update to our docs that includes an example of using `dotenv` with `turbo`. That explains how we recommend configuring your environment variables.

**Comment by iduuck** [comment]
@nathanhammond Perhaps I am blind onto this, but I am not able to find anything in the docs regarding the usage of `dotenv`. I am only able to find the example in the `examples/` folder, which is not helping me, since I am not able to get the build up and running (without a monkey-patch) on Vercel (it's telling me, that the root `.env` is not available, which is also true, since root `.env` is gitignore'd).

**Comment by nathanhammond** [comment]
https://turbo.build/repo/docs/handbook/dev#tutorial

**Comment by nathanhammond** [comment]
Though it sounds like you may be looking for support at the intersection between Vercel/Turborepo/.env? If so, please open a new issue with repro steps demonstrating your problem so we can help make clear how best to handle it.
