### ISSUE TITLE
turbo-ignore: fails with an unfriendly error if the monorepo root `package.json` does not have the `name` field

### ISSUE THREAD

**Issue by smorimoto** [vercel/turborepo#1859]
### What version of Turborepo are you using?

1.4.5

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

`turbo-ignore` fails with an unfriendly error if the monorepo root `package.json` does not have the `name` field.

I believe that in most projects it would probably never be a problem, but my team didn't put the `name` field in the root and tried to debug it by poking `turbo-ignore` a lot, but it just didn't work, so I figured it out by going to the source.

The reason for this is that the `scope` field returned by `getScopeFromPath` in `turbo-utils`, which `turbo-ignore` uses, depends on the `name` field in `package.json`.

https://github.com/vercel/turborepo/blob/04b077a1582badd4c8378b8357691b5795dad7ee/packages/turbo-ignore/src/index.ts#L23

If the `scope` of `argsScope` is not found, it will fallback to `pathScope`, but unfortunately in this situation the `scope` of `pathScope` is also `null`. The possible error in this case is almost always the missing `name` field, and in my opinion just a polite error message is fine.

https://github.com/vercel/turborepo/blob/1116799546f688ec17cd9fe708dae4413b182955/packages/turbo-utils/src/getScopeFromPath.ts#L6-L13

I think it makes sense to just make sure that `argsScope.scope` and `scope` aren't found here, and then give a hint for users.

https://github.com/vercel/turborepo/blob/04b077a1582badd4c8378b8357691b5795dad7ee/packages/turbo-ignore/src/index.ts#L24-L30

### Expected Behavior

It needs printing a more friendly error or different utility implementations.

### To Reproduce

Remove the `name` field from `package.json` in the root of your current turborepo monorepo.

**Comment by smorimoto** [comment]
Silent acknowledgement: Thank you @nicolas-webdev for introducing this tool at today's meeting!

**Comment by smorimoto** [comment]
Very simply, here's what I think should be done, and it's obviously a "good first issue"!

```diff
if (!scope) {
  console.error(
    "Error: app scope not found. turbo-ignore inferencing failed, proceeding with build."
  );
+ if (!pathScope.scope) {
+   console.error("friendly hint");
+ }
  console.error("");
  process.exit(1);
}
```

**Comment by t-i-0414** [comment]
@smorimoto 
Thanks for your report.
I work on this issue referring to your code snippet!

**Comment by smorimoto** [comment]
@t-i-0414 It's looking very good! I'm glad to see many people tackling this kind of issue!
