### ISSUE TITLE
Example lint script not working

### ISSUE THREAD

**Issue by steida** [vercel/turborepo#1869]
### What version of Turborepo are you using?

None

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

`"lint": "TIMING=1 eslint src/**/*.ts* --fix",` does not lint files.

`"lint": "TIMING=1 eslint 'src/**/*.ts*' --fix",` does lint files.

https://stackoverflow.com/questions/54165756/eslint-glob-is-not-considering-all-directories-recursively

### Expected Behavior

Should lint files.

### To Reproduce

Just try it.

**Comment by steida** [comment]
`"lint": "TIMING=1 eslint src --ext .ts,.tsx",` 

This is probably the best because it's not platform specific and it's recursive.

**Comment by mehulkar** [comment]
Could you link to which example you're talking about?
