### ISSUE TITLE
Error: Unsupported package manager version.

### ISSUE THREAD

**Issue by denissteinhorst** [vercel/turborepo#1880]
### What version of Turborepo are you using?

@latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

unable to install turborepo from scratch using a mac (m1) / pnpm

### Expected Behavior

install turborepo

### To Reproduce

dst@MBP Playground % npm -v
8.9.0

dst@MBP Playground % node -v
v18.2.0

dst@MBP Playground % pnpm -v
6.11.0

dst@MBP Playground % pnpx create-turbo@latest     
              
✔ Install the following package: create-turbo@latest? (Y/n) · true
Packages: +156
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/dst/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 156, reused 156, downloaded 0, added 156, done

/Users/dst/.pnpm-store/v3/tmp/_npx/25248/5:
+ create-turbo 1.4.5

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? ./my-turborepo
? Which package manager do you want to use? pnpm

Aborting installation.
**Unexpected error. Please report it as a bug:**
Error: Unsupported package manager version.
    at run (/Users/dst/.pnpm-store/v3/tmp/_npx/25248/5/node_modules/.pnpm/create-turbo@1.4.5/node_modules/create-turbo/dist/index.js:324:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

A new version of `create-turbo` is available!
You can update by running: yarn global add create-turbo

dst@MBP Playground %

**Comment by denissteinhorst** [comment]
Tried to figure it out over discord, a guy named "Matt" mentioned that this is probably the best way to find a solution. thanks in advance.

**Comment by mehulkar** [comment]
In v1.4.5, pnpm6 isn't supported: https://github.com/vercel/turborepo/blob/v1.4.5/packages/create-turbo/src/constants.ts#L26-L34

So we need a release after https://github.com/vercel/turborepo/pull/1837 was merged. cc @tknickman @nathanhammond

**Comment by nathanhammond** [comment]
Release in flight: https://github.com/vercel/turborepo/actions/runs/3011563882

1.4.6 will address this.
