### ISSUE TITLE
Inputs referencing files outside of a package don't affect the task hash

### ISSUE THREAD

**Issue by AlCalzone** [vercel/turborepo#1913]
### What version of Turborepo are you using?

1.4.6

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

I've defined a task in my pipeline as follows:
```
		"lint": {
			"dependsOn": [],
			"inputs": [
				"!(build)/**/*.{ts,json}",
				// The style based linting tasks depend on the corresponding configuration in the repo root
				"../../.eslintrc.js",
				"../../.eslintignore",
				"../../.prettierrc.js",
				"../../.prettierignore",
				"../../tsconfig.eslint.json"
			],
			"outputs": []
		},
```
which is supposed to make the workspace tasks depend on the global configuration in the repo root.
According to https://github.com/vercel/turborepo/issues/1064, this is supposed to be working, but even after changing `.prettierrc.js`, I'm getting cache hits instead of re-running the tasks.

### Expected Behavior

The tasks should be re-run.

### To Reproduce

1. Have a task in a workspace depend on files outside the workspace.
2. Run the task
3. Change one of the referenced files outside the workspace
4. Run the task again, see cache hit.

**Comment by gsoltis** [comment]
I believe this should be fixed in #1937 which is in the latest canary: https://github.com/vercel/turborepo/releases/tag/v1.4.7-canary.0

If there's still a problem in that release, I'll be happy to reopen.

**Comment by AlCalzone** [comment]
Seems fixed, thanks!

**Comment by scamden** [comment]
if try this for a path into another dep it doesn't seem to work:
```
  "lint": {
      "outputs": [],
      "inputs": ["**/*", "../rig/eslint-preset.js"]
    },
 ```

where rig is one of the workspaces and is included as a dep everywhere via `"rig": "workspace:*",`
    
turbo version 1.6.3 
(sidenote but turbo also doesn't throw any kind of error if I specify a totally non-existent file there)

**Comment by scamden** [comment]
opened separate issue here: https://github.com/vercel/turbo/issues/2999
