### ISSUE TITLE
Error: Unsupported package manager version

### ISSUE THREAD

**Issue by TheLeoP** [vercel/turborepo#1916]
### What version of Turborepo are you using?

@latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

1. `npx create-turbo@latest example`
2. select npm (or yarn as well) as package manager

```
Aborting installation.
Unexpected error. Please report it as a bug:
Error: Unsupported package manager version.
    at run (/home/luis/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/index.js:333:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

### Expected Behavior

create-turbo should sucesfully create a monorepo

### To Reproduce

1. `npx create-turbo@latest example`
2. select npm (or yarn as well) as package manager

```
Aborting installation.
Unexpected error. Please report it as a bug:
Error: Unsupported package manager version.
    at run (/home/luis/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/index.js:333:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

Important information:

Node and yarn are installed as snaps.

**Comment by nathanhammond** [comment]
Unfortunately, this is going to need a more detailed reproduction. We are unable to reproduce it with those steps. This is likely due to npm and yarn not being executable from the context of that current process.

**Comment by TheLeoP** [comment]
It turns out that the problem was the Node version provided by Ubuntu via snaps just like in [this expo issue](https://github.com/expo/expo/issues/18349). I'm not sure if the problem is about the Node version itself or rather the Node related executables not being executable as you said.

**Comment by nathanhammond** [comment]
Great, thanks for following back up!
