### ISSUE TITLE
Automatic inference doesn't work as expected

### ISSUE THREAD

**Issue by mauricekleine** [vercel/turborepo#1921]
### What version of Turborepo are you using?

1.4.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I'm aware that this is an edge case, but we ran into an issue in which automatic inference was not working as expected for our app that was bootstrapped with Create React App, but uses Vite for the build step. Since we still need to migrate our test suite from `react-scripts` to maybe something like `vitest`, our app has both the `react-script` and `vite` dependencies. 

The check for the existince of `react-scripts` comes before the check for the existence of `vite` in the [inference script](https://github.com/vercel/turborepo/blob/a650e73cfa0aa265ba582a39dd1ee87aefa7251f/cli/internal/inference/inference.go) which in our case incorrectly marks our app as a CRA app.

### Expected Behavior

The app should be correctly marked as a Vite app.

An idea could be by checking which command (`react-scripts` or `vite`) is used when running a Turborepo command - for example, our `build` command uses `vite build` but our `test` command runs `react-scripts test`.

### To Reproduce

Create a new Turborepo project with a Vite app that uses a `VITE_` environment variable, and that also lists `react-scripts` as it's dependcy. Now run the `build` command to cache it, change the environment variable, run `build` again and notice that the cached output is returned.

**Comment by gsoltis** [comment]
Hmm. If I understand correctly, you have a hybrid package, that should be treated differently based on which task you are currently running?

**Comment by gsoltis** [comment]
FWIW, you can add the environment variables yourself to the task definitions in `turbo.json` as a workaround.

**Comment by nathanhammond** [comment]
@gsoltis's proposal is actually our recommended solution.

We will never be able to guarantee perfect inference and this code exists primarily to reduce the size of an API footgun that we can't otherwise easily protect you from.

In other words: we don't intend to infer past the first match, and for people in your scenario we expect you to continue enumerating the required environment variable dependencies.

**Comment by mauricekleine** [comment]
@gsoltis @nathanhammond yes I'm aware, and it totally makes sense 👍
