### ISSUE TITLE
ESlint missing in ui package of default turborepo setup

### ISSUE THREAD

**Issue by valkedev** [vercel/turborepo#1939]
### What version of Turborepo are you using?

1.4.6

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

Started new project with `npx create-turbo@latest` but there is no `.eslintrc.js` file in `ui` package by default so `yarn lint` in root folder exists with errors. It should be there regasrding to documentation: https://turborepo.org/docs/getting-started/create-new

### Expected Behavior

Tasks:    3 successful, 3 total
Cached:    0 cached, 3 total
Time:    4.909s 

### To Reproduce

* Set up new project with `npx create-turbo@latest`
* Run `yarn lint` in root folder

**Comment by gsoltis** [comment]
I am unable to reproduce this problem. I tried the steps described and got 
```
Tasks:    3 successful, 3 total
Cached:    0 cached, 3 total
Time:    1.767s
```

As far as I can tell, this is working as intended. I don't think there is supposed to be an `.eslintrc.js` in the `ui` package. The docs [here](https://turborepo.org/docs/getting-started/create-new#understanding-eslint-config-custom) suggest that the root and `eslint-config-custom` should be used. 

If you want to publish a sample repository demonstrating the problem, I'm happy to reopen the issue.
