### ISSUE TITLE
Docs homepage perceptibly laggy on mobile

### ISSUE THREAD

**Issue by mattpocock** [vercel/turborepo#1940]
### What version of Turborepo are you using?

N/A

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Other

### Describe the Bug

Reported in this tweet:

https://twitter.com/z4o4z/status/1569617976273551367

On Chrome/iPhone

### Expected Behavior

N/A

### To Reproduce

N/A

**Comment by nathanhammond** [comment]
This has been resolved.
