### ISSUE TITLE
Pnpm workspace still unable to prune 

### ISSUE THREAD

**Issue by zigang93** [vercel/turborepo#1941]
### What version of Turborepo are you using?

1.4.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

https://github.com/vercel/turborepo/pull/1819 this PR already included at version 1.4.6

but when I try to run `pnpm turbo prune --scope=web --docker`
it show error: `this command is not yet implemented for nodejs-pnpm`

### Expected Behavior

expect `pnpm turbo prune --scope=web --docker` to be work

### To Reproduce

example repo: https://github.com/vercel/turborepo/tree/main/examples/with-docker

**Comment by weyert** [comment]
There is now canary or new release yet that includes this new functionality. I am waiting for it too :)

**Comment by gsoltis** [comment]
Can you try the latest canary? https://github.com/vercel/turborepo/releases/tag/v1.4.7-canary.0

**Comment by weyert** [comment]
I have tried out only it's not copying over the patches that were created with PNPM. 
The lock file has:

```yaml
lockfileVersion: 5.4
patchedDependencies:
  tailwindcss-theme-swapper@0.4.1:
    path: patches/tailwindcss-theme-swapper@0.4.1.patch
    hash: 74sdngpia5abwdbohdpkd2yzba
```

but the `patches`-directory didn't get copied to the output directory of the `prune`-action

**Comment by gsoltis** [comment]
@chris-olszewski can you take a look?

**Comment by zigang93** [comment]
@gsoltis It works at canary version,  thanks
@weyert I tried replace package.json `turbo` from `latest` to `^1.4.7-canary.0` and `pnpm i` agian.. it should work

for those who want to make it work at docker pnpm  example
```Dockerfile
# 1. Generate a sparse/partial monorepo with a pruned lockfile for a target workspace. https://turborepo.org/docs/reference/command-line-reference#turbo-prune---scopetarget

# Refer to this original https://github.com/vercel/turborepo/blob/main/examples/with-docker/apps/web/Dockerfile

FROM node:alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

# Set working directory
WORKDIR /app

COPY . .
RUN corepack enable
# will remove turbo@1.4.7-canary.0 after stable release of 1.4.7
RUN pnpm dlx turbo@1.4.7-canary.0 prune --scope=web --docker


# 2. Rebuild the source code only when needed
FROM node:alpine AS builder
WORKDIR /app

# Build the project and its dependencies
ENV NEXT_TELEMETRY_DISABLED 1

# set your APP_NAME
ENV APP_NAME=web

COPY .gitignore .gitignore
COPY --from=deps /app/out/json/ .
COPY --from=deps /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=deps /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN corepack enable
RUN pnpm install

COPY --from=deps /app/out/full/ .
COPY turbo.json turbo.json
RUN pnpm turbo run build --filter=$APP_NAME...

# 3. Production image, copy all the files and run next
FROM node:alpine AS runner

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV=production

# set your APP_NAME
ENV APP_NAME=web

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# comment out below if you don't have public folder
COPY --from=builder /app/apps/$APP_NAME/public public

COPY --from=builder --chown=nextjs:nodejs /app/apps/$APP_NAME/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/$APP_NAME/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD node apps/$APP_NAME/server.js
```

**Comment by weyert** [comment]
> @gsoltis It works at canary version, thanks @weyert I tried replace package.json `turbo` from `latest` to `^1.4.7-canary.0` and `pnpm i` agian.. it should work

Yeah, but as I said above for me it's not copying the patch files that are created with `patch`-command (https://pnpm.io/cli/patch). If it's a built-in function of `pnpm` it might be a good idea to ensure it gets copied along.

**Comment by nathanhammond** [comment]
￼@weyert can you open a new issue for this and mention Chris?￼
