### ISSUE TITLE
Use `.json` file type for eslint config in `create-turbo` utility 

### ISSUE THREAD

**Issue by Hacksore** [vercel/turborepo#1962]
### What version of Turborepo are you using?

1.22.19

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Currently the `create-turbo` tool will create the next template with an `eslint.js` file where as when creating `create-next-app` it's using a `.json` file.

Right now I have issues when trying to turn a next app to be fully ESM based and loading a `eslint.js` file yields the following error when building.

```
web:build: $ next build
web:build: info  - Linting and checking validity of types...
web:build: error - ESLint: Cannot read config file: /Users/hacksore/Code/opensource/turborepo-nextjs-esm/apps/web/.eslintrc.js Error: require() of ES Module /Users/hacksore/Code/opensource/turborepo-nextjs-esm/apps/web/.eslintrc.js from /Users/hacksore/Code/opensource/turborepo-nextjs-esm/node_modules/@eslint/eslintrc/lib/config-array-factory.js not supported. Instead change the require of .eslintrc.js in /Users/hacksore/Code/opensource/turborepo-nextjs-esm/node_modules/@eslint/eslintrc/lib/config-array-factory.js to a dynamic import() which is available in all CommonJS modules.
```
Demo repo: https://github.com/Hacksore/turborepo-nextjs-esm

If I use a `eslint.json` file no issues occur so either we have to fix this upstream in next or just switch out the template file type.

Happy to raise a PR to at least fix the file type of the eslint config but figured it is best to open an issue to discuss more first.

### Expected Behavior

- Convert NextJS app to use ESM
- Build has no errors

### To Reproduce

- `git clone https://github.com/Hacksore/turborepo-nextjs-esm.git`
- `cd turborepo-nextjs-esm`
- `yarn` / `npm install`
- `yarn build` / `npm run build`

**Comment by mehulkar** [comment]
Couple thoughts:

- Changing the default to `.json` seems ok to me, but we could also rename it to `.eslintrc.cjs` (or in your example repo, rename it to `.mjs` extension)
- It sounds like your conversion to ESM involves manual work anyway, so you'd be converting other things also? In that case, why does the default for the lint config matter more than other things?

**Comment by Hacksore** [comment]
@mehulkar I think you're right that if I am making the conscious decision to use ESM I can also make the change to the lint config to use `.mjs`/`.cjs` (I just tested and it worked fine respectively).

My thought was `.json` was a bit more flexible regardless of what format you chose to use.

**Comment by mehulkar** [comment]
I'm ok with JSON as a reasonable default, if there was a compelling reason to change it. If that reason is to also support ESM, it's not ideal that [ESlint docs say they don't support ESM][1]. They have a new [experimental feature that will][2], so I'd be more inclined to make changes once that was the default.

Will let others from @vercel/turbo-oss chime in though!

[1]: https://eslint.org/docs/latest/user-guide/configuring/configuration-files#configuration-file-formats
[2]: https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new

**Comment by Hacksore** [comment]
The one drawback to JSON is comments are not part of standard spec.

This is considering there are comments in use, which currently there are.
https://github.com/vercel/turborepo/blob/main/packages/create-turbo/templates/_shared_ts/.eslintrc.js#L3

**Comment by mehulkar** [comment]
Yeah that's exactly why I prefer the JS variety. I do think `create-turbo` needs to provide a great experience out of box. It's a bit outside the purview of turborepo to really _care_ about lint configs, but considering that in #1881, @mattpocock is including a section on Linters, I think it would be worthwhile for us to be able comment through config files to explain how they work and they they're trying to do.

**Comment by Hacksore** [comment]
@mehulkar I agree and since I have a good workaround there is not much merit in this proposed change.

Closing out this issue but greatly appreciate the dialogue and suggestions you provided.
