### ISSUE TITLE
Error on selecting yarn for initializing monorepo

### ISSUE THREAD

**Issue by sky-kryst** [vercel/turborepo#1976]
### What version of Turborepo are you using?

1.4.6

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

`
? Which package manager do you want to use? yarn

Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: import_fs.default.cpSync is not a function
    at run (C:\Users\skykr\AppData\Roaming\npm-cache\_npx\10788\node_modules\create-turbo\dist\index.js:328:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

### Expected Behavior

Install dependencies

### To Reproduce

npx create-turbo@latest

then select yarn

**Comment by nathanhammond** [comment]
Upgrade Node.js to 16 or newer.
