### ISSUE TITLE
Bug When Creating a new Project

### ISSUE THREAD

**Issue by jmarbutt** [vercel/turborepo#2020]
### What version of Turborepo are you using?

Latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I am running 

```
npx create-turbo@latest
```

I then proceed to give it a directory and select `npm` then I get:

```
Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: import_fs.default.cpSync is not a function
    at run (/Users/jonathan/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/index.js:328:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Expected Behavior

To not Fail

### To Reproduce

The steps are provided above but here is a video also. 

https://user-images.githubusercontent.com/1386587/191338734-29272615-e5eb-41d6-9e14-5b4b4bf6b74f.mp4

**Comment by tknickman** [comment]
Please use node 16 or greater!

**Comment by jmarbutt** [comment]
Thanks
