### ISSUE TITLE
Feature Request: support `npm run dev` specify port

### ISSUE THREAD

**Issue by PangYiMing** [vercel/turborepo#2037]
### Describe the feature you'd like to request

Feature Request: support `npm run dev` specify port

`npm run dev --port 5389` 

### Describe the solution you'd like

Feature Request: support `npm run dev` specify port

`npm run dev --port 5389` 

### Describe alternatives you've considered

I need to specify the port in dev mode. because port 300x is not available.

**Comment by nathanhammond** [comment]
Look into argument separators. I suspect that you need to pass in something that looks like one of these to get the behavior you're looking for:

```sh
npm run dev -- --port 5389
npm run dev -- -- --port 5389
```
