### ISSUE TITLE
run failed: could not unmarshal lockfile: : yaml: line 9047: did not find expected ',' or '}'

### ISSUE THREAD

**Issue by tjx666** [vercel/turborepo#2039]
### What version of Turborepo are you using?

1.5.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

![image](https://user-images.githubusercontent.com/41773861/191723219-aba31f32-24ba-4594-93a9-96f188b963dd.png)

![image](https://user-images.githubusercontent.com/41773861/191723348-cb83db07-1fc5-4938-a062-01110cd6a5e1.png)

The most recent work version is 1.4.6

### Expected Behavior

No error

### To Reproduce

Private project, I will create a reproduce repository when I have time

**Comment by weyert** [comment]
Which version of PNPM?

**Comment by tjx666** [comment]
> Which version of PNPM?

7.12.1

**Comment by nathanhammond** [comment]
@tjx666 Can you create a [gist](https://gist.github.com/) with your lockfile so that we can run tests against it?

**Comment by nathanhammond** [comment]
It's throwing here, https://github.com/go-yaml/yaml/blob/f6f7691b1fdeb513f56608cd2c32c51f8194bf51/parserc.go#L1091

But I don't know what input we have to be feeding it to get there.

**Comment by tjx666** [comment]
```

  /toidentifier/1.0.1:
    resolution: {integrity: sha512-o5sSPKEkg/DIQNmH43V0/uerLrpzVedkUh8tGNvaeXpfpuwjKenlSox/2O/BTlZUtEe+JG7s5YhEz608PlAHRA==, tarball: toidentifier/download/toidentifier-1.0.1.tgz?cache=0&sync_timestamp=1636943523553&other_urls=https%3A%2F%2Fregistry.npmmirror.com%2Ftoidentifier%2Fdownload%2Ftoidentifier-1.0.1.tgz}
    engines: {node: '>=0.6'}
    dev: false

```

**Comment by chris-olszewski** [comment]
Testing against some other YAML 1.2 parsers it looks like the tarball string in the resolution object should be wrapped in quotes due to the `?` it contains

**Comment by chris-olszewski** [comment]
Digging into this more this is an issue with the `go-yaml` package not conforming to the YAML 1.2 spec. Will work on submitting a PR upstream so we don't trip over this.

**Comment by chris-olszewski** [comment]
I've submitted https://github.com/go-yaml/yaml/pull/905 which should fix this issue once it is merged
