### ISSUE TITLE
Turbo not picking up the right dependencies

### ISSUE THREAD

**Issue by iDuuck** [vercel/turborepo#2055]
### What version of Turborepo are you using?

1.4.6 - 1.5.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When I am trying to run the `dev` task of the `example-app` package, there is a problem with turbo, that it's not running the ([dependent](https://github.com/iDuuck/turbo-issue/blob/main/packages/example/package.json#L10)) build task of the `@foo/cli` package (like how it's defined [in the turbo.json](https://github.com/iDuuck/turbo-issue/blob/main/turbo.json#L9))

### Expected Behavior

I am expecting, that when I defined `["^build"]` for the `dev` task (as `dependsOn`), that the `build` task is run before the `dev` task.

### To Reproduce

I created a repository with the issue: https://github.com/iDuuck/turbo-issue

**Comment by iDuuck** [comment]
nvm, this was due to execution with `parallel`. But is this in any way planned on being supported?

**Comment by gsoltis** [comment]
Yes, we do intend on supporting running certain tasks in "dev" mode after having run their dependencies in a future release.
