### ISSUE TITLE
eslint-config-turbo don't work with turbo 1.5

### ISSUE THREAD

**Issue by yovanoc** [vercel/turborepo#2072]
### What version of Turborepo are you using?

1.5.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

<img width="847" alt="image" src="https://user-images.githubusercontent.com/7302317/192094441-00db31bb-1f90-4d3b-8133-f504cc3f3b23.png">

### Expected Behavior

should work now with the new `env` key in turbo.json

### To Reproduce

Just a simple turbo 1.5.2 example with eslint-config-turbo

**Comment by gnohj** [comment]
`eslint-config-turbo` should be upgraded to `0.0.4`

**Comment by yovanoc** [comment]
I have this version

**Comment by DanCymonz** [comment]
im having same issue but not sure whats going on. Even when i delete the turbo.json file i get the same error

` Error: $AUTH0_AUDIENCE is not listed as a dependency in turbo.json` etc error

**Comment by DanCymonz** [comment]
looking at the source for it. maybe it should error if it cant find turbo.json. looks like it just bails?

**Comment by iDuuck** [comment]
Let me check this. I had implemented the change for the new environment variable declarations in the plugin.

Would you mind, sharing the usage of the `process.env`, so that I can add a test-case for this?

**Comment by yovanoc** [comment]
@iDuuck Where do you want I log the process.env exactly?

**Comment by iduuck** [comment]
@yovanoc I wanna know the context. The function or lines you are using the process.env in. The eslint-plugin comes with several test cases, and I want to double check the usage in your case.

**Comment by yovanoc** [comment]
Oh yes that was my mistake, mb.
