### ISSUE TITLE
Cache hash changes on windows without any change

### ISSUE THREAD

**Issue by byCedric** [vercel/turborepo#2075]
### What version of Turborepo are you using?

1.5.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I created a [simple example repo](https://github.com/byCedric/expo-monorepo-example) with pnpm and turbo. When I played around, I noticed my cache hits were flaky on Windows. I'm not sure what's going on here.

I get different cache key results without changing anything within the repo or having any open process accessing the files.

Here is the log with multiple `pnpm build --dry-run` results without changing anything. 
> Notice how the order of `Dependenceis` randomly changes, and the `Hash` too for all except `@acme/eslint-config`.

[turbo-repo-log.txt](https://github.com/vercel/turborepo/files/9640915/turbo-repo-log.txt)

### Expected Behavior

Without changing files in the repository, I expect the hash to stay the same. In this case, that works inside a docker instance (tested with `node:16-alpine` - same machine, docker desktop) but not in just Windows. I'm using:

```
Edition: Windows 11 Pro
Version: 22H2
OS build: 22621.521
Experience: Windows Feature Experience Pack 1000.22634.1000.0
```

```
Windows Terminal
Version: 1.14.2282.0
```

### To Reproduce

Also, I tested the same thing in GHA to rule out issues with my machine. [You can see the same thing happening there](https://github.com/byCedric/expo-monorepo-example/actions/runs/3122544115):
  - ubuntu provides the same hash more often ([see run](https://github.com/byCedric/expo-monorepo-example/actions/runs/3122544115/jobs/5064552018#step:5:24))
    > Edit: seems also to be an issue there, mostly in the **apps/\*** projects, but I have no idea why.
  - windows provides what seems to be "random" hashes most of the time ([see run](https://github.com/byCedric/expo-monorepo-example/actions/runs/3122544115/jobs/5064552032#step:5:24))

Or try it locally (it requires Windows).

- `$ git clone git@github.com:byCedric/expo-monorepo-example.git ./windows-hash-issue`
- `$ cd ./windows-hash-issue`
- `$ pnpm i; pnpm build`
- Now, without doing anything, run `$ pnpm build --dry-run` multiple times.
- Check the `Hash` and `Cached (Local)`, they change without any changes

**Comment by byCedric** [comment]
I also tested the Metro cache, but with the same results: https://github.com/byCedric/expo-monorepo-example/actions/runs/3122579428 (both ubuntu and windows)

**Comment by gsoltis** [comment]
Thanks for the repro! I'll see if I can figure out what's happening here.

**Comment by pChausseC** [comment]
I am also having issues with flaky cache hits when nothing has changed. But on I'm on Mac. I suspect the issue is with pnpm, but I'm not sure. I was also able to single out specific packages in my repo for which the cache would always miss, so I thought something might be off with their build step or input definition. I tried to switch up a few things to no avail.  

BUT when changing package manager to **yarn,** cache hits were 100% consistent. Maybe you can check if that changes something for you? Hopefully this can help you find a possible issue/solution.

**Comment by gsoltis** [comment]
I can confirm I'm able to reproduce this. It looks like it maybe be related to `pnpm` lockfile resolution. I'm digging in on it and I'll let you all know once I have something.

**Comment by gsoltis** [comment]
Quick update: `pnpm` can resolve the same dependency to multiple versions for different workspaces. Our resolution algorithm was taking the first version it found in the lockfile, which caused different hashes, depending on the iteration order of the lockfile. 

#2090 updates the resolution to work per-workspace, so we should be getting the correct version each time, and importantly, a stable result.

**Comment by gsoltis** [comment]
Hey all, if you get a chance, would you mind trying again w/ `turbo@1.5.4-canary.0`? It includes the above fix. We'd like to make sure we're handling all of the `pnpm`-related edge cases

**Comment by byCedric** [comment]
I'm running the tests: https://github.com/byCedric/expo-monorepo-example/actions/runs/3138719465

**Comment by pChausseC** [comment]
Fixed it for me! Thank you @gsoltis 🚀

**Comment by johnschult** [comment]
@gsoltis Same here! Thanks, you're the man 😎

**Comment by gnohj** [comment]
Works for me, thanks @gsoltis

**Comment by gnohj** [comment]
@gsoltis not sure if this is a bug.. but lets say I run `turbo run lint`.. then I run `turbo run build` soon right after.. `build` is defined as having a`dependsOn: ["lint", "^build"]`.. shouldnt the `lint` tasks have cache hits, since they were ran prior? Other than that, everything seems to be in working order when I expliclity run a task via `turbo run` but not when added to `dependsOn`.

**Comment by byCedric** [comment]
> @gsoltis not sure if this is a bug.. but lets say I run `turbo run lint`.. then I run `turbo run build` soon right after.. `build` is defined as having a`dependsOn: ["lint", "^build"]`.. shouldnt the `lint` tasks have cache hits, since they were ran prior? Other than that, everything seems to be in working order when I expliclity run a task via `turbo run` but not when added to `dependsOn`.

Might be better to open a new issue for this, as this one is closed and I think unrelated. 😄
