### ISSUE TITLE
Vercel not detecting .vercel_build_output (svelte-kit) when building with turbo

### ISSUE THREAD

**Issue by Fedeorlandau** [vercel/turborepo#208]
### What version of Turborepo are you using?

1.0.6

### Describe the Bug

For some reason Vercel is not detecting the `.vercel_build_output` content and generating the serverless functions/routes/static files accordingly.

I've set up 2 projects on Vercel using the same repository, one is building the frontend app with svelte-kit and the other one with turborepo. Check the screenshots:

### Expected Behavior

To get Vercel detecting the build generated by turbo.

### To Reproduce

| Without turbo  | With turbo |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/10283686/145724297-ca601085-feb3-4727-9986-e783eb9dea37.png) | ![image](https://user-images.githubusercontent.com/10283686/145724313-4101de43-fafe-48e0-a166-43d8c54f9f8d.png) |
| As you can see, vercel is detecting the .vercel_build_output content | The adapter is generating the folder but not detecting the content afterwards  |

| Without turbo  | With turbo |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/10283686/145724387-ceb5461e-b962-4bdf-8972-d696194eaf64.png)|  ![image](https://user-images.githubusercontent.com/10283686/145724375-80549b76-4643-456f-99e2-e0bf4c64faf0.png) |
| Website running fine |  ![image](https://user-images.githubusercontent.com/10283686/145724469-f9e4b90f-993c-4940-baeb-0d43bea5f5e6.png) |

```json
{
    "private": true,
    "name": "test",
    "workspaces": [
        "apps/*"
    ],
    "scripts": {
        "frontend:prod": "yarn workspace frontend build",
        "backend:prod": "yarn workspace backend build && yarn workspace backend start:prod",
        "bootstrap": "rimraf node_modules && yarn && yarn start"
    },
    "devDependencies": {
        "rimraf": "^3.0.2",
        "turbo": "^1.0.6"
    },
    "turbo": {
        "baseBranch": "origin/main",
        "pipeline": {
            "build": {
                "dependsOn": ["^build"],
                "outputs": [".vercel_build_output/**", ".svelte-kit/**"],
                "cache": false
            },
            "test": {
                "dependsOn": ["^build"],
                "outputs": []
            },
            "lint": {
                "outputs": []
            },
            "dev": {
                "cache": false
            },
            "frontend#deploy": {
                "dependsOn": ["frontend#build"]
            }
        }
    }   
}
```

Thank you!

**Comment by jaredpalmer** [comment]
Set turbo to run from the root directory with something like:  `cd ../.. && npx turbo run build —scope=<app> —includeDependencies`

**Comment by Fedeorlandau** [comment]
@jaredpalmer  hi there, thank you for your answer.

I'm running it from the root directory. If you check the screenshot above you'll see the the root directory is "./".

I've tried to `turbo run build -scope=frontend -includeDependencies` but the result is the same.

The .vercel_build_output is there but vercel is not doing anything with it:

**This is what is missing from the pipeline with turbo**
```
Detected Serverless Functions in ".vercel_build_output"
--
19:05:10.888 | Detected Static Assets in ".vercel_build_output"
19:05:10.888 | Detected Routes Configuration in ".vercel_build_output"
```

Thanks

**Comment by Fedeorlandau** [comment]
Fixed it. I've changed a few things.

![image](https://user-images.githubusercontent.com/10283686/145726730-fd0eafc9-6202-415c-a4b7-c2f79e1ffe6e.png)

Thank you for your work. Turbo is amazing.

**Comment by jaredpalmer** [comment]
You can remove build output and install commands, I think vercel should infer those and solve the problem

**Comment by Fedeorlandau** [comment]
You're 100% correct. Thank you again.
