### ISSUE TITLE
Example: Component library where each component it it's own package

### ISSUE THREAD

**Issue by leerob** [vercel/turborepo#209]
### Describe the feature you'd like to request

A starter example component library where each component is published as its own NPM package.

### Describe the solution you'd like

- Turborepo
- SWC for compilation and test running (through Jest)
- Package publishing (could be Lerna or something else)
- ESLint
- TypeScript
- A way to view components

### Describe alternatives you've considered

Maybe [tsup](https://github.com/vercel/turborepo/blob/main/examples/kitchen-sink/packages/ui/package.json#L15) is a better solution here? Open to suggestions.

Storybook doesn't seem like the right choice because it brings in webpack and Babel and ideally this solution avoids those entirely.

**Comment by leerob** [comment]
Another thought: maybe the component library includes our preferred way of staying - is it Tailwind? Stitches?

**Comment by jaredpalmer** [comment]
Great idea

**Comment by kylemh** [comment]
IMO #269 doesn't resolve this issue. The key thing missing would be per-component versioning.

I need to do this for work anyways, so I don't mind contributing back!

How far can I go with this template? Want me to integrate husky + lint-staged? Can I integrate Intuit's Auto? @leerob said no Storybook and [I haven't been able to set it up anyways](https://github.com/vercel/turborepo/discussions/374) so I can go with Nextra.

**Comment by AbdallahAbis** [comment]
@kylemh @jaredpalmer @leerob any updates on this. The current template is very basic as it's missing testing and previewing components using storybook or something similar. also it misses Husky and lint-staged and maybe commitlint. also, it would be great if eslint is treated as tsconfig, so you can have both browser and server rules seprated.

**Comment by kylemh** [comment]
I'll definitely contribute as soon as I have any free time.

I did what I could to help by outlining what I think is missing [here](https://github.com/vercel/turborepo/discussions/983)

I'm sure Jared is absolutely trying his best to tackle everything, always, all at once ❤️

**Comment by leerob** [comment]
**Update:** We now have a design system example using:

- 🏎 [Turborepo](https://turborepo.org/) — High-performance build system for Monorepos
- 🚀 [React](https://reactjs.org/) — JavaScript library for user interfaces
- 🛠 [Tsup](https://github.com/egoist/tsup) — TypeScript bundler powered by esbuild
- 📖 [Storybook](https://storybook.js.org/) — UI component environment powered by Vite

https://github.com/vercel/turborepo/tree/main/examples/design-system

**Comment by krisb** [comment]
Was going to raise an issue on best practice for nextjs + design system package + storybook, and stumbled on this one.  Seems like the design system example is good basis.  I had a couple of queries on it...

1. Storybook is added to the app, not the package - I would expect storybook to be used to test and validate the components (atoms, molecules etc)
2. An example using Image would be good as I think this presents some challenges due to the nextjs static image loading from public - a use case would be a background repeating image for texture or something similar - this is pretty much a major stumbling block for me at present

**Comment by power-cut** [comment]
@leerob Is there any example available related to Vue & Storybook ?
