### ISSUE TITLE
#1097  重现

### ISSUE THREAD

**Issue by dongyanghe** [vercel/turborepo#2091]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

This project: https://github.com/munafio/react-vue-turborepo-starter.git

You can repeat the question,

### Expected Behavior

#1097

### To Reproduce

#1097

**Comment by dongyanghe** [comment]
Setting "turbo": "=1.2.3" can restore to normal

**Comment by chris-olszewski** [comment]
Hi, if this is an instance of the behavior described in #1097 can you provide the various pieces of information listed out in [the final comment](https://github.com/vercel/turborepo/issues/1097#issuecomment-1248404433)?

**Comment by dongyanghe** [comment]
node v16.15.1
npm 8.19.2
pnpm 7.12.2




First clone the repo, then install the dependencies

```
npm install
```

after that, start the development server (apps running in parallel)

```
npm run dev
```
cmd return:

> react-vue-turborepo-starter@0.0.0 dev
> turbo run dev --parallel

 ERROR  failed to calculate global hash: error hashing files. make sure that git has been initialized failed to read `git hash-object`: exec: "git": executable file not found in %PATH%

**Comment by dongyanghe** [comment]
Sorry, I'm a newcomer and don't know what to provide. If it's not for this problem, you can close it. Thank you

**Comment by nathanhammond** [comment]
@dongyanghe

我們已經搵到呢個問題謝謝
We've already found the problem. Thank you!

**Comment by chris-olszewski** [comment]
@dongyanghe Could you make sure that you're using the latest turbo? (`npm turbo version` should output 1.5.4). I notice that the repo you linked has a checked in lockfile and turbo is at version `1.3.4`.

The error message you got seems to be from [an older version](https://github.com/vercel/turborepo/pull/1747/files#diff-ff06fc2beb2a8e4393b7af0b80b1c63bf04bb8604aec785c35df31d8826e1329L91).
