### ISSUE TITLE
Error with old CRA project 

### ISSUE THREAD

**Issue by MariuzM** [vercel/turborepo#2103]
### What version of Turborepo are you using?

1.5.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

When doing `npm run dev` getting error in one of the projects. This project used to be on it's own so i copy and paste main files. I don't have this issue with CRA plain and vite projects. 

```
ERROR in ./src/App.tsx 1:40-144

Module not found: Error: You attempted to import <PROJECT>/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
```

### Expected Behavior

When doing npm run dev it should start projects in dev mode

### To Reproduce

npm run dev

**Comment by chris-olszewski** [comment]
Hi, from the short error message that you posted this doesn't appear to be coming from turborepo. Could you provide a repo with a reproduction of this error? If that isn't possible could you provide your `turbo.json` and the relevant `package.json` files?

**Comment by MariuzM** [comment]
Hello thank you i think it's the issue with NPM because using Yarn or PNPM i don't have this, i will close this ticket now thank you
