### ISSUE TITLE
Unable to run `create-playwright` at root level with `pnpm dlx create-playwright -w`

### ISSUE THREAD

**Issue by zigang93** [vercel/turborepo#2114]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

cannot properly create playwright `pnpm dlx create-playwright` at turborepo root level
if I run with `-w` which is `pnpm dlx create-playwright -w` will create new folder `-w`..

### Expected Behavior

able run `pnpm dlx create-playwright -w` at root level

### To Reproduce

any turborepo example

**Comment by chris-olszewski** [comment]
This doesn't seem to be related to turbo. I'm able to reproduce the same behavior in an empty directory. What behavior should happen with `-w`? I'm unable to find the flag in the [defined cli flags](https://github.com/microsoft/create-playwright/blob/main/src/cli.ts#L52)
