### ISSUE TITLE
In the demos, move the `config`-specific packages to a separate workspace

### ISSUE THREAD

**Issue by davestewart** [vercel/turborepo#2119]
### Describe the feature you'd like to request

In the demos, move the configuration based packages to their own folder, `config`.

This would:

- make it easier to locate the shared packages vs tripping over config (which is tweaked rarely!)
- bring it more into line the apps / docs / packages example [in the docs](https://turborepo.org/docs/handbook/workspaces)
- make it clear you really do have the freedom to do as you need

### Describe the solution you'd like

The new directory structure would look like this, for example, the kitchen sink:

```
+- kitchen-sink
    +- apps
    |   +- admin
    |   +- api
    |   +- blog
    |   +- storefront
    +- config
    |   +- eslint-config-custom-server
    |   +- eslint-config-custom
    |   +- jest-presets
    |   +- tsconfig
    +- packages
        +- logger
        +- ui
```

### Describe alternatives you've considered

Moving all configs to a [nested workspace](https://github.com/vercel/turborepo/issues/942), but this isn't supported yet.

**Comment by mattpocock** [comment]
I'd prefer not to add a third concept here - that's more for us to explain. Shared packages = shared code. Apps = leaf nodes. I think that's clear enough and isn't improved by adding a third concept: config.
