### ISSUE TITLE
improve output when using remote caching

### ISSUE THREAD

**Issue by ilovett** [vercel/turborepo#2129]
### Describe the feature you'd like to request

It seems to be hard to determine if remote cache is even being used sometimes.

It might be great to add more explicit information on the output *if remote caching is enabled*

### Describe the solution you'd like

When remote caching is enabled, show the number of jobs which were taken from local vs. remote

```
 Tasks:    3 successful, 3 total
Cached:    3 cached, 2 remote, 1 local, 3 total
  Time:    765ms >>> FULL TURBO
```

I'm not even sure if it's possible to have partial remote & partial local but I assume it would be at some point.

### Describe alternatives you've considered

I used to see `Remote computation` something something experimental.  I'd like to see sort of confirmation that that is enabled and working correctly, and especially if misconfigured, eg: expired token :/

**Comment by mehulkar** [comment]
Yep this was just released in 1.5.5!

**Comment by nathanhammond** [comment]
I'm reopening; I want to capture the local vs. remote distinction from this proposal in the final output summary.

**Comment by chris-olszewski** [comment]
Team decided that we think the current cache status line is the right amount of information.
