### ISSUE TITLE
.turbo-cookie file created in monorepo root

### ISSUE THREAD

**Issue by mehulkar** [vercel/turborepo#2134]
### What version of Turborepo are you using?

1.5.5

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

When upgrading to turbo@1.5.x and running a command a `.turbo-cookie` file appears in the root of the monorepo. First reported in #2034 (not yet clear if it is related to the daemon)

- https://github.com/vercel/turborepo/issues/2034#issuecomment-1260816431
- https://github.com/vercel/turborepo/issues/2034#issuecomment-1263475701

### Expected Behavior

N/A

### To Reproduce

N/A

**Comment by mehulkar** [comment]
@klapec @fveauvy can you tell me what package manager you're using? I tried repro'ing in a simple case https://github.com/mehulkar/turbo-repro-cookie-file and I'm not able to reproduce the issue yet. (Feel free to jump into our Discord if you want to chat a little more synchronously! I'll hang out there for a little while)

**Comment by klapec** [comment]
I can't log into discord right now (it's 8:30pm in here, family stuff :P) but here are the details:
`yarn@1.22.19` `nodejs@16.16.0`

**Comment by fveauvy** [comment]
As I said in #2034 :

My package manager is `yarn@1.22.19` and using `nodejs@16.15.1`.
What's weird is I don't have this issue when I'm using vscode integrated terminal to run turbo commands.

**Comment by gsoltis** [comment]
Currently looking into if this is related to `turbo` being invoked from a global install, rather than local to a repository

**Comment by gsoltis** [comment]
Verified that this is _not_ related to global install, but instead to slow filewatching queues on macos. In the event where we timeout, `turbo` was failing to cleanup the file it was using to check for filewatching capabilities. This should be fixed in the linked PR and will be in an upcoming release.
