### ISSUE TITLE
Provide a CONTRIBUTING.md

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#214]
### Discussed in https://github.com/vercel/turborepo/discussions/213

<div type='discussions-op-text'>

<sup>Originally posted by **mhatvan** December 12, 2021</sup>
So I came across this project a couple of days ago, and I would love to make some code contributions for it ;)
 
As a noob in go, I would need some kind of `CONTRIBUTING.md` or similar onboarding guide to get the project up and running.</div>

**Comment by jaredpalmer** [comment]
<img width="1522" alt="CleanShot 2022-01-26 at 14 01 10@2x" src="https://user-images.githubusercontent.com/4060187/151229323-6805d1b4-203d-4784-b684-5a05e6f015d2.png">
<img width="1522" alt="CleanShot 2022-01-26 at 14 01 19@2x" src="https://user-images.githubusercontent.com/4060187/151229344-b6e25b90-c9fe-493a-bad0-931785b4fbb7.png">
<img width="570" alt="CleanShot 2022-01-26 at 14 01 33@2x" src="https://user-images.githubusercontent.com/4060187/151229353-9ebdeedb-ab95-4be5-9f30-a61c6edb31f8.png">
<img width="482" alt="CleanShot 2022-01-26 at 14 01 45@2x" src="https://user-images.githubusercontent.com/4060187/151229358-2ca6cc9c-b51e-42aa-b4f4-6dfbff622213.png">
<img width="495" alt="CleanShot 2022-01-26 at 14 02 04@2x" src="https://user-images.githubusercontent.com/4060187/151229364-99bca7eb-45c2-439d-a22e-8dc098fed355.png">
<img width="503" alt="CleanShot 2022-01-26 at 14 02 19@2x" src="https://user-images.githubusercontent.com/4060187/151229371-312e55bb-126f-4d71-8c2a-2f00d8e24742.png">
<img width="401" alt="CleanShot 2022-01-26 at 14 02 28@2x" src="https://user-images.githubusercontent.com/4060187/151229378-d601b2ab-3dd6-4780-adbc-1da5750d969f.png">
<img width="1522" alt="CleanShot 2022-01-26 at 14 02 38@2x" src="https://user-images.githubusercontent.com/4060187/151229413-dc7b9638-1466-4765-836c-da18d6696223.png">

**Comment by tknickman** [comment]
We've got a [CONTRIBUTING.md](https://github.com/vercel/turborepo/blob/main/CONTRIBUTING.md) and a [.devcontainer](https://github.com/vercel/turborepo/tree/main/.devcontainer) setup now.
