### ISSUE TITLE
Add repository and homepage link to eslint turbo npm packages

### ISSUE THREAD

**Issue by kriswuollett** [vercel/turborepo#2159]
### Describe the feature you'd like to request

Be able to navigate from the eslint turbo npm package pages, like https://www.npmjs.com/package/eslint-plugin-turbo, to the source code in this repository for ease of use.

### Describe the solution you'd like

Add the package metadata necessary for the links on the npm package pages, like https://www.npmjs.com/package/eslint-plugin-turbo, to show up upon next publish.

### Describe alternatives you've considered

No alternatives considered.

**Comment by tknickman** [comment]
This will be fixed on the next release!
