### ISSUE TITLE
Move config to `turbo.json`

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#217]
### Describe the feature you'd like to request

Move turbo configuration into its own file `turbo.json`

### Describe the solution you'd like

- Move config 
- Add script to codemod
- Release a minor

### Describe alternatives you've considered

- `turbo.yaml`
- Use HCLv2

Continues #183

**Comment by eric-burel** [comment]
Hi, .json fields validation is often uneasy, would it be possible to support a .js as well. Maybe even using comments for type hints (I've seen some libs do that though I can't find any example back)?

**Comment by stepan662** [comment]
I'm all for this feature as package.json gets bloated quite fast.

I also struggle with using npm and lerna with turbo. As turbo requires 'workspaces' field in package.json, but when I put it there my npm install will start installing also dependencies for packages, which I don't want - I want to use `lerna bootstrap` for that.

So for my usecase it would be beneficial to have possibility to define workspaces outside of package.json.

**Comment by aeweda** [comment]
would appreciate this getting implemented 
atm i can't use turborepo due to using a `package.yaml` instead of `package.json` with `pnpm`

**Comment by mrtnbroder** [comment]
> would appreciate this getting implemented atm i can't use turborepo due to using a `package.yaml` instead of `package.json` with `pnpm`

You can safely write json in yaml, since yaml is a superset of json.
