### ISSUE TITLE
Create changelog docs for latest release - Docker build fail after v1.5.6 release

### ISSUE THREAD

**Issue by adarshaacharya** [vercel/turborepo#2198]
### Describe the feature you'd like to request

Due to latest v1.5.6 release of turborepo, docker build is failing but can't figure out what's the exact issue. Since last changelog released was for v1.5.1, please create new one with changes made and breaking changes if there are any.

I've got following error

```sh
RUN yarn global add turbo
 Fetching packages...
Linking dependencies...
 Building fresh packages...
error /usr/local/share/.config/yarn/global/node_modules/turbo: Command failed.
Exit code: 1

```

### Describe the solution you'd like

creating changelog after each release

**Comment by IkeLutra** [comment]
I believe it is a bug in the postinstall script.
Here is a more detailed log from installation: `npm install --no-update-notifier --no-fund --global pnpm turbo`
```
121 verbose pkgid turbo@1.5.6
122 verbose cwd /
123 verbose Linux 5.10.104-linuxkit
124 verbose node v16.17.1
125 verbose npm  v8.15.0
126 error code 1
127 error path /usr/local/lib/node_modules/turbo
128 error command failed
129 error command sh /tmp/postinstall-e52d70af.sh
130 error node:internal/errors:477
130 error     ErrorCaptureStackTrace(err);
130 error     ^
130 error
130 error <ref *1> Error: spawnSync /usr/local/lib/node_modules/turbo/bin/turbo ENOENT
130 error     at Object.spawnSync (node:internal/child_process:1112:20)
130 error     at spawnSync (node:child_process:827:24)
130 error     at Object.execFileSync (node:child_process:870:15)
130 error     at validateBinaryVersion (/usr/local/lib/node_modules/turbo/install.js:25:6)
130 error     at /usr/local/lib/node_modules/turbo/install.js:308:5 {
130 error   errno: -2,
130 error   code: 'ENOENT',
130 error   syscall: 'spawnSync /usr/local/lib/node_modules/turbo/bin/turbo',
130 error   path: '/usr/local/lib/node_modules/turbo/bin/turbo',
130 error   spawnargs: [ '--version' ],
130 error   error: [Circular *1],
130 error   status: null,
130 error   signal: null,
130 error   output: null,
130 error   pid: 26,
130 error   stdout: null,
130 error   stderr: null
130 error }
131 verbose exit 1
132 timing npm Completed in 65188ms
133 verbose unfinished npm timer reify 1665478312917
134 verbose unfinished npm timer reify:build 1665478377779
135 verbose unfinished npm timer build 1665478377780
136 verbose unfinished npm timer build:deps 1665478377780
137 verbose unfinished npm timer build:run:postinstall 1665478377790
138 verbose unfinished npm timer build:run:postinstall:node_modules/turbo 1665478377791
139 verbose code 1
```

My docker image was `node:16-alpine` with no additions

**Comment by prakashharisharma** [comment]
Any workaround ?? Facing same issue.
```
#9 [pruner 1/3] RUN yarn global add turbo
#9 sha256:414f928a3764b82d686b02f50c42204728f93ca324553de85c10f19e17c456d9
#9 0.489 yarn global v1.22.19
#9 0.542 [1/4] Resolving packages...
#9 1.069 [2/4] Fetching packages...
#9 2.326 [3/4] Linking dependencies...
#9 2.368 [4/4] Building fresh packages...
#9 2.523 error /usr/local/share/.config/yarn/global/node_modules/turbo: Command failed.
#9 2.523 Exit code: 1
#9 2.523 Command: node install.js
#9 2.523 Arguments: 
#9 2.523 Directory: /usr/local/share/.config/yarn/global/node_modules/turbo
#9 2.523 Output:
#9 2.523 node:internal/errors:856
#9 2.523   const err = new Error(message);
#9 2.523               ^
#9 2.523 
#9 2.523 Error: Command failed: node /usr/local/share/.config/yarn/global/node_modules/turbo/bin/turbo --version
#9 2.523 /usr/local/share/.config/yarn/global/node_modules/turbo/bin/turbo:13
```

**Comment by Andersos** [comment]
> Any workaround ?? Facing same issue.

If you pin turbo to version 1.5.5 it should work fine:

`RUN yarn global add turbo@1.5.5`

**Comment by gsoltis** [comment]
Apologies, the release notes are generated. I suspect that this is related to the switch to enable `CGO`. I'll take a look at the docker issue, we'll either need to update our build process or docs on dependencies in docker environments.

**Comment by Rykuno** [comment]
I'll hop on this. We're utilizing `turbo@1.5.6` and downgrading the docker build to `turbo@1.5.5` fixed this issue.

**Comment by prakashharisharma** [comment]
> Any workaround ?? Facing same issue.
> 
> ```
> #9 [pruner 1/3] RUN yarn global add turbo
> #9 sha256:414f928a3764b82d686b02f50c42204728f93ca324553de85c10f19e17c456d9
> #9 0.489 yarn global v1.22.19
> #9 0.542 [1/4] Resolving packages...
> #9 1.069 [2/4] Fetching packages...
> #9 2.326 [3/4] Linking dependencies...
> #9 2.368 [4/4] Building fresh packages...
> #9 2.523 error /usr/local/share/.config/yarn/global/node_modules/turbo: Command failed.
> #9 2.523 Exit code: 1
> #9 2.523 Command: node install.js
> #9 2.523 Arguments: 
> #9 2.523 Directory: /usr/local/share/.config/yarn/global/node_modules/turbo
> #9 2.523 Output:
> #9 2.523 node:internal/errors:856
> #9 2.523   const err = new Error(message);
> #9 2.523               ^
> #9 2.523 
> #9 2.523 Error: Command failed: node /usr/local/share/.config/yarn/global/node_modules/turbo/bin/turbo --version
> #9 2.523 /usr/local/share/.config/yarn/global/node_modules/turbo/bin/turbo:13
> ```

Thanks @Rykuno It worked after downgrading to turbo@1.5.5

**Comment by laat** [comment]
> Any workaround ?? Facing same issue.

You can either pin the dependency to 1.5.5:

```Dockerfile
FROM node:alpine
RUN yarn global add turbo@1.5.5
```

or add `libc6-compat`:
```Dockerfile
FROM node:alpine
RUN apk add --no-cache libc6-compat
RUN yarn global add turbo@1.5.6
```

**Comment by gsoltis** [comment]
> add `libc6-compat`

I think this is the correct path forward for `alpine` compatibility. It looks like `alpine` doesn't ship `glibc` by default, instead preferring `musl`. We can look into shipping a `musl` build in the future, but the current build expects `glibc`.

I'll get that added to the docs.

**Comment by yanmao-cc** [comment]
```docker
FROM node:16-alpine AS builder
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app
RUN yarn global add turbo
COPY . .
RUN turbo prune --scope=web --docker

# Add lockfile and package.json's of isolated subworkspace
FROM node:16-alpine AS installer
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/yarn.lock ./yarn.lock
RUN yarn install

# Build the project
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
RUN yarn turbo run build --filter=web...

FROM node:16-alpine AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=installer /app/apps/web/next.config.js .
COPY --from=installer /app/apps/web/package.json .

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static

CMD node apps/web/server.js

```

**Comment by adarshaacharya** [comment]
> Use with libc6-compat and 16-alpine
> 
> ```
> FROM node:16-alpine AS builder
> # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
> RUN apk add --no-cache libc6-compat
> # Set working directory
> WORKDIR /app
> RUN yarn global add turbo
> COPY . .
> RUN turbo prune --scope=web --docker
> 
> # Add lockfile and package.json's of isolated subworkspace
> FROM node:16-alpine AS installer
> # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
> RUN apk add --no-cache libc6-compat
> WORKDIR /app
> 
> # First install the dependencies (as they change less often)
> COPY .gitignore .gitignore
> COPY --from=builder /app/out/json/ .
> COPY --from=builder /app/out/yarn.lock ./yarn.lock
> RUN yarn install
> 
> # Build the project
> COPY --from=builder /app/out/full/ .
> COPY turbo.json turbo.json
> RUN yarn turbo run build --filter=web...
> 
> FROM node:16-alpine AS runner
> WORKDIR /app
> 
> # Don't run production as root
> RUN addgroup --system --gid 1001 nodejs
> RUN adduser --system --uid 1001 nextjs
> USER nextjs
> 
> COPY --from=installer /app/apps/web/next.config.js .
> COPY --from=installer /app/apps/web/package.json .
> 
> # Automatically leverage output traces to reduce image size
> # https://nextjs.org/docs/advanced-features/output-file-tracing
> COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
> COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
> 
> CMD node apps/web/server.js
> ```

@prakashharisharma look like this is the new solution moving forward.

**Comment by michealroberts** [comment]
This was certainly a breaking change imho, which has introduced a different set of architecture dependencies and should have only have been pushed as a turbo version 2.

The libc6-compat fixed as outlined above simply will not work on linux/amd64 architectures.

Scrambling for a fix is not a nice feeling.

**Comment by artemchs** [comment]
> This was certainly a breaking change imho, which has introduced a different set of architecture dependencies and should have only have been pushed as a turbo version 2.
> 
> The libc6-compat fixed as outlined above simply will not work on linux/amd64 architectures.
> 
> Scrambling for a fix is not a nice feeling.

It seems like the problem isn't fixed yet or there isn't right documentation on how to fix it. Even though this issue has been closed for a long time, I still get an error that's described here, so I thought it may be useful to ask y'all for a solution.

Here's my Dockerfile that's used then in my docker-compose.yml:

```dockerfile
# Alpine image
FROM node:22.1.0-alpine AS alpine
RUN apk update

# Setup pnpm and turbo on the alpine base
FROM alpine as base
RUN npm i -g pnpm turbo
RUN pnpm config set store-dir ~/.pnpm-store

# Prune projects
FROM base AS pruner

WORKDIR /app
COPY . .
RUN turbo prune --scope=api --docker

# Build the project
FROM base AS builder

WORKDIR /app

# Copy lockfile and package.json's of isolated subworkspace
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=pruner /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY --from=pruner /app/out/json/ .

# First install the dependencies (as they change less often)
RUN --mount=type=cache,id=pnpm,target=~/.pnpm-store pnpm install --frozen-lockfile

# Copy source code of isolated subworkspace
COPY --from=pruner /app/out/full/ .

RUN turbo build --filter=api
RUN --mount=type=cache,id=pnpm,target=~/.pnpm-store pnpm prune --prod --no-optional
RUN rm -rf ./**/*/src

# Final image
FROM alpine AS runner

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nodejs
USER nodejs

WORKDIR /app
COPY --from=builder --chown=nodejs:nodejs /app .
WORKDIR /app/apps/api

ARG PORT=8080
ENV PORT=${PORT}
ENV NODE_ENV=production

EXPOSE ${PORT}

# CMD node apps/${PROJECT}/dist/main.js
CMD ["sh", "-c", "source .env.production && node apps/${PROJECT}/dist/main.js"]
```

Whenever I run my docker-compose.yml that uses this Dockerfile I get an error that says: "WARNING  No locally installed `turbo` found. Using version: 2.0.6.". I thought I'd find a solution to this problem in this issue, but I didn't. Yet it may be possible that I've made a mistake somewhere else that somehow affects the monorepo configuration, but it seems improbable.

**Comment by ba2sik** [comment]
it happens to me also, turbo 2.1.1

**Comment by AbhyArya20** [comment]
Same issue with me also, turbo 2.2.3

I am struggling to find the solution from last 2days
