### ISSUE TITLE
create-turbo@latest fails

### ISSUE THREAD

**Issue by justusburger** [vercel/turborepo#2206]
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When running `npx create-turbo@latest`, I get the following error:

```
Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: import_fs.default.cpSync is not a function
    at run (/Users/justus.burger/.npm/_npx/21097/lib/node_modules/create-turbo/dist/index.js:338:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

It happens for me reliably. I'm not sure if it's something with my setup, but I doubt it.

### Expected Behavior

I would expect the command to create a new repo.

### To Reproduce

As described above.

![Screenshot 2022-10-12 at 08 59 45](https://user-images.githubusercontent.com/4091173/195272254-81b758fa-31b0-483a-bf57-d976d548b6ab.png)

**Comment by gsoltis** [comment]
Tracking this in #2208 

Currently, `create-turbo` requires node 16, but we should make node 14 work as well.
