### ISSUE TITLE
npx create-turbo@latest not work

### ISSUE THREAD

**Issue by moonlitusun** [vercel/turborepo#2208]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

npx create-turbo@latest

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? test
? Which package manager do you want to use? pnpm

Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: import_fs.default.cpSync is not a function
    at run (/Users/rocsun/.npm-cache/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/index.js:338:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

### Expected Behavior

ok

### To Reproduce

Describe the Bug

**Comment by gsoltis** [comment]
This looks like a node version issue. Currently, `create-turbo` requires Node 16. We should be able to support node 14 though as well.

**Comment by nathanhammond** [comment]
Use node@16. Closing for now, though we will go back and enable v14 support.
