### ISSUE TITLE
Running a pipeline with --parallel causes turbo to run wrong commands

### ISSUE THREAD

**Issue by felskov** [vercel/turborepo#2221]
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

We're experiencing issues with turbo running the wrong commands when adding the `--parallel` flag to run long running scripts.

Specifically, we have two packages, lets call them `utils` and `design-system`. We're using rollup to bundle `utils` and storybook to run a development environment for `design-system` - in other words, they have different implementations of the dev script in package.json.

When we run `npx turbo run dev --parallel --filter=design-system...` what happens is that both packages ends up running the same script. It seems to be undeterministic which script gets run, sometimes both try to run rollup, sometimes both try to run storybook. The weird part is that the scripts are being run in the context of the packages, so we get errors from either storybook/rollup about missing configuration files.

If you create a new folder and paste the following snippets from "To reproduce", then run these commands:

```bash
$ npm install
$ npx turbo run dev --parallel --filter=design-system...
• Packages in scope: design-system, utils
• Running dev in 2 packages
• Remote caching disabled
design-system:dev: cache bypass, force executing 97606a8ac1bf2981
utils:dev: cache bypass, force executing 9febea30acd9845a
utils:dev: 
utils:dev: > utils@1.0.0 dev
utils:dev: > echo 'run from utils'
utils:dev: 
design-system:dev: 
design-system:dev: > design-system@1.0.0 dev
design-system:dev: > echo 'run from design-system'
design-system:dev: 
design-system:dev: run from design-system
utils:dev: run from design-system
```

Note that turbo seems to recognize the correct commands in the initial output, which tells us what's supposed to execute - but in the output below, we get "run from design-system" from both packages.

### Expected Behavior

The correct script should be run in the context of each package. In the example command from above, I would expect distinct output from each package:

```bash
$ npm install
$ npx turbo run dev --parallel --filter=design-system...
• Packages in scope: design-system, utils
• Running dev in 2 packages
• Remote caching disabled
design-system:dev: cache bypass, force executing 97606a8ac1bf2981
utils:dev: cache bypass, force executing 9febea30acd9845a
utils:dev: 
utils:dev: > utils@1.0.0 dev
utils:dev: > echo 'run from utils'
utils:dev: 
design-system:dev: 
design-system:dev: > design-system@1.0.0 dev
design-system:dev: > echo 'run from design-system'
design-system:dev: 
design-system:dev: run from design-system
utils:dev: run from utils
```

### To Reproduce

We've created a tiny setup to reproduce the issue:

**package.json**
```json
{
  "name": "turbo-issue",
  "version": "1.0.0",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "devDependencies": {
    "turbo": "^1.5.6"
  }
}
```

**turbo.json**
```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "dev": {
      "cache": false
    }
  }
}
```

**packages/design-system/package.json**
```json
{
  "name": "design-system",
  "version": "1.0.0",
  "scripts": {
    "dev": "echo 'run from design-system'"
  },
  "dependencies": {
    "utils": "*"
  }
}
```

**packages/utils/package.json**
```json
{
  "name": "utils",
  "version": "1.0.0",
  "scripts": {
    "dev": "echo 'run from utils'"
  }
}
```

**Comment by gsoltis** [comment]
You're asking `turbo` to run `dev` in `design-system` *and all of its dependencies*, which includes `utils`. Furthermore, you're asking `turbo` to run them all in parallel, ignoring dependency relations, so `turbo` starts `dev` in `utils` and `design-system` simultaneously. 

If you want to build `utils` and then run the dev server for `design-system`, `design-system#dev` should depend on `^build`, and you should run `turbo run dev --filter=design-system`

**Comment by felskov** [comment]
@gsoltis Thanks for the fast reply. Yes, you are correct in what I'm asking turbo to do - I do indeed want to run them in parallel, as they'll both be running in watch mode.

The issue here is not that turbo starts them simultaneously - it's that turbo starts the _same script_ simultaneously, in spite of them actually being different for the two packages. As you can see from the output in my case to reproduce, turbo runs `echo 'run from design-system'` for both package, even tho it _should_ run `echo 'run from design-system'` for design-system and ``echo 'run from utils'` for utils :)

**Comment by gsoltis** [comment]
Ah, gotcha. Sorry about that, I'll reopen

**Comment by gsoltis** [comment]
I've modified the basic example from the repo as follows:
```
diff --git a/examples/basic/apps/web/package.json b/examples/basic/apps/web/package.json
index 87ec7d3e..451605ff 100644
--- a/examples/basic/apps/web/package.json
+++ b/examples/basic/apps/web/package.json
@@ -3,7 +3,7 @@
   "version": "1.0.0",
   "private": true,
   "scripts": {
-    "dev": "next dev",
+    "dev": "echo 'in web'",
     "build": "next build",
     "start": "next start",
     "lint": "next lint"
diff --git a/examples/basic/packages/ui/package.json b/examples/basic/packages/ui/package.json
index 7f1ec735..f3769e6b 100644
--- a/examples/basic/packages/ui/package.json
+++ b/examples/basic/packages/ui/package.json
@@ -5,7 +5,8 @@
   "types": "./index.tsx",
   "license": "MIT",
   "scripts": {
-    "lint": "TIMING=1 eslint \"**/*.ts*\""
+    "lint": "TIMING=1 eslint \"**/*.ts*\"",
+    "dev": "echo 'in ui'"
   },
   "devDependencies": {
     "@types/react": "^17.0.37",
```

and then ran `npx turbo run dev --parallel --filter=web...` and unfortunately was not able to reproduce the issue. 

```
• Packages in scope: eslint-config-custom, tsconfig, ui, web
• Running dev in 4 packages
• Remote caching disabled
web:dev: cache bypass, force executing dc995a87d3500796
ui:dev: cache bypass, force executing 99338aa0f6d8d96c
ui:dev:
ui:dev: > ui@0.0.0 dev
ui:dev: > echo 'in ui'
ui:dev:
web:dev:
web:dev: > web@1.0.0 dev
web:dev: > echo 'in web'
web:dev:
ui:dev: in ui
web:dev: in web

 Tasks:    2 successful, 2 total
Cached:    0 cached, 2 total
  Time:    261ms
```


Can you provide a sample repository that demonstrates the issue? It seems like there must be some piece of the puzzle we're missing.

**Comment by felskov** [comment]
@gsoltis Thanks for the follow-up. So upon creating a repo to reproduce the issue, I experienced something odd. I got this error:

```bash
npx turbo run dev --parallel --filter=design-system...                                                        master!

• Packages in scope: design-system, utils
• Running dev in 2 packages
• Remote caching disabled
design-system:dev: cache bypass, force executing 154368f646370c70
utils:dev: cache bypass, force executing 86016ed3465a43b3
utils:dev: 
utils:dev: > utils@1.0.0 dev
utils:dev: > echo 'run from utils'
utils:dev: 
design-system:dev: 
design-system:dev: > design-system@1.0.0 dev
design-system:dev: > echo 'run from design-system'
design-system:dev: 
design-system:dev: run from utils
utils:dev: sh: /var/folders/91/qfq8fm3n655dn18lq0vw1wk00000gn/T/dev66569225869.sh: No such file or directory
utils:dev: npm ERR! Lifecycle script `dev` failed with error: 
utils:dev: npm ERR! Error: command failed 
utils:dev: npm ERR!   in workspace: utils@1.0.0 
utils:dev: npm ERR!   at location: /Users/felskovaps/Code/berlingske/turbo-parallel-issue/packages/utils 
utils:dev: ERROR: command finished with error: command (/Users/felskovaps/Code/berlingske/turbo-parallel-issue/packages/utils) npm run dev exited (1)
command (/Users/felskovaps/Code/berlingske/turbo-parallel-issue/packages/utils) npm run dev exited (1)

 Tasks:    1 successful, 2 total
Cached:    0 cached, 2 total
  Time:    552ms 

 ERROR  run failed: command  exited (1)
```

That got me thinking about what was up with the odd /var/folders references, and then I realized I'm running node with `fnm` and I've had the "--use-on-cd" option enabled. If I disable that setting on fnm this bug no longer occurs, so as it turns out this is an issue with fnm and not turbo.

Sorry to have wasted your time!

**Comment by gsoltis** [comment]
No worries at all, glad you figured it out!
