### ISSUE TITLE
Svelte Kit example cannot import ui from internal package

### ISSUE THREAD

**Issue by yeetsquad747** [vercel/turborepo#2241]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When I use the svelte kit example from turborepo, it breaks since it can't import the local package packages/ui.

### Expected Behavior

It should just work and import the local ui package.

### To Reproduce

1. `npx degit vercel/turborepo/examples/with-svelte with-svelte`
2. `cd with-svelte`
3. `pnpm install`
4. `pnpm run build`

**Comment by tknickman** [comment]
The svelte example won't work with pnpm out of the box. You'll need to add a pnpm workspaces file, and adjust the workspace dependencies.

**Comment by yeetsquad747** [comment]
Alright thank you for the clarification. Makes a lot more sense.
