### ISSUE TITLE
Preserve rich terminal output

### ISSUE THREAD

**Issue by dsilvasc** [vercel/turborepo#2251]
### Describe the feature you'd like to request

Running build tools through turbo leads to plain output: no spinners, colors, and other terminal progress animation/indicators.

Would it be possible to preserve the original output like [nx](https://nx.dev/more-concepts/turbo-and-nx#11.-transparency) does?

![turbo-nx-terminal](https://user-images.githubusercontent.com/24484414/196227186-44094ba5-5ecf-4e2a-a38b-3de20fb5efa5.gif)

### Describe the solution you'd like

Maybe some mechanism to choose which tasks with rich output to foreground (could even start by defaulting to only the last one).

### Describe alternatives you've considered

I've tried running turbo to run tasks up to the one I'm interested in, then ctrl-c and run that task directly, bypassing turbo.  For example, running `yarn test`, waiting for dependencies to execute, then stopping turbo, then running `yarn jest` instead of `test`.  It works, but is cumbersome.

**Comment by mehulkar** [comment]
> no spinners, colors, and other terminal progress animation/indicators.

After #2126, we can probably stream through the output from the underlying output without interfering with it. The example you showed in the gif looks like it's only missing the colors from `info`, `warn`, etc. We could see how it looks without turbo prefixes. Want to take a stab at it?

**Comment by dsilvasc** [comment]
Sounds good.  I tried turbo 1.5.6 which I think includes that commit, but I still see the prefixes and plain output.  Should I try a different version or config?

**Comment by mehulkar** [comment]
> Sounds good. I tried turbo 1.5.6 which I think includes that commit, but I still see the prefixes and plain output.

You'll still see the prefixes in the output, but if you look at the cached logs `packages/your-package/.turbo/*.log`, it should be the plain output. Separating the realtime log output from the cached output was important for the purpose of making sure caches aren't invalidated based on different user options.

The key to preserving the colors from the underlying process is probably somewhere in this code: https://github.com/vercel/turborepo/blob/b852c57fa28b61650762bf01a32da1e7f18bcf6c/cli/internal/logstreamer/logstreamer.go#L133-L159

**Comment by mehulkar** [comment]
Looks like we have this issue open already in #223.

**Comment by nathanhammond** [comment]
We're investigating taking on a project that would vastly improve our UI. Doing something more-clever here is definitely on our roadmap.
