### ISSUE TITLE
Example: supabase, tailwindcss and python

### ISSUE THREAD

**Issue by mr-bjerre** [vercel/turborepo#226]
### Describe the feature you'd like to request

Add a starter repo using [`supabase`](https://supabase.com/), [`tailwindcss`](https://tailwindcss.com/) and python (maybe using [`poetry`](https://python-poetry.org/docs/) for managing dependencies)

### Describe the solution you'd like

Similar to the current [kitchen sink](https://github.com/vercel/turborepo/tree/main/examples/kitchen-sink) example. Preferebly just built on top.

### Describe alternatives you've considered

I realize that turborepo is not built for python applications but it would still be cool to see the best possible solution currently. E.g. what to put in cache etc.

**Comment by jaredpalmer** [comment]
Thanks for making the issue. Right now we are just going to focus on JavaScript and TypeScript. So going to close this for now. 

As you can see from how we use call `go build` in `cli/package.json` internally https://github.com/vercel/turborepo/blob/main/cli/package.json#L7, the same setup is possible in Python. It will be up to you to set things up correctly

**Comment by mr-bjerre** [comment]
Fair. Can we reopen if I omit the python part?
