### ISSUE TITLE
NPM v8 prune fails with package.json unmarshaling error

### ISSUE THREAD

**Issue by weyert** [vercel/turborepo#2270]
### What version of Turborepo are you using?

1.6.0.canary.0

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I am trying to use the `prune` command which since 1.6.0 canary build also supports NPM v8. Only when I am trying the command `turbo prune --scope=demo -vvv` then I am getting the following error shown:

```
❯ turbo prune --scope=demo -vvv         
2022-10-19T03:33:14.981+0100 [ERROR] turbo: error: could not construct graph: 1 error occurred:
        * json: cannot unmarshal array into Go struct field NpmPackage.packages.engines of type map[string]string


 ERROR  could not construct graph: 1 error occurred:
        * json: cannot unmarshal array into Go struct field NpmPackage.packages.engines of type map[string]string
```

I have searched my `package.json` in my repo and the only one that includes a `engines`-property is the one located in the root which has the following value:

```
  "engines": {    "node": ">= 14"  },
```

If I remove this property from the `package.json`-file I am still getting this error. Could it be its reading more `package.json` files? Maybe in the `node_modules`-directories that could be problematic? If so, would it be possible to output the path/location problematic package.json's file?

### Expected Behavior

Would be able to successfully prune the project when using NPM package manager

### To Reproduce

I am working on a repo

**Comment by weyert** [comment]
After a bit of debugging it looks like the problem is my `package-lock.json` file which lists all the dependencies and some of the dependencies have the format `engines: ["node >= 11.0"]` which the `turborepo` doesn't like.

One of the packages I am using has a dependency on `ansi-html-community` which has this problematic line, see: https://github.com/mahdyar/ansi-html-community/blob/master/package.json#L28

**Comment by kevinsimper** [comment]
I get the same error
```
> [builder 7/7] RUN turbo prune --scope=stacker --docker:
#14 0.179  ERROR  could not construct graph: 1 error occurred:
#14 0.179 	* json: cannot unmarshal array into Go struct field NpmPackage.packages.engines of type map[string]string
```

**Comment by nathanhammond** [comment]
@weyert @kevinsimper: new canary is up, let me know if that addresses your issues!

**Comment by weyert** [comment]
@nathanhammond The error is gone with the latest canary build. Thank you :)

**Comment by kevinsimper** [comment]
@nathanhammond Yes, it does not generate any errors now, can test it 👍
