### ISSUE TITLE
Changes to environment variable in env file ignored by git not respected when building Next.js app locally

### ISSUE THREAD

**Issue by ericmatthys** [vercel/turborepo#2275]
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Changes to environment variable values in files ignored by git do not affect the computed hash and will incorrectly result in cache hits.

### Expected Behavior

Regardless of whether an env file is ignored by git, changes to its environment variables should still affect whether there is a cache hit.

### To Reproduce

With a `build` task that builds a Next.js app:

**`.gitignore`**
```
.env*.local
```

**`turbo.json`**
```json
{
  "globalDependencies": [".env.local"],
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "env": ["EXAMPLE"],
      "outputs": [".next/**"]
    }
  }
}
```

**`packages/a/.env.local`**
```
EXAMPLE="1"
```

**Steps to reproduce**
1. Clean `.turbo` directories out
2. `turbo build`
3. Change `EXAMPLE` value to `2`
4. `turbo build` again

Notice the cache hit on the second build. Now remove `.env*.local` from the `.gitignore` file and run through those steps again. Notice the cache miss on the second build.

**Comment by ericmatthys** [comment]
> turbo, having calculated a task hash prior to invoking the build script, will be unable to discover the NEXT_PUBLIC_GA_ID=UA-00000000-0 environment variable and thus unable to partition the cache based upon that, or any environment variable configured by dotenv.

> Be careful to ensure that all of your environment variables are configured prior to invoking turbo!

Reading this in the docs, I'm not sure how environment variables are supposed to work with Next.js apps built locally with Turborepo. Next.js uses `dotenv` in https://github.com/vercel/next.js/blob/canary/packages/next-env/index.ts to load the appropriate env config file. Given this note in the docs though, I also don't understand why the change to `.gitignore` affects its behavior as I'm seeing.

**Comment by ericmatthys** [comment]
I needed to use a glob pattern like `"globalDependencies": ["**/.env.*local"]` 🤦

**Comment by nathanhammond** [comment]
Thank you for coming back and posting your solution. These help people who also do the same thing.

https://xkcd.com/979/
