### ISSUE TITLE
Using `dotenv` breaks `--filter`

### ISSUE THREAD

**Issue by ianstormtaylor** [vercel/turborepo#2277]
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

If you define a task with `dotenv` before it the `--filter` argument is ignored. For example:

```js
scripts: {
  dev: "dotenv turbo run dev --filter=apps/*"
}
```

It will not respect the filter, and run in every workspace instead.

### Expected Behavior

Should respect the filter.

### To Reproduce

See above.

**Comment by ianstormtaylor** [comment]
Tracked this down right after posting, for anyone in the future who's running into this, you need to add `--` after `dotenv` to pass arguments ([docs](https://github.com/entropitor/dotenv-cli#flags-to-the-underlying-command)). So it would instead be:


```ts
scripts: {
  dev: "dotenv -- turbo run dev --filter=apps/*"
}
```

**Comment by nathanhammond** [comment]
@ianstormtaylor Thank you for filing an issue. These little notes are how we help improve the experience for everybody.
