### ISSUE TITLE
Extension/plugin ecosystem on top of Turborepo

### ISSUE THREAD

**Issue by isaacmclellan** [vercel/turborepo#2282]
### Describe the feature you'd like to request

Some sort of plugin/extension system on top of Turborepo, allowing the community to extend Turborepo's core functionality with plugins/extensions.

### Describe the solution you'd like

An API for extending Turborepos core functionality, with a marketplace for the plugins. (kind of like the Vercel extension marketplace)

### Describe alternatives you've considered

I have not considered any alternatives.

**Comment by nathanhammond** [comment]
Yup! This is a _fantastic_ idea. We should _definitely_ do that.

(I'm going to leave this closed for now, we very much do not need to track it here as an issue.)
