### ISSUE TITLE
Document all debug flags

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#229]
### Describe the feature you'd like to request

Document all remaining hidden, internal flags

### Describe the solution you'd like

Add the following to the [CLI Reference docs ](https://github.com/vercel/turborepo/blob/main/docs/pages/docs/reference/command-line-reference.mdx)

- `--trace`
- `--heap`
- `--cpuprofile`
- `-v`, `-vv`, `-vvv`

**References:**

https://github.com/vercel/turborepo/blob/main/cli/cmd/turbo/main.go#L27-L37

https://github.com/vercel/turborepo/blob/main/cli/internal/config/config.go#L126-L137

### Describe alternatives you've considered

On might argue that `--trace`, `--heap`, and `--cpuprofile` should only go in Contributing.md (#214). However, given our commitment to observability, it seems like there shouldn't be any undocumented APIs

**Comment by VarunSAthreya** [comment]
Hey, I would like to work on this issue.

**Comment by weyert** [comment]
@VarunSAthreya are you picking up this issue?

**Comment by VarunSAthreya** [comment]
@weyert  Yes
