### ISSUE TITLE
ERROR  run failed: error preparing engine: the given task has not been registered

### ISSUE THREAD

**Issue by HeavenlyEntity** [vercel/turborepo#2291]
### What version of Turborepo are you using?

1.5.1

### What package manager are you using / does the bug impact?

npm, Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Windows

### Describe the Bug

Hello fellow hackers!

The turbo repo is not allowing my dev server to start using turbo but I am able to start it manually via in the `apps/[appname]` folder. I am trying to run `turbo run dev:table-widget --parallel` which is referring to a CRA that is just `yarn start`. When I run that I get:

```shell
$ yarn run dev:table-widget
yarn run v1.22.10
$ turbo run dev:table-widget --parallel
 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:                                                                                       
        - the process identified by the pid in the file at C:\Users\devvvvin\AppData\Local\Temp\turbod\80bf74a1a94d651f\turbod.pid is not running, and remove C:\Users\devvvvin\AppData\Local\Temp\turbod\80bf74a1a94d651f\turbod.pid
        - check the logs at C:\Users\devvvvin\AppData\Local\turborepo\logs\80bf74a1a94d651f-portalgen-app.log                                                                                                                      
        - the unix domain socket at C:\Users\devvvvin\AppData\Local\Temp\turbod\80bf74a1a94d651f\turbod.sock has been removed                                                                                                      
        You can also run without the daemon process by passing --no-daemon                                                                                                                                                       
 ERROR  run failed: error preparing engine: the given task has not been registered
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Yet when I run it with the `--no-daemon` flag I get:

```shell
$ yarn run dev:table-widget
yarn run v1.22.10
$ turbo run dev:table-widget --parallel --no-daemon
 ERROR  run failed: error preparing engine: the given task has not been registered
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I am running version **1.5.1** of turbo on a windows 10 machine. Inside of a git bash terminal. If someone could let me know what's going on. This started happening after I had to delete the `node_modules` folder to fix issues with an `eslint` package

### Expected Behavior

Look through all `package.json`'s and run scripts with this key. 

### To Reproduce

1. Create new turborepo project
2. Add two apps 1 CRA on nodeJS project (backend simulation)
3. Create scripts to run dev server via turbo and add to turbo.json
4. run yarn install in root
5. Have to delete all node_modules
6. I run `npm exec --workspaces -- npx rimraf node_modules && npx rimraf node_modules`
7. Rerun yarn in root and try to run dev server again. 

My original version of turbo was `1.5.6` but I downgraded to `1.5.1` to see if that would fix the issue and tried reinstalling by running `yarn` and still didn't work.

Additionally, I looked at the `.log` file and it stops watching a directory on this line
`turbod.rpc server.fsnotify: watching directory C:\Users\devvvvvin\Documents\Github\portal\apps\backend\src\cabinet\RootApp\app\scripts\lib\node_modules\hmac-drbg\lib`

I get no detailed fatal error so I am confused. Also I have no `.pid` or `.sock` even generating. 

Thank you! 😁

**Comment by mehulkar** [comment]
```
 ERROR  run failed: error preparing engine: the given task has not been registered
```

Most likely you need to add `dev:table-widget` to `turbo.json`. If it's already there, try without the hyphen, maybe? https://github.com/vercel/turborepo/pull/2267 should improve this error message a little bit.

**Comment by nathanhammond** [comment]
I believe @mehulkar is correct here. I'm going to close this issue, but if this _doesn't_ address your issue please let us know and we'll reopen!

**Comment by HeavenlyEntity** [comment]
The hyphen isn't the problem because I have to build processes one `build-web` and the other `build-ns` and they worked just fine?

**Comment by nathanhammond** [comment]
The daemon issue is a _warning_. It reports a condition but it does not impact success or failure of execution. It was very carefully designed to ensure that holds as an invariant while we are stabilizing it.

**Comment by nathanhammond** [comment]
What I see in your logs from the update appears to be a successful run? Is there anything else to do here?

**Comment by HeavenlyEntity** [comment]
@nathanhammond No other than figuring out the cause of why the Daemon suddenly stopped working after I had to delete `node_modules`
