### ISSUE TITLE
turbo run '--api' option not supported

### ISSUE THREAD

**Issue by mattpocock** [vercel/turborepo#230]
### What version of Turborepo are you using?

1.0.6

### Describe the Bug

The docs describe the `--api` option of the 'run' command, but the CLI errors with 'unknown flag'.

### Expected Behavior

Expected behaviour is unknown, this is poorly documented and I was trying things out trying to make Turborepo run on a GH action.

### To Reproduce

`yarn turbo run build --api="any-value-here"` on any turbo starter.

**Comment by jaredpalmer** [comment]
Confirmed regression.
