### ISSUE TITLE
`turbo` not working in alpine based docker image

### ISSUE THREAD

**Issue by Hacksore** [vercel/turborepo#2310]
### What version of Turborepo are you using?

1.6.1

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

```
 $ docker run --platform=linux/amd64 --entrypoint /bin/sh -it node:alpine
Unable to find image 'node:alpine' locally
alpine: Pulling from library/node
213ec9aee27d: Pull complete
66aac75c18e5: Pull complete
383ec8ade08a: Pull complete
dabca2e7d79d: Pull complete
Digest: sha256:bdd47da7e6d246549db69891f5865d82dfc9961eae897197d85a030f254980b1
Status: Downloaded newer image for node:alpine
/ # npx create-turbo@latest
Need to install the following packages:
  create-turbo@1.6.1
Ok to proceed? (y) y

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? ./my-turborepo
? Which package manager do you want to use? npm

>>> Created a new turborepo with the following:

 - apps/web: Next.js with TypeScript
 - apps/docs: Next.js with TypeScript
 - packages/ui: Shared React component library
 - packages/eslint-config-custom: Shared configuration (ESLint)
 - packages/tsconfig: Shared TypeScript `tsconfig.json`

>   Installing dependencies...
Aborting installation.
  npm install has failed.

/ # cd my-turborepo/
/my-turborepo # npm run build

> my-turborepo@0.0.0 build
> turbo run build

sh: turbo: not found
```

### Expected Behavior

Turbo to be found and work as normal 😅 

### To Reproduce

Run the same steps from the description.

**Comment by rafaeltab** [comment]
Take a look at this comment, and my comment afterward.
https://github.com/vercel/turborepo/issues/2293#issuecomment-1288148253

**Comment by Hacksore** [comment]
Created a sample repo for testing and it is working perfectly now!

@rafaeltab, thanks for the quick response.

**Comment by zigang93** [comment]
nope.. still not working at pnpm..

**Comment by nathanhammond** [comment]
@zigang93 your report doesn't provide us any actionable information. Given that the OP's issue was resolved by the guidance in this thread we _know_ that this was the correct fix for them. If you have other issues please file a new bug.

**Comment by Hacksore** [comment]
@zigang93 I'm not a `pnpm` user but I created a branch on my demo repo you can use to raise a new issue.

Maybe is similar to the original issue here, a missing native dep, but you'll have to investigate more. 

https://github.com/Hacksore/turborepo-alpine-test/tree/pnpm

**Comment by matthewdfleming** [comment]
I see this starting with 1.5.6.. 1.5.5 is good.
