### ISSUE TITLE
Document load time impacts vs other bundlers

### ISSUE THREAD

**Issue by benjamind** [vercel/turborepo#2340]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

Bundling performance is not just about build speed, it's primary function is to improve user experience through optimal loading strategies.

This needs documentation and comparison against other bundling tools.

### Describe the solution you'd like

Load time comparisons, bundle size comparisons and documentation on splitting / loading optimizations. Compared against rollup, esbuild and webpack optimized outputs.

### Describe alternatives you've considered

Not documenting this means users will have to find out for themselves and that is a high cost to entry.

<sub>[PACK-2500](https://linear.app/vercel/issue/PACK-2500/document-load-time-impacts-vs-other-bundlers)</sub>

**Comment by padmaia** [comment]
The main reason it isn't documented is that we don't support production builds yet. We will make that more clear and be sure to document production runtime performance once we do.

**Comment by padmaia** [comment]
We'll post build performance numbers once we have builds finished.
