### ISSUE TITLE
Setting up via create-turbo should have yarn checks

### ISSUE THREAD

**Issue by ShubhamKushwah** [vercel/turborepo#241]
### Describe the feature you'd like to request

Scenario:
Uninstall yarn completely from the system, and run

```
npx create-turbo@latest yourapp
```

It will fail at the second step where it should install the packages via yarn. Because yarn isn't there.

And it gives an unhelpful error:
```
Installing dependencies...
  Aborting installation.
    yarn install has failed.
```

### Describe the solution you'd like

Instead of giving that error, there can be 3 approaches:

1. Tell the user exactly that `yarn` isn't found on their system, so either set up the project using `npm`. Just make it like: `Press Y to setup with npm instead`, or they can quit and restart with `npm`.
2. the Second approach would be to say: `Command yarn not found. Press 1 to install it, or press 2 to set up with npm instead.`
3. Third way would be to simply install `yarn` automatically. Just put a message saying `Installing yarn...`

### Describe alternatives you've considered

The alternative is to understand why `yarn install` would fail, which could be because of many reasons I guess. Then figure out that you don't have `yarn` installed, so install it first, then go back to the Turborepo setup.

**Comment by jaredpalmer** [comment]
Agree

**Comment by m19c** [comment]
I would like to work on it.

**Comment by iDarkLightning** [comment]
I am getting this exact same issue for NPM as well, `npm install has failed` as opposed to `yarn install has failed`.

**Comment by fkapsahili** [comment]
In my case this was the error when I ran `yarn install` after bootstrapping:
`error turborepo-basic-shared@0.0.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.16.2"`

So i had to update Node.js.
