### ISSUE TITLE
Turborepo cant unmarshall yarn lock generated under (crlf) windows  on linux (lf)

### ISSUE THREAD

**Issue by Floffah** [vercel/turborepo#252]
### What version of Turborepo are you using?

1.0.7

### Describe the Bug

context: [this repo](https://github.com/floffah/collaborated)

On my (windows) pc, all turbo commands work fine, but when i deploy it to vercel, i get the following error:
```
Running "turbo run build test lint deploy database"
20:15:34.159 | unmarshal
20:15:34.160 | ERROR  yarn.lock: yaml: line 6: mapping values are not allowed in this context
20:15:34.165 | Error: Command "turbo run build test lint deploy database" exited with 1
```

where line 6 is this
![image](https://user-images.githubusercontent.com/27270386/145882610-b5a8b85e-980e-484a-8d58-a9f3bd1462f2.png)

i assumed this isnt a problem with vercel and something weird going on with the windows to linux differences in yarns lockfile not being reflected in turborepos unmarshalling process

this happens with both v1 and berry lockfiles (slight difference in line number, v2 will fail on the version line under _metadata but follows a similar format to v1, i use v1 here because the docs say v1 is the only supported version and the error is also present there)

### Expected Behavior

Turborepo should unmarshall the yarn lock fine and start building

### To Reproduce

1. create a repo that has the scripts database, build, test, lint, deploy, dev (not sure if all of these are necessary)
2. deploy in production to vercel running all of these (obviously minus dev)
3. wait for yarn to install
4. see the error above

**Comment by jaredpalmer** [comment]
Thanks for the write up. Investigating

**Comment by Yuyz0112** [comment]
Also run into this issue, in my case, change the yarn.lock file from `CRLF` to `LF` fixes the problem.

**Comment by jaredpalmer** [comment]
@Yuyz0112 is the fix here as simple as add `\r` in lockfile parsing?

**Comment by Yuyz0112** [comment]
@jaredpalmer 

Looks like the `CRLF` has a `^M` after each line, so it breaks the first YAML field. I'm using vscode's toolbar to convert `CRLF` to `LF`.

![image](https://user-images.githubusercontent.com/13651389/146235262-2e108423-353b-4ba0-a00d-1b227398b0dd.png)

**Comment by jaredpalmer** [comment]
@Floffah will give it a shot

**Comment by weyert** [comment]
@Floffah I am trying to assist in solve this problem. Do I understand you correctly that the problem is reproducible in your earlier mentioned repo?  https://github.com/floffah/collaborated

**Comment by Floffah** [comment]
> @Floffah I am trying to assist in solve this problem. Do I understand you correctly that the problem is reproducible in your earlier mentioned repo?  https://github.com/floffah/collaborated

Yes, the vercel deployments have failed with it for the past few commits

**Comment by weyert** [comment]
@Floffah I have been able to reproduce it locally, I am getting the following:

```bash
❯ yarn build:simple                                                                                             
yarn run v1.22.17
$ yarn turbo run build --only
$ /Users/weyert/Development/Projects/Opensource/turborepo/repros/collaborated/node_modules/.bin/turbo run build --only
unmarshal
 ERROR  yarn.lock: yaml: line 6: mapping values are not allowed in this context
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Working on a fix now :)

**Comment by weyert** [comment]
Reproducible steps for `turborepo`-repository:

```bash
brew install dos2unix
unix2dos yarn.lock
yarn build
```

**Comment by jaredpalmer** [comment]
What is the suggested workaround here?

**Comment by weyert** [comment]
I was able to get it mostly working by switching to  #13#10 for splitting lines but then I went down a rabbit hole of using Scanner instead.

**Comment by bel7aG** [comment]
`yarn -O install`

**Comment by borislemke** [comment]
Running into the same issue. Our original yarn.lock file is generated by yarn version 3.2.1, but when creating a prune of one of the packages, the resulting lock file is version 1.

Original file:
```
# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8
```

by prune:
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
...
```

yarn fails
```
$ yarn        
Syntax Error: Expected "\n", "\r", or "\r\n" but ":" found.
```

**Comment by nathanhammond** [comment]
Berry (Yarn 3) support is "best effort" at this time. Watch for PRs from @chris-olszewski.

**Comment by TheKnarf** [comment]
This is still a problem, just hit it today and was not able to find a solution. Ended up removing `turbo prune` from my Dockerfile as it didn't work. 

Can this issue be reopened?
