### ISSUE TITLE
[Turbopack] Use `hmr_to_commit` data in HMR benchmark

### ISSUE THREAD

**Issue by yyx990803** [vercel/turborepo#2562]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

When running the `next-dev` benchmarks, I noticed that the `hmr_to_eval` and `hmr_to_commit` metrics are reporting the same numbers for Vite (~101ms)*, while for Turbopack it shows significant difference (~15ms vs ~54ms).

Since the eval-to-commit cost is shown to be significant in the Turbopack case, the `hmr_to_eval` benchmark for Vite seem to be flawed. I am not sure about the exact cause - this could be due to different HMR mechanisms, but there is definitely something wrong: the eval time and commit time should not be the same.

Given this, comparisons / claims based on the `hmr_to_eval` metrics should also be considered flawed. If there is no satisfactory solution to fix `hmr_to_eval` for Vite, then my suggestion is to use `hmr_to_commit` for comparisons instead. It is IMO also the more reasonable metrics to focus on since it better reflects HMR performance perceived by the user.

\* The stats are gathered on M1 mbp with [this PR to use SWC for Vite](https://github.com/vercel/turbo/pull/2561) applied.

### Describe the solution you'd like

- Use `hmr_to_commit` as the metrics for comparing HMR performance, or at least include it alongside `hmr_to_eval` for reference.

- Update [public benchmarks](https://github.com/vercel/turbo/blob/main/docs/pages/pack/docs/benchmarks.mdx) accordingly.

### Describe alternatives you've considered

Identify why `hmr_to_eval` and `hmr_to_commit` are showing identical numbers for Vite.

<sub>[PACK-2501](https://linear.app/vercel/issue/PACK-2501/[turbopack]-use-hmr-to-commit-data-in-hmr-benchmark)</sub>

**Comment by anthonyshew** [comment]
Closing since Turbopack is no longer in this repo.

**Comment by septatrix** [comment]
> Closing since Turbopack is no longer in this repo.

Then please move it to the correct repo to preserve votes, subscribers, and history!
