### ISSUE TITLE
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by samrathchadha** [vercel/turborepo#259]
### What version of Turborepo are you using?

1.0.9

### Describe the Bug

```
../../packages/components/Loading.tsx
Module parse failed: Unexpected token (4:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   // very simple spinner
|   return (
>     <section className="flex h-screen">
|       <img
|         className="m-auto my-auto"
```
This is the error and the code is here: https://github.com/samrathchadha/web/tree/unstable

### Expected Behavior

The code should have run

### To Reproduce

Clone the repository and install the dependencies(with pnpm)

**Comment by jaredpalmer** [comment]
Turbo is running properly. You are likely not transpiling your libraries. Have a look at the  next-transpile-modules package

**Comment by samrathchadha** [comment]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/69572668/145927387-82e3cfd0-6af4-41f9-b673-757df44ad254.png">
That worked but now tailwindcss doesn't work across workspaces. Any suggestions on how to fix this?
