### ISSUE TITLE
Docs: Add examples with github actions

### ISSUE THREAD

**Issue by mr-bjerre** [vercel/turborepo#261]
### Describe the feature you'd like to request

It would be great with examples of github actions that both uses remote caching and without

### Describe the solution you'd like

Maybe the current [kitchen sink](https://github.com/vercel/turborepo/tree/main/examples/kitchen-sink) example could be extended.

### Describe alternatives you've considered

It doesn't need to be in `.github` folder as an actual action but just document how a `yaml` could look like that efficiently uses [`actions/cache@v2`](https://github.com/actions/cache) and turborepo's caching.

This also becomes extra interesting to see with [docker examples](https://github.com/vercel/turborepo/issues/215).

**Comment by julianYaman** [comment]
Are there any updates to this yet?

**Comment by DaniAkash** [comment]
I'm currently following https://github.com/vercel/turborepo/issues/451#issuecomment-1002409285 implementation with the fix mentioned in https://github.com/vercel/turborepo/issues/451#issuecomment-1008089326. If this implementation actually solves caching, we just have to update the kitchen sink example with the action.yml file
