### ISSUE TITLE
Turbo gets stuck on circular dependencies

### ISSUE THREAD

**Issue by jakst** [vercel/turborepo#262]
### What version of Turborepo are you using?

1.0.9

### Describe the Bug

Our monorepo contains a few circular dependencies. We are actively working to remove them, but have some more work to do there.

When running for example `yarn turbo run build` with config `"dependsOn": ["^build"]`, turborepo will just get stuck after printing `• Running lint in 89 packages`. I assume it's going into an endless loop as CPU usage goes up significantly.

### Expected Behavior

It would be nice if turbo threw a warning and exited gracefully on this. Preferably including a description of the dependency circle (can sometimes be several packages long). 

### To Reproduce

* Init a new repo with turbo
* Point two packages at each other in respective package.json
* Make sure `"build": { "dependsOn": ["^build"] }` is set in the pipeline config
* run `yarn turbo run build`

**Comment by jaredpalmer** [comment]
Probably regression from v0.7. On my phone right now, but yes, we should be checking for task graph validity and cycles prior to run. 

We used to do this, but was possibly omitted accidentally during v0.8.5 scheduler refactor. 

Will be a one liner.

**Comment by betaorbust** [comment]
Just confirmed this in my own repo -- a circular dependency results in a hung task with the turbo process taking up 100% cpu 👍

**Comment by Pagebakers** [comment]
Having this issue too, although I don't have any direct circular dependencies in my local packages and I'm not sure how to figure out what the culprit is.

Building individual packages is super fast, within seconds. Running all with concurrency 1 or 10 takes more than 30 minutes with super high cpu load.

**Comment by CryogenicPlanet** [comment]
Any updates on this?

**Comment by gsoltis** [comment]
This should be fixed, we now produce an error for circular dependencies that shows the cycle in question.
