### ISSUE TITLE
Parse lockfile to trigger workspace cache invalidations

### ISSUE THREAD

**Issue by Jakst** [vercel/turborepo#263]
### Describe the feature you'd like to request

Some times the top level lockfile changes without a corresponding change in a package.json. One such example is when you run `yarn-deduplicate` (or `yarn dedupe` in v2/v3).

This should ultimately trigger cache invalidations for the workspaces that have had their dependencies changed in the lockfile. This is not the case currently, which can lead to the package upgrades not being deployed until later changes come in. If any dependency upgrade caused a bug this would be really hard to debug since it would be deployed with a different set of changes.

### Describe the solution you'd like

Changes in for example yarn.lock should be parsed to determine which workspace packages to invalidate cache for.

### Describe alternatives you've considered

Forcing complete cache eviction on every change to yarn.lock

**Comment by jaredpalmer** [comment]
Yep! It already works this way for yarn.lock (on non-windows machines #145)

**Comment by Jakst** [comment]
Ok, doing some more testing I see that it actually works with yarn v1. 

However, we're using yarn v3. I know that it's not explicitly supported, but it seems to work well for other tasks. Since the yarn v2/v3 lockfile format is pure yaml, it should make adding support for it fairly straight forward.

Could we reopen this issue with the narrowed goal of supporting yarn v2/v3? @jaredpalmer

**Comment by Jakst** [comment]
Here's a repo with reproduction: https://github.com/Jakst/turbo-yarn-v3-repro


To reproduce:

- Checkout the main branch and run `yarn`
- Run `yarn turbo run build`
- Checkout the `modified-lockfile` branch and run `yarn`
- Run `yarn turbo run build`
- Observe that the turbo build caches were not busted by the changes in the lockfile

**Comment by Jakst** [comment]
I'll re-post this as a separate issue
