### ISSUE TITLE
Yarn v2 support

### ISSUE THREAD

**Issue by vincent-lecrubier-skydio** [vercel/turborepo#264]
### Describe the feature you'd like to request

Support for Yarn v2, at least in `node_modules` linker mode.

### Describe the solution you'd like

Support yarn v2 like yarn v2 is supported

### Describe alternatives you've considered

Switching to other package manager, but this can be costly, and Yarn v2 is actually the best in my opinion

**Comment by jaredpalmer** [comment]
Duplicate of #237
