### ISSUE TITLE
Add support for scoped packages

### ISSUE THREAD

**Issue by selbekk** [vercel/turborepo#266]
### Describe the feature you'd like to request

I would like to release my packages under an [npm scope](https://docs.npmjs.com/cli/v8/using-npm/scope)  - like `@myorg/react` and `@myorg/lint-rules`. 

Right now, I can't figure out a way to do that with TurboRepo, because it can't resolve repos whenever I add a scope to the front of a package name.

I'm not sure if this is a feature or a bug request - kind of both, because I feel like this should be a pretty common use case for Turborepo users.

### Describe the solution you'd like

I would like to specify the name of the package in its `package.json` - like `@myorg/react` - and that should make it available under that name in other parts of the monorepo.

I would prefer if the name of the package didn't have to be parroted to the folder name - so that my file structure would continue to be `packages/react` :) 

### Describe alternatives you've considered

I can't think of any other alternatives, other than not scoping our packages (not an option for us).

**Comment by jaredpalmer** [comment]
Hey sorry for confusion, but this already works this way. See `--scope` flag in the documentation. 

Make sure you're correctly specifying the flag value with equal sign me quote, no space in between. 

https://turborepo.org/docs/reference/command-line-reference#option-syntax

https://turborepo.org/docs/reference/command-line-reference#--scope

**Comment by selbekk** [comment]
It works! 🙌🏻 Thanks :) 

This might have been documented in a more straight forward way, or just work out of the box though – as future improvement points or whatever. 

Thank you for the quick support!

**Comment by fivethreeo** [comment]
I think the issue is with npm and not turbo. https://github.com/npm/cli/issues/3637 - Not sure if related to his issue, but could be.

**Comment by thien-do** [comment]
Agree with @selbekk that my first impression is it would be nice if just work out of the box. Not sure if there is any downside yet
