### ISSUE TITLE
Turborepo CLI is using artifacts v8 instead of v1 

### ISSUE THREAD

**Issue by gaspar09** [vercel/turborepo#278]
### What version of Turborepo are you using?

1.0.9

### Describe the Bug

Turborepo CLI is using artifacts v8 instead of v1 

https://github.com/vercel/turborepo/commit/49b94f7e60a2b2436d6321a1b500f084a8159b60

### Expected Behavior

Expected to use v1

### To Reproduce

Use turborepo CLI with remote caching on

**Comment by jaredpalmer** [comment]
Oof.
