### ISSUE TITLE
Support Node.js 12 in `create-turbo`

### ISSUE THREAD

**Issue by tbranyen** [vercel/turborepo#279]
### What version of Turborepo are you using?

@latest

### Describe the Bug

I use nvm to keep my Node version fixed to v12. When I do this and run `npx create-turbo@latest` I see the following:

![image](https://user-images.githubusercontent.com/181635/146088616-ef3a7858-a266-4dfc-b185-c1fedb7ee8a4.png)

When I unload nvm to get my system Node version and re-run create-turbo, I see the following:

![image](https://user-images.githubusercontent.com/181635/146088747-daaaea33-3e2e-40ad-8f44-7d6d65c75fdc.png)

### Expected Behavior

I expect that Turborepo can use yarn with Node v12 to install dependencies without aborting. In the case of using the Node version 16.11.1, I expect that Turborepo can find yarn.

### To Reproduce

Use Arch Linux or some other Linux distribution that has yarn and Node as system-level packages potentially? I'm also using yarn v1, should I be on v2?

**Comment by jaredpalmer** [comment]
I think that `create-turbo` requires Node.js 14+ which is LTS. 

Node.js 12 is EOL

**Comment by jaredpalmer** [comment]
If you clone one of the examples (with a tool like [degit](https://github.com/Rich-Harris/degit)), you should be able to use Node.js 12. (`turbo` itself is written in Go, so this is just about the `create-turbo` package)

**Comment by tbranyen** [comment]
The second part of the issue shows a problem with Node 16. I have yarn 1 installed at my system level and works fine with both versions of Node. When I run `which yarn` I get `/usr/bin/yarn` which seems pretty standard. Do I need yarn 2?

**Comment by tbranyen** [comment]
> If you clone one of the examples (with a tool like [degit](https://github.com/Rich-Harris/degit)), you should be able to use Node.js 12. (`turbo` itself is written in Go, so this is just about the `create-turbo` package)

This makes complete sense, the tool is in Go, so if I wanted to incorporate into an existing monorepo, it should just-work. I was just hung up on the scaffolder. Thank you!
