### ISSUE TITLE
Add examples for react applications

### ISSUE THREAD

**Issue by nopresnik** [vercel/turborepo#281]
### Describe the feature you'd like to request

All of the current demos almost exclusively use NextJS.  It would be a great to see at least one demo built using React.

### Describe the solution you'd like

A demo that can be found in the demos folder containing a monorepo of two React applications utilising common components.

### Describe alternatives you've considered

n/a

**Comment by nopresnik** [comment]
Love this project by the way.  Great job @jaredpalmer  and @vercel!

**Comment by jaredpalmer** [comment]
Thanks! 

Next.js uses React. The [kitchen-sink](https://github.com/vercel/turborepo/tree/main/examples/kitchen-sink) example also includes a [Vite x React app ](https://github.com/vercel/turborepo/tree/main/examples/kitchen-sink/apps/admin) and a [Remix x React app](https://github.com/vercel/turborepo/tree/main/examples/kitchen-sink/apps/blog)
