### ISSUE TITLE
It says yarn is not installed when it's installed

### ISSUE THREAD

**Issue by alexismellamo** [vercel/turborepo#285]
### What version of Turborepo are you using?

1.0.10

### Describe the Bug

It says yarn is not installed but it is installed

![Screen Shot 2021-12-15 at 1 06 18](https://user-images.githubusercontent.com/11366687/146139852-d9f46b55-1673-4b55-a6a3-aeee87af9596.png)

### Expected Behavior

I can use yarn

### To Reproduce

run `npx create-turbo@latest`

**Comment by MariuzM** [comment]
same for me

**Comment by john-afolabi** [comment]
I also face the same issue using Windows

**Comment by CapsAdmin** [comment]
I also have the same problem on Linux (kde neon, based on ubuntu 20.04)

**Comment by AyoubBenAl1** [comment]
i think I found the problem still investigating

**Comment by CapsAdmin** [comment]
I cannot reproduce the problem with the following localy, so maybe npm_config_user_agent is set to something strange when running create-turbo from npx.

```js
const inquirer = require("inquirer");
const { execSync } = require("child_process");

function shouldUseYarn() {
  try {
    const userAgent = process.env.npm_config_user_agent;
    if (userAgent) {
      return Boolean(userAgent && userAgent.startsWith("yarn"));
    }
    execSync("yarnpkg --version", { stdio: "ignore" });
    return true;
  } catch (e) {
    return false;
  }
}

const isYarnInstalled = shouldUseYarn();

async function main() {
  let answers = await inquirer.prompt([
    {
      name: "packageManager",
      type: "list",
      message: "Which package manager do you want to use?",
      choices: [
        {
          name: "Yarn",
          value: "yarn",
          disabled: !isYarnInstalled && "not installed",
        },
        { name: "NPM", value: "npm" },
        // { name: "PNPM", value: "pnpm" },
      ],
    },
    {
      name: "install",
      type: "confirm",
      message: function (answers) {
        return `Do you want me to run \`${answers.packageManager} install\`?`;
      },
      default: true,
    },
  ]);
}

main();
```

**Comment by AyoubBenAl1** [comment]
the issue was here
`if (userAgent) {
      return Boolean(userAgent && userAgent.startsWith("yarn"));
    }`
    
if you used npm this will always return false and the function won't continue to the next line that checks if yarn is installed
