### ISSUE TITLE
Build Skipping

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#303]
### Describe the feature you'd like to request

`turbo` currently always hardlinks/moves the artifact from the cache into position. This is wasteful. It should be able to skip recent work, not just recycle it.

### Describe the solution you'd like

The naive approach is to leave some kind of `lastHash` value in a json file in the `.turbo` directory (either in rootor in the package itself)  right after calling / part of `turboCache.Fetch()`. 

On the next run, if that `lastHash` matches the calculated hash of the current package task, turbo would assume that the artifact is already present and no-op (don't move any files).

**Problems**
- This assumes that cache objects are immutable (which they are not)
  - Although this might be fixable with looking at modifications times?
- If the output directory is altered (mutated), turbo will no-op with an invalid state

---
**Rush** 
Rush does effectively what is described above here, but merely writes key:value file-to-hash and checks for shallow equals:
https://github.com/microsoft/rushstack/blob/7d8ff23ab4b500123434e7b5a0ca0400278aece1/apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts#L291-L302

### Describe alternatives you've considered

- Hashing outputs?

**Comment by gsoltis** [comment]
This is getting rolled up into the daemon / file-watching work.
