### ISSUE TITLE
Use algolia docs search on docs site

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#304]
### Describe the feature you'd like to request

Nextra's default search isn't very good and people are only able to sort by title. We should implement Algolia Docsearch 

### Describe the solution you'd like

- I've already submitted an application to the doc search program, so hopefully we get out index and key soon
- Update current search component to use algolia's doc search library. It should be a button that looks like an input for a11y that launches the algolia search popup
https://github.com/vercel/turborepo/blob/8d22a39e19f22136d64920e02fec7c2d51dc248c/docs/nextra-theme-docs/search.js#L1 
-  The implementation can be lifted out of Formik's docs here: 
https://github.com/jaredpalmer/formik/blob/master/website/src/components/Search.tsx#L38-L91  
- Additional work is needed to index the documentation properly

**Comment by meehawk** [comment]
@jaredpalmer first time contributor here. Can I take this up?
