### ISSUE TITLE
Kitchen sink dev not working

### ISSUE THREAD

**Issue by mr-bjerre** [vercel/turborepo#306]
### What version of Turborepo are you using?

1.0.12

### Describe the Bug

I've noticed a few errors in the examples provided. This one is regarding kitchen sink where `yarn dev` fails for the `api` service. I.e. `nodemon` is not installed in `api`.

### Expected Behavior

I'd expect all examples to run without errors. Maybe we should add some testing on all the examples - not sure how to test all the `dev/watch` jobs though

### To Reproduce

Run `yarn dev` in kitchen sink

**Comment by jaredpalmer** [comment]
Ahh yeah. Can you add nodemon to deps in a PR?

**Comment by mr-bjerre** [comment]
Sure - will do tomorrow (DK time here).

Should I add an issue for adding tests on examples as well?

**Comment by mr-bjerre** [comment]
Fixed in PR #316
