### ISSUE TITLE
Turbo CLI prune method panics when scope not found

### ISSUE THREAD

**Issue by bernessco** [vercel/turborepo#330]
### What version of Turborepo are you using?

1.0.15

### Describe the Bug

turbo prune doesn't work

### Expected Behavior

to create pruned output

### To Reproduce

yarn turbo prune --scope=admin-api --docker
yarn run v1.22.15
$ /Users/mantas/Projects/sandbox/monorepo/node_modules/.bin/turbo prune --scope=admin-api --docker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13c8764]

goroutine 1 [running]:
turbo/internal/prune.(*PruneCommand).Run(0xc0000977c0, {0xc0000b0060, 0x2, 0x2})
        /Users/jared/dev/vercel/turbo/cli/internal/prune/prune.go:108 +0x3c4
github.com/mitchellh/cli.(*CLI).Run(0xc0000eb7c0)
        /Users/jared/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.main.func9({0x0, 0x14cd35e}, {0xc0000b0050, 0x100cf01, 0x3}, {0x0, 0x180d568}, {0x0, 0x0}, 0xc0000eb7c0, ...)
        /Users/jared/dev/vercel/turbo/cli/cmd/turbo/main.go:161 +0x385
main.main()
        /Users/jared/dev/vercel/turbo/cli/cmd/turbo/main.go:166 +0xb3b
error Command failed with exit code 2.

**Comment by bernessco** [comment]
@jaredpalmer Do you need more information about env or usage?

**Comment by vavra7** [comment]
I am experiencing exactly the same issue. In example project command works just fine but in my project the command always crash.

```
$ /home/vavra/Projects/ww/node_modules/.bin/turbo prune --scope=product
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7cc124]

goroutine 1 [running]:
turbo/internal/prune.(*PruneCommand).Run(0xc0000a76f0, {0xc0000a8170, 0x1, 0x1})
        /Users/jared/dev/vercel/turbo/cli/internal/prune/prune.go:108 +0x3c4
github.com/mitchellh/cli.(*CLI).Run(0xc0000f37c0)
        /Users/jared/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.main.func9({0x0, 0x8cf3b5}, {0xc0000a8160, 0x40d201, 0x2}, {0x0, 0xc0c168}, {0x0, 0x0}, 0xc0000f37c0, ...)
        /Users/jared/dev/vercel/turbo/cli/cmd/turbo/main.go:161 +0x385
main.main()
        /Users/jared/dev/vercel/turbo/cli/cmd/turbo/main.go:166 +0xb3b
```

turbo v1.0.19

**Comment by bernessco** [comment]
@vavra7 I found out my mistake, when providing scope it has to be the exact package name that is set in the package.json. turbo v1.0.19

@jaredpalmer I could close this issue, but it could be better to throw a human-readable error, that package was not found or something like that

**Comment by jaredpalmer** [comment]
Will change title

**Comment by vavra7** [comment]
@bernessco ou there is the problem! I provided folder name which is `${appName}` as scope but in package.json the name of the app is `@${projectName}/{appName}`. Thank you.

**Comment by gsoltis** [comment]
This now gives a proper error message
