### ISSUE TITLE
Trying to serialize non-JSON files

### ISSUE THREAD

**Issue by phelipetls** [vercel/turborepo#333]
### What version of Turborepo are you using?

1.0.15

### Describe the Bug

After running any task, the program fails because it tries to parse the file as JSON.

```
$ npx turbo@1.0.15 run validate
 ERROR  error parsing .eslintignore: invalid character '/' looking for beginning of value
```

Sometimes the file is `.eslintignore`, `.editorconfig`, something inside `.git`, or even a `README.md` file.

It does not happen in version 1.0.14, so I'm assuming it was introduced in 1.0.15.

```
$ npx turbo@1.0.14 run validate
• Running validate in 0 packages

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    11ms >>> FULL TURBO

```

### Expected Behavior

It shouldn't be trying to serialize these files as if they were in JSON format.

### To Reproduce

I was able to reproduce the error by removing the `workspaces` field from the `package.json` in the [basic example](https://github.com/vercel/turborepo/tree/main/examples/basic) and then running `npx turbo@1.0.15 lint`.

```
$ npx turbo run lint
 ERROR  error parsing README.md: invalid character '#' looking for beginning of value
```

**Comment by jaredpalmer** [comment]
This should be solved in 1.0.19+

**Comment by KarolNov** [comment]
Running into this again at version 1.0.24. I tried spiking how we could benefit from turbo for tasks/caching while keep using Lerna, but turbo tries to parse .md files on any task.

**Comment by jaredpalmer** [comment]
turbo requires workspaces at the moment, so this isn’t technically bug. Turbo is doing exactly what it is supposed to do here, although the error message could indeed be better.

**Comment by KarolNov** [comment]
Cool, I never developed anything in Go, but this seems simple enough, so maybe I'll contribute that change. Thanks for the great work on making monorepos fast!
