### ISSUE TITLE
`console.error` not printing when running `turbo run dev --parallel`

### ISSUE THREAD

**Issue by baptisteArno** [vercel/turborepo#337]
### What version of Turborepo are you using?

1.0.13

### Describe the Bug

When running Next.js apps using `turbo run dev --parallel`, the output of the errors that emanate from the server-side (for example when calling an API route) is not printed into the console.

### Expected Behavior

It should print out `console.error`

### To Reproduce

- Clone the basic Turbo repo example
- Create an API route that throws an error
- Run `turbo run dev --parallel`
- Trigger the error
- No error log is shown in console

**Comment by jaredpalmer** [comment]
Should be fixed in latest canary
