### ISSUE TITLE
Turborepo with React 18 crashes bad

### ISSUE THREAD

**Issue by selbekk** [vercel/turborepo#338]
### What version of Turborepo are you using?

1.0.16

### Describe the Bug

I ran `npx create-turbo`, chose NPM as my package manager, and then ran the following:

```
cd apps/docs && npm i react@rc react-dom@rc next@latest
cd ../web && npm i react@rc react-dom@rc next@latest
```

Then I ran `npm run dev`, and opened both `localhost:3000` and `localhost:3001`.

Both failed client side, but in different ways.

For `localhost:3000`, the console says:

```
TypeError: _server.default.renderToReadableStream is not a function
```

For `localhost:3001`, the console says:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

I noticed that when I log out `React.version`, it says 18.0.0-rc.0-……… on the server side, and when I breakpoint through the client, I find that react and react-dom is version 17. I also notice that the top level node_modules has react@17 in it, while the apps/[web|docs]/node_modules folders have version 18 in them.

Then, if I go into each of the apps folders and run `npm install`, I get the same error both places:

```
../../packages/ui/Button.tsx
Module parse failed: Unexpected token (2:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export const Button = () => {
>   return <button>Boop</button>;
| };
|
```

There's something weirdly wrong here.

### Expected Behavior

I would expect entering my apps/* folders, and run `npm install react@rc react-dom@rc next@latest` would… just work.

### To Reproduce

Follow the repro steps above, or clone down this repository: 

https://github.com/selbekk/turbo-test-react-18

**Comment by jaredpalmer** [comment]
This is likely a bug with next-transpile-modules and not turbo itself. Will confirm when I get to the office

**Comment by jaredpalmer** [comment]
Confirmed. Can you post an issue in that repo? I will also bring it up with Next.js team. Sorry about that! For now, you can build your ui library with a tool like tsup https://tsup.egoist.sh/

**Comment by selbekk** [comment]
Yeah, here's the issue I guess :) https://github.com/martpie/next-transpile-modules#i-have-trouble-with-duplicated-dependencies-or-the-invalid-hook-call-error-in-react

If this is the case, I'll just start watch tasks in all packages, and import the compiled builds

**Comment by 7iomka** [comment]
> https://github.com/martpie/next-transpile-modules#i-have-trouble-with-duplicated-dependencies-or-the-invalid-hook-call-error-in-react

Any example how you plan to watch compiled builds please?
