### ISSUE TITLE
Error when building the Remix blog example in Kitchensink

### ISSUE THREAD

**Issue by jon301** [vercel/turborepo#344]
### What version of Turborepo are you using?

1.0.17

### Describe the Bug

The Remix blog example in Kitchensink does not build:

![image](https://user-images.githubusercontent.com/122108/146578508-8e7e6ce0-d26c-4904-bad6-f143f24ad9dc.png)

### Expected Behavior

It should build without errors.

### To Reproduce

- Clone `https://github.com/vercel/turborepo`
- Install deps (yarn/npm install)
- Go to `examples/kitchen-sink/apps/blog`
- `yarn build`

**Comment by jaredpalmer** [comment]
Should be fixed now
