### ISSUE TITLE
Support more flexible package stage build

### ISSUE THREAD

**Issue by fz6m** [vercel/turborepo#348]
### Describe the feature you'd like to request

Suppose I have dependency chain like this:

```bash
  A lib -> B lib -> C app
```

At this point I wanted to build only to B stage (need A B) , and not build C app. 
I tried to execute:

```bash
  turbo run build --scope="B" --include-dependencies
```

But all packages(A B C) `build` command was executed.

A B is like a global dependency for the project.
When I have a particularly large number of subprojects, it is complicated to start them at project root path, while it is easy to execute the start command in one of the subproject dir path (because they don't need to add scripts)

```js
  "scripts": {
    "dev:app1": "turbo run dev --scope=\"app1\"",
    "dev:app2": "turbo run dev --scope=\"app2\"",
    "dev:app3": "turbo run dev --scope=\"app3\"",
    "dev:app4": "turbo run dev --scope=\"app4\"",
    "dev:app5": "turbo run dev --scope=\"app5\"",
    // ...... This may have increased the cost
  },
```

### Describe the solution you'd like

For example, adding the `break` option discards all dependency chains after B

```bash
  turbo run build --scope="B" --include-dependencies --break
```

This equates to

  A lib -> B lib  ~~-> C app~~

```bash
  turbo run build --scope="B" --break
```

This equates to

B lib  ~~-> C app~~

This behaves as if switch would exit at `break`.

### Describe alternatives you've considered

My current solution is to set up two different build scripts:

```js
  // C app
  "scripts": {
    "build:app": "..."
  },
```

```js
  // A / B lib
  "scripts": {
    "build": "..."
  },
```

In this way, executing the `build` will get the expected result:

```bash
  turbo run build --scope="B" --include-dependencies
  # or
  turbo run build --scope="A"
```

Finally, only A B is involved in the build

**Comment by jaredpalmer** [comment]
Thanks for the writeup! There's already an RFC for new filtering syntax that's more expressive #105 . Let's move discussion there?
