### ISSUE TITLE
Add commitlint for project

### ISSUE THREAD

**Issue by initdc** [vercel/turborepo#353]
### Describe the feature you'd like to request

Style the commit msg

### Describe the solution you'd like

```
yarn add -D husky @commitlint/{config-conventional,cli}

yarn husky add .husky/commit-msg 'yarn commitlint --edit $1'
```
check

https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional

### Describe alternatives you've considered

pre-commit hook

**Comment by jaredpalmer** [comment]
Hey! I think this is a bit too opinionated so let's add it to https://turborepo.org/docs/guides/complimentary-tools. Can you make a PR? Going to close this in the interim.

Side note: husky is quite large library and there are slimmer alternatives FWIW.
