### ISSUE TITLE
Error importing UI button package component to react app 

### ISSUE THREAD

**Issue by Emyboy** [vercel/turborepo#360]
### What version of Turborepo are you using?

@latest

### Describe the Bug

After creating a new project, I replaced the next.js app and created a create-react-app project. I added the UI as a dependency using a wildcard Ex "UI": "*"

once the project refreshed I got this error 👇🏽

![image](https://user-images.githubusercontent.com/34845973/146659826-cd9ec342-e44a-459e-9ce7-d95b47e2af06.png)

### Expected Behavior

I expected it to display the button from the UI package

### To Reproduce

Delete the next.js app that comes with generating a new project and generate a new create-react-app project (with typescript) `npx create-react-app my-app --template typescript`

Then import the button from the UI package into App.js

**Comment by souzaramon** [comment]
Same here, aparently cra is not suported out of the box

**Comment by thien-do** [comment]
Turbo is working as expected. If you want to use a package, you either need to:
- Ensure the code can be consumed directly (either write it in plain JS, or transform/transpile/compile it ourselves)
- Or ask the app to transpile the package

This is why in the base setup there is next-transpile-something :D

**Comment by darrenbarklie** [comment]
For anyone else finding this thread first, [Jared's guidance here](https://github.com/vercel/turborepo/issues/449#issuecomment-1002661402) put me on the right track for usage with CRA/Remix.

Specifically:

1. Install `npm i tsup -D` to UI project ([docs](https://github.com/egoist/tsup))
2. In UI's `package.json` configure `build` and `dev` scripts to compile output (to **/dist** directory):
```js
    "build": "tsup src/index.tsx --format esm,cjs --dts --external react",
    "dev": "tsup src/index.tsx --format esm,cjs --watch --dts --external react",
```
3. Also in UI's `package.json`, update source file locations to match this **/dist** location:
```js
    "main": "./dist/index.js",
    "module": "./dist/index.mjs",
    "types": "./dist/index.d.ts",
```
4. In your CRA/Remix's `package.json`, ensure you are importing the `ui` library:
```js
    "dependencies": {
        ...
        "ui": "*"
    },
```
5. Import and use components as usual:
```jsx
import { Button } from "ui";

const Home: FC = (props) => {
  return (
    <div>
      <Button />
    </div>
  );
};

```
6. Updates to UI components will automatically update and refresh the CRA, whereas a change to the Remix codebase is necessary to recompile and display modifications.

**Comment by goldo** [comment]
is there any way to auto recompile remix following packages/ui changes ? I find it unusable for day to day development to have to restart the whole app juste for a UI component change.

**Comment by Aliemeka** [comment]
> Turbo is working as expected. If you want to use a package, you either need to:
> 
> * Ensure the code can be consumed directly (either write it in plain JS, or transform/transpile/compile it ourselves)
> * Or ask the app to transpile the package
> 
> This is why in the base setup there is next-transpile-something :D

How do I do this. My UI components can be import but the tailwind styles are not

**Comment by souzaramon** [comment]
> How do I do this. My UI components can be import but the tailwind styles are not

@Aliemeka Just use vite and your life will be so much easier

**Comment by hayder-uruit** [comment]
it works but I'm not able to import style.css for storybook

**Comment by feelchi1star** [comment]
> For anyone else finding this thread first, [Jared's guidance here](https://github.com/vercel/turborepo/issues/449#issuecomment-1002661402) put me on the right track for usage with CRA/Remix.
> 
> Specifically:
> 
>     1. Install `npm i tsup -D` to UI project ([docs](https://github.com/egoist/tsup))
> 
>     2. In UI's `package.json` configure `build` and `dev` scripts to compile output (to **/dist** directory):
> 
> 
> ```js
>     "build": "tsup src/index.tsx --format esm,cjs --dts --external react",
>     "dev": "tsup src/index.tsx --format esm,cjs --watch --dts --external react",
> ```
> 
>     3. Also in UI's `package.json`, update source file locations to match this **/dist** location:
> 
> 
> ```js
>     "main": "./dist/index.js",
>     "module": "./dist/index.mjs",
>     "types": "./dist/index.d.ts",
> ```
> 
>     4. In your CRA/Remix's `package.json`, ensure you are importing the `ui` library:
> 
> 
> ```js
>     "dependencies": {
>         ...
>         "ui": "*"
>     },
> ```
> 
>     5. Import and use components as usual:
> 
> 
> ```js
> import { Button } from "ui";
> 
> const Home: FC = (props) => {
>   return (
>     <div>
>       <Button />
>     </div>
>   );
> };
> ```
> 
>     6. Updates to UI components will automatically update and refresh the CRA, whereas a change to the Remix codebase is necessary to recompile and display modifications.

I Already have the setup, how can i enable a change in props from web to make effect in the Ui package 
```
// web/signup.tsx

  <FormGroup className="gap-3" display={"flex"} col={1} gap={8}>
            <Input require inputType="email" label="Email" name="email"></Input>
            <Input
              require
              inputType="text"
              label="Password"
              name="password"
            ></Input>
          </FormGroup> 
```
       
 ```
      // ui/formGroup.tsx
       
       import React, { useState } from "react";
export function FormGroup({
  className,
  col = 1,
  gap = 4,
  display = "grid",
  children,
}: {
  className?: string;
  gap?: number;
  col?: number;
  display?: "grid" | "flex";
  children: React.ReactNode;
}): JSX.Element {
  if (display === "flex") {
    <div className={`ui-flex ${className}`}>{children}</div>;
  }

  return (
    <div className={`ui-grid ui-grid-cols-${col} ui-gap-${gap}`}>
      {children}
    </div>
  );
}
```

Note am using tailwindcss.

@darrenbarklie 
@thien-do 
@leerob

**Comment by Aliemeka** [comment]
> > How do I do this. My UI components can be import but the tailwind styles are not
> 
> @Aliemeka Just use vite and your life will be so much easier

Vite is incompatible with some packages I'm using. I actually found the fix.
