### ISSUE TITLE
Add moduleResolution Node as default

### ISSUE THREAD

**Issue by thien-do** [vercel/turborepo#361]
### Describe the feature you'd like to request

Having `moduleResolution` in base tsconfig or react-library tsconfig

### Describe the solution you'd like

I want to use 3rd-party dependencies (i.e. node_modules) under my packages (e.g. packages/ui) out of the box

### Describe alternatives you've considered

The current situation works ok enough, as there is a clear message from TypeScript suggesting changing moduleResolution the first time we try to import a library. However I think turborepo should just work

**Comment by jaredpalmer** [comment]
Sounds great. Can you make a PR for this that updates the template and starters?
