### ISSUE TITLE
Silence cache hit logs

### ISSUE THREAD

**Issue by richardwillars** [vercel/turborepo#364]
### Describe the feature you'd like to request

To minimise the output of information in the terminal and make it easier to see what was cached and what wasn't, it'd be useful to be able to minimise unnecessary terminal output. Cache hit logs are often not very useful to be seen in the terminal, as those tasks have successfully passed so you wouldn't usually need to be able to see them.. they're just noise at that point.

### Describe the solution you'd like

A --silenceCachedLogs flag passed to the turborepo cli that allows you to silence the output of logs when there is a cache hit. Ie putting this line in a conditional: https://github.com/vercel/turborepo/blob/788d57506abfe3d1a9d1d9e2e4ac9a2b65998ec4/cli/internal/run/run.go#L457

### Describe alternatives you've considered

A summary table after turborepo has finished outputting which summarises what was cached and what wasn't, and how long each non-cached step took to run. Perhaps that could be done in conjunction with the above?

**Comment by jaredpalmer** [comment]
Great feature request.

**Comment by weyert** [comment]
Maybe we can move it to the `verbose`  logging?
