### ISSUE TITLE
[turbopack] [webworker] After import webworker, can not execute webworker script

### ISSUE THREAD

**Issue by loclv** [vercel/turborepo#3643]
### What version of Turbopack are you using?

I don't know exactly, but I'm using `"next": "13.1.5"` with `next dev --turbo`.

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

After I import webworker script with `new URL()`:

```typescript
const plusWorker = new Worker(new URL('../workers/task-name', import.meta.url));
```

I develop with the `next dev --turbo` script, but unfortunately, the following error occurred:

```text
Refused to execute script from 'http://localhost:3000/_next/static/assets/d6f517fec7dcd080.ts' because its MIME type ('video/vnd.dlna.mpeg-tts') is not executable.
```

You can see full source code at [here](https://github.com/loclv/nextjs-template/tree/feature/web-worker-turbopack-bug).

Then, I back to webpack with the `next dev` script, everything works fine!

Here is the complete code. `src/pages/index.tsx` file's content:

```typescript
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useEffect } from 'react';

export default function Home() {
  useEffect(() => {
    const plusWorker = new Worker(new URL('../workers/plus', import.meta.url));

    plusWorker.onmessage = (event) => {
      console.log('🍏 Message received from worker: ', event.data);
    };

    plusWorker.onerror = (event) => {
      if (event instanceof Event) {
        console.log('🍎 Error message received from worker: ', event);
        return event;
      }

      console.log('🍎 Unexpected error: ', event);
      throw event;
    };

    plusWorker.postMessage([1, 2]);

    return () => {
      plusWorker.terminate();
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Get started by editing</p>
        </div>
      </main>
    </>
  );
}
```

`src/workers/plus.ts` file's content:

```typescript
import { TWorkerMess } from '@/models';

const onmessage = (event: MessageEvent<TWorkerMess>) => {
  console.log('🐝 Worker: Message received from main script');
  const data = event.data;
  const result = data[0] + data[1];

  const workerResult = 'Result: ' + result;
  console.log('🐝 Worker: Posting message back to main script');
  postMessage(workerResult);
};

addEventListener('message', onmessage);
```

`src/models/worker.ts` file's content:

```typescript
export type TWorkerMess = number[];
```

When run `next dev` or `pnpm dev` output on console log is below:

> 🐝 Worker: Message received from main script
> 
> 🐝 Worker: Posting message back to main script
> 
> 🍏 Message received from worker: Result: 3

### Expected Behavior

I can execute webworker script with turbopack.

### To Reproduce

Described in the Bug detail.

### Reproduction Repo

https://github.com/loclv/nextjs-template/tree/feature/web-worker-turbopack-bug

<sub>[PACK-2504](https://linear.app/vercel/issue/PACK-2504/[turbopack]-[webworker]-after-import-webworker-can-not-execute)</sub>

**Comment by masterkain** [comment]
same issue, also without turbo, has to resort to disabling turbo, enabling webpack and `InjectManifest` from `workbox-webpack-plugin` to deposit a .js file in public/  and then call my service worker like this `const registration = await navigator.serviceWorker.register('/stream-sw.js', { scope: './' });` avoiding the import.meta.url stuff.

would be nice to have direct support for both typescripted web workers and service workers.

**Comment by Cretezy** [comment]
Still getting the same error on Next.js v14.1.0.

**Comment by hiroki0525** [comment]
same issue on Next.js v14.1.0 ( App Router )

**Comment by timneutkens** [comment]
`new Worker()` is not supported in Turbopack yet. We're planning to add it after Turbopack is stable in Next.js.

**Comment by joacub** [comment]
> is not supported in Turbopack yet. We're planning to add it after Turbopack is sta

im was searching and searching and searching about this and there is not one mention in the whole nextjs docs, you should add this to people struglling with this.

**Comment by timneutkens** [comment]
It's already in the docs: https://nextjs.org/docs/architecture/turbopack#unsupported-features

**Comment by PFJoey** [comment]
+1

**Comment by chris-olszewski** [comment]
Closing as Turbopack as [moved homes](https://vercel.com/blog/turbopack-moving-homes)

**Comment by swappy-2003** [comment]
what error is this i did gpt but its say web worker it not working something like this



```
./node_modules/@ffmpeg/ffmpeg/dist/esm/classes.js:105:28`

Module not found: Can't resolve <dynamic>
  103 |         if (!this.#worker) {
  104 |             this.#worker = classWorkerURL ?
> 105 |                 new Worker(new URL(classWorkerURL, import.meta.url), {
      |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  106 |                     type: "module",
  107 |                 }) :
  108 |                 

```
https://nextjs.org/docs/messages/module-not-found

This error occurred during the build process and can only be dismissed by fixing the error.

**Comment by afshawnlotfi** [comment]
Any reason why this ticket is closed. Turbopack still doesn't have WebWorker support as of `"next": "15.1.6"`

**Comment by rezurrector** [comment]
"next": "15.1.0"
error TP1001 new Worker(./worker.js relative, {"type": "module"}) is not statically analyse-able

**Comment by maiconsanson** [comment]
The only solution is to use Webpack in both `development` and `production`.

**Comment by swappy-2003** [comment]
Pretty much true turbopack should fix this

**Comment by afshawnlotfi** [comment]
> The only solution is to use Webpack in both `development` and `production`.

My solution was just hosting the workers in `public/` as js files and referring as "/{pathToWorkerInPublic}" . Doesn't work with Typescript workers but if you have a TS project you can compile and use in JS workers. This is a temp workaround, not sure to host workers in public long term.

**Comment by ManuelAngel99** [comment]
Can confirm that this is still an active issue. The only solution I found was to follow @afshawnlotfi approach
