### ISSUE TITLE
Security FAQ for those who need ISO27001 or SOC2 compatible Vendors

### ISSUE THREAD

**Issue by ckortekaas** [vercel/turborepo#388]
### Describe the feature you'd like to request

Hi Turborepo team!

I was led here by your FAQ (https://turborepo.org/docs/faq) about where to ask when the security section does not answer enough questions.  We have about 20 general security questions that are pretty common to the industry (especially any SaaS products that use Vanta). Where is the appropriate place to ask these questions?

**Comment by jaredpalmer** [comment]
Please send all inquiries through https://vercel.com/security


Thanks!
