### ISSUE TITLE
Caching environment variables on Vercel

### ISSUE THREAD

**Issue by lukebussey** [vercel/turborepo#401]
### What version of Turborepo are you using?

1.0.19

### Describe the Bug

On Vercel I have a public environment variable set called `NEXT_PUBLIC_SEGMENT_WRITE_KEY`. It's set to one value for production, and another for preview and development.

If I deploy a preview branch with the build command set to `cd ../.. && yarn turbo run build --scope=website --includeDependencies --no-deps` and preview the site, the correct env var for preview/dev used.

But then if I then do a production deployment, the env var for preview/dev is still used. The env var is used within a function, within a component like this:

```js
  const renderSnippet = () => {
    const opts = {
      apiKey: process.env.NEXT_PUBLIC_SEGMENT_WRITE_KEY,
      load: true,
      page: true,
    };

    if (!opts.apiKey) {
      return null;
    }

    return snippet.min(opts);
  };
```

Clearing the build command so it's just the Next.js default restores the normal behaviour.

### Expected Behavior

Correct production env var is picked up and used.

### To Reproduce

1. Create a public environment variable with different values for production and preview/development.
2. Render `process.env.NEXTJS_PUBLIC_<var name>` to page.

**Comment by lukebussey** [comment]
@jaredpalmer 🙌🏻

**Comment by rodsfreitas** [comment]
Same happening here. This is critical. Our whole production environment was unexpectedly mapped to development, and disrupted our workflow.

**Comment by cedric-marcone** [comment]
We've been bitten by this issue in production.
As a temporary fix, you can add the `--force` CLI parameter to bypass the cache and force a full rebuild.

**Comment by lukebussey** [comment]
> We've been bitten by this issue in production.
> 
> As a temporary fix, you can add the `--force` CLI parameter to bypass the cache and force a full rebuild.

That worked great! Thanks!

**Comment by ColmanHumphrey** [comment]
We also lost production for a while there... One thing that was a bit tricky was that even 30 minutes after I edited the environmental variables stored in Vercel (that is, the value was not in any of the `.env` files), the old values were still used. Shouldn't that also have invalidated the cache? Even ignoring the blurring of the various environments, wouldn't this mean (without `--force`) you can't change an env variable in Vercel and then redeploy to use it?

**Comment by jaredpalmer** [comment]
Hey y'all. I'm working on the fix right now. You can track here: #495

**Comment by jaredpalmer** [comment]
Hopefully will have canary out in a bit. TLDR you will be able to add $SOME_ENV_VAR to `dependsOn` to impact cache/hash of a relevant task(s) in your pipeline. In additiona, you can also or rename/update env vars to contain `THASH` somewhere in them (e.g. `NEXT_PUBLIC_THASH_MY_CUSTOM_KEY`) and turbo will alter the global hash accordingly based on these values. The former method (`dependsOn` + package-specific task)  is more targeted and can give you a higher cache hit rate vs. altering the env var way which will global hash (which will impact all task hashes).

**Comment by jaredpalmer** [comment]
For very ambitious folks on the bleeding edge, you can try `turbo@canary` and read the upcoming docs here: https://turbo-site-git-refactor-hashable-env-vars.vercel.sh/docs/features/caching#alter-caching-based-on-environment-variables-and-files

**Comment by ColmanHumphrey** [comment]
Thanks @jaredpalmer!

**Comment by jaredpalmer** [comment]
Release in https://github.com/vercel/turborepo/releases/tag/v1.0.25

**Comment by dmnd** [comment]
I just broke prod in my turbo + nextjs + vercel app by deploying a preview env environment variable to production. A few thoughts:

* Feels like there's opportunity for tighter integration here that will make it harder to screw things up like I did. I already tell vercel about my env vars, perhaps in a vercel/nextjs app turbo can do the right thing by default? 
* I'd also prefer a safer default of not reusing the build cache across environments. Perhaps that's only unlocked by providing env vars as build inputs.
* I'm surprised that inlining env vars happens before turbo computes hashes. Feels like there is lots of scope for similar errors, e.g. adding a new babel transform or macro or minifier etc.

I'm new to turbo so likely some of these specific suggestions aren't workable, but generally, it'd be nice if this pitfall could be mitigated somehow.

**Comment by samantha-wong** [comment]
Just got burnt. This is still an issue for us still as well on v1.6.3 :(

**Comment by mxa0079** [comment]
We just ran into this issue on v28.13.2 of the Vercel CLI.

**Comment by exception** [comment]
Still an issue for us on latest turbo as well.

**Comment by Smilefounder** [comment]
The issue still exists.

**Comment by ardasatata** [comment]
Happen to me as well, 
it says `production`
<img width="194" alt="Screenshot 2023-08-15 at 12 39 48" src="https://github.com/vercel/turbo/assets/17568508/b6aa723c-66ed-4fc2-b464-a28bb66a2a5e">

But I got `staging` environment value instead 😢

**Comment by mikhail-karan** [comment]
Still running into this issue.

**Comment by logan-anderson** [comment]
Still getting this issue (Building a react app with Vite if that helps) on version 1.11.1
