### ISSUE TITLE
Start only a single app, and have that app's dependencies build.

### ISSUE THREAD

**Issue by NullVoxPopuli** [vercel/turborepo#417]
Related discussion: https://github.com/vercel/turborepo/discussions/372

### Describe the feature you'd like to request

In a largeish monorepo, (150+ JS/TS projects), it's infeasible to build everything, even if just initially -- there are entire teams that never see sections of the monorepo, so why make their machines pay the cost of building / starting those apps?

Today, when doing `turbo run <cmd>`, it seems that `<cmd>` is run in _every project_ that defines a `<cmd>` in `package.json#scripts` -- which is totally reasonable for small monorepos!

I would like the following behavior,
given a config: 
```json
{
  "turbo": {
    "baseBranch": "origin/main",
    "pipeline": {
      "start": { "dependsOn": ["^build"], "cache": false },
      "build": { "dependsOn": ["^build"] },
      "lint": {},
      "lint:fix": {},
    }
  },
}  
```
I would like the following to happen:
- when "starting an app for local development", currently: `yarn turbo run start --scope='my-app' --include-dependencies`
- build all the dependent projects in the monorepo (that have a `build` script)

What happens right now:
 - in addition to the above _all_ dependent projects are also "started" (even though I feel like I didn't tell them to?)

### Describe the solution you'd like

maybe a `--target='app-name'` or `--entry='app-name'` instead of scope, that _only_ runs the specified script in at the traget/entrypoint but first does the dependencies' build step (per the config).

so, `yarn turbo run start --target="app-name" would
1. run `build` in all dependencies
2. run `start` in `app-name`

### Describe alternatives you've considered

I _could_ try to re-work my scripts in my packages so that `start` means something else so this'd be a non-issue -- but that's a lot of work across a big monorepo that demands incremental changes :upside_down_face: 
In small monorepos, it's reasonable to do have a "watch"-like behavior across all your packages (I assume that's what the `dev` pipeline refers to in the docs), and I can do that for the small open source monorepo I have here: https://github.com/NullVoxPopuli/limber/pull/377 (there are like.. 5 packages).
but starting 30+ libraries in watch mode during development isn't a great option if app devs are going to stick to their apps.
For C.I., it's also important have the above requested behavior, because I'll need to run tests for a specific app and that app's dependencies need to be built in non-watch mode before the tests for the one app run.

**Comment by jaredpalmer** [comment]
So I did some further testing and am convinced we need to accelerate the move to #81 ASAP.

**Comment by jaredpalmer** [comment]
95% certain you can do this now with: 
```
turbo run start --scope='my-app' --include-dependencies --no-deps
```

```json5 {
  "turbo": {
    "baseBranch": "origin/main",
    "pipeline": {
      "start": { "dependsOn": ["^build"], "cache": false },
      "build": { "dependsOn": ["^build"] },
      "lint": {},
      "lint:fix": {},
    }
  },
} ```

**Comment by NullVoxPopuli** [comment]
Nay, that does too much.
for example, in this reproduction: https://github.com/NullVoxPopuli/limber/pull/377 (linked in the OP),
I see this output: 
```
❯ yarn turbo run start --scope="limber" --include-dependencies --no-deps
yarn run v1.22.17
$ /home/nullvoxpopuli/Development/NullVoxPopuli/limber/node_modules/.bin/turbo run start --scope=limber --include-dependencies --no-deps
• Packages in scope: @nullvoxpopuli/horizon-theme, @nullvoxpopuli/limber-codemirror, @nullvoxpopuli/limber-monaco, limber
• Running start in 4 packages
@nullvoxpopuli/horizon-theme:build: cache miss, executing b1b4694caa284856
@nullvoxpopuli/limber-monaco:build: cache miss, executing 106ee955d60bfd7e
@nullvoxpopuli/limber-monaco:start: cache miss, executing 9ef29e1e7efbb710
@nullvoxpopuli/limber-monaco:build: $ node build.js
@nullvoxpopuli/horizon-theme:build: $ tsc --build
@nullvoxpopuli/limber-monaco:start: $ echo 'this should not be ran by turborepo when running the root start'
@nullvoxpopuli/limber-monaco:start: this should not be ran by turborepo when running the root start
@nullvoxpopuli/limber-codemirror:build: cache miss, executing 23ecca135eda1449
@nullvoxpopuli/limber-codemirror:build: $ node build.js
limber:start: cache miss, executing 75b6f924fe7250b2
limber:start: $ TAILWIND_MODE=watch ember serve
 
limber:start:     Building:
```

`start` is invoked for all sub-packages, which is incorrect, as I only want to start the app

**Comment by derekdowling** [comment]
Using @jaredpalmer's suggestion of `turbo run start --scope='my-app' --include-dependencies --no-deps` I was able to achieve the desired behavior. I'd naively expect these flags to be the default desired behavior when using `--scope`.

@NullVoxPopuli I think you've uncovered another unexpected behavior. If you provide `--scope="non-existant-pkg" or `--scope="non-existant-path/**"` turbo-repo will execute the command across all matches rather than doing nothing. This confused me quite a bit when I was trying to originally use scope because I missed the point that it matches solely against package names and not relative paths.

**Comment by NullVoxPopuli** [comment]
> I was able to achieve the desired behavior. 

I mean, I still don't want dependencies' `start` to be ran when I want only my app's `start` to be ran. I just want my dependencies `build` to run (which is why I've specified my config as such)

>  If you provide --scope="non-existant-pkg"

but my package exists..

```
❯ cat frontend/package.json | jq '.name'
"limber"
```

**Comment by derekdowling** [comment]
@NullVoxPopuli got it. For my "start" use case, none of my apps dependencies also contain a "start" so I am not encountering the issue you're describing 👍

**Comment by NullVoxPopuli** [comment]
great -- I need my projects to have a start for their own self-contained development :upside_down_face:

**Comment by NullVoxPopuli** [comment]
I found out about graph generation in my test repo:

```
yarn turbo run start --scope='limber' --include-dependencies --graph
```

![image](https://user-images.githubusercontent.com/199018/153773326-0a627128-cbcd-4767-8ee8-ada755d743ae.png)

this is a good visual representation of all the `start` commands I don't want to run. :sweat_smile: 
(I only want the `start` of one app to run, `build` of everything else)

**Comment by jaredpalmer** [comment]
See https://turborepo.org/docs/features/filtering and `--filter=<package_name>...` flag in `turbo@1.2`

**Comment by NullVoxPopuli** [comment]
thanks!
