### ISSUE TITLE
Make root package.json name value same as directory

### ISSUE THREAD

**Issue by nikolasgioannou** [vercel/turborepo#430]
### Describe the feature you'd like to request

When you run `npx create-turbo@latest my-beastly-project`, the `name` field in the root `package.json` is `turborepo-basic-shared`. I think this should be `my-beastly-project` or whatever the directory was called.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

**Comment by tknickman** [comment]
Good call, because you can input a path here, we could use the last segment of the path for the name.
