### ISSUE TITLE
Possible bug with the integration of external local packages and Remix

### ISSUE THREAD

**Issue by viniciusflv** [vercel/turborepo#449]
### What version of Turborepo are you using?

1.0.23

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

**Given** the default examples from both the turborepo and remix CLIs
**When** importing the Button component from the ui local package
**Then** receives an ESM related syntax error on the page

```
import * as React from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**PS: It works properly with CJS**
### Expected Behavior

**Given** the default examples from both the turborepo and remix CLIs
**When** importing the Button component from the ui local package
**Then** don't receive an ESM related syntax error on the page

### To Reproduce

Example repo: https://github.com/viniciusflv/remix-esm-bug

npm: 8.1.0
node: 14.15.5

Run
`npx create-turbo@latest`

Remove next examples from ./app (Optional)

Run inside ./app
`npx create-remix@latest`

Remove remix package-lock.json and node_modules

Run on root
`npm i`

Import and use ui Button component at the main route **apps/remix/app/routes/index.tsx**

Run dev
`npm run dev`

Open on localhost to see the error

**Comment by jaredpalmer** [comment]
This is because the default turbo example `ui` doesn't transpile itself, but rather lets next.js do it via `next-transpile-modules`. The suggestion is to use something like `tsup` like in the kitchen sink example here https://github.com/vercel/turborepo/tree/main/examples/kitchen-sink/packages/ui

**Comment by developer239** [comment]
For future reference people who use Nest.js:

In your app with `health: "*"` dependency:
```
import { HealthModule } from 'health'

@Module({
  imports: [
    HealthModule,
  ],
})
export class AppModule {}
```

Then in your `packages/health/package.json`:
```
{
  "name": "health",
  "version": "0.0.0",
  "publishConfig": {
    "access": "public"
  },
  "main": "./dist/health.module.js",
  "types": "./dist/health.module.d.ts",
  "scripts": {
    "build": "tsup src/*.ts --dts --format cjs"
  },
  "devDependencies": {
    "@anatine/esbuild-decorators": "^0.2.19",
    "tsconfig": "*",
    "tsup": "^6.7.0"
  },
  "dependencies": {
    "@nestjs/common": "^9.4.1",
    "@nestjs/swagger": "^6.3.0",
    "@nestjs/terminus": "^9.2.2"
  }
}
```

And then finally `packages/health/tsup.config.ts`
```
import { esbuildDecorators } from '@anatine/esbuild-decorators'
import { defineConfig, Options } from 'tsup'

export default defineConfig((options: Options) => ({
  ...options,
  sourcemap: true,
  clean: true,
  esbuildPlugins: [esbuildDecorators()],
}))
```

**Comment by Geebrox** [comment]
> For future reference people who use Nest.js:
> 
> In your app with `health: "*"` dependency:
> 
> ```
> import { HealthModule } from 'health'
> 
> @Module({
>   imports: [
>     HealthModule,
>   ],
> })
> export class AppModule {}
> ```
> 
> Then in your `packages/health/package.json`:
> 
> ```
> {
>   "name": "health",
>   "version": "0.0.0",
>   "publishConfig": {
>     "access": "public"
>   },
>   "main": "./dist/health.module.js",
>   "types": "./dist/health.module.d.ts",
>   "scripts": {
>     "build": "tsup src/*.ts --dts --format cjs"
>   },
>   "devDependencies": {
>     "@anatine/esbuild-decorators": "0.2.19",
>     "tsup": "6.7.0"
>   },
>   "peerDependencies": {
>     "@nestjs/common": "9.4.1",
>     "@nestjs/swagger": "6.3.0",
>     "@nestjs/terminus": "9.2.2",
>     "tsconfig": "*"
>   }
> }
> ```
> 
> And then finally `packages/health/tsup.config.ts`
> 
> ```
> import { esbuildDecorators } from '@anatine/esbuild-decorators'
> import { defineConfig, Options } from 'tsup'
> 
> export default defineConfig((options: Options) => ({
>   ...options,
>   sourcemap: true,
>   clean: true,
>   esbuildPlugins: [esbuildDecorators()],
> }))
> ```

You can use `tsup-node` as far as you do not need to bundle **Node.js** app.
See: https://tsup.egoist.dev/#excluding-all-packages
