### ISSUE TITLE
Turob hangs when a package command includes --watch (part 2)

### ISSUE THREAD

**Issue by NullVoxPopuli** [vercel/turborepo#464]
### What version of Turborepo are you using?

1.0.24-canary.1

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

I have a package that does `tsc --build --watch`, and turbo hangs as a result (because watch never ends)

### Expected Behavior

all commands run

### To Reproduce

- have several projects, an app and some libraries
- define:
```
  "turbo": {
    "pipeline": {
      "dev": {
        "dependsOn": [
          "^dev"
        ]
      },
```
- have one of the library/package.json#scripts.dev be `tsc --build --watch`
- observe app's `dev` script is never ran

Repro:
 - https://github.com/NullVoxPopuli/limber/pull/377
 - commit: https://github.com/NullVoxPopuli/limber/pull/377/commits/aea628dc28e0286be4d4109d1097174e46b0ce60
 - run `yarn dev`

**Comment by jaredpalmer** [comment]
This actually isn't a turbo bug. You tsc build process terminate with --watch, thus turbo will not know "release" the go routine internally, and you will be limited to the concurrency level you have set (`--concurrency=10` by default). I think what you're really asking for is a way to build all the dependencies before running dev, and or running with the `--parallel` flag.

**Comment by NullVoxPopuli** [comment]
yeah, I mean, `tsc` is just an example here, in development, I'd like the power to have `rollup --watch`, too

**Comment by NullVoxPopuli** [comment]
if that's not possible, that's _fine_, I suppose. No other tool supports that... which... isn't my favorite status quo, but :shrug:

**Comment by NullVoxPopuli** [comment]
it does mean I need https://github.com/vercel/turborepo/issues/417 due to differences in semantics between start/dev/watch/etc commands.

**Comment by NullVoxPopuli** [comment]
I super appreciate how fast ya'll are working on turborepo tho <3

**Comment by stevebeauge** [comment]
> if that's not possible, that's _fine_, I suppose. No other tool supports that... which... isn't my favorite status quo, but 🤷

pnpm and its workspace command allow this.

For example, in one of my largest monorepo I have in the root package.json file something like this:

    "scripts": {
        "dev": "pnpm --stream --parallel --filter ./packages/* run serve",
        ....
    },

which will call serve command in every packages/* folder, in parrallel
