### ISSUE TITLE
`kitchen-sink` example fails on tests

### ISSUE THREAD

**Issue by hyeomans** [vercel/turborepo#466]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When running `yarn test` on `examples/kitchen-sink` fails with:

```
ui:test:     src/__tests__/index.test.tsx:7:17 - error TS2584: Cannot find name 'document'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.

ui:test:     7     const div = document.createElement("div");
ui:test:                       ~~~~~~~~

ui:test: Test Suites: 1 failed, 1 total
ui:test: Tests:       0 total
ui:test: Snapshots:   0 total
ui:test: Time:        2.321 s
ui:test: Ran all test suites.
ui:test: error Command failed with exit code 1.
ui:test: Error: command finished with error: exit status 1
child_process.js:830
    throw err;
    ^
```

### Expected Behavior

Tests should pass

### To Reproduce

* Download `examples/kitchen-sink`
* `cd examples/kitchen-sink && yarn install && yarn test`
*

**Comment by kbenrafik** [comment]
I can reproduce the same issue.
I've created a fix for it: https://github.com/vercel/turborepo/pull/473
