### ISSUE TITLE
Kill other processes when another fails

### ISSUE THREAD

**Issue by arpadgabor** [vercel/turborepo#470]
### What version of Turborepo are you using?

v1.0.24-canary.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Not sure if there is a way to fix this but:

Trying to start development mode on multiple projects and if one fails the already started processes remain running. Running `dev` again crashes because ports are already used.

There is a similar issues #288 regarding a used port, but does not really fit with this issue.

### Expected Behavior

If one app crashes, stop the others as well.

### To Reproduce

```
• Packages in scope: cms, config, docs, tsconfig, ui, web
• Running dev in 6 packages
docs:dev: cache miss, executing 47fd78234aadaeb7
web:dev: cache miss, executing 675697dc9592dfab
cms:dev: cache miss, executing 9c92b9d17ad2bd7a

web:dev: > web@0.0.0 dev /home/arpad/projects/monorepo-starter/apps/web
web:dev: > next dev


docs:dev: > docs@0.0.0 dev /home/arpad/projects/monorepo-starter/apps/docs
docs:dev: > next dev --port 3001


cms:dev: > cms@0.1.0 dev /home/arpad/projects/monorepo-starter/apps/cms
cms:dev: > strapi develop

web:dev: ready - started server on 0.0.0.0:3002, url: http://localhost:3002
docs:dev:  ELIFECYCLE  Command failed with exit code 1.
docs:dev: Port 3001 is already in use.
docs:dev: Error: command finished with error: exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

This is in the pnpm template (I realise I am using strapi and apparently it does not work well with pnpm, but the issue still stands).

**Comment by gsoltis** [comment]
I'm going to reopen this, as I think this is separate from signal handling from external events. I *think* the behavior should be failing the `turbo` run if one of the child processes fails, and propagating a signal to child processes to ensure they exit.
