### ISSUE TITLE
turbo prune fails when renaming yarn-tmp.lock file

### ISSUE THREAD

**Issue by maximeMD** [vercel/turborepo#503]
### What version of Turborepo are you using?

1.0.24

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

First, thanks for you amazing work 😄 👍 

Whenever I use `yarn turbo prune --scope=web` , even with the default starter, i get the following error :

`
ERROR  Failed finalize lockfile: rename C:\Users\xxxxxxxx\test-turborepo\out\yarn-tmp.lock C:\Users\xxxxxxxx\test-turborepo\out\yarn.lock: The process cannot access the file because it is being used by another process.
`

### Expected Behavior

Finish the turbo prune command without any error

### To Reproduce

```
npx create-turbo@1.0.24
cd my-turborepo
yarn turbo prune --scope=web
```

Node v16.13.1
Windows 10

**Comment by maximeMD** [comment]
FIY Everything works fine inside WSL !

**Comment by b12k** [comment]
This issue is reproducible also using `turbo@1.1.0-canary.2` (on Win10)
![изображение](https://user-images.githubusercontent.com/10243265/151072606-f1f5ea20-6efd-487f-be5d-f734fff4eeee.png)
