### ISSUE TITLE
Create react app test hangs

### ISSUE THREAD

**Issue by mr-bjerre** [vercel/turborepo#505]
### What version of Turborepo are you using?

1.0.24

### What package manager are you using / does the bug impact?

pnpm 6.22.2

### What operating system are you using?

Mac

### Describe the Bug

If I create a new CRA app with

```
pnpm dlx create-react-app cra --template typescript
```

and run `turbo run test` then it hangs after tests completes.

Note you have to delete `node_modules` and `package-log.json` in new `cra` folder and then run `pnpm install` in project root.

### Expected Behavior

I'd expect the command to exit after running the tests.

### To Reproduce

As in described in the bug details

**Comment by jaredpalmer** [comment]
I don't think this is turbo issue but rather that Create React App doesn't expect to be in a workspace and so it tries to install node_modules normally. There isn't much turbo can do here I don't think for the timebeing/foreseable future
