### ISSUE TITLE
Discord invite link is invalid

### ISSUE THREAD

**Issue by OskarD** [vercel/turborepo#508]
### What version of Turborepo are you using?

1.0.24

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3 (not supported)

### What operating system are you using?

Mac

### Describe the Bug

The Discord invite link on both the website and in this repo is invalid

https://turborepo.org/discord

### Expected Behavior

Working link

### To Reproduce

Go to https://turborepo.org/discord

**Comment by jaredpalmer** [comment]
Just changed it. here is the direct link anyways: https://discord.com/invite/sSzyjxvbf5

**Comment by OskarD** [comment]
> Just changed it. here is the direct link anyways: https://discord.com/invite/sSzyjxvbf5

It doens't work either :(

**Comment by jaredpalmer** [comment]
I and others aren't able to repro? Maybe something else going on?

<img width="780" alt="CleanShot 2022-01-06 at 12 11 21@2x" src="https://user-images.githubusercontent.com/4060187/148422405-be3e976c-0979-4762-9d4d-9e9df60aaec2.png">

**Comment by OskarD** [comment]
> I and others aren't able to repro? Maybe something else going on?
> 
> <img alt="CleanShot 2022-01-06 at 12 11 21@2x" width="780" src="https://user-images.githubusercontent.com/4060187/148422405-be3e976c-0979-4762-9d4d-9e9df60aaec2.png">

Thanks, it works in Incognito mode so I guess it's something on my end. Sorry to bother you :)
