### ISSUE TITLE
Option to ignore certain blobs from calculated hash

### ISSUE THREAD

**Issue by JoeyEamigh** [vercel/turborepo#528]
### Describe the feature you'd like to request

As the title says, I would like the option to ignore certain blobs from Turborepo's calculated hash. This is useful for ignoring tests directories so that I can make an edit to a test and when tests depend on build step it does not rebuild the project.

### Describe the solution you'd like

This is an under the hood hashing thing, but maybe have a field in the turbo JSON as an array of ignored globs.

### Describe alternatives you've considered

none really

**Comment by aomarks** [comment]
Related to https://github.com/vercel/turborepo/issues/523

**Comment by jaredpalmer** [comment]
Duplicate of #523
