### ISSUE TITLE
Better error message when defining a pipeline incorrectly

### ISSUE THREAD

**Issue by rvlewerissa** [vercel/turborepo#530]
### Describe the feature you'd like to request

When I incorrectly swapped the `<package>#<task>` as `<task>#<package>`, I received the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14003a8]

goroutine 28 [running]:
turbo/internal/run.(*RunCommand).Run.func3({0xc000216080, 0xd})
        turbo/internal/run/run.go:381 +0x188
turbo/internal/core.(*scheduler).Execute.func1({0x1449600, 0xc00429d2d0})
        turbo/internal/core/scheduler.go:109 +0x1bd
github.com/pyr-sh/dag.(*Walker).walkVertex(0xc0041deb40, {0x1449600, 0xc00429d2d0}, 0xc00038d980)
        github.com/pyr-sh/dag@v1.0.0/walk.go:377 +0x2ff
created by github.com/pyr-sh/dag.(*Walker).Update
        github.com/pyr-sh/dag@v1.0.0/walk.go:300 +0xf85
```

Here I do not have any package named: `task`

### Describe the solution you'd like

Would be nice if there would be a more descriptive error message :)

### Describe alternatives you've considered

Package `<task>` not found.

**Comment by DLesage25** [comment]
Bump ^

**Comment by gsoltis** [comment]
This no longer crashes. I edited my pipeline to have a `build1#ui` entry, then ran `turbo run build1 --filter=ui`. I got ``` ERROR  task `build1` not found in turbo `pipeline` in "turbo.json". Are you sure you added it?```
