### ISSUE TITLE
[turbopack] The image format WebP is not supported

### ISSUE THREAD

**Issue by TzviPM** [vercel/turborepo#5347]
### What version of Next.js are you using Turbopack in?

Next.js v13.4.6

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

This bug occurs when using `next dev --turbo`.

I use webp for most images on tzvipm.dev. I have an import like this in my root `page.tsx`:

```
import portrait from '../public/portrait.webp';
```

when running `next dev --turbo`, and navigating to the home page, I get the following error in my terminal:

```
$ next dev --turbo
>>> TURBOPACK (beta)

Thank you for trying Next.js v13 with Turbopack! As a reminder,
Turbopack is currently in beta and not yet ready for production.
We appreciate your ongoing support as we work to make it ready
for everyone.

Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack
Please direct feedback to: https://nextjs.link/turbopack-feedback

ready - started server on [::]:3000, url: http://localhost:3000
error - [image] public/portrait.webp
  Processing image failed
  unable to decode image data
  
  Caused by:
  - The image format WebP is not supported

warning - [parse]
  ... [3 paths] are hidden, run with --show-all to show them
```

In the browser, I also see an error:

<img width="1123" alt="Screenshot 2023-06-21 at 9 47 39 AM" src="https://github.com/vercel/turbo/assets/1950680/a63c081f-3315-46b7-a38e-6a501a9ac152">

### Expected Behavior

Images in webp format should be incuded in the page without errors

### To Reproduce

1. In a nextjs app with app dir routing, include an image in `webp` format. You can use the one from my site to help debug, if you'd like: https://www.tzvipm.dev/portrait.webp
2. Run `next dev --turbo`

**Comment by jridgewell** [comment]
@kwonoj I believe you enabled webp for next images, right?

**Comment by kwonoj** [comment]
No, it is blocked by build platform support as far as I recall.

**Comment by TzviPM** [comment]
Apparently webp support landed in today’s release. I’ll test and confirm

**Comment by alexeightsix** [comment]
I was experiencing the same error and updated my NextJS version in my package.json to 13.4.10 and I'm no longer getting the error.

**Comment by ryanjafari** [comment]
I'm using Next 15.0.0-canary.14 (turbo) and still getting this message if anyone has any ideas for me. Converted the images to png in meantime.

<img width="498" alt="Screenshot 2024-06-06 at 3 30 11 PM" src="https://github.com/vercel/turbo/assets/29539/ebef2298-9135-482d-bbf5-09f94748b055">

**Comment by GiangLe1999** [comment]
Any solutions for this?

**Comment by ryanjafari** [comment]
I ended up not relying on webp, I wasn't able to get this working any other way

**Comment by Judge-Paul** [comment]
Can confirm this is still the case on v14.2.22
