### ISSUE TITLE
[turborepo] Turbo requiring a pnpm workspace file

### ISSUE THREAD

**Issue by samcx** [vercel/turborepo#5357]
### What version of Turborepo are you using?

1.10.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

![CleanShot 2023-06-21 at 21 37 18@2x](https://github.com/vercel/turbo/assets/28912696/45b42558-20a3-4cad-9add-2a5c9bd203af)

It looks like `v.1.10.4-canary.4` and above are requiring a `pnpm-workspace.yaml`, when it is not the case for previous versions. 

### Expected Behavior

I expect Turborepo to be able to run without a `pnpm-workspace.yaml` file, as stated in the docs → https://turbo.build/repo/docs/getting-started/add-to-project.

### To Reproduce

Simply try to run a full turbo on the Reproduction Repo with `v.1.10.4-canary.4` and above.

### Reproduction Repo

https://github.com/samcx/samcx

**Comment by dr-iroh** [comment]
I have exactly the same issue

**Comment by gsoltis** [comment]
Sorry about this, we've identified the issue (#5362) and will be releasing a new patch release shortly!

**Comment by gsoltis** [comment]
@samcx @dr-iroh can you try with `turbo@1.10.5`?

**Comment by samcx** [comment]
@gsoltis Working again with `turbo@1.10.5`!

**Comment by dr-iroh** [comment]
@g-plane turbo works again, thanks

**Comment by dr-iroh** [comment]
@gsoltis turbo works again, thanks

**Comment by kevanantha** [comment]
> @samcx @dr-iroh  @kevanantha  can you try with `turbo@1.10.5`?

it works. thanks
