### ISSUE TITLE
[turbopack] Unable to get the configuration of PostCSS from package.json

### ISSUE THREAD

**Issue by mogeko** [vercel/turborepo#5369]
### What version of Next.js are you using Turbopack in?

13.4.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

According to the [document of postcss-load-config](https://github.com/postcss/postcss-load-config#packagejson), PostCSS supports configuring it using the `postcss` field in `package.json` or a configuration file.

However, **the `postcss` field in `package.json` is not working** when I using PostCSS with Turbopack.

<img width="1552" alt="截屏2023-06-23 11 26 40" src="https://github.com/vercel/turbo/assets/26341224/6eb95135-17ea-4fb9-818c-2f9781e5b956">

Then, I tried to create a `.postcssrc.json` and copied the same configuration into it, everything is in line with expectations.

<img width="1552" alt="截屏2023-06-23 11 33 22" src="https://github.com/vercel/turbo/assets/26341224/be75b016-429d-44ef-8b85-6b3d2615bcc0">

### Expected Behavior

Use `postcss` in `package.json` to configure PostCSS, which should get the same results as using a configuration file.

### To Reproduce

1. Create a project that uses Next.js and PostCSS, for example: [Next.js + Tailwind CSS Example](https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss)
2. Removed `postcss.config.js` to prevent it from interfering with experiments
3. Configure Post CSS using `postcss` in `package.json`:
   ```json
   "postcss": {
     "plugins": [
       "tailwindcss",
       "autoprefixer"
     ]
   }
   ```
4. Run Next.js with Turbopack:
   ```
   pnpm next dev --turbo
   ```

### Reproduction Repo

https://github.com/mogeko/movisea

<sub>[PACK-2499](https://linear.app/vercel/issue/PACK-2499/[turbopack]-unable-to-get-the-configuration-of-postcss-from)</sub>

**Comment by chris-olszewski** [comment]
Closing as Turbopack as [moved homes](https://vercel.com/blog/turbopack-moving-homes)
