### ISSUE TITLE
turbo/pnpm/lerna does not understand workspace protocol

### ISSUE THREAD

**Issue by brentertz** [vercel/turborepo#546]
### What version of Turborepo are you using?

1.0.25

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Error when running lerna command using pnpm in turborepo that uses workspace protocol. `workspace:*`

```bash
➜ turbo-test git:(master) ✗ pnpm lerna bootstrap
lerna notice cli v4.0.0
lerna info versioning independent
lerna ERR! Error: Unsupported URL Type "workspace:": workspace:*
```

### Expected Behavior

> tl;dr you can use Lerna and Turbo together.

From https://turborepo.org/docs/guides/migrate-from-lerna

I expected this to work, since the documentation says that the tools work together.

### To Reproduce

Add lerna to a turborepo that uses pnpm.  Try to run a lerna command, like `pnpm lerna bootstrap`.

**Comment by fivethreeo** [comment]
This is a lerna issue, not turbo/pnpm.

**Comment by brentertz** [comment]
Perhaps, but the turborepo documentation clearly states that you can use the tools together.  If this is not the case, then it should likely be noted.

**Comment by fivethreeo** [comment]
The issue is pnpm and lerna, turbo works with lerna.

**Comment by brentertz** [comment]
Okay, thanks...
