### ISSUE TITLE
Turborepo doesn't always take defined environment variables into the hash

### ISSUE THREAD

**Issue by leolabs** [vercel/turborepo#548]
### What version of Turborepo are you using?

1.0.25

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

With a certain number of environment variables, Turborepo stops taking their value into the hash which leads to cache hits even when the environment variables have changed.

Demo video:

https://user-images.githubusercontent.com/541628/149146035-72db9677-e0c9-48bc-ba35-ed594890f1e1.mp4

### Expected Behavior

When one of the environment variables changes, it should affect the calculated hash.

### To Reproduce

Repro repo: https://github.com/leolabs/turborepo-env-repro

Config from `package.json`:

```json
{
  "turbo": {
    "pipeline": {
      "build": {
        "dependsOn": [
          "^build"
        ],
        "outputs": [
          "dist/**",
          ".next/**"
        ]
      },
      "web-site#build": {
        "dependsOn": [
          "^build",
          "$NEXT_PUBLIC_CLIENT_ID",
          "$NEXT_PUBLIC_AUDIENCE",
          "$NEXT_PUBLIC_DOMAIN"
        ],
        "outputs": [
          "dist/**",
          ".next/**"
        ]
      },
      "lint": {
        "outputs": []
      },
      "dev": {
        "cache": false
      }
    }
  },
}
```

**Comment by jaredpalmer** [comment]
Fix in #547

**Comment by leolabs** [comment]
That was quick, thanks! Do you have an estimate of when this will be released?

**Comment by RohitKumarGit** [comment]
how to fix this I am still having this issue
