### ISSUE TITLE
turbo@1.0.25 doesn't detect any packages

### ISSUE THREAD

**Issue by PavlMais** [vercel/turborepo#549]
### What version of Turborepo are you using?

1.0.25

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

After updating to 1.0.25 turbo doesn't detect any packages

```
> test@1.0.0 build /home/paul/r/test
> turbo run build

• Packages in scope: 
• Running build in 0 packages

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    2ms >>> FULL TURBO 
```

### Expected Behavior

in 1.0.24 everything works fine

```
> test@1.0.0 build /home/paul/r/test
> turbo run build

• Packages in scope: @test/api, @test/shared, test-server, test-ui
• Running build in 4 packages
@test/shared:build: cache miss, executing 3ecd2717612f3d54
@test/shared:build: 
...
```

### To Reproduce

update to 1.0.25 and run any script e.g dev, build

**Comment by jaredpalmer** [comment]
Does this problem happen in 1.0.26?

**Comment by YousignAdmin** [comment]
Yes it is.
```bash
• Packages in scope:
• Running build in 0 packages

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    13ms >>> FULL TURBO

❯ turbo --version
1.0.26
```

**Comment by wab** [comment]
Yes it is
```bash
• Packages in scope:
• Running build in 0 packages

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    13ms >>> FULL TURBO

❯ turbo --version
1.0.26
```

**Comment by samburgers** [comment]
Same here. Steps to replicate:

```
npx create-turbo@latest
```

```
? Where would you like to create your turborepo? .
? Which package manager do you want to use? npm
```

Delete folder `apps/docs`

```
npm run dev

> turborepo-basic-shared@0.0.0 dev
> turbo run dev --parallel

• Packages in scope: 
• Running dev in 0 packages

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    9ms >>> FULL TURBO
  ```

**Comment by jaredpalmer** [comment]
Investigating

**Comment by shunkakinoki** [comment]
Same here. Some packages are missing, vercel builds failing

**Comment by jaredpalmer** [comment]
Can you upgrade to .27?

**Comment by shunkakinoki** [comment]
Thank you for the response!

Did that, resolved to multiple versions, but not working

**Comment by PavlMais** [comment]
same problem with 1.0.27 and 1.0.28

**Comment by shunkakinoki** [comment]
Doesn't help ... the detected packages completely differ depending on ci envs or local

**Comment by rix1** [comment]
I experienced this on a brand new repo (after running `❯ npx create-turbo@latest`) as well. 

The initial run works great, but if I rename a directory Turbo doesn't seem to be able to resolve any packages... Not sure if it helps, but at least here's a way to reproduce:

1. `❯ npx create-turbo@latest` (selecting `pnpm`)
2. `❯ pnpm dev` (works)
3. `❯ mv packages/ui/ packages/ui-new` (rename package)
2. `❯ pnpm dev` (doesn't work)
3. `❯ mv packages/ui-new/ packages/ui` (revert)
4. `❯ pnpm dev` (works again)

<details><summary>Screenshot of terminal output</summary>

<img width="637" alt="Screenshot by Rix1 2022-01-14 at 23 10 37" src="https://user-images.githubusercontent.com/2470775/149591961-e4d60d37-95ac-48f4-aecd-45e76619c4e7.png">


</details>

**Comment by mm-webx** [comment]
Same for my side, node 16.13.1, created by npx use "./" as target and detect 0 packages:

`node/v16.13.1/bin/node /Users/webx/.nvm/versions/node/v16.13.1/lib/node_modules/npm/bin/npm-cli.js run build --scripts-prepend-node-path=auto

> turborepo-basic-shared@0.0.0 build
> turbo run build

• Packages in scope: 
• Running build in 0 packages

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    9ms >>> FULL TURBO


Process finished with exit code 0`

**Comment by mm-webx** [comment]
I change version to 1.0.25, then run "build", then update again to "latest" and delete all ".turbo" folders, now working fine.

**Comment by davidboom95** [comment]
Same problem here. Tried some of the solutions here without success.

**Comment by shunkakinoki** [comment]
How does the package detection work at the moment? not from yarn workspaces?

**Comment by miestasniyo** [comment]
v1.0.28

```sh
yarn create turbo
cd my-app
yarn dev # works > Packages in scope: config, docs, tsconfig, ui, web
rm -rf apps/docs
yarn dev # doesn't work > Packages in scope: 
```

**Comment by cdaringe** [comment]
Looking through the [24->25 diff](https://github.com/vercel/turborepo/compare/9c0bb5651df7c352919078e320653b6e419209a8...1751deb5c0f1152c2267078ba24f65ebb43de56b), I don't see anything obvious. There is some pnpm specific logic changes, but those seem around `dlx` for installation, which is not correlated with this failure mode.

Confirmed, downgrade to 24 restores expected behavior.

**Comment by jaredpalmer** [comment]
If you move or rename a package, re-running `pnpm install` works. I wonder if this is something to do with: https://github.com/vercel/turborepo/commit/8c871d49fa006ee9411b6549d124480fae4f1c77

**Comment by jaredpalmer** [comment]
Can confirm this issue is with https://github.com/vercel/turborepo/commit/8c871d49fa006ee9411b6549d124480fae4f1c77

**Comment by betaorbust** [comment]
Just a few more datapoints: 

In my monorepo (yarn), I have 
```json
    "workspaces": [
        "packages/*",
        "apps/*"
    ],
```
and only the items in /packages are found. 

Things I've tried that didn't work:
- Removing the "packages/*": 0 packages found
- Moving package from /apps to /packages: moved package now detected as part of /packages, no /apps found.
- Moving a building package in /packages to /apps: all /packages found, no /apps found (and not the one I moved there.)
- Messing around with scope

Things that did work: 
- Downgrading to 1.0.24

**Comment by JonasHiltl** [comment]
I'm still experiencing this with `v1.0.28` on WSL.
After renaming the directory & package name inside a workspace the whole workspace doesn't get recognized anymore.

**Comment by shunkakinoki** [comment]
I solved it by removing symlinks altogether. 
Probably some symlinks were broken, leading to turborepo not recognizing it.
Hope this helps!

**Comment by JonasHiltl** [comment]
@shunkakinoki yea I ended up doing the same

**Comment by bartem88** [comment]
i'm still seeing this issue after upgrading to 1.0.28, @shunkakinoki how did you fix it? not sure what you mean by removing symlinks

**Comment by shunkakinoki** [comment]
`find -type l -delete` and remove symlinks, and then figure out what symlinks breaks turborepo

**Comment by shikelong** [comment]
same issue in 1.0.28

**Comment by shikelong** [comment]
> same issue in 1.0.28

I fix this issue by run clean step, and then reinstall root level dependencies.

```bash

pnpm run clean

pnpm install

pnpm run dev
# now it's ok

```

My clean script: `"clean": "turbo run clean && rm -rf node_modules"`

**Comment by JonasHiltl** [comment]
@shikelong what is the `clean` script inside the packages/apps?

**Comment by shikelong** [comment]
> 

```bash
"clean": "rm -rf .turbo && rm -rf node_modules && rm -rf dist"
```

**Comment by shikelong** [comment]
At first, I use pnpm as packageManager. And I install dependencies in isolate mode.
In this mode, turbo can detect packages.
But Storybook can work in isolate mode, So I change node-linker config to hoisted. But in this mode, turbo cannot detect packages even I run clean script.
So, finally, I switch to yarn classical. It's all ok —— Storybook and turbo-repo apps detecting.

**Comment by JonasHiltl** [comment]
The problem with your `clean` script is that turbo can't execute it in the missing packages, because the symlinks are broken so turbo has issues detecting the actual packages present in the workspaces. 
For examples when having an `apps` and `common` workspace. Then a package inside the `apps` workspace got deleted, which broke some symlinks, the `clean` script off the packages inside `apps` will not get executed.
Running the `clean` script manually in every `package` also doesn't help

**Comment by bkiac** [comment]
I still get this issue with `1.0.28` when I create/move/delete packages, but cleaning up the `node_modules` and reinstalling from root fixes it.

**Comment by PavlMais** [comment]
This issue was fixed in `1.1.0-canary.2`

**Comment by BlackGlory** [comment]
I encountered this problem in 1.1.4 and 1.1.5.

**Comment by koo6357** [comment]
i had same issue
Check if the folder name in apps and  project name in package.json are different.
In my case, this was the problem
it should be same

**Comment by xbtmatt** [comment]
I encountered this issue because I was linking my packages in `pnpm-workspaces.yaml` like so:

```yaml
packages:
  - "api/*"
  - "frontend/*"
```

when I needed to do it as:

```yaml
packages:
  - "api"
  - "frontend"
```

Because `api` and `frontend` were actually top-level packages, not a directory of packages.

**Comment by jeffng50** [comment]
Same with npm here @xbtmatt 's solution fixed it for me, the [docs](https://turbo.build/repo/docs/crafting-your-repository/structuring-a-repository) should mention it
