### ISSUE TITLE
scope docs in --help may be misleading?

### ISSUE THREAD

**Issue by NullVoxPopuli** [vercel/turborepo#552]
### What version of Turborepo are you using?

1.0.26

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

```
  --scope                Specify package(s) to act as entry points for task
                         execution. Supports globs.
```

with just reading this, it seems like `--scope` could be used to achieve any of these issues:
 - https://github.com/vercel/turborepo/issues/414
 - https://github.com/vercel/turborepo/issues/348
 - https://github.com/vercel/turborepo/issues/417
 
 but `--scope` _ignores_ `dependencies`, no matter what. 

### Expected Behavior

docs for scope are clear about what the intent is?
atm, it seems, `dependsOn` is ignored, which I think should be called out.

when running `turbo run start`, `dependsOn` is respected.

### To Reproduce

Read the misaligned expectations in  https://github.com/vercel/turborepo/issues/417 :sweat_smile:

**Comment by NullVoxPopuli** [comment]
It _feels like_ the turbo.json config isn't used.

For example, I have this entry in `pipeline`
```json
{
  "pipeline": {
    "start": {
      "dependsOn": [
        "^build"
      ],
    },
  }
}
```

and when I run: 
```bash
yarn turbo run start --scope="limber" --graph
```
I get this graph:
![image](https://user-images.githubusercontent.com/199018/153773596-4a321f55-0b96-4872-82dc-f0b1fb9e6295.png)

I would have expected that the `build` task for each dependency be ran.

**Comment by jaredpalmer** [comment]
`--scope` is being deprecated. See https://turborepo.org/docs/features/filtering and the new `--filter` flag in `turbo@1.2`
