### ISSUE TITLE
Add `turbo migrate` / `turbomod` package for automated migrations

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#555]
### Describe the feature you'd like to request

We need a way to make breaking changes less painful and provide a smooth upgrade path between `turbo` versions.

### Describe the solution you'd like

Add a new CLI package called `turbo-migrate` or `turbomod` that can hold `turbo` migration scripts / codemods for when we need to make breaking changes to user's monorepos, code, or turbo configurations. 

At the moment, I think the package can be written in TypeScript. If we one day do need it written in Go, we can deal with it then. For now, we only need to modify `package.json`.

- It should be modeled after https://github.com/vercel/next.js/tree/canary/packages/next-codemod. We aren't using jscodeshift so that part is irrelevant for now. The parts that are good are the CLI API, the ability to select codemod and run it, throwing if git status isn't clean.

```sh
npx @turbo/migrate <transform> <path>
```

`transform` - name of transform, see available transforms below.
`path` - files or directory to transform
`--dry` Do a dry-run, no code will be edited
`--print` Prints the changed output for comparison
`--force` Force execute a codemod

- We should add a page to the documentation listing what each codemod does, just like https://nextjs.org/docs/advanced-features/codemods
- 2 codemods should be written / can be helpful for stubs
  - Add `packageManager` key to `package.json` in the root and in each workspace's `package.json`
  - Move `turbo` config out of `package.json` and into a new `turbo.json` that lives at the root of the monorepo

 

### Describe alternatives you've considered

N/A

**Comment by Xenfo** [comment]
> * Add `packageManager` key to `package.json` in the root and in each workspace's `package.json`

I think it's only needed in the root `package.json`. It might be better backwards from wherever Turbo was run until we find the root `package.json`.
