### ISSUE TITLE
Build issue on a react native app using turborepo

### ISSUE THREAD

**Issue by divyanshunegi** [vercel/turborepo#562]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

I have a turborepo which consists of 
apps/
------/ web
------/ landing-web
------/ server
------/ mobileapp (RN)

for my setup all the other apps work fine, but React Native app throws error while building, I found out that the reason was earlier
- Podfile in iOS was not able to find node_modules folder (the reason being in turborepo the node_module folder contains the simlink, so I changed the path of node_modules on podfile in ios, pod install process worked)

- While building the iOS app, again build errors were thrown, so I changed all the paths of node_modules in the pbxproj file in ios directory which made the build process successful

- Last step when app was run it shows a red screen as `react-native` not found error on the ios device, and path of node modules is not correctly shown, as seen in this image

![image](https://user-images.githubusercontent.com/1754414/149618544-1c274b42-deac-406f-8ad7-0face9350812.png)

### Expected Behavior

The setup should build and run the react native app, and also why do we need to changed the node modules file path, cant we use the simlink for the paths ?

### To Reproduce

add a react native project in the apps directory using turborepo, try running the sample project.

**Comment by karlmarxlopez** [comment]
Have you tried/seen the metro config and other configs on this tutorial? https://dev.to/brunolemos/tutorial-100-code-sharing-between-ios-android--web-using-react-native-web-andmonorepo-4pej

**Comment by Kubessandra** [comment]
Could you share your metro.config.js and package.json ?

**Comment by 3imed-jaberi** [comment]
Mostly, you need to update your ` metro.config.js` file.

I can share with you my config which work perfectly with **Yarn Workspaces (yarn 1)**!
So, If you use TurboRepo with Yarn Workspaces (yarn 1), probably it's work too!

```js
// `metro.config.js` file
const exclusionList = require('metro-config/src/defaults/exclusionList');
const {
  getMetroTools,
  getMetroAndroidAssetsResolutionFix,
} = require('react-native-monorepo-tools');

const monorepoMetroTools = getMetroTools();

const androidAssetsResolutionFix = getMetroAndroidAssetsResolutionFix();

module.exports = {
  transformer: {
    // Apply the Android assets resolution fix to the public path...
    publicPath: androidAssetsResolutionFix.publicPath,
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  server: {
    // ...and to the server middleware.
    enhanceMiddleware: middleware => {
      return androidAssetsResolutionFix.applyMiddleware(middleware);
    },
  },
  // Add additional Yarn workspace package roots to the module map.
  // This allows importing importing from all the project's packages.
  watchFolders: monorepoMetroTools.watchFolders,
  resolver: {
    // Ensure we resolve nohoist libraries from this directory.
    blockList: exclusionList(monorepoMetroTools.blockList),
    extraNodeModules: monorepoMetroTools.extraNodeModules,
  },
};
``` 

> Note: also you need to use the [`nohoist`](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) to keep the react-native module on the same level as your mobile workspace.

**Comment by nathanhammond** [comment]
Configuration of Metro is the correct solution, the incompatibility is not with React Native and Turborepo, it's between React Native/Metro and the package manager's workspaces setup.

I'm closing this bug. Thank you @3imed-jaberi for sharing your configuration!

**Comment by wmonecke** [comment]
Hello guys, 

I am having a hard time adding react-native to my `turborepo` starting template.

What I've done:

1. Created a new monorepo using `npx create-turbo@latest`
2. `cd` into `apps` and start a new react-native project called "mobile" (i.e. `npx react-native init mobile`)

It just throws an error that it is unable to find some packages. I see that some packages which should be in the `mobile/node-modules` directory are now at the root node_modules.

What am I doing wrong here? I cant seem to find a RN starter without expo.

**Comment by daviddripps** [comment]
@wmonecke - did you add `nohoist` to your `package.json` as @3imed-jaberi mentioned above? For a simple project, this should do the trick...

```
{
  "workspaces": {
    "nohoist": [
      "react-native",
      "react-native/**"
    ]
  }
```
