### ISSUE TITLE
Next.js build fails when 'outputStandalone' experimental feature is enabled

### ISSUE THREAD

**Issue by malithmcr** [vercel/turborepo#565]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

First off, thank you for the great product. 

I just started a brand new project with turborepo and wanted to use 'outputStandalone' experimental feature. The reason to use this feature is my docker images are too big without it. 

My next.config.js file is like this:
```

const withTM = require("next-transpile-modules")(["ui"]);

module.exports = withTM({
  reactStrictMode: true,
  experimental: {
    outputStandalone: true,
  },
});

```

Screenshot
<img width="1568" alt="Screenshot 2022-01-16 at 19 49 30" src="https://user-images.githubusercontent.com/4549859/149673716-acbe5ca6-0ce8-4c1a-b471-da7f0e9c1420.png">

### Expected Behavior

Successful build 

### To Reproduce

Create a new project with Turborepo then enable  'outputStandalone: true'

**Comment by m4tta** [comment]
Encountering the same thing but in a NX monorepo

**Comment by marcelltoth** [comment]
Have you read the [*Caveats* section here](https://nextjs.org/docs/advanced-features/output-file-tracing#caveats)?

You probably need to set `outputFileTracingRoot` in case you havent

**Comment by jaredpalmer** [comment]
@marcelltoth is correct. See the caveats section linked. Going to close this one.
