### ISSUE TITLE
Quotes around true in private field causes an error

### ISSUE THREAD

**Issue by Jytesh** [vercel/turborepo#573]
### What version of Turborepo are you using?

1.0.28

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

 ERROR  package.json: json: cannot unmarshal string into Go struct field PackageJSON.private of type bool
 
 When package.json has 
 `{ "private": "true"}`
 
 `{ "private": true }` works as expected

### Expected Behavior

To not error out, and carry out the same behaviour as `{ "private": true }`

### To Reproduce

package.json
```
{ "private": "true" }
```

**Comment by Xenfo** [comment]
Private is supposed to be a boolean set `"private": true`. https://docs.npmjs.com/cli/v8/configuring-npm/package-json#private

**Comment by gsoltis** [comment]
I think @Xenfo is right, `"private": "true"` is technically an invalid `package.json` and the solution is to use a valid `package.json`. I'm happy to revisit if there's a compelling reason for needing to support this particular exception.
