### ISSUE TITLE
Add descriptions to docs pages for SEO

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#576]
### Describe the feature you'd like to request

Add SEO `description` to frontmatter each `.mdx` page in [`docs/pages`](https://github.com/vercel/turborepo/tree/main/docs/pages/docs). As you can below `description` and subsequently `og:description` HTML meta tags are empty at the moment...

<img width="822" alt="CleanShot 2022-01-20 at 10 17 16@2x" src="https://user-images.githubusercontent.com/4060187/150367179-08675d2d-1b29-45e0-a692-f673e82df6c0.png">

### Describe the solution you'd like
Add `description` to MDX frontmatter:

```diff
---
title: Some page title
+ description: Some description for search engines
---
```

The description will then show up on Google and thus need to be SEO-friendly. They should be between 50 and 160 characters. See moz link about descriptions: https://moz.com/learn/seo/meta-description

### Describe alternatives you've considered

N/A

**Comment by becca** [comment]
@molebox is this something the docs team can help us with, by chance? looks like a great win for our customers

**Comment by MaedahBatool** [comment]
PR submitted https://github.com/vercel/turborepo/pull/614
