### ISSUE TITLE
Can't add npm package to default turborepo demo app

### ISSUE THREAD

**Issue by rdickert** [vercel/turborepo#590]
### What version of Turborepo are you using?

1.0.28

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Using `npm install --save` in an app directory breaks the app.

npm version: 8.1.0
node v17.0.1

### Expected Behavior

App adds my npm package and runs as expected. 

My same repro process substituting `yarn add` seems to work as I'd expect. Maybe I will just use yarn for now.

Am I using it wrong? This is my first time with a lerna-style monorepo. Maybe I did something dumb... I did spend a decent amount of time trying to make things work. 

### To Reproduce

Repro on an arm mac:

1. `npx create-turbo@latest repro `
2. `cd repro`
3. `npm run dev` #  localhost:3000 works shows the button
4. `cd apps/web`
5. `npm install --save lodash` # or any package, maybe. NPM logs some unexpected vulnerability warnings
6. `cd ../..`
7. `npm run dev`

```bash
➜  repro git:(main) ✗ npm run dev

> turborepo-basic-shared@0.0.0 dev
> turbo run dev --parallel

• Packages in scope: config, docs, tsconfig, ui, web
• Running dev in 5 packages
web:dev: cache miss, executing c1f130393f1650f9
docs:dev: cache miss, executing a8f7e1f878ade6d8
web:dev:
web:dev: > web@0.0.0 dev
web:dev: > next dev
web:dev:
docs:dev:
docs:dev: > docs@0.0.0 dev
docs:dev: > next dev --port 3001
docs:dev:
docs:dev: ready - started server on 0.0.0.0:3001, url: http://localhost:3001
web:dev: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
docs:dev: info  - automatically enabled Fast Refresh for 1 custom loader
docs:dev: event - compiled client and server successfully in 206 ms (158 modules)
web:dev: info  - automatically enabled Fast Refresh for 1 custom loader
web:dev: event - compiled client and server successfully in 991 ms (158 modules)
web:dev: wait  - compiling /_error (client and server)...
web:dev: event - compiled client and server successfully in 34 ms (159 modules)
web:dev: wait  - compiling / (client and server)...
web:dev: error - ../../packages/ui/Button.tsx
web:dev: Module parse failed: Unexpected token (3:9)
web:dev: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
web:dev: | import * as React from "react";
web:dev: | export const Button = () => {
web:dev: >   return <button>Boop</button>;
web:dev: | };
web:dev: |
web:dev: (node:16641) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
web:dev: (Use `node --trace-deprecation ...` to show where the warning was created)
web:dev: info  - automatically enabled Fast Refresh for 1 custom loader
```

**Comment by jaredpalmer** [comment]
@rdickert unfortunately unlike yarn and pnpm, npm doesn't autodetect that it is in a workspaces monorepo when you run `npm install` from a subdirectory. We have been in contact with the npm tam and they are going to fix this behavior soon. 

cc @nlf

**Comment by rdickert** [comment]
@jaredpalmer Thanks for the rapid and helpful response!
