### ISSUE TITLE
Cannot search in docs

### ISSUE THREAD

**Issue by Xenfo** [vercel/turborepo#615]
### What version of Turborepo are you using?

N/A

### What package manager are you using / does the bug impact?

N/A

### What operating system are you using?

Other

### Describe the Bug

I can’t search in docs, it’s always loading. I don’t think Vercel ENV vars were updated when docs were upgraded.

### Expected Behavior

To be able to search.

### To Reproduce

N/A

**Comment by jaredpalmer** [comment]
We are investigating as we speak. @shuding
