### ISSUE TITLE
[turbopack] NextJs 14 An issue occurred while parsing a tsconfig.json file. extends doesn't resolve correctly

### ISSUE THREAD

**Issue by ShravanSunder** [vercel/turborepo#6298]
### What version of Turborepo are you using?

nextjs 14

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

After upgrading to nextjs 14, i'm getting this issue with my tsconfig

An issue occurred while parsing a tsconfig.json file.
extends doesn't resolve correctly

here is the tsconfig
```ts
{
  "extends": "@askluna/configs/tsconfig.base.json",
	"compilerOptions": {
		"target": "ESNext",
		"lib": ["dom", "dom.iterable", "esnext"],
		"allowJs": true,
		"checkJs": true,
		"skipLibCheck": true,
    "strict": true,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "preserve",
		"incremental": true,
		"noUncheckedIndexedAccess": true,
		"baseUrl": ".",
		"paths": {
      "~core/*": ["../../packages/askluna-core/src/*"],
      "~ui/*": ["../../packages/askluna-ui/src/*"],
      "~~/*": ["./src/*"],
    },
		"plugins": [{ "name": "next" }]
	},
	"include": [
		".eslintrc.cjs",
		"next-env.d.ts",
		"**/*.ts",
		"**/*.tsx",
		"**/*.cjs",
		"**/*.mjs",
    // "../../packages/**/src/**/*",
		".next/types/**/*.ts",
	],
}

```

here is next config
```ts

await import('./src/env.mjs');

/** @type {import("next").NextConfig} */
const config = {
	// pageExtensions: ['js', 'jsx', 'ts', 'tsx', 'md', 'mdx'],
	transpilePackages: ['@askluna/core', '@askluna/ui'],
	reactStrictMode: true,

	// @ts-ignore
	webpack: (wbconfig, options) => {
		// /** @type {import("webpack").Configuration} */
		const config = wbconfig;

		config.resolve.fallback = {
			...config.resolve.fallback,
			fs: false, // the solution
		};
		config.resolve.alias = {
			...config.resolve.alias,
		};

		return config;
	},

	// typedRoutes: true,
	experimental: {
		swcPlugins: [],
		forceSwcTransforms: true,
		taint: true,
		turbo: {
			resolveAlias: {
				fs: './src/empty.ts',
			},
			rules: {
				// Option-less format
				'*.mdx': ['@mdx-js/loader'],
			},
		},
	},
};

export default config;
```

### Expected Behavior

extends should work with nextjs 14 turborepo

### To Reproduce

try a nextjs monorepo with tsconfig extends

<sub>[PACK-2505](https://linear.app/vercel/issue/PACK-2505/[turbopack]-nextjs-14-an-issue-occurred-while-parsing-a-tsconfigjson)</sub>

**Comment by steveafrost** [comment]
I'm also experiencing this issue and what I noticed is it is particular to `next dev --turbo`. When the dev server is started _without_ the turbo flag, the tsconfig is read as expected.

**Comment by ShravanSunder** [comment]
Yes, my project worked on next 13 turbo. It works on next 14 webpack.

**Comment by 7iomka** [comment]
I didn't have it working correctly on version 13 either.
I had to copy the settings to each package or app

**Comment by Warmachine13** [comment]
same problem maybe some extra config on experimental

**Comment by cdaringe** [comment]
Would be great to get some debug info outta https://github.com/vercel/turbo/blob/3d44253bd9519ea0a551349c5bc3dffa36ac0538/crates/turbopack-ecmascript/src/typescript/resolve.rs#L105. It's yielding failures for me with `../../tsconfig.json`, which resolves in no-turbo mode (and just by plain inspection 😄, and cmd+click)!

**Comment by wadefletch** [comment]
I am also having this problem, though it only occurs when I add a file with `"use server"`.

**Comment by astrooom** [comment]
Same exact issue here.

**Comment by maloyuso** [comment]
Same issue here only when using `next dev --turbo`

**Comment by SunHuawei** [comment]
> Would be great to get some debug info outta
> 
> https://github.com/vercel/turbo/blob/3d44253bd9519ea0a551349c5bc3dffa36ac0538/crates/turbopack-ecmascript/src/typescript/resolve.rs#L105
> 
> . It's yielding failures for me with `../../tsconfig.json`, which resolves in no-turbo mode (and just by plain inspection 😄, and cmd+click)!

I debugged it on my local. It resolves the tsconfig.json file with this line, and the path seems good. https://github.com/vercel/turbo/blob/3d44253bd9519ea0a551349c5bc3dffa36ac0538/crates/turbopack-ecmascript/src/typescript/resolve.rs#L144

I also created a new project with `npx create-next-app@latest`, I tried 
```
"extends": "./node_modules/which-collection/tsconfig.json",
```

and add `use server`, but I still cannot reproduce the issue. That would be helpful if anyone could provide a way to reproduce it.

**Comment by inceenes10** [comment]
I'm having difficulty pinpointing the exact conditions that trigger the problem.

Would it be possible for you to provide some guidance on how to effectively reproduce the issue? Any additional insights or steps you could offer would be helpful.

I upgraded nextjs version to 14.2.2, the error message is like below with turbo mode open.

<img width="962" alt="image" src="https://github.com/vercel/turbo/assets/24212049/aa75ee63-c4d7-46da-a534-07ecb248cb84">

**Comment by danilodecanini** [comment]
Same issue here only when using next dev --turbo

**Comment by chris-olszewski** [comment]
Closing as Turbopack as [moved homes](https://vercel.com/blog/turbopack-moving-homes)

**Comment by amitav13** [comment]
@chris-olszewski How are github issues to be treated? Should they be reopened with a link to this one in the nextjs repo?

**Comment by pippinmole** [comment]
> Closing as Turbopack as [moved homes](https://vercel.com/blog/turbopack-moving-homes)

That's fine, but it's also still an issue. Is there an existing issue open for this?

**Comment by devniel** [comment]
Hello, same issue here, the extends reference is not resolved when using `next dev --turbo`, if we remove `--turbo` it works as expected.

**Comment by geekysaurabh001** [comment]
Version 16.1.4. turbo pack issue still persists even after 2 years.

**Comment by JoshFransix** [comment]
mehhnn, no actual solution yet... been tryna solve this
