### ISSUE TITLE
turbo depends on package.json

### ISSUE THREAD

**Issue by jcayzac** [vercel/turborepo#641]
### What version of Turborepo are you using?

1.1.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

`turbo` fails when the repo contains a `package.yaml` instead of a `package.json`, which is allowed when using `pnpm`.

> ```
> ERROR  package.json: open package.json: no such file or directory
> ```

Is there any reason why `turbo` requires `package.json`, given its configuration lives in `turbo.json` ?

### Expected Behavior

`turbo` only depends on `turbo.json`, and works fine with `pnpm` when using a `package.yaml`.

### To Reproduce

```sh
npx create-turbo@latest
# select pnpm as a package manager
# cd into the created repo

mv package.json package.yaml
turbo run build
```

**Comment by Xenfo** [comment]
We still use `package.json` to get other properties of your packages such as their name.

**Comment by jaredpalmer** [comment]
We don't support `package.yaml`, I don't think we will either as its non-standard (despite pnpm supporting it). Perhaps we should add documentation about this decision

**Comment by jcayzac** [comment]
FWIW it'd be trivial to support using `@pnpm/read-project-manifest`:

```ts
import readProjectManifest from '@pnpm/read-project-manifest'
const { manifest, fileName } = await readProjectManifest(process.cwd())
```
