### ISSUE TITLE
with-pnpm template and an api server using prisma produces an unsupported url type error

### ISSUE THREAD

**Issue by RomanMunar** [vercel/turborepo#647]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Using the with-pnpm template with primsa and running pnpx prisma generate causes an `Unsupported URL Type "workspace:": workspace:*` error

This issue might be related to [issue#546](https://github.com/vercel/turborepo/issues/546)
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

[log.txt](https://github.com/vercel/turborepo/files/7970194/log.txt)

### Expected Behavior

Be able to run prisma commands

### To Reproduce

I've created a reproduction repo for this.
run the commands below to see the error
`cd apps/api`
`pnpx run prisma generate`

[turborepo-pnpm-prisma-bug](https://github.com/RomanMunar/turborepo-pnpm-prisma-bug)

**Comment by RomanMunar** [comment]
yarn does not seem to have this error. will be using it for now.

**Comment by weyert** [comment]
You are using npm instead of Pnpm?

**Comment by weyert** [comment]
Even using yarn in api apps directory. Probably want to make sure you are using Pnpm everywhere

**Comment by RomanMunar** [comment]
the yarn template I mean. does not have the error. I'm only using pnpm. even aliased it to npm 😅

**Comment by RomanMunar** [comment]
Finally got the time to look more in to this issue.
The solution is to manually specify the output of prisma client

```js
// apps/api/prisma/schema.prisma
generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/prisma/prisma-client"
}
```
