### ISSUE TITLE
Add support for yarn berry v3 with PnP as install strategy  

### ISSUE THREAD

**Issue by wdfinch** [vercel/turborepo#693]
### Describe the feature you'd like to request

I would like to be able to use this tool with yarn berry v2/v3 as my package manager and Plug'n'Play as the install strategy.

### Describe the solution you'd like

I would like the tool to support Plug'n'Play as the install strategy when using yarn berry. 

### Describe alternatives you've considered

Using another install strategy.

**Comment by thebanjomatic** [comment]
Can we get clarification on what support needs to be added here? I have tested locally by commenting out the `util.IsNMLinker(cwd)` check, and `turbo run` works fine with yarn 3 and the pnp linker (monorepo with around 50 packages). I would imagine `turbo prune` doesn't work, but if that's the case would you be open to a pull request that moves the `isNMLinker` check into the prune command specifically to enable yarn pnp for run?

**Comment by jaredpalmer** [comment]
This is now available in `turbo run` for `turbo@1.2`+

**Comment by wdfinch** [comment]
Great news! Thanks so much for working on this.

**Comment by geekuillaume** [comment]
It seems that only the node-module linker from yarn is supported (https://github.com/vercel/turborepo/blob/c09cb4bb659645ea7bc350709f98efa6974c1b9b/cli/internal/packagemanager/berry.go#L86). This issue is related to the PnP linker so it should be re-open

**Comment by arnoudius** [comment]
Would be really nice if nodeLinker: pnp could be supported.

**Comment by HosseinAgha** [comment]
@jaredpalmer, As @thebanjomatic explained, looks like the `yarn prune` is not supported yet.  
Should we follow this up in this issue or open another issue?

**Comment by Scherebart** [comment]
Hello everyone!
Is this problem with support for yarn 3 pnp being resolved somewhere else?
Or is this subject dead for now?

Thanks!

**Comment by nathanhammond** [comment]
We currently have no plans to support Yarn 3 (Berry) in PNP mode. It was never supported (in spite of the earlier mention in this thread). The path to support for this is one of two options:

1. Open a PR. We will accept this work if done by the community and maintain it in perpetuity.
2. We're corporate-sponsored OSS. If your company needs this and is a Vercel Enterprise customer reach out through your account manager and we can start a discussion.

**Comment by Scherebart** [comment]
@nathanhammond 
Thank you for clarifying this matter for me!

**Comment by alamothe** [comment]
Yarn PNP is de facto standard for monorepos. How is it possible that it's not supported?
