### ISSUE TITLE
turborepo can't find packages in "test" directories

### ISSUE THREAD

**Issue by gavinsharp** [vercel/turborepo#695]
### What version of Turborepo are you using?

1.1.2

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

We have an NPM workspaces monorepo with a workspace named `capabilities/test`:

- `package.json`
  - `workspaces: ["capabilities/*"]`
- `capabilities/test/package.json`
  - `name: "capability-test"`

We were trying to invoke turborepo e.g. `turbo run build --scope=capability-test --no-deps`, but were very confused why it wasn't working (it would effectively ignore the `scope` parameter and build everything).

There was no debug output that explained why the `--scope` parameter was seemingly ignored.

I spotted this non-configurable list of "workspace ignore" patterns, which I suspect to be the culprit:
https://github.com/vercel/turborepo/blob/e6a88d292dfb5b8bec695e0f63f2fed8866039c3/cli/internal/context/context.go#L537

### Expected Behavior

Packages defined in directories named `test` should still be discovered by Turborepo.

Alternatively, there should be an option to configure which paths are ignored for the purposes of finding packages.

### To Reproduce

- Create a workspace that contains a package defined in a directory named `test`
- Try to invoke a build script for that package using e.g. `turbo run build --scope=capability-test`

**Comment by jaredpalmer** [comment]
Sorry for the headache. These are the same workspace ignore rules as PNPM's https://github.com/pnpm/pnpm/blob/917b95c01fd4e6b347dd6159506756693dc051ec/packages/find-packages/src/index.ts#L7

Since one of our support package managers doesn't allow this, I don't think `turbo` should. It'd be great to document this explicitly, perhaps in a new section on `Troubleshooting` @molebox

**Comment by gavinsharp** [comment]
@jaredpalmer as an NPM user, being constrained by a PNPM behaviour is offensive! 😆

I suppose ideally the ignore patterns would be conditional on the package manager in use, but I will grant this is an edge case.

Thanks for the quick response; agree that docs would be helpful, I'll just rename the code for now.

**Comment by cinan** [comment]
I had no idea packages mustn't contain `test` in their name (using yarn berry). This should be mentioned in docs.
