### ISSUE TITLE
Website search doesn't work

### ISSUE THREAD

**Issue by lostfictions** [vercel/turborepo#701]
### What version of Turborepo are you using?

n/a

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Other

### Describe the Bug

Hi, the searchbox on the website doesn't work for me, in either Chrome or Firefox. Seems to be the same issue as #649 / #615 -- I see the same output in my console. From a comment on #649 it seems like that was marked as fixed but maybe never actually fixed?

### Expected Behavior

Searchbox shows results, doesn't throw an error on hitting return key.

### To Reproduce

Focus searchbox, try typing anything, try hitting return

**Comment by jaredpalmer** [comment]
@shuding

**Comment by jaredpalmer** [comment]
Fixed now. Thanks for report. Much appreciated!
