### ISSUE TITLE
[WARNING] Did not find "packageManager" in your package.json. Please run "npx @turbo/codemod add-package-manager"  ERROR  could not check if yarn is berry: could not detect yarn version: exit status 126

### ISSUE THREAD

**Issue by mven** [vercel/turborepo#707]
### What version of Turborepo are you using?

1.1.2

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Environment:

```
Node 16.13.2
NPM: 8.4.1
```

I'm setting up turborepo on an **existing** NPM + Lerna monorepo. I've followed the docs and have a proper `turbo.json` in the root. When I try to run my `npm run build` (script aliased to: `turbo run build`) I get the following error:

```sh
[WARNING] Did not find "packageManager" in your package.json. Please run "npx @turbo/codemod add-package-manager"
 ERROR  could not check if yarn is berry: could not detect yarn version: exit status 126
```

In the first line about `packageManager`, I ran `npx @turbo/codemod add-package-manager` and nothing happened. I ran it twice to be sure. I ended up investigating a bit more and found a relatively new ([experimental](https://nodejs.org/api/packages.html#packagemanager)) property as of Node `v16.9` that wasn't in my `package.json`. I've since added `"packageManager": "8.4.1"` to my `package.json` and now turborepo successfully builds. 

Comments I had regarding each line:

1) `[WARNING] Did not find "packageManager" in your package.json. Please run "npx @turbo/codemod add-package-manager"` 

The turborepo documentation doesn't mention `packageManager` property. Since it's an [experimental property](https://nodejs.org/api/packages.html#packagemanager) should turborepo require it to be in a `package.json` in order to run it? The console shows a warning, yet the build is breaking. Perhaps the build is breaking due to the next line.

2)  `ERROR  could not check if yarn is berry: could not detect yarn version: exit status 126`

I'm running strictly `npm` and `lerna`. `yarn` doesn't exist in this project, so it looks like it's erroneously detecting I have `yarn`.

Here's my `turbo.json`

```json
{
  "baseBranch": "origin/primary",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"]
    },
    "test": {
      "dependsOn": ["^build"],
      "outputs": []
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "cache": false
    }
  }
}

```

### Expected Behavior

Following the Turborepo  [Getting Started](https://turborepo.org/docs/getting-started#npm) page, I should be able to run `turbo run build` and it should kick off the build process without any errors or warnings that break the build. It should also properly recognize that I have `npm` and not `yarn`.

### To Reproduce

Follow the [Getting Started](https://turborepo.org/docs/getting-started#npm) guide to set up Turborepo on an existing `npm` repo.

**Comment by s10mcow** [comment]
Docs have the fix...

https://turborepo.org/docs/reference/codemods#add-package-manager

**Comment by jaredpalmer** [comment]
`"packageManager": "npm@8.4.1"`

**Comment by kevinsimper** [comment]
@jaredpalmer The examples does not contain that :)

**Comment by stephyswe** [comment]
This should be fixed or give some good advice. 

As a normal dev-user. I went into the turbo-repo, found the 'basic' example and copied it to my system. I did as suggested in the README. Yarn to install packages. then i tried to tried to run "yarn run dev" - and it did work but I ended up with the following message

```
$ yarn run dev
yarn run v1.22.17
$ turbo run dev --parallel
[WARNING] Did not find "packageManager" in your package.json. Please run "npx @turbo/codemod add-package-manager"
```

so as described i ran "npx @turbo/codemod add-package-manager" and did yarn run dev install again, and still got the same warning message. And coming here to look at issues to find a fix. It stands you should add "packageManager": "npm@8.4.1"
to the package.json in root directory I assume.

Q. Why would we add npm as packageManager and still use yarn to install the node_modules?
