### ISSUE TITLE
scope/ignore with many tasks not working

### ISSUE THREAD

**Issue by morriq** [vercel/turborepo#715]
### What version of Turborepo are you using?

1.12

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

We have issue with skiping som projects while running commands.

works well:
`pnpm turbo run lint --scope="packages/**/*"`

takes all projects from monorepo
`pnpm turbo run lint build --scope="packages/**/*"`

### Expected Behavior

`pnpm turbo run lint build --scope="packages/**/*"`

respects scope/ignore argument

### To Reproduce

1. `npx create-turbo@latest` with pnpm
2. `pnpm turbo run lint build --scope="packages/**/*"`

**Comment by morriq** [comment]
Actually ... repo created from `npx create-turbo` not respects even single commands: `pnpm turbo run lint  --scope="packages/**/*"`

prints: `• Packages in scope: config, docs, tsconfig, ui, web

**Comment by jaredpalmer** [comment]
Thanks for the write up and sorry for the confusion. `--scope` flag filtering against `name` keys in `package.json`s and not the filesystem paths

`turbo` should throw a better error message here. Closing in favor of #716

**Comment by morriq** [comment]
@jaredpalmer I can't agree. So why this command behaves diffrent when run single command:
`pnpm turbo run lint --scope="packages/**/*"`

vs 

`pnpm turbo run lint build --scope="packages/**/*"`

first takes less amount of projects.

---

ANYWAY

the same scenario is with usage 
`pnpm turbo run lint build --ignore="packages/**/*"`

```
• Packages in scope: config, docs, tsconfig, ui, web
• Running build, lint in 5 packages
```

**Comment by fz6m** [comment]
I'm also having this problem
Any `--ignore` option will not work

**Comment by danielweck** [comment]
Yep, this older issue is still relevant:
https://github.com/vercel/turborepo/issues/445#issuecomment-1058900760
