### ISSUE TITLE
Global dependencies always cause tree walk

### ISSUE THREAD

**Issue by madcowfred** [vercel/turborepo#720]
### What version of Turborepo are you using?

1.1.2

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

If a `globalDependencies` entry is a single file (in our case a base tsconfig), it [still causes a full tree walk](https://github.com/vercel/turborepo/blob/0c24f5a620c4429809714616aec358f8bf560af7/cli/internal/context/context.go#L176). On Linux machines (tested under WSL2 on Windows and a bare metal Linux machine) this is quite performant (300-500ms overhead), but much slower on the OS X machines we use (~5-10s overhead depending on model). Removing `globalDependencies` makes a very noticeable improvement to any invocation of `turbo`.

### Expected Behavior

A single file global dependency (no `$` and no glob wildcard characters) should only check for that file, not initiate a full tree walk.

### To Reproduce

On OS X, add some files to `globalDependencies` and compare build times with and without. Our repository is private and I'm not sure how to go about creating a large enough test case.

**Comment by jaredpalmer** [comment]
Thanks for the writeup. We should fix this

**Comment by mcrowder65** [comment]
Just noticed this today.

Adding globalDependencies to this small turborepo example https://github.com/mcrowder65/turborepo-example

Running with cached builds take about ~1 second with a global dependency listed

Running with cached builds without global dependencies: ~0.30 seconds

**Comment by Kingwl** [comment]
## With `globalDependencies`
<img width="324" alt="image" src="https://user-images.githubusercontent.com/6831019/163940442-5a8642d1-d84f-4dfb-8bcf-72135e24cd97.png">

<img width="395" alt="image" src="https://user-images.githubusercontent.com/6831019/163940364-3a372595-b379-4606-a295-3439e768fd43.png">

## Without `globalDependencies`
<img width="372" alt="image" src="https://user-images.githubusercontent.com/6831019/163940518-45b0e4cd-ff74-4d93-8832-0b45924155e7.png">

It's impacted a tons of performance.
