### ISSUE TITLE
Unable to remove files from affecting scope with `--ignore=`

### ISSUE THREAD

**Issue by glesperance** [vercel/turborepo#728]
### What version of Turborepo are you using?

1.1.3-canary.1

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

The `--ignore` argument is not effective at removing files from affecting the cache hash / scope.

I want to use `--ignore="**/*` to allow me to cache a build based solely on the files and environment variables I choose. Not on the entire content of the package.

### Expected Behavior

Files ignored by the `--ignore=**/*` glob should not affect cache hash / scope.

### To Reproduce

1. `$ npx create-turbo@latest`
2. `$ cd my-turborepo`
3. `$ yarn turbo run build`
4. `$ touch apps/web/new-file.txt`
5. `$ yarn turbo run build --ignore="**/*" --scope=web` 

(5) should not result in a cache miss.

**Comment by ragrag** [comment]
this issue has been a huge blocker for me to migrate to Turborepo at my org, would love to see it
hopefully getting fixed or resolved with https://github.com/vercel/turborepo/pull/81 which looks very promising

**Comment by glesperance** [comment]
@ragrag Just saw that you mentioned some "scope" + "ignore" hacks[1]. Do you think there is any way to get to my use case with those? It would help to have this until #81 is done.

[1] https://github.com/vercel/turborepo/pull/81#issuecomment-1036845898

**Comment by ragrag** [comment]
@glesperance the only way it can currently be done (as far as I know of) is to explicitly specify each package you intent to run the script on with --scope,
e.g
--scope="pkg1" --scope="pkg2" --scope="pkg3" ..etc

**Comment by glesperance** [comment]
Yeah. Ok that confirms what i found as well. We're going to have to wait for #81.

**Comment by jaredpalmer** [comment]
We've refactored `--ignore` and introduced `--filter` in `turbo` v1.2. See https://turborepo.org/docs/features/filtering for more info. It should work as expected now.
