### ISSUE TITLE
Post-cache scripts

### ISSUE THREAD

**Issue by rafaeltab** [vercel/turborepo#731]
### Describe the feature you'd like to request

I would like to be able to specify scripts that run after cache was used in a pipeline.

For example, if you have a pipeline that runs a docker build and saves the output to a directory as a tarbal, I would like to be able to load this image from the file system if it was restored using cache.

### Describe the solution you'd like

I would like an optional field in pipelines that allow post-cache scripts. It could look as follows:

```json
{
    "pipeline": {
        "build-docker": {
            "output": [
                "docker/build/build.tar"
            ],
            "post-cache-scripts": [
                "load-docker"
            ]
        }
    }
}
```

The `load-docker` script would then exist on the `package.json` of the respective project. For this example it would look like this:
`docker load -i ./docker/build/build.tar` this would load the docker image into the docker environment.

It may be a good idea to add it on the cache field as follow:
```
{
    "pipeline": {
        "build-docker": {
            "output": [
                "docker/build/build.tar"
            ],
            "cache": {
                "post-scripts": [
                    "load-docker"
                ]
            }
        }
    }
}
```

### Describe alternatives you've considered

For the example I provided the only alternative would be not using cache. Sine turbo can not load the docker image again.

Another alternative is writing a script that takes the output of the turbo command and checks if it contains FULL TURBO, then if it does run the command. This would not work for specific projects, there may be some workaround that would work for individual projects.

**Comment by gsoltis** [comment]
Would it be possible to split your task into two steps, one to build and one to load, and mark the loading step as not cacheable?

**Comment by rafaeltab** [comment]
Of course, in this specific case, it may be possible to work around it, this is actually the way I solved it for myself. However, there are cases where you would want to only run it for the cached scripts and not the normally executed scripts. 

The example was purely for an example of how this feature could be applied.

**Comment by jaredpalmer** [comment]
Agree with @gsoltis, I would express `load` as a separate task, otherwise it is modeled as a side effect. Going to close for now, but perhaps we'll revisit in future if more concrete use cases come up that don't fit the current model.
