### ISSUE TITLE
Does Turborepo plan to provide a JavaScript API?

### ISSUE THREAD

**Issue by WJCHumble** [vercel/turborepo#746]
### Describe the feature you'd like to request

Provide a JavaScript API.

### Describe the solution you'd like

For example:

```javascript
import Turbo from "turbo"

const turbo = new Turbo(config)
turbo.run(command, option)
```

### Describe alternatives you've considered

None.

**Comment by jaredpalmer** [comment]
Yes, it's something we'll likely expose after our performance refactor which will leverage a daemon + rpc service which can then be called from multiple languages/other processes
