### ISSUE TITLE
Move to pflag/viper or cobra

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#759]
### Describe the feature you'd like to request

Because we manually parse CLI args, users are getting stuck with the inflexible syntax. 

See #758 
### Describe the solution you'd like

Switch to viper and pflags for config and flags parsing 

Or

Switch to Cobra and drop mitchelh/cli. This would also let us auto generate documentation

### Describe alternatives you've considered

N/A

**Comment by Xenfo** [comment]
I'd be willing to work on this.
