### ISSUE TITLE
Ability to set concurrency to max (equal to CPU cores) `--concurrency=max`

### ISSUE THREAD

**Issue by moltar** [vercel/turborepo#761]
### Describe the feature you'd like to request

I am not an expert in this area, but I think it's counter-productive to set the concurrency to a higher number than there are CPU cores available for CPU-hungry processes, like tests and builds, as these processes would be competing for resources.

Thus, a default setting of 10 might be counter-productive in certain environments, like CI, where the number of cores can be lower.

For example, [GitHub Actions](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) only have 2 cores available for Windows and Linux, yet 3 for macOS.

### Describe the solution you'd like

I think there should be a way to specify "max" or some other variation of that, that signals Turbo to sniff out the number of cores and set the concurrency to that value.

### Describe alternatives you've considered

```sh
turbo run build --concurrency=$(node -r os -e 'process.stdout.write(os.cpus().length.toString())')
```

**Comment by marcelltoth** [comment]
In my opinion it would probably be even better if we could set the global default using an environment variable. I'm sure many people are like us: we have a long and complex CI pipeline with lots of jobs, adding `--concurrency` everywhere is cumbersome. 

It would be much simpler if we could specify e.g. `TURBO_DEFAULT_CONCURRENCY=4` globally, then we
1. wouldn't have to litter the CI config file with `--concurrency` settings everywhere.
2. would have a single place to change in case I were to change the executor size.

Note that simply changing turbo's default to the CPU count (like `jest` does for example) **is not adequate**, as some CI providers like CircleCI always show a lot of CPU cores (32 in CCI's case), regardless of the actually available size.

**Comment by moltar** [comment]
I think these are separate features and both have the place.
