### ISSUE TITLE
Docs: Explain how workspaces work

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/turborepo#784]
Add a page about what `yarn`, `pnpm`, and `npm` workspaces are and how they work. It should explain:

- What are workspaces?
- Why would you use them?
- How do they work?
- How do they relate to `turbo`?

**Comment by mehulkar** [comment]
Does this cover most things? https://turborepo.org/docs/guides/workspaces cc @mattpocock 

First added in https://github.com/vercel/turborepo/pull/884

**Comment by mehulkar** [comment]
The handbook does a pretty good job I think: https://turborepo.org/docs/handbook/workspaces
