### ISSUE TITLE
dependsOn from a root task

### ISSUE THREAD

**Issue by shanecash** [vercel/turborepo#7899]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/shaneuuid/turborepo-dependson-bug

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

turbo@1.13.3-canary.0

### Describe the Bug

This bug was mentioned in a previous discussion but an issue wasn't opened: #1745 

A root task `//#` cannot depend on a workspace task without erroring.

Given a turbo.json of this:
```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "//#pre-build": {
      "dependsOn": []
    },
    "build": {
      "dependsOn": ["//#pre-build", "^build"]
    },
    "//#pre-dev": {
      "dependsOn": ["build"]
    },
    "dev": {
      "dependsOn": ["//#pre-dev"]
    }
  }
}
```

And a root package.json of this:
```json
{
  "name": "turborepo-dependson-bug",
  "version": "1.0.0",
  "scripts": {
    "pre-build": "node -e \"console.log('Ran pre-build')\"",
    "build": "turbo run build",
    "pre-dev": "node -e \"console.log('Ran pre-dev')\"",
    "dev": "turbo run dev"
  },
  "workspaces": [
    "packages/*"
  ],
  "license": "ISC",
  "dependencies": {
    "turbo": "^1.13.3-canary.0"
  }
}
```

Running `npm run dev` will result in this error:
![Screenshot from 2024-04-03 13-17-16](https://github.com/vercel/turbo/assets/95544653/fcfedea5-11fb-4822-b271-ff7356e2a089)

From my understanding, it should run?

### Expected Behavior

See above.

### To Reproduce

See above.

**Comment by anthonyshew** [comment]
This is working correctly. Tasks without a `^` refer to tasks within the same entity (package or Workspace root).

In the case of a Root Task, `build` would refer to a `#//build` task, which the error is correctly stating doesn't exist in your `turbo.json`.
