### ISSUE TITLE
Inconsistent remote caching on Windows

### ISSUE THREAD

**Issue by GeeWizWow** [vercel/turborepo#801]
### What version of Turborepo are you using?

1.1.4

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows / Linux (WSL)

### Describe the Bug

For the same codebase:
- Windows generates different hashes to Linux
- Windows fails to leverage remote cache, where as Linux does

### Expected Behavior

- Windows should generate the same hashes as Linux or vice versa
- Windows should leverage remote cache under the same circumstances as Linux

#### Setup 

**In both a Windows and Linux environment, run the following:**

1. Run `npx create-turbo@latest` - using yarn v1 and accepting all other defaults
1. Move to `my-turborepo` and edit the package.json to contain the following:
    ```diff
    -    "build": "turbo run build"
    +    "build": "turbo run build -vvv --api=http://localhost:5001 --team=test --token=test",
    +    "clean": "rm -rf node_modules/.cache/turbo && rm -rf apps/*/.next && rm -rf apps/*/.turbo && rm -rf packages/*/dist && rm -rf packages/*/.turbo",
    ```
1. Run the following commands: `yarn clean && yarn build`
1. Run the above commands a second time once the first build has completed.

#### Observe

On Linux:

- Linux completes both builds producing the following hashes: `73f177e42dcb2bfe` and `9ddfee65314a17a0`.
- Linux uploads the artefacts from the first run to the remote cache server.
- On the second run Linux reproduces the same hashes, fetches artefacts from the remote cache server and produces a cache hit, replaying the output.

On Windows:

- Windows completes both builds producing the following hashes: `82041f42cadada82` and `5f63f7c3e391c788`.
- Windows uploads the artefacts from the first run to the remote cache server.
- On the second run Windows reproduces the same hashes, fetches artefacts from remote cache, but produces a cache miss and rebuilds the projects

**Comment by GeeWizWow** [comment]
Some further info on the caching issue, it looks like Windows is producing/ uploading invalid cache files, my remote cache server is saving the files as .tar.gz archives, opening them to inspect reveals that the linux archives contain a valid nested folder structure:

```
apps/
     docs/
          .turbo/
              turbo-build.log
          .next/
              ... .js
```

Where as windows archives contain all the files in the root of the archive with the folder structure described in the file name:

```
appsdocs.nextbuild-manifest.json
appsdocs.nextBUILD_ID
...
```

Replacing the contents of the windows created archives with the contents of the Linux created archives results in valid cache hits, and everything working as expected

**Comment by GeeWizWow** [comment]
We did some debugging this morning and tracked it down to the output of

https://github.com/vercel/turborepo/blob/c9f7264d494b8cfc1c9f1f2c0762e2a2175b725c/cli/internal/run/run.go#L655

It's producing system dependent path separators, which when passed to the tar writer 

https://github.com/vercel/turborepo/blob/c9f7264d494b8cfc1c9f1f2c0762e2a2175b725c/cli/internal/cache/cache_http.go#L61-L63

produces an invalid archive on windows.

Changing the following line to force all path separators to be Unix seems to fix the issue and produces valid archives on Windows, which are then correctly pulled and used.

```diff
// cache_http.go

import (

+ "path/filepath"

...

- if err := cache.storeFile(tw, file); err != nil {
+ if err := cache.storeFile(tw, filepath.ToSlash(file)); err != nil {
```

**Comment by thebanjomatic** [comment]
@GeeWizWow Were you planning to submit a PR for this? I have run into what appears to be the same issue on windows and recalled seeing this issue a few weeks ago.

**Comment by GeeWizWow** [comment]
Happy to if there's desire from the maintainers.

CC'ing one of the code owners for visibility @jaredpalmer
