### ISSUE TITLE
ignore flag doesn't work

### ISSUE THREAD

**Issue by fz6m** [vercel/turborepo#819]
### What version of Turborepo are you using?

1.1.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I try :

```bash
  turbo run build --ignore="**/*"
  # or
  turbo run build --ignore="*"
  # or
  turbo run build --ignore="**"
```

### Expected Behavior

I expect `turbo` should not execute `build` command, do nothing.

But `turbo` still executed `build`

### To Reproduce

...

**Comment by Chrischuck** [comment]
Same issue with Yarn.

**Comment by jaredpalmer** [comment]
--ignore command is for gitginore paths with --since flag. you can use `!` with --scope to ignore based on name

**Comment by Chrischuck** [comment]
@jaredpalmer 

`turbo run build --scope=!ignoredPackage` still builds the ignored package.

Based on what you said, are the docs not up to date?

https://turborepo.org/docs/reference/command-line-reference#--scope

https://turborepo.org/docs/reference/command-line-reference#--ignore

Thanks

**Comment by Chrischuck** [comment]
For others having this issue, the ignored package was a dependency for me, so adding the `--no-deps` flag resolved this for me.
