### ISSUE TITLE
Cannot find module 'turbo' on CI

### ISSUE THREAD

**Issue by elviocb** [vercel/turborepo#824]
### What version of Turborepo are you using?

1.1.5

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

When I run the lint locally `yarn lint` it triggers the script `lint: turbo run lint-code`, so all packages are triggered. The linter works fine. When the job is triggered from a github action it immediately fails:

```
Cannot find module 'turbo'
```

This issue is similar to this one: https://github.com/vercel/turborepo/issues/820

In this case updating to `1.1.5` didn't solve the issue

### Expected Behavior

turbo commands work on github actions

### To Reproduce

Try to run any turbo command on a github action

**Comment by elviocb** [comment]
I found the issue. I was setting the `yarn` flag `--ignore-optional`when installing the dependencies on ci and turns out that turbo is installed as an optional dependency:

<img width="531" alt="Screen Shot 2022-03-04 at 19 56 38" src="https://user-images.githubusercontent.com/6453211/156853485-80a8bc97-3a14-4c98-aa15-2a6ae638b3d5.png">

I removed the flag when running `yarn install` and everything works fine.

**Comment by rosskuyper** [comment]
I ran into this issue and in the end I discovered that I had installed pnpm 6 via the installation instructions for `node.js is not preinstalled` when it was. I'm assuming there was then a node version mismatch going on somewhere. Installing so that it would use the system node fixed the issue.

**Comment by mlynch** [comment]
I had a similar issue in both CI and locally when using npm (not yarn), after updating node/npm and turbo to latest, it's working again.

**Comment by imjordanxd** [comment]
@joshmanders did you ever find a solution? This keeps popping up and it's beginning to get quite frustrating.

**Comment by joshmanders** [comment]
> @joshmanders did you ever find a solution? This keeps popping up and it's beginning to get quite frustrating.

I don't remember, haven't ran into this issue in a while.

**Comment by mkwhalen** [comment]
Making turbo the first in the list of devDependecies worked for me

**Comment by sebasfavaron** [comment]
Had an issue like this too and downgrading node from v18.12.0 -> v16.18.0 worked for me

**Comment by nathanhammond** [comment]
Every single one of you posting about this makes me believe that you were encountering a cache issue.

For future travelers: if you encounter this please make sure you perform a test without any cached modules on the system.
