### ISSUE TITLE
Can't select clean log output

### ISSUE THREAD

**Issue by kossnocorp** [vercel/turborepo#8306]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

NA

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Other

### Which canary version will you have in your reproduction?

NA

### Describe the Bug

The new terminal UI does not allow you to select a clean log output. It adds the left frame, so multiline log output will contain noise in the best case or be broken (i.e., JSON).

### Expected Behavior

I can select a log output without extra symbols.

### To Reproduce

Try selecting log with the new terminal UI.

### Additional context

Anthony asked me to open the issue: https://x.com/anthonysheww/status/1798157868824404247

**Comment by chris-olszewski** [comment]
This is something we want to get to, but it might take a little bit of time to get to since it requires us to reimplement mouse selection to respect the task output pane's boundaries.

**Comment by ryantbrown** [comment]
Are there any workarounds or anything we can do in the meantime?

**Comment by chris-olszewski** [comment]
This was fixed in https://github.com/vercel/turborepo/pull/8713 and released in [2.0.10](https://github.com/vercel/turbo/releases/tag/v2.0.10)
