### ISSUE TITLE
Docs: with-docker example apk update before apk add

### ISSUE THREAD

**Issue by danielwarke** [vercel/turborepo#8339]
### What is the improvement or update you wish to see?

The Dockerfiles in the with-docker example show the following code: 
```
RUN apk add --no-cache libc6-compat
RUN apk update
```
I'm no alpine expert, but from what I understand it doesn't make any sense to run `apk update` after `apk add`. The alpine wiki [specifically mentions that you should run `apk update` before `apk add`](https://wiki.alpinelinux.org/wiki/Alpine_Package_Keeper#Update_the_Package_list). 
Our [linter has caught this](https://rules.sonarsource.com/docker/RSPEC-6595/) and warns that performing the operations this way can increase the Docker image size. 
Is there a reason for performing these commands in this order? If so, can we have the reason for this added to the documentation (e.g. a comment on the Dockerfiles)? 

### Is there any context that might help us understand?

Examples pulled from: 
https://github.com/vercel/turbo/blob/main/examples/with-docker/apps/web/Dockerfile
https://github.com/vercel/turbo/blob/main/examples/with-docker/apps/api/Dockerfile

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/guides/tools/docker#example

**Comment by anthonyshew** [comment]
Thanks for pointing this out! Example fixed and docs update is rolling.
