### ISSUE TITLE
Docs reference "npmClient" in turbo.json, but the schema does not

### ISSUE THREAD

**Issue by VanTanev** [vercel/turborepo#838]
### What version of Turborepo are you using?

1.1.5

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

https://turborepo.org/schema.json does not have an `npmClient` option, but the docs reference it: https://turborepo.org/docs/reference/configuration#npmclient

### Expected Behavior

Schema and docs should match.

### To Reproduce

It seems like either the schema or the docs are outdated?

**Comment by fz6m** [comment]
You can specify the npm client in the `package.json` > `packageManager`

```js
// package.json
{
    "packageManager": "pnpm@6.20.0"
}
```

**Comment by VanTanev** [comment]
@fz6m Hey, I know about that option.

This issue is about a mismatch between Turborepo's docs and the `turbo.json` schema.

**Comment by jaredpalmer** [comment]
This was legacy and never removed from v0.3 (pre-golang / pre-oss). We ought to remove

**Comment by kraenhansen** [comment]
> We ought to remove

Does that mean `npm` is (and will not be) not supported?
