### ISSUE TITLE
BREAKING REGRESSION:  Turbo no longer recognizes and builds dependencies / devDependencies for ^build

### ISSUE THREAD

**Issue by jlarmstrongiv** [vercel/turborepo#847]
### What version of Turborepo are you using?

1.1.5

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Turbo can no longer recognize dependencies, e.g. with ^build scripts

This causes all build commands to be run in any order, meaning that turbo generally crashes when package dependencies aren’t built yet.

### Expected Behavior

Turbo works like 1.1.4

### To Reproduce

Reproduction [here](https://dropover.cloud/704bc6)

- Download
- npm install
- npm install -g turbo@1.1.5
- turbo run build

To run correctly, do the same steps with turbo@1.1.4

**Comment by jlarmstrongiv** [comment]
This fork is very helpful for debugging https://github.com/vercel/turborepo/pull/846

**Comment by jlarmstrongiv** [comment]
Workarounds:

- Downgrade to 1.1.4 
- Run `find . -mindepth 2 -type f -name package.json -not -path '*node_modules*' -not -path '*.git/*' -not -path '*docs/*' -not -path '*bin/*' -execdir grep 'build' package.json \; -execdir test ! -d dist \; -execdir npm run build \;`

**Comment by chrisflatley** [comment]
Same issue (though running in Debian)

**Comment by gsoltis** [comment]
I was able to verify; thanks for the repro! I'll dig into what's going wrong.

**Comment by gsoltis** [comment]
@jlarmstrongiv  Looks like the issue is a combination of #802 and the way that dependencies are being specified via `file:`. As a workaround, can try specifying dependencies via package name? As an example, in `apps/nextjs/example/package.json`, switch the dependencies to things like `"@nodejs/example": "*"` instead of `"@nodejs/example": "file:..."`

@chrisflatley can you give examples of how you are defining your dependencies in your `package.json` files? Are they via package name + version or file paths or some other mechanism?

**Comment by chrisflatley** [comment]
All our project dependencies are defined as "@product-name/module-name":"*".

**Comment by gsoltis** [comment]
@chrisflatley and they match the `"name"` field in the dependency `package.json`? If so, it may be a different issue.

**Comment by chrisflatley** [comment]
Yes, they should match exactly.

Chris Flatley
***@***.***
________________________________

**Comment by gsoltis** [comment]
@chrisflatley can you open a new issue with a repro or description that mirrors your setup? I believe this one is directly related to `file:...` dependencies, and I'd like to investigate yours separately to see if there is a different regression.

**Comment by jlarmstrongiv** [comment]
@gsoltis the workaround builds everything properly, but I remember I had to switch from the `*` to `file:` syntax to fix another underlying issue.  Can’t remember for the life of me why that was…

**Comment by gsoltis** [comment]
@jlarmstrongiv great. I think we would recommend not using the `file:...` syntax unless it is a special circumstance. But at the same time, it shouldn't be broken. I'll see if I can get support for `file:...` back properly working.

**Comment by chrisflatley** [comment]
I'll try to recreate what we have. Looking at #802, I wonder if it is because we use semantic release?

Our version numbers in the package.json version are always 0.0.0-development. (Semantic release figures out the rest). 

Our dependencies are then ask for packageName:*. 

I see the tests seem to have some case for pre-release versions, (though I'm not sure if they are considered valid or not).

**Comment by gsoltis** [comment]
@chrisflatley that looks like it. It appears that semver [ignores prerelease versions](https://github.com/Masterminds/semver#working-with-prerelease-versions) when matching, unless the patch version already matches. So technically, `"*"` doesn't match `"0.0.0-development"`.

Is the version within your control to change to `"0.0.0"` or is the prerelease required by semantic release?

**Comment by chrisflatley** [comment]
Semantic release sets it to `0.0.0-development` by default (https://github.com/semantic-release/cli#what-it-does) and manages it from there itself. 

To be honest I've never looked any deeper into it, than just setting it up and letting it do its thing.

**Comment by gsoltis** [comment]
Got it. Ok, I'll see if we can come up with the right way to support this.

**Comment by jlarmstrongiv** [comment]
Thank you @gsoltis !  Switching away from `file:` to `*` ended up leading to:
```
npm ERR! No workspaces found:
npm ERR!   --workspace=@configs/eslint
```
So I moved back to the original `file:` syntax

**Comment by jlarmstrongiv** [comment]
Confirmed that 1.1.16 works 🚀

**Comment by gsoltis** [comment]
@chrisflatley I believe #855 should make this work for your setup again.
