### ISSUE TITLE
new TUI does not resize on window resize

### ISSUE THREAD

**Issue by huilensolis** [vercel/turborepo#8477]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

not necessary, just create a monorepo and run turbo <script>

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

2.0.2

### Describe the Bug

if you run a script on your terminal with `turbo <script>` and resize the window, the TUI will not resize.

if you have a workspace divided in two terminal windows, in one you run `turbo <script>` and then open the terminal with turborepo in full screen, the TUI will not adapt to the new screen width

### Expected Behavior

to update its width as the window resizes

### To Reproduce

create a new monorepo
create a script that doesn't exit interactive mode

run the script
resize window

see the broken TUI

**Comment by MickL** [comment]
I experience the same in iTerm on macOS

**Comment by AndreaPontrandolfo** [comment]
For me it's different. 
With the **old** TUI, the TUI wasn't resizing along the terminal pane. Same as you are describing.
BUT with the **new** TUI i'm experiencing a different behaviour.
If i start a command with a little window, the TUI will not be present, it will just revert the turborepo process to behave as `interactive: false` (like, it's working exactly as before the TUI got introduced).
If i start the command with a taller window, the new TUI takes over and works perfectly.

**Comment by AndreaPontrandolfo** [comment]
Just noticed that actually this is an intended behavior made in https://github.com/vercel/turbo/pull/8457. 
Why was this decision taken? This doesn't look right.

**Comment by chris-olszewski** [comment]
@AndreaPontrandolfo This decision was made due to the TUI requiring a certain minimum amount of area. Attempting to run the TUI in a terminal with less area results in an incorrect render or a crash.
