### ISSUE TITLE
regression: turbo couldn't find packages

### ISSUE THREAD

**Issue by dulmandakh** [vercel/turborepo#851]
### What version of Turborepo are you using?

1.1.5

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

I upgraded turbo to 1.1.5 then tried to run _turbo run build_ on my server and it couldn't find packages, output below.

```
• Packages in scope: 
• Running build in 0 packages

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    83ms >>> FULL TURBO
```

### Expected Behavior

find packages, and run pipeline.

### To Reproduce

it was run on Debian 11 with node 16, and latest yarn.

**Comment by gsoltis** [comment]
@dulmandakh Can you describe how you are specifying dependencies in your `package.json` files? There is currently a regression around `file:...` dependencies (#847).

**Comment by jaredpalmer** [comment]
Try 1.1.6

**Comment by dulmandakh** [comment]
@gsoltis I use yarn workspaces, and we don't use file: dependencies, but just package names.

@jaredpalmer tried 1.1.6, and regression persists.

**Comment by jaredpalmer** [comment]
@dulmandakh can you try w/ `turbo@1.1.7-canary.0` ?

can you share how you are defining your workspaces in package.json as well as how you specify versions of local packages as dependencies in your package.json's? Are you using `*`?

**Comment by dulmandakh** [comment]
@jaredpalmer 

This is how we define packages, also we use * to specify local dependency.

```json
 "workspaces": [
    "packages/*",
    "sites/*"
  ],
```

**Comment by gsoltis** [comment]
@dulmandakh I will see if I can reproduce the issue with that setup.

**Comment by gsoltis** [comment]
@dulmandakh I was not able to reproduce the issue, but I made a repo using yarn workspaces that I think matches your description, based on the `kitchen-sink` example in this repo: https://github.com/gsoltis/turbo-yarn-workspaces

Would you mind taking a look and either describing what's different from your setup, or if possible, send me a PR to match your setup?

**Comment by sibelius** [comment]
I'm running `turbo@1.1.7-canary.1` and it is just not finding 1 of my scoped packages

```
yarn turbo run build --scope='@app/test' --no-deps
```

all the other `@app/*` works as expected

not sure if /test is problematic

**Comment by gsoltis** [comment]
@sibelius that's pretty odd. I don't think there's anything special about `/test`. If you can try from `main`, try w/ `--dry-run` to help see what's going on. Otherwise, maybe `--graph=deps.png` will help shed some light on it. In both cases, try running with `--scope='@app/test'` and without, to get the full graph.

**Comment by jaredpalmer** [comment]
Correction: You cannot have package in a directory named `test`. https://github.com/vercel/turborepo/blob/main/cli/internal/context/context.go#L475-L482 This is to comply with pnpm which uses the same ignores patterns we use

**Comment by sibelius** [comment]
what would be a good name for a package test utils ? @app/testutils?

**Comment by jaredpalmer** [comment]
The package itself canbe named test.

**Comment by gsoltis** [comment]
@dulmandakh Just wanted to check in, did you manage to get your dependencies picked up? If you want to use the latest canary, you should be able to use `--dry` to check what would be run.

**Comment by gsoltis** [comment]
I'm going to close this given that it's been some time, but if you continue to have trouble I'll be happy to reopen and investigate.
