### ISSUE TITLE
cache miss with --no-deps option

### ISSUE THREAD

**Issue by MrHertal** [vercel/turborepo#852]
### What version of Turborepo are you using?

1.1.5

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Hello,

The documentation section that concerns the --no-deps option says:

> Let's say you have packages A, B, C, and D where A depends on B and C depends on D. You run turbo run build for the first time and everything is built and cached. Then, you change a line of code in B. With the --deps flag on, running turbo run build will execute build in B and then A, but not in C and D because they are not impacted by the change. If you were to run turbo run build --no-deps instead, turbo will only run build in B.

I am in a similar situation, I have packages A, B, C etc. that all depend on Z package.

Here is my `tubo.json`:

```
{
  "pipeline": {
    "lint": {
      "outputs": []
    }
  }
}
```

When I run `turbo run lint` the first time, lint is run on each packages and everything is cached.

If I make a change to package Z and run `turbo run lint` again, lint is run on each packages and everything is cached again.

But if I change something in package Z and run `turbo run lint --no-deps`, lint is also run on each packages (all with cache miss).

### Expected Behavior

I would expect that `turbo run lint --no-deps` only runs lint on package Z (1 cache miss) and not on parent packages that would hit cache.

### To Reproduce

Make a repo with several packages that all depend on one package. Try the --no-deps option on a task after changing something on that package.

**Comment by jaredpalmer** [comment]
`--deps` is being deprecated. See https://turborepo.org/docs/features/filtering and the new `--filter` flag in `turbo@1.2`
