### ISSUE TITLE
Scoped tasks not working if turbo is spawned on a child folder if the scoped package has `" "`

### ISSUE THREAD

**Issue by charlie632** [vercel/turborepo#870]
### What version of Turborepo are you using?

1.1.6

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

If you have the following file structure:

```
package.json
turbo.json
- someStuff/
      - build.js
      - packages/
             /// Scoped packages
```

And inside `build.js` you have:

```js

const path = require('path');

const { spawn } = require('child_process');

let cmd = './node_modules/.bin/turbo'
let args = ['run', 'lint', '--scope="@corp/pkf1"']

spawn(cmd, [...args], {
  cwd: path.resolve(__dirname, '..'),
  detached: true,
  stdio: 'inherit',
});


```

Running:

```
node someStuff/build.js
```

You'll get the following:

```
 ERROR  failed resolve packages to run invalid scope: No packages found matching the provided scope pattern.
```

Adding the `--cwd` flag to the turbo command does nothing.

However, running the command on `spawn` at the "root" of the monorepo works as expected

### Expected Behavior

Should run scoped tasks

### To Reproduce

Reproduction repo

https://github.com/charlie632/turbo-scoped-tasks-repro

**Comment by charlie632** [comment]
Lol this is weird.... TL;DR:

Spawning a process in a child directory with
```
--scope="pkg_name"
```

will result in an error.

Removing the `" "` make it work.

However, If you manually run the command on your terminal, it will work

**Comment by charlie632** [comment]
So... adding `shell: true` to the spawn options make this work, even with `" "`.... 

So the question is... is this a parsing error from turborepo, or just weird nodejs stuff?

**Comment by jaredpalmer** [comment]
Spaces are not allowed in flags at the moment. See #759
