### ISSUE TITLE
Feature: awesome-turborepo

### ISSUE THREAD

**Issue by iamclaytonray** [vercel/turborepo#875]
### Describe the feature you'd like to request

It'd be awesome to have an `awesome-turborepo` repo, which would be a list of the awesome things the community has made using turborepo (open source, apps, boilerplates, examples, etc).

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

Search through github, which isn't very fast and no "quality control" as far as what I'm looking at. Could be an empty repo or very incomplete, etc.

**Comment by petermekhaeil** [comment]
I've started one: https://github.com/petermekhaeil/awesome-turborepo. 

Happy to move it under [vercel](https://github.com/vercel) if the team wants.

**Comment by jaredpalmer** [comment]
Let's invest this energy into docs. Most awesome lists become rapidly outdated (e.g. https://github.com/unicodeveloper/awesome-nextjs)
