### ISSUE TITLE
Select scope automatically based on the current directory

### ISSUE THREAD

**Issue by smmoosavi** [vercel/turborepo#881]
### Describe the feature you'd like to request

Right now, we can specify scope with the `--scope` option. Also, if we are not at the root of the project when executing `yarn turbo run build`, it says:

```
cd packages/my-app
yarn turbo run build
 ERROR  Could not find turbo.json. Follow directions at https://turborepo.org/docs/getting-started to create one
```

My suggestion is that the "change directory" is equal to "choose the scope."

```
yarn turbo run build --scope=my-app

# same as

cd packages/my-app
yarn turbo run build
```

### Describe the solution you'd like

- [ ] find up turbo.json
- [ ] find scope based on current directory
- [ ] use that scope

### Describe alternatives you've considered

no idea

**Comment by smmoosavi** [comment]
Nice, close this one if it is not needed.

**Comment by tknickman** [comment]
Closing to consolidate the discussion on https://github.com/vercel/turborepo/issues/550. Thanks @smmoosavi.
