### ISSUE TITLE
'INCLUDE_VUE'     ...Finishing writing to cache...    Oops! Turbo has crashed.

### ISSUE THREAD

**Issue by vae139** [vercel/turborepo#8940]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

wu

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

pnpm why turbo

### Describe the Bug

"name" = "turbo"
"operating_system" = "Windows 10.0.22631 (Windows 11 Education) [64-bit]"
"crate_version" = "2.0.6"
"explanation" = '''
file 'library\std\src\io\stdio.rs' at line 1118
'''
"cause" = "failed printing to stdout: Windows stdio in console mode does not support writing non-UTF-8 byte sequences"
"method" = "Panic"
"backtrace" = """
﻿
0: 0x7ff610094874 - <unresolved>
1: 0x7ff610093a66 - <unresolved>
2: 0x7ff6100949b4 - <unresolved>
3: 0x7ff6100912ef - <unresolved>
4: 0x7ff610091406 - <unresolved>
5: 0x7ffe5070257d - <unresolved>
6: 0x7ffe52a0af28 - <unresolved>"""

### Expected Behavior

pnpm run build

### To Reproduce

![image](https://github.com/user-attachments/assets/22442beb-9cd6-47e5-b67e-83cf8ab55745)

**Comment by chris-olszewski** [comment]
Closing as there hasn't been any response. Please reopen if you are still experiencing this issue!

**Comment by fuzhenn** [comment]
> Can you attempt the solution suggested in [this comment](https://github.com/vercel/turbo/issues/7075#issuecomment-2085583353)?
> 
> If that doesn't work could you provide a reproduction repo? This error is highly dependent on the artifacts/logs that a task produces.

It works for me, Thanks very much!
对于中文windows用户，勾选系统区域设置中的 `Beta版：使用Unicode UTF-8 提供全球语言支持` 选项即能解决。
选项位置：
设置 -> 时间和语言 -> 语言和区域 -> 相关设置中的管理语言设置 -> 更改系统区域设置
