### ISSUE TITLE
Keypress interaction with `vite` doesn't work ("o"+Enter doesn't open web)

### ISSUE THREAD

**Issue by shanike** [vercel/turborepo#8952]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/shanike/turborepo-bug-repro

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

2.0.12-canary.3

### Describe the Bug

Hi! When using `vite` and `turbo`, the `"tui"` works nicely but has an annoying unexpected bug:  
The part that works: The "gui" opens and runs as expected, and when pressing `"Enter"` on the persistent `vite` job, it focuses into it and allows typing.  
The part afterwards which doesn't work: writing the letter `"o"` followed by an `"Enter"` -> nothing happens

### Expected Behavior

When writing the letter `"o"` followed by an `"Enter"` in a `vite` job -> vite opens the localhost web on the correct job's port. This does not happen with v2 of turbo.

### To Reproduce

1. Install turbo
2. On 1 app install vite
3. Create a "dev" vite+turbo task
Now,
4. `pnpm exec turbo dev` on apps/apps-a
will run vite with turbo and won't open the web when writing `o + Enter`  
But
4. `pnpm dev`
Will open the web when writing `o + Enter` 

### Additional context

On turbo `v1.13.4` with `experimentalUI` turned on -> it DOES work: it opens the web when "interacting" with the vite task and pressing `o + enter`

**Comment by chris-olszewski** [comment]
A few questions:
- Do any of the other commands work such as `h + Enter` showing help text?
- Does `pnpm exec turbo dev --env-mode=loose` have different behavior?
- Does `open http://localhost:5173/` open the browser for you? (I think this is the command `vite` uses, but I could be wrong)


I wasn't able to reproduce so I'm wondering if this is Linux specific.
https://github.com/user-attachments/assets/040c9bc0-4928-4ade-a987-0f019691327c

**Comment by chris-olszewski** [comment]
Closing as there hasn't been any updates. Please reopen if you're still experiencing this issue!
