### ISSUE TITLE
turbo 2.0.10 prints turbo version to stderr breaking CI pipeline

### ISSUE THREAD

**Issue by chanep** [vercel/turborepo#8961]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

pnpm

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

2.0.12

### Describe the Bug

starting at turbo 2.0.10 any turbo task as 
`turbo lint`
prints 
`turbo <version>` e.g. `[2mturbo 2.0.10[0m`
to stderr breaking CI pipelines

### Expected Behavior

if task does not fail nothing goes to stderr like it was 2.0.9 version

### To Reproduce

turbo lint --force 2> error.txt

### Additional context

There is no canary available, the most recent version is 2.0.12

**Comment by chanep** [comment]
It seems it is a trace output, 
but telemetry is disable and there is no vervosity set in the command but turbo still sends turbo version to stderr

**Comment by NicholasLYang** [comment]
Hey, @chanep, we added the turbo version output so users can understand which version of turborepo they're running. This had previously been a point of confusion for users. To disable the output, you can pass the `TURBO_PRINT_VERSION_DISABLED` flag to turbo: `TURBO_PRINT_VERSION_DISABLED=true turbo build`

**Comment by chanep** [comment]
Thanks!. But why new patch versions (from 2.0.9 to 2.010) sends new stuff to stderr that needs a new unknown ENV VAR setting to run ok in a pipeline? shouldn't be TURBO_PRINT_VERSION_DISABLED true by default?

**Comment by NicholasLYang** [comment]
Yeah, sorry, we didn't realize stderr was being monitored so carefully. We'll try to be more careful next time!
