### ISSUE TITLE
Docs: Registering Root Tasks - Incorrect/Unclear example

### ISSUE THREAD

**Issue by nickfujita** [vercel/turborepo#8972]
### What is the improvement or update you wish to see?

The current documentation seems to suggest that by creating the `lint:root` script in the root `package.json` file, and the `//#lint:root: {}` task in `turbo.json` alongside `lint: {}` task, running `turbo run lint` should execute the `lint` script in all packages in the repo, along with the `lint:root` script in the root `package.json`. At least that's how I understood it to mean.

### Is there any context that might help us understand?

[Registering Root Tasks](https://turbo.build/repo/docs/crafting-your-repository/configuring-tasks#registering-root-tasks)
## Existing
Running `pnpm lint` only runs `lint` scripts in packages, but not the root level `lint:root` script.
#### turbo.json
```json
{
  "tasks": {
    "lint": {
      "dependsOn": ["^lint"]
    },
    "//#lint:root": {} 
  }
}
```

#### package.json
```
{
  "scripts": {
    "lint": "turbo run lint",
    "lint:root": "eslint ."
  }
}
```

## Correction - Option 1
Runs `lint:root` in addition to `lint` scripts in all packages, by separately calling `lint:root` in the `turbo run` statement
#### turbo.json
```json
{
  "tasks": {
    "lint": {
      "dependsOn": ["^lint"]
    },
    "//#lint:root": {} 
  }
}
```

#### package.json
```
{
  "scripts": {
    "lint": "turbo run lint lint:root",
    "lint:root": "eslint ."
  }
}
```

## Correction - Option 2
Runs `lint:root` in addition to `lint` scripts in all packages by removing `:root` suffix from the script in the root `package.json`, and making the script the calls `turbo run lint` be named something else (eg. lint-abcdef, lint-all)
#### turbo.json
```json
{
  "tasks": {
    "lint": {
      "dependsOn": ["^lint"]
    },
    "//#lint": {} 
  }
}
```

#### package.json
```
{
  "scripts": {
    "lint-all": "turbo run lint",
    "lint": "eslint ."
  }
}
```

### Does the docs page already exist? Please link to it.

https://turbo.build/repo/docs/crafting-your-repository/configuring-tasks#registering-root-tasks

**Comment by anthonyshew** [comment]
Fixed in https://github.com/vercel/turborepo/pull/9098. Thank you!
