### ISSUE TITLE
Request for having a `turbo.js` or/and `turbo.ts` to configure turbo

### ISSUE THREAD

**Issue by denik1981** [vercel/turborepo#899]
### Describe the feature you'd like to request

When building your `turbo.json` config file, there is the point where it becomes pretty large to manage. It will be nice to have the alternative `turbo.{js,ts}` to programmatically skip code duplication, conditionally load a configuration setting, extract setting to an env-related module, etc. There are many advantages of having a ts/js config file that I don't think is worth mentioning all of them.

### Describe the solution you'd like

`turbo.js` and/or `turbo.ts` as a developer choice in how it builds the turbo configuration.

### Describe alternatives you've considered

None, besides extending the capabilities of the `json` settings but it will be quite a headache and most of the requirements needed are already covered in the language (js/ts)

**Comment by jaredpalmer** [comment]
Turbo is written in Golang. We ideally want to avoid starting a node.js process just to read configuration until it becomes unbearable to do so. I too appreciate the convenience, but it makes it impossible to statically analyze

**Comment by JREAM** [comment]
Turbo is written in Rust @ [https://turbo.build](https://turbo.build)  
  
\> _Turbo is an incremental bundler and build system optimized for JavaScript and TypeScript, written in Rust._
