### ISSUE TITLE
Add fallbacks to commands that don't exist

### ISSUE THREAD

**Issue by mcrowder65** [vercel/turborepo#904]
### Describe the feature you'd like to request

In my primary application, a developer may run `yarn start:ssl` to run localhost with ssl certs, or they may run `yarn start`

So running `turbo run start` globally works well because it will run start in `primary` project, and `shared` project.

However, running `turbo run start:ssl` will only run `start:ssl` inside of the `primary` project.

It would be nice if turbo could recognize that `start:ssl` does not exist inside of `shared` and will fallback to the `start` script instead.

### Describe the solution you'd like

`turbo run start:ssl` will first look for `start:ssl` in all projects, and any projects that do not have `start:ssl`, will look for `start`.

### Describe alternatives you've considered

For now, I manually added `start:ssl` inside of `shared`.

**Comment by adrienjoly** [comment]
We have a similar need:
- context: our CI calls `yarn test:unit:coverage`
- problem: that yarn script is implemented by our main package, but not by others... => only unit tests of the main package are being run!
- possible solution: be able to tell turborepo to run `yarn test:unit` for packages that don't have a `test:unit:coverage` script

**Comment by mehulkar** [comment]
Looks the same as #648!
