### ISSUE TITLE
turbo multi `--filter` not working as expected

### ISSUE THREAD

**Issue by zigang93** [vercel/turborepo#9043]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

-

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo 2.0.14

### Describe the Bug

// Any packages in `apps` subdirectories except ./apps/docs
`turbo run build --filter=./apps/* --filter=!./apps/docs`

this command always can't found the apps/docs

my terminal env is zsh

### Expected Behavior

should be able to filter out / exclude

### To Reproduce

run turbo run build --filter=./apps/* --filter=!./apps/docs

**Comment by chris-olszewski** [comment]
You need to quote your filter as `!` is a special character in `zsh`: 
```
$ turbo run build --filter='./apps/*' --filter='!./apps/docs' --output-logs=hash-only --ui=stream
turbo 2.0.14

• Packages in scope: web
• Running build in 1 packages
• Remote caching disabled
web:build: cache hit, suppressing logs 75a2ab88cc7dbb6f

 Tasks:    1 successful, 1 total
Cached:    1 cached, 1 total
  Time:    90ms >>> FULL TURBO
```
