### ISSUE TITLE
can't run script in all the workspaces before root script

### ISSUE THREAD

**Issue by alyahmedaly** [vercel/turborepo#9072]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/alyahmedaly/turbo-root-script-issue

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo@2.1.0 ,and latest canary both have same issue

### Describe the Bug

I want to run build in all workspaces packages before running the main script in package.json on the root level
but not sure if there is anything I need todo

I think this error I got is a bug or miss understanding from my side In this case I have build in dependsOn inside //#build:client:app task but looks like turbo trying to fix build task in the root and not in running my workspaces packages

for example if I used @packagename#build in dependsOn it will work as expected but I don't want to put all the package names here

❯ npx turbo run //#build:client:app --graph
missing_root_task_in_turbo_json (link)

× //#build needs an entry in turbo.json before it can be depended on because it is a task declared in the root package.json
╭─[turbo.json:83:1]
83 │ "//#build:client:app": {
84 │ "dependsOn": [ "//#build:client:vendor", "build"],
· ───┬───
· ╰── add an entry in turbo.json for this task
85 │ "inputs": [
╰────

### Expected Behavior

I should be able to depend on workspaces scripts

### To Reproduce

run ❯ turbo run fancy on the shared repo

**Comment by alyahmedaly** [comment]
>The error message is correct, in the definition for //#build:client:app you have declared "build" as a dependency which since you're in the root package will be //#build which doesn't exist. If you defined a //#build, then the error would go way. 

That is clear I got this point after trying to add //#build task, maybe we can improve the error here.
>If you want instead to run all of the dependencies build tasks you would use ^build instead. See the [docs for declaring task dependencies](https://turbo.build/repo/docs/crafting-your-repository/configuring-tasks#depending-on-tasks-in-dependencies-with-).
I tried this one as well but it's not executing the scripts in my workspaces
```
"//#fancy":{
      "dependsOn": ["^build"]
    }
❯ npx turbo run fancy --graph
turbo 2.1.0
digraph {
        compound = "true"
        newrank = "true"
        subgraph "root" {
                "[root] //#fancy" -> "[root] ___ROOT___"
        }
}
```
>Does this need to be at the root package or can you create a new package that depends on all relevant packages? You could use ^build on a new package that depends on all packages in your workspace e.g.

100% agree with you but in my case it require huge refactor as for legacy reasons using workspaces was a way to improve the project state this is how the project look like

```
```

**Comment by alyahmedaly** [comment]
sorry closed the issue by mistake, so most of the code is already inside workspaces/packages but we still have big part under src dir and they are not a package so we have one package.json at root handle deps and builds.

so in ideal scenario I would create a package for server and client for under another workspace for example `apps` but this will be hard for now, do you have any advice how can I workaround it?

**Comment by alyahmedaly** [comment]
Ok, I think I was having diff mindset coming from `wireit` which build on the scripting idea more than workspaces,
changing my mindset I added 2 new package.json under client and server dir adding then to the workspaces config then enable `import/no-extraneous-dependencies` to help me fill the dependancies on this 2 new package.json and make my root level task depend on the new packages instead

**Comment by chris-olszewski** [comment]
It sounds like you're on the right path. Closing, but please feel free to reopen if you encounter any issues/have more questions.

**Comment by bestickley** [comment]
I have the same exact issue as this title describes. I'm using a root level `lint` and `format` task as suggested by the [oxc turbo docs](https://turborepo.dev/docs/guides/tools/oxc), but I want to depend upon a Next.js `typegen` command that runs in all packages that have it. I cannot use `^build` because the root workspace does not have all of those Next.js apps as a dependency. I cannot define a `//#typegen` task because it would result in recursive error.

**How can I have a root script `dependsOn` a script I want run in all packages?**
