### ISSUE TITLE
busted zsh completions

### ISSUE THREAD

**Issue by mulchy** [vercel/turborepo#9080]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

sorry no repo

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo 2.0.12, turbo 2.1.0

### Describe the Bug

typing `turbo --` and pressing tab gives this error

```
_arguments:comparguments:327: invalid option definition: --[no-]daemon[Force turbo to either use or not use the local daemon. If unset turbo will use the default detection logic]
```

### Expected Behavior

A list of options is shown

### To Reproduce

run `turbo completion zsh` and save the output somewhere your shell is configured to read completion information from

**Comment by chris-olszewski** [comment]
This is due to a limitation with the library we use for command line parsing. It looks like there's progress being made (https://github.com/clap-rs/clap/pull/5545) so I'll try updating the library and see if that helps with completions.
