### ISSUE TITLE
Expo Metro Server can't resolve my packages

### ISSUE THREAD

**Issue by Chuazz** [vercel/turborepo#9090]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/Chuazz/instagram-clone

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

turbo@2.0.14

### Describe the Bug

i followed [#4771](https://github.com/vercel/turborepo/issues/4771) to fix typescript error but it return me "Unable resolve module ..." when i prebuild with expo. 
![image](https://github.com/user-attachments/assets/2da37e8a-31ae-40ce-b087-3c54c818fd3c)
![image](https://github.com/user-attachments/assets/08126c29-a3d4-46d8-b5fb-84515dae71a0)

### Expected Behavior

metro server can resolve my package

### To Reproduce

`yarn && yarn dev:mobile`

**Comment by chris-olszewski** [comment]
Does the issue occur if `turbo` isn't used? e.g. `cd apps/mobile && yarn dev:mobile`

**Comment by Chuazz** [comment]
> Does the issue occur if `turbo` isn't used? e.g. `cd apps/mobile && yarn dev:mobile`

i will try it and reply you later

**Comment by Chuazz** [comment]
> Does the issue occur if `turbo` isn't used? e.g. `cd apps/mobile && yarn dev:mobile`

still not working 
![image](https://github.com/user-attachments/assets/5d38516a-ce18-4dc9-9dc8-bcc040874e39)

**Comment by Chuazz** [comment]
it only work for index.js not work for custom another path like ./query/index.js
![image](https://github.com/user-attachments/assets/a6979140-b3b1-4115-812f-63ee648e68ee)

**Comment by Chuazz** [comment]
just figure out that react native not working like nodejs on web so i use babel to create an alias for it(so silly)
