### ISSUE TITLE
Expo Go not working

### ISSUE THREAD

**Issue by spr021** [vercel/turborepo#9129]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

yarn dlx create-turbo@latest --example with-react-native-web

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

yarn why v1.22.19

### Describe the Bug

After run apps of mono repo with turborepo, all apps are running even the react native app but Expo Go controls are not working in the terminal.
<img width="612" alt="Screenshot 2024-09-09 at 20 42 13" src="https://github.com/user-attachments/assets/6d762d9f-d21b-48ea-be04-f2a647e930c9">

### Expected Behavior

I expected after run, controls work for example after entering a word and pressing enter, run the emulator.

### To Reproduce

I just clone this repo from turborepo examples and run the project
https://github.com/vercel/turborepo/tree/main/examples/with-react-native-web

**Comment by NicholasLYang** [comment]
Hi, could you try with the TUI? To do so, pass `--ui tui` to your `turbo` command

**Comment by tknickman** [comment]
Check out the docs on [interactive](https://turbo.build/repo/docs/reference/configuration#interactive) tasks as well
