### ISSUE TITLE
Turbo is unable to compile source with pdfjs

### ISSUE THREAD

**Issue by Matts** [vercel/turborepo#9195]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/Matts/pdfjs-and-turbo-incompat

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

-

### Describe the Bug

The code that crashes is never run, but the fact that it "could" run causes turbo to freak out on both client and server side

### Expected Behavior

This should work

### To Reproduce

See https://github.com/mozilla/pdf.js/discussions/18804
- Create a nextjs + turbo project
- Follow the example installation at https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples
- You will receive a compilation error from turbopack (see image below)

it seems that turbo pre-interprets import statements and tries to resolve them. I see that there is a webpack ignore statement, possibly there has to be a similar statement for turbo

![image](https://github.com/user-attachments/assets/6a4ae82d-e174-4245-a4d5-6f1388852e31)

### Additional context

I am not technically included enough to reproduce this within turborepo but seeing as this does not happen with old dev server it must be turbo.

**Comment by chris-olszewski** [comment]
Hello, Turbopack is no longer part of this repository. Could you file an issue in it's new repository [vercel/next.js](https://github.com/vercel/next.js)?
