### ISSUE TITLE
Turbo can't find any packages in the defined workspaces if current dir is a symbolic link

### ISSUE THREAD

**Issue by olethomas** [vercel/turborepo#920]
### What version of Turborepo are you using?

1.1.9

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

When the current directory is a symbolic link, turbo can't find any packages in the defined workspaces. When current directory is not a symbolic link it runs as expected.

Config:
```json
"workspaces": [
    "tools/*",
    "packages/plugins/*",
    "packages/themes/*",
    "packages/styles/*"
],
```

Output when current dir is symbolic:
```
turbo run build
Packages in scope: 
Running build in 0 packages

Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
Time:    11ms >>> FULL TURBO
```

Related: https://github.com/vercel/turborepo/issues/549#issuecomment-1062227032

### Expected Behavior

Turbo builds based on the packages defined in workspaces

### To Reproduce

Put the root directory of your project in a symbolic link

**Comment by BlackGlory** [comment]
https://github.com/vercel/turborepo/blob/5d2a7b4a01b55bf059aa9b2338f19998e4840e53/cli/internal/fs/copy_file.go#L88
Related to this line, after testing, if I change it to true, it works as expected.
