### ISSUE TITLE
turbo fails on FreeBSD: Error: Unsupported platform: freebsd x64 LE

### ISSUE THREAD

**Issue by yurivict** [vercel/turborepo#9210]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

n/a

### What package manager are you using / does the bug impact?

Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Other

### Which canary version will you have in your reproduction?

n/a

### Describe the Bug

turbo breaks on FreeBSD with these messages:
```
     [exec] error /usr/ports/devel/RStudio/work-desktop/rstudio-2024.09.0-375/src/gwt/lib/quarto/node_modules/turbo: Command failed.
     [exec] Exit code: 1
     [exec] Command: node install.js
     [exec] Arguments: 
     [exec] Directory: /usr/ports/devel/RStudio/work-desktop/rstudio-2024.09.0-375/src/gwt/lib/quarto/node_modules/turbo
     [exec] Output:
     [exec] /usr/ports/devel/RStudio/work-desktop/rstudio-2024.09.0-375/src/gwt/lib/quarto/node_modules/turbo/node-platform.js:41
     [exec]     throw new Error(`Unsupported platform: ${platformKey}`);
     [exec]           ^
     [exec] 
     [exec] Error: Unsupported platform: freebsd x64 LE
     [exec]     at pkgAndSubpathForCurrentPlatform (/usr/ports/devel/RStudio/work-desktop/rstudio-2024.09.0-375/src/gwt/lib/quarto/node_modules/turbo/node-platform.js:41:11)
     [exec]     at checkAndPreparePackage (/usr/ports/devel/RStudio/work-desktop/rstudio-2024.09.0-375/src/gwt/lib/quarto/node_modules/turbo/install.js:260:28)
     [exec]     at Object.<anonymous> (/usr/ports/devel/RStudio/work-desktop/rstudio-2024.09.0-375/src/gwt/lib/quarto/node_modules/turbo/install.js:310:1)
     [exec]     at Module._compile (node:internal/modules/cjs/loader:1469:14)
     [exec]     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
     [exec]     at Module.load (node:internal/modules/cjs/loader:1288:32)
     [exec]     at Module._load (node:internal/modules/cjs/loader:1104:12)
     [exec]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
     [exec]     at node:internal/main/run_main_module:28:49
```

On FreeBSD we will eventually have the "turbo" binary provided by the devel/turbo port. (Currently turbo doesn't build due to the Rust version mismatch.)

The turbo NodeJS module should attempt to find the /usr/local/bin/turbo binary executable, and fail only when it isn't present. It shouldn't be looking for some freebsd turbo package like it does for other distros.

### Expected Behavior

n/a

### To Reproduce

The problem is reproducable when RStudio is built on FreeBSD.

### Additional context

n/a

**Comment by tknickman** [comment]
Hey thanks for the issue! We currently only have plans to support the platforms listed here:
https://turbo.build/repo/docs/getting-started/support-policy#platforms
