### ISSUE TITLE
100% CPU Utilization on a single core while turbo repo is active

### ISSUE THREAD

**Issue by Suvansarkar** [vercel/turborepo#9211]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/Qilin-Inc/Qilin

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

turbo@2.1.2

### Describe the Bug

I'm facing an issue where when I start the turbo repo, it takes up 100% cpu util from one core only. Making my laptop go a bit toasty. Is there any way of distributing the workload across multiple cores so it doesn't get as hot?

Note: This doesn't happen when I run my applications on standalone.

Applications in the repo:
1. A nestjs backend application running on port 4000
2. A nextJs frontend application running on port 3000

What I have tried: --concurrency=100% and --parallel flags (They don't seem to  work)

System info:
i5 13450HX
Nvidia RTX 4050 (mobile)
16GB RAM
Arch Linux - Hyprland WM

Core utilisations with v/s without turbo repo for reference:
![image](https://github.com/user-attachments/assets/a745e670-58c2-4135-9b01-cd22a0b75a1f)
![image](https://github.com/user-attachments/assets/078d8faa-74c7-48f1-92c2-490a77156340)

### Expected Behavior

The turbo repo distributes load evenly between all CPU's and not hog up a single core like shown in the second image

### To Reproduce

Install the turborepo starter pack in a linux environment.

`npx create-turbo@latest`

run the turbo repo

`npm run dev`

### Additional context

Works fine on windows as far as I have tested it. This is an issue only on linux.

**Comment by bwilytsch** [comment]
Same happens to me.

**Comment by busybox11** [comment]
Same for me. Looks like the daemon keeps running in the background ever after Ctrl-C and also takes 100% CPU of a single core at all times.

**Comment by smoove** [comment]
Same on my arch laptop, one core always has 100% load. I left it for an hour, still 100%.

**Comment by chris-olszewski** [comment]
Could test out `2.1.4-canary.9`? It contains https://github.com/vercel/turborepo/pull/9132 that should significantly reduces the amount of CPU time spent checking for user input.

**Comment by smoove** [comment]
> Could test out `2.1.4-canary.9`? It contains #9132 that should significantly reduces the amount of CPU time spent checking for user input.

CPU is now chilling @ 2% :+1:

**Comment by busybox11** [comment]
Can also confirm this has fixed the issue!

**Comment by tknickman** [comment]
Closing for now, but please open a new issue if this re-appears!

**Comment by chris-olszewski** [comment]
Just putting this here for interested parties that this change did introduce some small TUI bugs which should be fixed in 2.2.2
