### ISSUE TITLE
Affected dependency graph/output does not show dependent components when using git ref filters

### ISSUE THREAD

**Issue by maciejfalski-p** [vercel/turborepo#9234]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

none

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.1.3

### Describe the Bug

My github actions build pipeline intends to build only apps affected between the current commit and the last successful build commit. To grab the last successful commit, I use https://github.com/nrwl/nx-set-shas action, which works perfectly. turbo build, however, doesn't build all the necessary components when using git ref filters.

### Expected Behavior

Correctly calculate the dependency graph of all modules/apps affected by a change in a submodule. 

### To Reproduce

I made a few commits in a repo to `@repo/components` module. These commits are after git-ref <0a9262d1fce6ada>. All apps (app1 and app2) in my repo depend on `@repo/components`. 

When running:
`npx turbo run build --filter="[0a9262d1fce6ada...HEAD]"  --dry=json | jq -cr '.packages'`
I should see: `["@repo/components", "app1", "app2"]`
but I only see: `["@repo/components"]`

Hence, my apps won't get rebuilt and in consequence, redeployed.

**Comment by maciejfalski-p** [comment]
I found out that, an expected behaviour can be achieved by using `--affected flag`, ie

```
export TURBO_SCM_BASE=234asdf35... 
export TURBO_SCM_HEAD=45fdq2gs...  
npx turbo run build --affected
```
Not as nice as using `---filter`. Also you cannot use`--affected` with other filters, ie `--filter="{apps/*}`.

**Comment by NicholasLYang** [comment]
Hey, thanks for the issue. You can also use `--filter=...[base..head]` if you wish to compose with other filters. The `...` prefix indicates that all dependent packages should be built too (docs [here](https://turbo.build/repo/docs/crafting-your-repository/running-tasks#filtering-to-include-dependents)). We're working on making `--affected` usable with other filters, but there's an issue of whether it should be an `OR` or an `AND` operation, i.e. should additional filters allow you to add on more packages, or should they restrict your existing package set?

**Comment by maciejfalski-p** [comment]
Great, thanks for your swift response. That works.
