### ISSUE TITLE
Package interdependency

### ISSUE THREAD

**Issue by darklight9811** [vercel/turborepo#925]
### What version of Turborepo are you using?

1.1.9

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

Packages can't depend on packages, if you try to do it. It won't be able to load the dependency of that package. Throwing:

```
Module parse failed: Unexpected token (3:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

### Expected Behavior

Packages should be able to depend on other packages.

### To Reproduce

- Download the default turbo example
- Make another package called helpers
- Import it in the ui package
- Try to run the application (need to open it, it won't detect it only by doing `dev` command)

**Comment by jaredpalmer** [comment]
You need to add that package to `next-transpile-modules` array in your app's next.config.js


Read more here: https://www.npmjs.com/package/next-transpile-modules
