### ISSUE TITLE
Support differentiation of sources for dependencies and devDependencies for cyclical dependency checks

### ISSUE THREAD

**Issue by mpodwysocki** [vercel/turborepo#9253]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

turbo build

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

 2.1.3

### Describe the Bug

As we are trying to move the [`azure-sdk-for-js`](https://github.com/Azure/azure-sdk-for-js/tree/feat/pnpm-migration) to [`pnpm`](https://pnpm.io/), we have several issues with calculating the dependency graph.

If we have the following packages

```json
{
  "name": "@azure/identity",
  "devDependencies": {
    "@azure/keyvault-keys": "workspace:*"
  }
}
```

```json
{
  "name": "@azure/keyvault-keys",
  "devDependencies": {
    "@azure/identity": "workspace:*"
  }
}
```

This should cause a cyclical dependency problem.  However, if we break it using npm direct links, then the dependency graph should not detect a cyclical graph.

```json
{
  "name": "@azure/identity",
  "devDependencies": {
    "@azure/keyvault-keys": "npm:@azure/identity:4.1.0"
  }
}
```

```json
{
  "name": "@azure/keyvault-keys",
  "devDependencies": {
    "@azure/identity": "npm:@azure/keyvault-keys@4.8.0"
  }
}
```

Currently, the tool only checks for the package name, but not the source, but to make sure there isn't a cyclical reference, we need to also check the source if it is `npm:`, `file:`, `github:` or `workspace:`

### Expected Behavior

There should be no cyclic dependency detected if they are using `npm:`, `file:` or `github:` links instead of just workspace 

### To Reproduce

Mono repo location on branch located here [pnpm-migration](https://github.com/Azure/azure-sdk-for-js/tree/feat/pnpm-migration)

**Comment by chris-olszewski** [comment]
I think there is still a cycle. In your [.npmrc](https://github.com/Azure/azure-sdk-for-js/blob/feat/pnpm-migration/.npmrc#L1) you have [link-workspace-packages](https://pnpm.io/npmrc#link-workspace-packages) enabled. This means that even if you specify a dependency via `npm:` protocol, it'll use the workspace dependency instead of pulling from `npm`.

Does the solution still persist if you disable `link-workspace-packages`?

**Comment by mpodwysocki** [comment]
Yes, fixed it and now everything works.
