### ISSUE TITLE
no rich log in terminal when developing

### ISSUE THREAD

**Issue by mengxi-ream** [vercel/turborepo#9288]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

I just use I just use `pnpm dlx create-turbo@latest`

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.2.0

### Describe the Bug

When I developing when `turbo run dev`, there is no any log when changing code

https://github.com/user-attachments/assets/00a16da0-a591-4fe9-a7fb-2e36a45ea821

### Expected Behavior

There need to have some log like:
```
web: .....
docs: ...
```

### To Reproduce

I just use `pnpm dlx create-turbo@latest` and then `turbo dev`

**Comment by mengxi-ream** [comment]
I'm sorry, I'm new to TurboRepo and I'm not sure what I should be looking for in the terminal logs. I uploaded a video above to show the issue.

**Comment by mengxi-ream** [comment]
https://github.com/user-attachments/assets/ab2c363f-ef55-4a62-868d-94712ef90475

Another video shows that "stream" works good. When refreshing the page, there is the log in the terminal. But "tui" shows nothing

**Comment by chris-olszewski** [comment]
It appears you're hitting what https://github.com/vercel/turborepo/pull/9289 fixes. I'm releasing 2.2.1 right now, could you test it once it gets released?

**Comment by mengxi-ream** [comment]
> It appears you're hitting what #9289 fixes. I'm releasing 2.2.1 right now, could you test it once it gets released?

problem solved. thank you!
