### ISSUE TITLE
`turbo watch dev` stops after updating a file

### ISSUE THREAD

**Issue by noxify** [vercel/turborepo#9328]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/noxify/turbo-kills-dev

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.2.4-canary.1

### Describe the Bug

We're using `turbo watch dev` in our app. With `turbo@2.1.3` everything worked as expected and if I update a file in a package, the app got updated.

Now with `turbo@2.2.3` and also with `turbo@2.2.4-canary-1` the process just stops if I update a file in a package.

Since I'm not good in explaining, here a quick recording which shows the behaviour:

https://github.com/user-attachments/assets/0fe7ff1f-c260-49eb-acc8-31eef0ef5fd3

### Expected Behavior

After updating a file in a package ( or in the app ), the dev server should run.

### To Reproduce

Clone the repo:

```
git clone https://github.com/noxify/turbo-kills-dev
```

Install the deps:

```
pnpm i
```

Start the dev server:

```
pnpm dev
```

Update a file in `packages/ui/src` and save the file.

### Additional context

It worked with `2.1.3` - I tested it in the repro also with `"dev": "turbo dev"` ( in the workspace package.json ) and it seems to work. So I assume it's just a problem with `turbo watch dev`.

System information:

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 12
Binaries:
  Node: 22.10.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.12.2
```

**Comment by noxify** [comment]
Maybe it's "works as designed" and not a bug.

Based on the docs:

( Ref: https://turbo.build/repo/docs/reference/watch#dependency-aware-persistent-tasks )

> When your script has a built-in watcher (like next dev) capable of detecting changes in dependencies, you don't need to use turbo watch. Instead, use your script's built-in watcher and mark the task as long-running using ["persistent": true](https://turbo.build/repo/docs/reference/configuration#persistent).

it seems to be a problem in my configuration and using `turbo dev` is the solution?

**Comment by skve** [comment]
I have noticed the same recently. I use turbo watch dev to both concurrently run my Next.js dev server and a build step in a package. Since a recent release this is broken as changing any file marks the Next.js dev server step as "complete" when its marked as a persistent task

**Comment by tngflx** [comment]
@skve i just revert back to turbo 2.1.3 and it worked fine again.. waiting for their next release.. I wonder why they're no test file for turbo watch? hmm...

**Comment by noxify** [comment]
updated the repro to `2.2.4-canary.2` and it seems to work now.

Thanks for the quick fix <3

**Comment by mayfieldiv** [comment]
I think there's still an issue when `interruptible: true` is set for the `dev` task. When changing a file in one project, all the unrelated running `dev` tasks stop running.

**Comment by theogravity** [comment]
Can confirm `2.2.4-canary.2` does fix the issue with next.js 15 and `turbo watch dev` (I also have a mix of packages that need watching + next.js).
