### ISSUE TITLE
Docs: Ability to Disable Certain Warnings

### ISSUE THREAD

**Issue by ivanskodje** [vercel/turborepo#9342]
## What 

We would like the ability to disable nagging warning messages.

## Why 

Currently whenever I run my app locally for local development, it is logging a lot of warnings on every single page I visit, since I use AVIF logos:

```
 POST / 200 in 102ms
 ⚠ ./public/res/logo-large.avif
AVIF image not supported
This version of Turbopack does not support AVIF images, will emit without optimization or encoding


 ⚠ ./public/res/logo.avif
AVIF image not supported
This version of Turbopack does not support AVIF images, will emit without optimization or encoding
``` 

I am sorry, but Turbopack's inability to handle AVIF images is **not** my problem, and I do not want to get nagged about it. 

We have not found any documentation or information about how to disable this. This is in fact so troublesome that we have removed turbopack from the projects, because the nag is so bothersome and makes it harder to keep track of logging. 
Essentially, this prevents us from working properly.

### Is there any context that might help us understand?

^

**Comment by chris-olszewski** [comment]
This is an issue with Turbopack, not Turborepo. Please open an issue in https://github.com/vercel/next.js/
