### ISSUE TITLE
Turbo fails to start if files in repo contain non utf-8 chars

### ISSUE THREAD

**Issue by Tofandel** [vercel/turborepo#9345]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/Tofandel/Turbobug

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

2.2.4-canary.2

### Describe the Bug

When files inside a directory contains non utf-8 turbo doesn't start with
```
× path error: Failed to convert path
  ├─▶ Failed to convert path
  ╰─▶ Path contains invalid UTF-8
 ```

### Expected Behavior

Turbo to just ignore those files if it doesn't understand them and continue on with the build

### To Reproduce

`touch 'o'$'\277\275''est.prof_59551'`

turbo.json
```json
{
  "$schema": "https://turbo.build/schema.json",
  "tasks": {
    "//#run:build": {
        "cache": false
    }
  }
}
```
`turbo run //#run:build`

### Additional context

Those files were the result of node profiling

This only happens if the script is scope with `//#something:script`

**Comment by NicholasLYang** [comment]
Hi @Tofandel, thanks for the issue! We made this decision a while ago to only permit UTF-8 encoding for file paths. We decided this for multiple reasons, such as a need to manipulate paths as strings, UTF-8 being the valid subset between Windows and Unix, and concern around having paths that look identical but are encoded differently. You can read more in the [camino docs](https://github.com/camino-rs/camino/?tab=readme-ov-file#what-is-camino). 

Could you expand on what the specific use case is for non-UTF-8 files? Ignoring the files feels a little tricky since it can lead to unexpected behavior, such as accidental cache misses

**Comment by Tofandel** [comment]
There is no use case for non utf-8 file, the problem is just that I ran node profiling to debug some stuff in my project and after that turbo simply wouldn't start, just because some files not in utf8 and not used by the project were present in the filesystem. This kind of files really shouldn't cause a whole build to fail and stop and they should just be skipped. Maybe with only a warning.

A cache miss is a much better option than a build failure

**Comment by Tofandel** [comment]
> But an accidental cache hit due to a user expecting a file to be included in the hash could be a serious issue.

Yes but that would happen only if the user has non standard utf8 files (who does) and in this case a warning that this file will not be used to compute the cache hash is also still much better than a full build faillure

**Comment by NicholasLYang** [comment]
Gotcha. I'll investigate and see if this is feasible

**Comment by Tofandel** [comment]
Hmm is it normal that even with this config

```
        "outputs": [],
        "inputs": [],
        "cache": false
```

The build still fails though?  Why is turbo even looking at the files in the first place if I don't want a cache? You can only *delete the files* to start the build or add them to gitignore

**Comment by Tofandel** [comment]
From what I gathered, the validation of utf-8 paths occurs here https://github.com/vercel/turborepo/blob/ba769dc14dbb556f6aace5c6c7c775ae894a2b1b/crates/turborepo-lib/src/turbo_json/mod.rs#L382-L398

Shouldn't we force inputs and outputs to be empty and not process them at all if `cache` is false
