### ISSUE TITLE
ModuleBuildError: Module not found & can't resolve local packages on Windows

### ISSUE THREAD

**Issue by kelvinsekx** [vercel/turborepo#9366]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue
https://github.com/[kelvinsekx/turbo-example](https://github.com/kelvinsekx/turbo-example/tree/main)/tree/main

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

2.2.4-canary.5

### Describe the Bug

Given the eslint and typescript packages,
their reference in the web apps don't resolve on windows. It returns a can't resolve correctly "@/acme/<package-name>" 

![Screenshot (116)](https://github.com/user-attachments/assets/960704bc-9f52-4281-8e89-8f05b27403b8)
![Screenshot (117)](https://github.com/user-attachments/assets/a83d44e0-e9c8-41cb-bacf-72b6ea57aff4)
![Screenshot (118)](https://github.com/user-attachments/assets/c45c9587-1df2-4a3d-9f38-c0af87fcc4fc)
![Uploading Screenshot (119).p
![Screenshot (115)](https://github.com/user-attachments/assets/3ce8036f-6ce6-4ec8-b98e-630cb2a17487)
ng…]()

### Expected Behavior

It should run successfully like it does on my WSL path

### To Reproduce

create a simple turbo example with create turbo, run in on windows.

**Comment by tknickman** [comment]
What node version are you using?

**Comment by kelvinsekx** [comment]
> What node version are you using?

The latest LTS

**Comment by kelvinsekx** [comment]
> What node version are you using?

22.11.0

**Comment by kelvinsekx** [comment]
> What node version are you using?

Hey, I'm tryna follow up

**Comment by anthonyshew** [comment]
For context, this doesn't appear to be a Turborepo-specific issue. TypeScript and/or Node.js isn't resolving something correctly.

We're not able to reproduce this. Is this happening immediately after you use `create-turbo`? Is it still happening with the latest version of `create-turbo`, npx create-turbo@latest`?

If so, would you be able to run `npx turbo info` and paste the output here?

Ultimately, module resolution isn't in scope for Turborepo, but I'd like to fix the example if there's something that can be fixed. I'm surprised this isn't resolving for you because we have lots of folks using `create-turbo` every day, including on Windows with npm.

**Comment by anthonyshew** [comment]
This is only a low-fidelity guess but if you run `npm cache clean --force` and try again, do things work?

**Comment by kelvinsekx** [comment]
> For context, this doesn't appear to be a Turborepo-specific issue. TypeScript and/or Node.js isn't resolving something correctly.
> 
> We're not able to reproduce this. Is this happening immediately after you use `create-turbo`? Is it still happening with the latest version of `create-turbo`, npx create-turbo@latest`?
> 
> If so, would you be able to run `npx turbo info` and paste the output here?
> 
> Ultimately, module resolution isn't in scope for Turborepo, but I'd like to fix the example if there's something that can be fixed. I'm surprised this isn't resolving for you because we have lots of folks using `create-turbo` every day, including on Windows with npm.

I got an error

```bash
turbo 2.2.4-canary.5

  × missing tasks in project

Error:   × could not find task `info` in project
```

**Comment by anthonyshew** [comment]
I apologize. `turbo info` is available above `2.3` so you'd need to run `npx turbo@latest info --skip-infer`.

Sorry about that!

**Comment by kelvinsekx** [comment]
> > For context, this doesn't appear to be a Turborepo-specific issue. TypeScript and/or Node.js isn't resolving something correctly.
> > We're not able to reproduce this. Is this happening immediately after you use `create-turbo`? Is it still happening with the latest version of `create-turbo`, npx create-turbo@latest`?
> > If so, would you be able to run `npx turbo info` and paste the output here?
> > Ultimately, module resolution isn't in scope for Turborepo, but I'd like to fix the example if there's something that can be fixed. I'm surprised this isn't resolving for you because we have lots of folks using `create-turbo` every day, including on Windows with npm.
> 
> I got an error
> 
> ```shell
> turbo 2.2.4-canary.5
> 
>   × missing tasks in project
> 
> Error:   × could not find task `info` in project
> ```

I had to uninstall and install again

```bash
 WARNING  No locally installed `turbo` found. Using version: 2.3.1.
turbo 2.3.1

CLI:
   Version: 2.3.1
   Path to executable: C:\Users\UKUEJUBOLA KELVIN\AppData\Local\npm-cache\_npx\fbdd2f0c7d6dfb27\node_modules\turbo-windows-64\bin\turbo.exe
   Daemon status: Not running
   Package manager: npm

Platform:
   Architecture: x86_64
   Operating system: windows
   WSL: false
   Available memory (MB): 2071
   Available CPU cores: 4

Environment:
   CI: None
   Terminal (TERM): unknown
   Terminal program (TERM_PROGRAM): unknown
   Terminal program version (TERM_PROGRAM_VERSION): unknown
   Shell (SHELL): unknown
   stdin: false
```

**Comment by anthonyshew** [comment]
> This is only a low-fidelity guess but if you run `npm cache clean --force` and try again, do things work?

Have you had a chance to try this?

Or tried with a newer version of `create-turbo`?

I'm fairly certain at this point that there is an issue with your computer. I'm not seeing anyone reporting this error elsewhere and we can't reproduce this.

**Comment by kelvinsekx** [comment]
I resolved this by moving the turbo repo out of C:/Users/{my_name} file path to plain C:/
