### ISSUE TITLE
Does `--no-daemon` really work?

### ISSUE THREAD

**Issue by JonnyBurger** [vercel/turborepo#9401]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

github.com/remotion-dev/remotion

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.2.4-canary.8

### Describe the Bug

I try to disable the daemon:

turbo.json: `{"daemon": false}`
and run a `watch` command with `--no-daemon`

```
bunx turbo --no-daemon -vv watch make
```

Yet, two processes get created (none running before):

<img width="348" alt="image" src="https://github.com/user-attachments/assets/642cfb75-bc46-44e0-b79a-1a0de9db6867">

and the logs say it uses the daemon:

```
2024-11-07T09:21:23.851+0100 [DEBUG] turborepo_lib::daemon::connector: got daemon with pid: 53043
```

```
2024-11-07T09:21:23.852+0100 [DEBUG] turborepo_lib::daemon::connector: connecting to socket: /var/folders/hs/mbxg3j_55ls1b_dhn50w32t00000gn/T/turbod/b56db5bdb8c4c0f1/turbod.sock
```

```
2024-11-07T09:21:23.852+0100 [DEBUG] turborepo_lib::daemon::connector: connected in 497µs
```

```
2024-11-07T09:21:23.852+0100 [DEBUG] turborepo_lib::run::package_discovery: discovering packages using daemon
```

etc.

And I get the dreaded `failed to discover packages` error pretty often, which is why I want to for now disable the daemon

### Expected Behavior

No daemon should be started

If this is intended and the flag doesn't work with watch mode, this should be documented

### To Reproduce

Clone repo above
Run `pnpm i && bunx turbo --no-daemon watch make`

### Additional context

This behavior goes at least back to 2.1.1 which also has this behavior

**Comment by JoCa96** [comment]
Noticed the same in  #9394

**Comment by chris-olszewski** [comment]
`turbo watch` requires the daemon so we have access to a persistent file watcher. https://github.com/vercel/turborepo/pull/9407 will add a warning that we're ignoring any requests to disable the daemon when performing a `watch`.
