### ISSUE TITLE
Keypress interaction with `vite` doesn't work ("o"+"Enter" doesn't open web)

### ISSUE THREAD

**Issue by shanike** [vercel/turborepo#9402]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/shanike/turborepo-bug-repro

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

2.2.4-canary.8

### Describe the Bug

`Vite`'s dev server is interactive. It accepts commands to perform operations like open the browser (`"o"`) and restart the server (`"r"`).

I know Turborepo `v1` passes terminal input along to a dev server that was started through turbo dev. But, in Turborepo 2.2.3 it doesn't, which results with the following case:

The part that works:   The "gui" opens and runs as expected, and when pressing `"Enter"` on the persistent vite job, it focuses into it and allows typing.
The part afterwards which doesn't work: Pressing the letter `"o"` followed by an `"Enter"` -> nothing happens.

### Expected Behavior

After pressing the letter `"o"` followed by an `"Enter"` in a `vite` job -> `vite` opens the localhost web on the correct job's port. This does not happen with v2 of turbo.

### To Reproduce

1. Install Turborepo
2. On 1 app install `vite`
3. Create a "dev" vite+turbo task  
Now,
4. `pnpm exec turbo dev` on apps/apps-a  
will run vite with turbo and **won't** open the web when pressing o + Enter

(But
5. `pnpm dev`  
**will** open the web when writing o + Enter)

### Additional context

On turbo `v1.13.4` with `experimentalUI` turned on -> it DOES work: it opens the web when "interacting" with the `vite` task and pressing o + Enter.

This issue re-opens issue https://github.com/vercel/turborepo/issues/8952.   
#### Addressing comment https://github.com/vercel/turborepo/issues/8952#issuecomment-2296647342:  
Thank you for your answer!
Unfortunately, we still encounter this strange behavior. The answers to your questions:
- The other commands `r + Enter`, `u + Enter`, `c + Enter`, `q + Enter` and `h + Enter` work correctly
- All the commands above do work as expected in `loose` mode, `open` command works as well
- Yes, `open http://localhost:5173/` in the terminal opens the web browser

**Comment by chris-olszewski** [comment]
Do you happen to know what `open` command your system is using? I believe `xdg-open` is the most common on Linux, but `man open` should show which one is getting used.

> All the commands above do work as expected in loose mode, open command works as well

I think this indicates `open` on your system is requiring some environment variable to work correctly. Could you try adding `BROWSER` and `BROWSER_ARGS` as [passThroughArgs](https://turbo.build/repo/docs/reference/configuration#passthroughenv) for your [dev task](https://github.com/shanike/turborepo-bug-repro/blob/main/my-turborepo/turbo.json#L12)? If that's successful I will add them to the default pass through.

**Comment by shanike** [comment]
Thanks for checking it out.

> Do you happen to know what open command your system is using? 

Seems it's `xdg-open` indeed
![image](https://github.com/user-attachments/assets/076345e6-94bb-4d72-8b32-2b81d9c1ba76)

> Could you try adding BROWSER and BROWSER_ARGS as [passThroughArgs](https://turbo.build/repo/docs/reference/configuration#passthroughenv) for your [dev task](https://github.com/shanike/turborepo-bug-repro/blob/main/my-turborepo/turbo.json#L12)?

Sadly it seems to still not open the browser. (Other letters still do work, like h+enter).
![image](https://github.com/user-attachments/assets/06930ca6-9777-445f-8ba0-39685ab17009)

**Comment by chris-olszewski** [comment]
I'm having trouble finding any documentation about other environment variables that are needed by `xdg-open` to function.

Could you try `env -i bash --noprofile --norc` and then in the new Bash shell run `open http://localhost:5173` and see if that gives us any hints to what could be happening? (`env -i bash --noprofile --norc` should start a bash shell with the minimal env vars required for operation and nothing more) If that succeeds would you mind providing the result of `env` in that Bash shell?
