### ISSUE TITLE
Docs: Nextjs 15 example

### ISSUE THREAD

**Issue by CodingXD** [vercel/turborepo#9403]
### What is the improvement or update you wish to see?

Currently, any new project created in Turborepo uses Nextjs 14. It would be great if it supports Nextjs 15 out of the box.

### Is there any context that might help us understand?

https://nextjs.org/

**Comment by sebalaini** [comment]
I agree, together with the Eslint 9 doc for Nextjs 15, there is already an issue https://github.com/vercel/turborepo/issues/7909

**Comment by anthonyshew** [comment]
Turborepo works with any framework (or language, really), so Next.js 15 is indeed supported.

Getting the example updated here!: https://github.com/vercel/turborepo/pull/9440

**Comment by sebalaini** [comment]
Hey @anthonyshew, thank you so much for that example. However, I would have prioritized nextJs 15 + React 18 + Eslint 9 instead of nextJs 15 + React 19. I don't think someone will ever use React 19 in production, but that's just my opinion.

Do you know when we could have an Eslint 9 example?

**Comment by anthonyshew** [comment]
Closed in https://github.com/vercel/turborepo/pull/9440.

There are a great deal of (large)applications running React 19 in production today. 👍

Going to be getting ESLint v9 up sooner than later! Just making sure to ship incremental changes.
