### ISSUE TITLE
`watch` should require a task

### ISSUE THREAD

**Issue by dimitropoulos** [vercel/turborepo#9446]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

create-turbo

### Which canary version will you have in your reproduction?

latest

### Enviroment information

```block
$ turbo info
turbo 2.3.0

CLI:
   Version: 2.3.0
   Daemon status: Running
   Package manager: pnpm

Platform:
   Architecture: x86_64
   Operating system: linux
   WSL: false
   Available memory (MB): 42298
   Available CPU cores: 16

Environment:
   CI: None
   Terminal (TERM): xterm-256color
   Terminal program (TERM_PROGRAM): vscode
   Terminal program version (TERM_PROGRAM_VERSION): 1.94.2
   Shell (SHELL): /bin/bash
   stdin: false
```

### Expected behavior

no allowing running `watch` without a task

### Actual behavior

```console
$ turbo watch
turbo 2.3.0

• Packages in scope: @repo/eslint-config, @repo/typescript-config, @repo/ui, docs, web
• Running  in 5 packages
• Remote caching disabled
```

### To Reproduce

run `turbo watch`

**Comment by takaebato** [comment]
I'll work on this if no one else is!

**Comment by anthonyshew** [comment]
@takaebato Go right ahead! Appreciate your help. 🙏
