### ISSUE TITLE
cli command often leaves me with bold text

### ISSUE THREAD

**Issue by zanona** [vercel/turborepo#945]
### What version of Turborepo are you using?

1.1.6

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

I am often left with bold text after running turbo commands.
Usually when I get the cached multicoloured 'FULL TURBO'  label.
![screenshot](https://user-images.githubusercontent.com/32017/160086284-9e890531-fd83-4a38-aeea-50baadc8e728.png)

### Expected Behavior

I would like to run turbo commands and  once exiting, either by reaching to it's end or forcibly by cancelling the process, having the text return to normal (not bold).

### To Reproduce

I usually run commands such as `npx turbo run build` and when getting a cached version the next shell prompt will be left in bold.

**Comment by gsoltis** [comment]
I believe this is fixed in the latest canary by #926
