### ISSUE TITLE
📚 Docs: --cache docs confusing

### ISSUE THREAD

**Issue by dipunm** [vercel/turborepo#9481]
### What is the improvement or update you wish to see?

The statement:

```
When an option is omitted, reading and writing are both disabled
```

in https://github.com/vercel/turborepo/blob/main/docs/repo-docs/reference/run.mdx#--cache-options

Is confusing.

### Is there any context that might help us understand?

I ran locally, and I believe it should say "reading and writing are both enabled". I thought maybe it meant if you omit the `:rw` part, but it just errors if you omit that (unless you use `local:,remote:`).

### Does the docs page already exist? Please link to it.

in https://github.com/vercel/turborepo/blob/main/docs/repo-docs/reference/run.mdx#--cache-options

**Comment by anthonyshew** [comment]
Would you have found it clearer if it was:
```
When a caching source is omitted, reading and writing are both disabled.
```

**Comment by anthonyshew** [comment]
Re-reading this now, I can see how it can be clearer in a handful of ways. Thank you for pointing this out. Hopefully it will be clearer after #9489.

**Comment by dipunm** [comment]
Thanks, I didn't realise that was the actual meaning, so it is clearer now.
