### ISSUE TITLE
🐛 Bug: Workspace project without `*` doesn't use repo's turbo

### ISSUE THREAD

**Issue by AlexErrant** [vercel/turborepo#9490]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/AlexErrant/turborepo-workspace-bug

### Which canary version will you have in your reproduction?

^2.3.1-canary.2

### Enviroment information

```block
CLI:
   Version: 2.3.1
   Path to executable: /home/alex/turborepo-workspace-bug/node_modules/.pnpm/turbo-linux-64@2.3.1/node_modules/turbo-linux-64/bin/turbo
   Daemon status: Not running
   Package manager: pnpm

Platform:
   Architecture: x86_64
   Operating system: linux
   WSL: true
   Available memory (MB): 17335
   Available CPU cores: 12

Environment:
   CI: None
   Terminal (TERM): xterm-256color
   Terminal program (TERM_PROGRAM): unknown
   Terminal program version (TERM_PROGRAM_VERSION): unknown
   Shell (SHELL): /usr/bin/zsh
   stdin: false
```

### Expected behavior

Running e.g. `turbo build` in a workspace project should work, even if it doesn't have a wildcard, like in `vite-project/` below:

```yaml
packages:
  - apps/*
  - packages/*
  - vite-project/
```

### Actual behavior

![image](https://github.com/user-attachments/assets/616967c2-2058-41e6-a430-59e61872e203)

```
 ~/turborepo-workspace-bug/vite-project  main 
❯ turbo build                                                                                                                                                                     98%  
╭──────────────────────────────────────────────────────────────────────────╮
│                                                                          │
│                     Update available v2.1.1 ≫ v2.3.0                     │
│    Changelog: https://github.com/vercel/turborepo/releases/tag/v2.3.0    │
│             Run "npx @turbo/codemod@latest update" to update             │
│                                                                          │
│          Follow @turborepo for updates: https://x.com/turborepo          │
╰──────────────────────────────────────────────────────────────────────────╯
 WARNING  No locally installed `turbo` found. Using version: 2.1.1.
turbo 2.1.1

  × missing packageManager field in package.json
```

This error message is somewhat misleading.

### To Reproduce

`git clone https://github.com/AlexErrant/turborepo-workspace-bug && cd turborepo-workspace-bug && pnpm i && cd vite-project && turbo build`

### Additional context

I'm _guessing_ [this LOC here](https://github.com/vercel/turborepo/blob/13bfef4024b12fd7163c2d46b06fa962b5168bbd/crates/turborepo-repository/src/package_manager/mod.rs#L539) is the culprit (or at least part of the problem), since `vite-project/` is literally _not_ a file.

**Comment by chris-olszewski** [comment]
Thank you for the report. This is the same issue as https://github.com/vercel/turborepo/issues/8599 so I will be closing this in favor of that. 

TL;DR our workspace globbing codepath differs slightly from our "am I in this workspace" check in a way that isn't super easy to resolve.

Closing in favor of https://github.com/vercel/turborepo/issues/8599
