### ISSUE TITLE
Allow additional cache configuration in turbo.json

### ISSUE THREAD

**Issue by gaspar09** [vercel/turborepo#952]
Allow the following options to be set in `turbo.json` cache options

- `remoteOnly: boolean`
  - Requires: https://github.com/vercel/turborepo/issues/833
- `cacheDirectory: string`
  - Def: https://github.com/vercel/turborepo/blob/42d7447f2f745f74160781291cb6557e73515f6a/cli/internal/cache/cache_fs.go#L17-L25 
https://github.com/vercel/turborepo/blob/466b09a7fe99316213ce06ebd30a54a1cf5e8c0f/cli/internal/config/config.go#L205

**Comment by jaredpalmer** [comment]
We determined that these aren't really necessary.
