### ISSUE TITLE
turbo is not supported on ppc64le architecture

### ISSUE THREAD

**Issue by vinodk99** [vercel/turborepo#9537]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

main

### Which canary version will you have in your reproduction?

main

### Expected behavior

turbo should show version

### Actual behavior

Turbo should support ppc64le 

### To Reproduce

Turbo should support ppc64le 

### Additional context

> turbo run prettier:format

***

Turborepo failed to start.

Turborepo detected that you are running:
linux ppc64

Turborepo supports your platform, but does not support your processor architecture.

**Comment by NicholasLYang** [comment]
Hi, thanks for the issue. Could you clarify the specific use case for this target? From my searching, `ppe64le` mostly seems to be used for embedded. Are you using turborepo in an embedded context?

We generally don't have the bandwidth to support more targets, however we are open to PRs for adding the target to the release pipeline, as long as the author is willing to help support that target moving forward.

**Comment by NicholasLYang** [comment]
Unless someone is willing to take ownership for this target, I'm going to close it for now
