### ISSUE TITLE
Whole package list is printed twice in watch mode

### ISSUE THREAD

**Issue by JonnyBurger** [vercel/turborepo#9538]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/remotion-dev/remotion

### Which canary version will you have in your reproduction?

2.3.3

### Enviroment information

```block
turbo 2.3.3

CLI:
   Version: 2.3.3
   Path to executable: /Users/jonathanburger/remotion/node_modules/.pnpm/turbo-darwin-arm64@2.3.3/node_modules/turbo-darwin-arm64/bin/turbo
   Daemon status: Running
   Package manager: pnpm

Platform:
   Architecture: aarch64
   Operating system: macos
   WSL: false
   Available memory (MB): 6906
   Available CPU cores: 8

Environment:
   CI: None
   Terminal (TERM): xterm-256color
   Terminal program (TERM_PROGRAM): iTerm.app
   Terminal program version (TERM_PROGRAM_VERSION): 3.5.10
   Shell (SHELL): /bin/zsh
   stdin: false
```

### Expected behavior

The whole package list should be printed once

### Actual behavior

The whole package list is printed twice

### To Reproduce

Clone remotion github repo and run `bunx turbo watch make`

### Additional context

![image](https://github.com/user-attachments/assets/30fc0b1d-ae82-4b0c-b90c-3eac8018d67f)

**Comment by maciej-ka** [comment]
I would like to give it a try.

**Comment by NicholasLYang** [comment]
Sounds great! The code is contained in [https://github.com/vercel/turborepo/blob/main/crates/turborepo-lib/src/run/watch.rs](watch.rs).
