### ISSUE TITLE
tui when searching with /, h will still hide the task list

### ISSUE THREAD

**Issue by macrozone** [vercel/turborepo#9553]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

none

### Which canary version will you have in your reproduction?

2.3.3

### Enviroment information

```block
CLI:
   Version: 2.3.3
   Path to executable: /Users/macrozone/git/panter/food-2050/node_modules/turbo-darwin-arm64/bin/turbo
   Daemon status: Running
   Package manager: berry

Platform:
   Architecture: aarch64
   Operating system: macos
   WSL: false
   Available memory (MB): 22675
   Available CPU cores: 12

Environment:
   CI: None
   Terminal (TERM): xterm-256color
   Terminal program (TERM_PROGRAM): iTerm.app
   Terminal program version (TERM_PROGRAM_VERSION): 3.5.10
   Shell (SHELL): /bin/zsh
   stdin: false
```

### Expected behavior

should not hide when searching

### Actual behavior

hides when searching

### To Reproduce

press /

press h

**Comment by chris-olszewski** [comment]
This was fixed in https://github.com/vercel/turborepo/pull/9543 which will be released in `2.3.4-canary.0`
