### ISSUE TITLE
fire a preflight request before uploading artifacts

### ISSUE THREAD

**Issue by promer94** [vercel/turborepo#956]
### Describe the feature you'd like to request

i just built my own turborepo cache server with nextjs and it works well locally.
But when i try to deploy it on vercel, i find many upload requests failed beacause of 5MB body size limit. 
I try to set 307 status to redirect the upload request to s3 endpoint directly but it does not work.

If the client can preflight HEAD request to the cache server and get the upload endpoint from it, then the artifacts will need to pass through the cache server at all. I think it will make the server implmentation easier.

### Describe the solution you'd like

```mermaid
flowchart TD
   A[HEAD /v8/artifact/hash] --> B{cache server};
    B -- new endpoint in header --> C[PUT /newEndpoint];
    B -- No --> D[PUT /v8/artifact/hash];
```

### Describe alternatives you've considered

NA

**Comment by EloB** [comment]
@promer94 did you use presigned urls for this?

**Comment by promer94** [comment]
> @promer94 did you use presigned urls for this?

Yes

**Comment by EloB** [comment]
@promer94 open or closed source? 🙂

**Comment by EloB** [comment]
@jaredpalmer I'm having problem `The request signature we calculated does not match the signature you provided. Check your key and signing method.`. Seems like preflight is adding extra parameters to the actual request. Is there a way to prevent that? I'm trying to use presigned urls with AWS S3.
