### ISSUE TITLE
eslint-plugin-turbo not working with Nitro v3

### ISSUE THREAD

**Issue by MickL** [vercel/turborepo#9571]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Which canary version will you have in your reproduction?

2.3.3

### Expected behavior

Using framework specific vars like `process.env.NITRO_DATABASE_URL` or `process.env.NUXT_API_URL` should be allowed but usage throws

> NITRO_DATABASE_URL is not listed as a dependency in turbo.json        turbo/no-undeclared-env-vars

### Actual behavior

Allow list should be on par with the docs: https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables#framework-inference

**Comment by MickL** [comment]
Is this somehow related to some other flag to identify the project? I just checked and it works correctly in a Nuxt project but not in a pure Nitro project with exactly the same eslint config

**Comment by anthonyshew** [comment]
Can you provide us a reproduction? We [have code](https://github.com/vercel/turborepo/blob/6036aec7add168b87cb53ef0a053f7c439a78bca/packages/eslint-plugin-turbo/lib/rules/no-undeclared-env-vars.ts#L115) for this, but a reproduction would help to show us if we have a bug or if something is mis-configured.

**Comment by anthonyshew** [comment]
Simple enough! Updating our detection here: #9608

**Comment by MickL** [comment]
Thanks for the fix! When will it be released? I checked regularly but still no update on npm.

**Comment by anthonyshew** [comment]
Looks to be in [https://github.com/vercel/turborepo/releases/tag/v2.3.4-canary.3](https://github.com/vercel/turborepo/releases/tag/v2.3.4-canary.3)!
