### ISSUE TITLE
/node_modules/.pnpm/turbo-linux-64@2.3.3/node_modules/turbo-linux-64/bin/turbo: line 3: "foo(" must be followed by )  ELIFECYCLE  Command failed with exit code 2.

### ISSUE THREAD

**Issue by vaynevayne** [vercel/turborepo#9588]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://stackblitz.com/~/github.com/vaynevayne/react-fabric

### Which canary version will you have in your reproduction?

 2.3.3

### Expected behavior

success sutup in stackbliz

### Actual behavior

error

### To Reproduce

open link waiting

**Comment by anthonyshew** [comment]
Hi, are you saying you see this issue specifically in Stackblitz? Does this happen when you're developing locally as well?

**Comment by vaynevayne** [comment]
@anthonyshew  specifically in Stackblitz
  codesandbox is work well, 
  https://codesandbox.io/p/github/vaynevayne/react-fabric/main?import=true

**Comment by anthonyshew** [comment]
In that case, there's probably not a lot we can do here. You may want to ask in the Stackblitz community about getting better support on their platform. Sorry to be unhelpful here!
