### ISSUE TITLE
When a URL is used for `packageManager` field of `package.json`, an error is thrown ("expected to match regular expression")

### ISSUE THREAD

**Issue by pkerschbaum** [vercel/turborepo#9611]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://codesandbox.io/p/devbox/https-github-com-inversify-inversifyjs-issues-1630-forked-mk4dgv?workspaceId=ws_UGoaic2rUkCT9cicv4uPWU

### Which canary version will you have in your reproduction?

2.3.4-canary.2

### Enviroment information

```block
turbo 2.3.4-canary.2

CLI:
   Version: 2.3.4-canary.2
   Path to executable: /project/workspace/node_modules/.pnpm/turbo-linux-64@2.3.4-canary.2/node_modules/turbo-linux-64/bin/turbo
   Daemon status: Running
   Package manager: pnpm

Platform:
   Architecture: x86_64
   Operating system: linux
   WSL: false
   Available memory (MB): 3018
   Available CPU cores: 2

Environment:
   CI: None
   Terminal (TERM): xterm-256color
   Terminal program (TERM_PROGRAM): unknown
   Terminal program version (TERM_PROGRAM_VERSION): unknown
   Shell (SHELL): /bin/bash
   stdin: false
```

### Expected behavior

`turbo run` should work.

### Actual behavior

`turbo run` throws an error:

```bash
➜  workspace git:(master) ✗ COREPACK_ENABLE_UNSAFE_CUSTOM_URLS=1 pnpm exec turbo run build
turbo 2.3.4-canary.2

invalid_package_manager_field

  × could not parse the packageManager field in package.json, expected to match regular expression (?P<manager>bun|npm|pnpm|yarn)@(?P<version>\d+\.\d+\.\d+(-.+)?)
   ╭─[/project/workspace/package.json:6:1]
 6 │   },
 7 │   "packageManager": "pnpm@https://registry.npmjs.org/@pkerschbaum/pnpm/-/pnpm-9.9.0-pkerschbaum-extensions-1.tgz",
   ·                     ──────────────────────────────────────────────┬──────────────────────────────────────────────
   ·                                                                   ╰── invalid `packageManager` field
 8 │   "dependencies": {
   ╰────
```

### To Reproduce

1. Open https://codesandbox.io/p/devbox/https-github-com-inversify-inversifyjs-issues-1630-forked-mk4dgv?workspaceId=ws_UGoaic2rUkCT9cicv4uPWU
2. Run:

   ```bash
   corepack enable
   COREPACK_ENABLE_UNSAFE_CUSTOM_URLS=1 pnpm install
   COREPACK_ENABLE_UNSAFE_CUSTOM_URLS=1 pnpm exec turbo run build
   ```

### Additional context

* Regex for `packageManager` seems to be this: https://github.com/vercel/turborepo/blob/ffd467909fd9e19e7c7b03a573848d5b04b2280a/crates/turborepo-repository/src/package_manager/mod.rs#L202

* `corepack` supports custom URLs nowadays: https://github.com/nodejs/corepack?tab=readme-ov-file#when-authoring-packages  
And using them might be needed by some projects, e.g. we at @hokify want to switch from official pnpm to a forked one, for that we need to set a custom URL.  
BTW we are very happy users of turborepo, great work!!

**Comment by anthonyshew** [comment]
Today, I learned Corepack can do that. I'm going to mark this with the `good-first-issue` label for right now as this is a relatively low lift - but a good get! You've also identified the exact line of code needed for the change. 😄
