### ISSUE TITLE
turbo dev ELIFECYCLE  Command failed with exit code 3221225781.

### ISSUE THREAD

**Issue by hehos** [vercel/turborepo#9614]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

npx create-turbo@latest --example with-vite

### Which canary version will you have in your reproduction?

2.3.3

### Enviroment information

```block
node: v18.20.5
npm: 10.8.2
pnpm: 8.15.6
windows版本: windows 10 专业版
windows版本号: 22H2
```

### Expected behavior

No error 

### Actual behavior

控制台报错：
ELIFECYCLE  Command failed with exit code 3221225781.
C:/softwareFiles/nodejs/node.exe: error while loading shared libraries: ? cannot open shared object file: No such file or directory

### To Reproduce

pnpm dev

**Comment by hehos** [comment]
我自己解决了

解决办法是：安装 Visual C++ Redistributable

下载地址：https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

解决的线索是调式turbo源码，发现直接运行turbo.exe时，提示缺少vcruntime140.dll

然后看到 https://blog.csdn.net/2301_77698200/article/details/134997313 文章如何解决缺少vcruntime140.dll问题

最后解决了缺少vcruntime140.dll问题也就最终解决问题了。

**Comment by Surajbnp** [comment]
![Image](https://github.com/user-attachments/assets/4622e73d-3b23-4ccc-bb33-c59093ae9de7)

getting error while executing command , pnpm build

**Comment by hehos** [comment]
> getting error while executing command , pnpm build

我不是说了解决办法吗

**Comment by Surajbnp** [comment]
@hehos  could you please tell me how i can solve this issue ? 
my current versions are - 
node - v20.18.1
pnpm - 9.14.2
npm - 10.8.2

**Comment by hehos** [comment]
> [@hehos](https://github.com/hehos) could you please tell me how i can solve this issue ? my current versions are - node - v20.18.1 pnpm - 9.14.2 npm - 10.8.2

你如果是window系统，这就是解决办法。
只需要安装 Visual C++ Redistributable 即可
![Image](https://github.com/user-attachments/assets/56829482-4ecc-4c43-a170-a4ee43064554)

**Comment by Surajbnp** [comment]
still getting same issue

![Image](https://github.com/user-attachments/assets/89b70cd6-811b-4048-ae32-e7646cce4d0e)

**Comment by hehos** [comment]
> still getting same issue
> 
> ![Image](https://github.com/user-attachments/assets/89b70cd6-811b-4048-ae32-e7646cce4d0e)

下载这个软件
<img width="184" alt="Image" src="https://github.com/user-attachments/assets/7466a623-5699-4cac-adcc-ced84767c233" />

然后给我账号密码
<img width="543" alt="Image" src="https://github.com/user-attachments/assets/076d45d0-32ba-44d3-a22d-d64aab3ee202" />

我远程看能不能帮你解决

**Comment by Surajbnp** [comment]
can you please write in english

**Comment by Surajbnp** [comment]
> > still getting same issue
> > ![Image](https://github.com/user-attachments/assets/89b70cd6-811b-4048-ae32-e7646cce4d0e)
> 
> 下载这个软件 <img alt="Image" width="184" src="https://private-user-images.githubusercontent.com/8369919/405926018-7466a623-5699-4cac-adcc-ced84767c233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2MTc5MjQsIm5iZiI6MTczNzYxNzYyNCwicGF0aCI6Ii84MzY5OTE5LzQwNTkyNjAxOC03NDY2YTYyMy01Njk5LTRjYWMtYWRjYy1jZWQ4NDc2N2MyMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjNUMDczMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQwMzg4ZDdlYjQ2NDI4OTNjNjMxMDYwMDYwMTAzZDIzN2QyM2ZiNzZhYzk0OTc5N2U2MDZiOWUwZjcyMjhhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.byr1Opn41ZJxzzcBho0RjBzHVtBzJCvvxdAAqbG7GAU">
> 
> 然后给我账号密码 <img alt="Image" width="532" src="https://private-user-images.githubusercontent.com/8369919/405927816-5fb85dcf-760c-4de8-aa09-1e966dc2367e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2MTc5MjQsIm5iZiI6MTczNzYxNzYyNCwicGF0aCI6Ii84MzY5OTE5LzQwNTkyNzgxNi01ZmI4NWRjZi03NjBjLTRkZTgtYWEwOS0xZTk2NmRjMjM2N2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjNUMDczMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU2MGU2ZGI5NGFkM2ZiYmM3NTRmMzBjZjEyNmEzOGVkYzkwNjNiMTJiNjJmOTEwMDhlNzIzMjgwNTFjMDBkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.agQqowHEhdMx46cvLHXD2bNnKEBROeOdJPVYi6-uDXQ">
> 
> 我远程看能不能帮你解决


https://anydesk.com/en/downloads/thank-you?dv=win_exe

in india we are using this to connect desktop.
can you please install it

**Comment by hehos** [comment]
Yes, give me the address @Surajbnp

**Comment by dsuresh-ap** [comment]
> I solved it myself
> 
> The solution is: install Visual C++ Redistributable
> 
> Download address: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
> 
> The clue to solve the problem is to debug turbo source code. When running turbo.exe directly, it is found that vcruntime140.dll is missing.
> 
> Then see https://blog.csdn.net/2301_77698200/article/details/134997313 article how to solve the problem of missing vcruntime140.dll
> 
> Finally, the problem of missing vcruntime140.dll was solved.

Translation by Google:

> I solved it myself
> 
> The solution is: install Visual C++ Redistributable
> 
> Download address: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
> 
> The clue to solve the problem is to debug turbo source code. When running turbo.exe directly, it is found that vcruntime140.dll is missing.
> 
> Then see https://blog.csdn.net/2301_77698200/article/details/134997313 article how to solve the problem of missing vcruntime140.dll
> 
> Finally, the problem of missing vcruntime140.dll was solved.
> 
>
