### ISSUE TITLE
Turbo cannot detect PNPM as package manager unless Yarn is installed

### ISSUE THREAD

**Issue by jaredmcateer** [vercel/turborepo#962]
### What version of Turborepo are you using?

1.1.10

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Turbo is unable to detect PNPM,  failing early

```
pnpm run build

> turborepo-basic-shared@0.0.0 build /home/jared/projects/vue-turbo
> turbo run build

 ERROR  could not check if yarn is berry: could not detect yarn version: exec: "yarn": executable file not found in $PATH
 ELIFECYCLE  Command failed with exit code 1.
```

It appears that the `GetBackends` fails when checking [`IsBerry`](https://github.com/vercel/turborepo/blob/526f08f2e9ee39234b7e71a856784a21aeb84662/cli/internal/backends/nodejs/nodejs.go#L122) and the user does not have Yarn installed.

### Expected Behavior

Turbo should not fail when failing to detect a package manager that is not being used.

### To Reproduce

- uninstall yarn
- create a turbo project using pnpm
- try to build or run the project

**Comment by vasco3** [comment]
It was working fine for me. Then I deleted node_modules and ran again `pnpm install`. That is when turborepo started throwing this error ` ERROR  could not check if yarn is berry:`

**Comment by domistry** [comment]
Deleting yarn.lock file worked for me
