### ISSUE TITLE
Unexpected token Delim('$') at [project]/app/globals.css:757:29

### ISSUE THREAD

**Issue by J4v4Scr1pt** [vercel/turborepo#9621]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/J4v4Scr1pt/ThnJK/tree/upgradeToNextjs15andReact19

### Which canary version will you have in your reproduction?

Nextjs 15

### Enviroment information

```block
I use NextJs 15
```

### Expected behavior

To work as with webpack.

### Actual behavior

Fails as soon as Turbo is trying to compile a page you navigate to.

### To Reproduce

Add --turbopack in the dev command in `package.json` and start the project.
![image](https://github.com/user-attachments/assets/3fbe3023-d384-4a55-b890-6e0b90fca250)

Navigate to any page and the error will appear. 

### Additional context

I'm using latest NextJs version and do not point to any specific Turbo version.

I have some custom Tailwind configuration that used to work with Nextjs and webpack. But with NextJs 15 and turbo being stable I wanted to use this. But then I get this error:
![image](https://github.com/user-attachments/assets/ffe11ca6-a0d5-47ae-80b9-ff71ae1359ad)

```
 ⨯ ./app/globals.css:758:30
Parsing css source code failed
  756 |   --background: ({ opacityVariable, opacityValue }) => {
  757 |           if (!isNaN(+opacityValue)) {
> 758 |             return `hsl(var(${nextuiColorVariable}) / ${opacityValue})`;
      |                              ^
  759 |           }
  760 |           if (opacityVariable) {
  761 |             return `hsl(var(${nextuiColorVariable}) / var(${nextuiOpacityVariable}, var(${opacityVariable})))`;

Unexpected token Delim('$') at [project]/app/globals.css:757:29
```

I can only fix the issue by removing the method or using webpack, which is not what I want :).

Same problem as in this thread that is closed: https://github.com/vercel/turborepo/issues/2356.
Last post encourage you start a new thread and not continue the current.

**Comment by chris-olszewski** [comment]
Turbopack has moved to [vercel/next.js](https://github.com/vercel/next.js), please open an issue there.
