### ISSUE TITLE
Turbo gets stuck if a cyclic dependency exists

### ISSUE THREAD

**Issue by leonheess** [vercel/turborepo#973]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Describe the Bug

In a lerna monorepo with a cyclic dependency turbo gets stuck without stopping or printing anything useful even in debug mode. 

### Expected Behavior

Stop the process and print an error after getting stuck.

### To Reproduce

1. Create a monorepo with a cyclic dependency
2. Run turbo run build

**Comment by jaredpalmer** [comment]
This has been fixed and is no longer possible in 1.2.4.
