### ISSUE TITLE
bug: Turbo should not die on permissions errors, and should log a warning for permissions errors inside workspaces

### ISSUE THREAD

**Issue by hrasekj** [vercel/turborepo#997]
### What version of Turborepo are you using?

1.1.10

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I have monorepo based on pnpm and for some reason turbo does not see packages in `apps/` folder. I tried to install all dependencies with `yarn` too, delete all caches and the result was the same.

package.json
```json
{
  "name": "root",
  "private": true,
  "engines": {
    "pnpm": ">=6.0.0",
    "node": "^16"
  },
  "packageManager": "pnpm@6.32.4",
  "scripts": {
    "dev": "turbo run dev --dry",
    // ...
  },
  "devDependencies": {
    "turbo": "^1.1.10"
  },
  // ...
}
```
turbo.json
```json
{
  "$schema": "https://turborepo.org/schema.json",
  "baseBranch": "origin/devel",
  "npmClient": "pnpm",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", ".next/**"]
    },
    "types": {
      "dependsOn": ["^types"],
      "outputs": ["typings/**"]
    },
    "dev": {
      "cache": false
    }
  }
}
```
pnpm-workspace.yaml
```yaml
packages:
  - 'apps/**'
  - 'packages/**'
```

All packages have naming convention like `@namespace/package`, which means that package named `@admin/web` is inside directory `apps/admin-web/` and `@admin/database` is inside directory `packages/admin-database`.

The `build` and `types` scripts are present in all packages in both folders `apps/` and `packages/`. The `dev` script is present only in packages in `apps/` folder.

```
> root@ dev /my-monorepo
> turbo run dev --dry


Packages in Scope
Name                  Path                          
@admin/database       packages/admin-database       

Tasks to Run
```

### Expected Behavior

I'm expecting to see packages in `apps/` folder too.

### To Reproduce

Next problem is reproduce. I tried example from docs `npx create-turbo@latest` and tried use my naming convention described here. And everything works as expected.

There must be something else i'm missing? :thinking: 

Thanks for any help.

**Comment by gsoltis** [comment]
Just to make sure I'm understanding:
 * In your normal monorepo, you see everything under `packages/` but nothing under `apps/`?
 * When you try an example or new monorepo, with `pnpm`, you are able to see both `apps/` and `packages/` ?
 * When you remove `.git` in your existing monorepo, and re-init, you see `apps/` and `packages/`?

We do ignore a couple of [file patterns](https://github.com/vercel/turborepo/blob/699ce71e3b22134a329049d6be70d13cacd7607f/cli/internal/context/context.go#L443) by default, but I don't see how `git` would affect that.

**Comment by hrasekj** [comment]
3x Yes. 

I'm trying to simulate the same steps in git to reproduce, but without luck so far. 

Its just a guess, but in docs i see [--since](https://turborepo.org/docs/reference/command-line-reference#--since) prop which uses `git diff`. Is git used only with this prop or in somewhere else?

**Comment by hrasekj** [comment]
I was wrong. The problem is something more hidden. File permissions. I have `docker/` folder with data from services created by docker.

Now its easy to replicate:
- `npx create-turbo@latest`
- `cd my-turborepo`
- `mkdir bug`
- `chmod 0700 bug`
- `sudo chown root: bug`
- `pnpm dev` <- no apps in scope

Looks like turbo silently dies on folder read permissions.

**Comment by gsoltis** [comment]
Ok, well, that makes a lot more sense. To be honest, I'm not sure if this is a bug or not. In this case it sounds like the permissions might be an accident, but I don't think we want `turbo` to fail to run in other cases where someone may have intentionally set permissions to keep `turbo` out. It might just be a case of "don't do that". Maybe a warning to `stderr` is appropriate?

**Comment by hrasekj** [comment]
Well, warning is nice, if that `bug/` folder will be inside `apps/` or `packages/` workspace folders, but that folder is next to them. It should be ignored.

Also in my repository I have `docker/` folder with `mysql/` in it. And whole `mysql/` folder is gitignored. And still turbo fails on that folder.

**Comment by gsoltis** [comment]
I can commit to a warning, and `turbo` not dying when it encounters a permissions error as a feature request. 

I will say we also broadly need to do better at respecting `.gitignore`.

**Comment by martinstepanek** [comment]
I am not sure if you understand the problem. The problematic folder (`bugFolder` with wrong permission) is not listed inside workspace, it's on the same level. 


Directory:
```
apps/                    <-- turbo has permission to this folder
packages/                <-- turbo has permission to this folder
bugFolder/               <-- turbo doesn't have permission to this folder
turbo.json
...
```

Then workspaces are:
pnpm-workspace.yaml
```
packages:
  - 'apps/**'
  - 'packages/**'
```

Then when running turbo command, it doesn't see `apps` workspace. 
`bugFolder` is not inside workspace, `bugFolder` is not listed as workspace. 

From my point of view, turbo should absolutely ignore `bugFolder` and should see `apps` and `packages` as workspaces, but it doesn't  


Shouldn't this be a bug instead of feature request?

**Comment by gsoltis** [comment]
Ah, you're right. We at the very least shouldn't die in that situation.
